### ISSUE TITLE
Restrict FHIR resource type from a user

### ISSUE THREAD

**Issue by georgehumperdinck** [microsoft/fhir-server#1019]
**User story**
As a developer, I want to restrict a fhir resource type from a user so that I can make accounts for different kinds of users.

**Acceptance criteria**
1. When I create an account, the endpoint "/Patient" or a fhir resource type should be available to user 1 but not available to user 2.

I already reviewed azure RBAC however permissions (like FHIR Data Reader) are applied to all fhir resource types.

Btw, this project is awesome! I hope to hear from you guys. Thanks.

**Comment by hansenms** [comment]
This is a relatively big topic area that we are planning some work in, but we will not be able to deliver anything in the sort term. In the short terms, there are workarounds with API management solutions where you can inspect the token from the user and force a user into a specific patient compartment based on some user table.

**Comment by uxbridgeroad** [comment]
hi @hansenms, I did not fully understand what you meant by "and force a user into a specific patient compartment based on some user table" .

Could you explain this further?
Thanks,

**Comment by hansenms** [comment]
I meant, I think, based on some information in the token and some other source of information, say a user is searching for `/Observation`, API management would look at the token and say, this is actually Patient with id `1234`, so API will rewrite the search to be `/Patient/1234/Observation`

**Comment by CaitlinV39** [comment]
@uxbridgeroad do you still have additional questions on Michael's suggestion? As he mentioned, we are doing some work on RBAC but don't have new features prioritized right now or any timeline for updates.
