### ISSUE TITLE
Data Importing

### ISSUE THREAD

**Issue by salacsoft** [microsoft/fhir-server#1027]
**User story**
As a Developer, I want to import the data I generate using the synthetichealth/Synthea.  how can I import it?

**Acceptance criteria**
1. Test Uploaded data from synthea.

**Comment by hansenms** [comment]
Have you looked at the https://github.com/Microsoft/fhir-server-samples repo, it has an Azure function that imports Synthea patients.

**Comment by salacsoft** [comment]
> Have you looked at the https://github.com/Microsoft/fhir-server-samples repo, it has an Azure function that imports Synthea patients.

should i clone the repo and deploy it to my azure resources? Sorry I am still newbie, thank you

**Comment by hansenms** [comment]
That depends on what you are trying to do. If you are just looking for a quick and dirty to load some synthea data, you could use this command line tool I have:

https://github.com/hansenms/FhirLoader

But if you want more of a demo environment of data loader, web app for accessing the data, etc. then you can follow the deployment instructions in https://github.com/Microsoft/fhir-server-samples to deploy the whole demo environment.

**Comment by salacsoft** [comment]
> That depends on what you are trying to do. If you are just looking for a quick and dirty to load some synthea data, you could use this command line tool I have:
> 
> https://github.com/hansenms/FhirLoader
> 
> But if you want more of a demo environment of data loader, web app for accessing the data, etc. then you can follow the deployment instructions in https://github.com/Microsoft/fhir-server-samples to deploy the whole demo environment.

I now uploaded the data in storage account. I watched your video on youtube https://www.youtube.com/watch?v=5vS7Iq9vpXE&t=696s, But I don't know how to reflect it in our server. iIsaw video about private links and functions, but I am still struggling.

**Comment by hansenms** [comment]
Did you deploy the fhir-server-samples environment? Or did you just deploy the FHIR service and then upload patients to a storage account?

**Comment by salacsoft** [comment]
> Did you deploy the fhir-server-samples environment? Or did you just deploy the FHIR service and then upload patients to a storage account?

no i did not deploy the fhir-server-samples, my colleague created resource azure api for FHIR. 
![image](https://user-images.githubusercontent.com/28214978/82244840-dd06f000-990f-11ea-9e7a-eb50d8c751f8.png)
then I just upload the patient in storage account.

**Comment by hansenms** [comment]
Just uploading the patients to a storage account is not going to do it, there has to be something ingesting them into the FHIR service. I would recommend you start with the command line tool that I listed above and you can upload them from your local computer.

**Comment by salacsoft** [comment]
> Just uploading the patients to a storage account is not going to do it, there has to be something ingesting them into the FHIR service. I would recommend you start with the command line tool that I listed above and you can upload them from your local computer.

this one? **https://github.com/hansenms/FhirLoader**

**Comment by hansenms** [comment]
Yes, that command line tool:

https://github.com/hansenms/FhirLoader

You will need to create a service client application in Azure Active Directory:

https://docs.microsoft.com/en-us/azure/healthcare-apis/register-service-azure-ad-client-app

And you will need to make sure that this service client has access to the FHIR API.

I would use something like Postman to verify that you can access the FHIR API before starting to upload patients.

**Comment by salacsoft** [comment]
> Yes, that command line tool:
> 
> https://github.com/hansenms/FhirLoader
> 
> You will need to create a service client application in Azure Active Directory:
> 
> https://docs.microsoft.com/en-us/azure/healthcare-apis/register-service-azure-ad-client-app
> 
> And you will need to make sure that this service client has access to the FHIR API.
> 
> I would use something like Postman to verify that you can access the FHIR API before starting to upload patients

I test my connection using postman I have access on fhir api, I am getting some patients. 
But I encountered another problem, i as just want to check the command --version 
![image](https://user-images.githubusercontent.com/28214978/82246583-f8272f00-9912-11ea-8fbf-aa5581a9a417.png)
![image](https://user-images.githubusercontent.com/28214978/82246660-19881b00-9913-11ea-8f5a-5676af21bc9e.png)

**Comment by salacsoft** [comment]
> Yes, that command line tool:
> 
> https://github.com/hansenms/FhirLoader
> 
> You will need to create a service client application in Azure Active Directory:
> 
> https://docs.microsoft.com/en-us/azure/healthcare-apis/register-service-azure-ad-client-app
> 
> And you will need to make sure that this service client has access to the FHIR API.
> 
> I would use something like Postman to verify that you can access the FHIR API before starting to upload patients.

Thank you,, I will try it.

**Comment by salacsoft** [comment]
> Yes, that command line tool:
> 
> https://github.com/hansenms/FhirLoader
> 
> You will need to create a service client application in Azure Active Directory:
> 
> https://docs.microsoft.com/en-us/azure/healthcare-apis/register-service-azure-ad-client-app
> 
> And you will need to make sure that this service client has access to the FHIR API.
> 
> I would use something like Postman to verify that you can access the FHIR API before starting to upload patients.

I encountered error here I just replace the {tenant_id} with my tenant id 
![image](https://user-images.githubusercontent.com/28214978/82247696-d62eac00-9914-11ea-9e34-1a6b9b3bd9ad.png)

**Comment by hansenms** [comment]
Looks like there is an actual argument name missing. Hard to help without seeing the command you typed. Can you paste it here (not screenshot, but text) and remove any sensitive data.

**Comment by salacsoft** [comment]
> Looks like there is an actual argument name missing. Hard to help without seeing the command you typed. Can you paste it here (not screenshot, but text) and remove any sensitive data.

dotnet run -- --client-secret "client-secret" --client-id "client-id" --input-folder ..\synthea-fhir\output\fhir\ --authority "https://login.microsoftonline.com/tenantid" --fhir-server-url "https://akos-staging.azurehealthcareapis.com" --max-degree-of-parallelism 14

Response file not found 'clientsecret'
Required argument missing for option: --client-secret
Unrecognized command or argument 'https://login.microsoftonline.com/tenantid'

**Comment by hansenms** [comment]
Based on your previous comments, it looks like you are on linux, so you should not have back slashes in there...and the input folder should point to where your synthea data actually is.

**Comment by salacsoft** [comment]
> Based on your previous comments, it looks like you are on linux, so you should not have back slashes in there...and the input folder should point to where your synthea data actually is.

the location of my FhirLoader and the sythea-fhir are in the same root folder, Okay ill remove the backslashes and try it again. Thank you

**Comment by salacsoft** [comment]
> Based on your previous comments, it looks like you are on linux, so you should not have back slashes in there...and the input folder should point to where your synthea data actually is.

As i tried again, the third error disappeared after i replace the back slashes with forward slash, is the client secret should be file and not the string value? Thank you

**Comment by hansenms** [comment]
Client secret is a string value. And so is client id. I would recommend that you first:

1. Set up a service client first.
2. Validate that you can get a token for this service client (Azure Active Directory client credentials flow, e.g. https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-oauth2-client-creds-grant-flow).
3. Validate that the token you get can be used to access the FHIR API.

In that process you will figure out what client id and client secrets are and make sure they work. It will be impossible to debug if you don't know that you have a working client application.

**Comment by salacsoft** [comment]
> Client secret is a string value. And so is client id. I would recommend that you first:
> 
> 1. Set up a service client first.
> 2. Validate that you can get a token for this service client (Azure Active Directory client credentials flow, e.g. https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-oauth2-client-creds-grant-flow).
> 3. Validate that the token you get can be used to access the FHIR API.
> 
> In that process you will figure out what client id and client secrets are and make sure they work. It will be impossible to debug if you don't know that you have a working client application.

I can get token using the postman with client credential,  I can also get patients using the token received from the postman.

**Comment by hansenms** [comment]
> I can get token using the postman with client credential, I can also get patients using the token received from the postman.

Then you should have a client secret.

**Comment by salacsoft** [comment]
> > I can get token using the postman with client credential, I can also get patients using the token received from the postman.
> 
> Then you should have a client secret.

yes,I put it inside the double quote after the --client-secret "@682-83=" something like that.

**Comment by salacsoft** [comment]
> > I can get token using the postman with client credential, I can also get patients using the token received from the postman.
> 
> Then you should have a client secret.

by the way the first character of my client secret is @ when i tried to remove the script seems to run but I am getting invalid credentials, when I put it back i got the error "response file not found"

**Comment by hansenms** [comment]
Try single quotes instead. You are probably using a shell that tries to evaluate the stuff in the quotes.

**Comment by salacsoft** [comment]
> Try single quotes instead. You are probably using a shell that tries to evaluate the stuff in the quotes.

yeah,i also tried it. but still i got the same error. I am thinking its like there is something with the @ at the beginning of the client secret. I don't know why this trigger the error.

**Comment by hansenms** [comment]
You may have to iterate a bit to figure out what the right way to pass in those arguments. I have run that loader from Linux, so it should work. You can always generate a new secret without `@` in it.

**Comment by salacsoft** [comment]
> You may have to iterate a bit to figure out what the right way to pass in those arguments. I have run that loader from Linux, so it should work. You can always generate a new secret without `@` in it.

okay ill try to generate again. Thank you

**Comment by salacsoft** [comment]
> You may have to iterate a bit to figure out what the right way to pass in those arguments. I have run that loader from Linux, so it should work. You can always generate a new secret without `@` in it.

I'm getting this response now in my terminal , is this correct?
![image](https://user-images.githubusercontent.com/28214978/82259278-49dab400-9929-11ea-85f1-8ad58264db6b.png)

**Comment by hansenms** [comment]
That looks right. You should be seeing patients in the database. You might want to consider scaling up your FHIR API throughput (looks like you are running at the default 400 RUs, so it is a bit slow and you are getting "Too Many Requests" error.

**Comment by salacsoft** [comment]
> That looks right. You should be seeing patients in the database. You might want to consider scaling up your FHIR API throughput (looks like you are running at the default 400 RUs, so it is a bit slow and you are getting "Too Many Requests" error.
> 
> You can also scale back the degree of parallelism to avoid some of the warnings and retries.

another question, can we access directly in the database?

**Comment by hansenms** [comment]
> another question, can we access directly the database?

No, not in the managed service. But if you want to run it yourself, you can deploy the Open Source code (this repo) and you would have access to the resources. 

That said, the the database schema is an "implementation detail" and is focused on search parameters and not necessarily on access to the raw FHIR resources. So it may be less useful that you would imagine.

**Comment by hansenms** [comment]
I'm gonna close this issue now.

**Comment by salacsoft** [comment]
> > another question, can we access directly the database?
> 
> No, not in the managed service. But if you want to run it yourself, you can deploy the Open Source code (this repo) and you would have access to the resources.
> 
> That said, the the database schema is an "implementation detail" and is focused on search parameters and not necessarily on access to the raw FHIR resources. So it may be less useful that you would imagine.

Thank you
