### ISSUE TITLE
Creating extensions

### ISSUE THREAD

**Issue by apmis** [microsoft/fhir-server#1028]
**User story**
As a User, I want to extend the patient resource so that  it can take more custom data endpoints.

How do I do this with the azure api for fhir?
Thanks

**Comment by hansenms** [comment]
You can add extensions on FHIR resources. Are you asking for some other feature.

**Comment by apmis** [comment]
Thanks @hansenms 
It is actually a question not a feature request!
I am looking for a "How-to"  step by step process. 
(I am relatively new to fhir)
Thanks once again

**Comment by hansenms** [comment]
Have you looked at this:

https://www.hl7.org/fhir/extensibility.html

**Comment by brendankowitz** [comment]
Closing this issue, this scenario is covered by using FHIR Extensions.
@apmis, please reopen if you find something that doesn't work as expected
