### ISSUE TITLE
Quantity values need to be indexed with min and max

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#103]
Condition.abatement-age search parameter is a quantity search parameter but the value can be a Range, which has low and high. To support this scenario, the quantity value needs to be indexed with both numbers in order to evaluate.

**Comment by CaitlinV39** [comment]
Opened investigation story for this AB#75836

**Comment by namadabu** [comment]
@CaitlinV39 I haven't yet looked into this as part of my current feature work. Not sure about others.
