### ISSUE TITLE
Support `$import`

### ISSUE THREAD

**Issue by salacsoft** [microsoft/fhir-server#1032]
**User story**
As a Developer, I want to transfer all the uploaded data from my local storage to my fhir service, I watched your video in youtube after you imported the names in became available to your Fhir Patient Resource how did you that? how can I trigger my storage account to transfer the data to my fhir service after I uploaded it?

**Acceptance criteria**
1. When I do Uploading to my local storage it should become available to my Fhir resources. We already have fhir service created. we can already add data using Postman with client credential token.

**Comment by hansenms** [comment]
Looks like a repeat of #1027 

I am going to rename this to reflect the work already being considered for `$import`
