### ISSUE TITLE
Link Account Storage to Fhir Database

### ISSUE THREAD

**Issue by salacsoft** [microsoft/fhir-server#1034]
**User story**
As a developer, I want to link my storage account to fhir database so that everytime i upload in storage container it will transfer the data to Fhir Database.

**Acceptance criteria**
1. When I do upload in my storage account it will automatically sync to my Fhir Database.

**Comment by hansenms** [comment]
It feels like this is some variation on #1027 and #1032 and is really about supporting the `$import` operator?

**Comment by CaitlinV39** [comment]
@salacsoft do you feel like your issue is captured in #1027 and #1032 or could you give more details on how this differs? Thanks!
