### ISSUE TITLE
Add support for "_sort" by "_lastUpdate" descending 

### ISSUE THREAD

**Issue by holpit** [microsoft/fhir-server#1037]
**User story**
As a user of HL7 FHIR Version 4, I want to search and **sort** results by **_lastUpdated** **descending** so that I can easily retrieve all the resources type in the order tipically used to display information to the end user.
Last informations are the most relevant.

**Acceptance criteria**
Create many resources eg Observation related to the same Patient;
Search all the Observation for that Patient with **_sort=-_lastUpdated**
Observations are retrived in descending order

This simple case resolve many use cases.

**Comment by brendankowitz** [comment]
Hi @holpit, we hear you. I don't have any ETAs on this just yet, but it is on our list of priorities

**Comment by CaitlinV39** [comment]
@rbans96 is this resolved or is there more work pending?

**Comment by rbans96** [comment]
> @rbans96 is this resolved or is there more work pending?

This is resolved.

**Comment by minhdongsss** [comment]
How about "_sort" by "name"?. Example Organization's name
