### ISSUE TITLE
sever failed

### ISSUE THREAD

**Issue by nono66s** [microsoft/fhir-server#1039]
**Describe the bug**
deploy failed

this how i set the sever
(because i can't find where to filled the repository url and repository branch so i filled at Msdeploy package url , is that wrong?)
![error](https://user-images.githubusercontent.com/50786471/82870029-d99fe400-9f61-11ea-9aee-c03745036d74.png)

and after i click ok it shows that i deploy failed
![error1](https://user-images.githubusercontent.com/50786471/82870120-03f1a180-9f62-11ea-9d67-28bfe3e41cb5.png)

![error2](https://user-images.githubusercontent.com/50786471/82870155-110e9080-9f62-11ea-8bb0-f7ad37e86694.png)

i wondering how to deal with this problem @@

**Comment by brendankowitz** [comment]
Hi @nono66s, the "MSDeploy Package Url" is an optional field, if you leave this blank the default will be used based on the FHIR Version you pick.
For the SQL deployment, make sure you also follow the [password complexity](https://docs.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver15#password-complexity) requirements

**Comment by nono66s** [comment]
Thanks i have successful deploy
