### ISSUE TITLE
Email Validation

### ISSUE THREAD

**Issue by salacsoft** [microsoft/fhir-server#1048]
**User story**
As a Developer, I want to validation email if it is already existing in the patient list so that I can avoid duplicate entry with the same email.

**Acceptance criteria**
1. When I do Post Request in Patients It should validate first before saving it in Fhir Resource.

**Comment by hansenms** [comment]
If you do a PUT to Patient with a specific patient id, e.g. if you are creating a patient with `id` = `123`, you would upsert it at `/Patient/123` and if it exists, we will make a new version (but not a new patient) and if it doesn't exist, it will get created.

You can also look at conditional create (https://www.hl7.org/fhir/http.html#ccreate) and update (https://www.hl7.org/fhir/http.html#cond-update)

**Comment by salacsoft** [comment]
What if I want to validate it against the email address, sometimes the payload does not have the id, the email address is inside telecom property right? I tried Patient?email=test@email.com but it did not work

**Comment by hansenms** [comment]
>  I tried Patient?email=test@email.com but it did not work

What do you mean by "it didn't work"? And have you looked at conditional create as suggested.

**Comment by hansenms** [comment]
So I just did a small test, if you `POST` this /Patient:

```http
POST https://<myaccount>.azurehealthcareapis.com/Patient
```

with payload:

```json
{
    "resourceType": "Patient",
    "active": true,
    "telecom": [
    	{
    		"system": "email",
    		"value": "jim@enterprise.com"
    	}
    ],
    "name": [
        {
            "use": "official",
            "family": "Kirk",
            "given": [
                "James",
                "Tiberious"
            ]
        },
        {
            "use": "usual",
            "given": [
                "Jim"
            ]
        }
    ],
    "gender": "male",
    "birthDate": "1960-12-25"
}
```

And set the following header:

```
If-None-Exist: email=jim@enterprise.com
```

The Patient will only get created if there is no patient with that email.

**Comment by brendankowitz** [comment]
This scenario sounds like it is covered by Conditional-Create/Update, I'm closing this for now. 
@salacsoft, please reopen if there is a bug or it doesn't perform as described

**Comment by salacsoft** [comment]
yeah, I got the wrong parameter as I look to conditional create, I replace email with _tag, it updates the  patient data with the current payload. but what if I don't want to update it instead it will just give me the error response that the email is already in used?

**Comment by salacsoft** [comment]
oh i havent used the if-none-exist i only used the put method with _tag parameter, it creates the patient when its not existing and update it if its already existing. I dont know how to use the if-none-exists in postmant where should i put it?

**Comment by salacsoft** [comment]
Thank you,it works as describe, I'm just expecting 422 response if the entity is already existing.

**Comment by hansenms** [comment]
![image](https://user-images.githubusercontent.com/1149740/83460314-f08b7e00-a41a-11ea-9847-98f8fae4e908.png)

**Comment by salacsoft** [comment]
yeah, I saw it too. Thank you hansenms you are very kind.
