### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by Baruch4413** [microsoft/fhir-server#1053]
**User story**
As a developer, I want to translate the schemas in order to support multiple languages.

**Acceptance criteria**
If I can query an endpoint and get the data but with corresponding keys:

| Column | Data  |
|----------|-------------|
| identificador | 1 |
| activo  | 1 |
| nombre | Baruch |
| sexo | male |

instead of:

| Column | Data  |
|----------|-------------|
| identifier | 1 |
| active  | 1 |
| name| Baruch |
| gender | male |

**Comment by hansenms** [comment]
Traditionally one would not localize (translate) the API as it is a contract between server and a client primarily. While it is somewhat readable by a human, it should mostly be machine readable and changing languages in software depending on the location of the API would not be encouraged. It would also be a violation of the FHIR spec. So I am gonna have to label this a "won't fix". This is not something we will be adding.
