### ISSUE TITLE
Hl7.Fhir.R5' may2020 returns fhirVersion": "4.2.0", expected is fhirVersion": "4.4.0",

### ISSUE THREAD

**Issue by uxbridgeroad** [microsoft/fhir-server#1054]
I wanted to test Updated package 'Hl7.Fhir.R5' to version '1.7.0-beta-may2020' (#1013).

Deployed R5 server  (via ARM  template and also via https://github.com/Microsoft/fhir-server/blob/master/docs/DefaultDeployment.md)
Checked the https://SERVICENAME.azurewebsites.net/metadata to obtain a capability statement which returned fhirVersion": "4.2.0", expected is fhirVersion": "4.4.0",

Many of the expected search parameters for SubstanceDefinition ado not seem to be available.

Is this expected or is there additional config need to deploy beta-may2020?

**Expected behavior**
capability statement returned fhirVersion": "4.4.0",

**Actual behavior**
capability statement returned fhirVersion": "4.2.0",

**Comment by brendankowitz** [comment]
I was testing something today and noticed newer functionality was missing with these deployments. I think a build step that updates these zip packages was missed when we moved to the unified build pipelines. Looking at getting this fixed

**Comment by brendankowitz** [comment]
Builds have been updated, you should be able to update (redeploy) now.
