### ISSUE TITLE
Cosmos db - partitioning in test environment

### ISSUE THREAD

**Issue by ellgre** [microsoft/fhir-server#1056]
**User story**
As a software developer, I want to be able to set partitioning rules for cosmos db in test  so that the datebase will be physically partitioned at a smaller size in test so that I can test partitioning functionality.

**Acceptance criteria**
1. When I set partitioning rules in test and when the selected treshold for physical partitioning is reached, then the test cosmos db database is physically partitioned .

**Comment by hansenms** [comment]
I think this probably more of a question for Cosmos DB, but I believe that if you set the throughput > 10k RU/s you will get another partition. Did you try that?

**Comment by CaitlinV39** [comment]
@ellgre I wanted to follow up to see if you had additional questions after trying Michael's suggestion above? Please let me know otherwise I will plan to close out the issue. Thanks!

**Comment by ellgre** [comment]
Thank  you for following up. Michael’s suggestion worked perfectly for us.
