### ISSUE TITLE
Wrong results when doing paginated searches within single http-request scope

### ISSUE THREAD

**Issue by emyklebost** [microsoft/fhir-server#1057]
Hi,

We're developing a register using the fhir-server packages and cosmosdb. To meet business-requirements we've injected extra logic as mediatr-pipeline-behaviors (validation etc.). This has worked fine, but we've recently encountered problems after the cosmosdb started using multiple physical partitions and the results are spread across multiple pages.

As part of our business-logic within a pipeline-behavior we use the mediator to search for resources using business-identifiers. The searches are simple and expects 0 or 1 results, and we iterated using the continuation-token to handle cases where the result is not on the first page. The issue is that we now experience unexpected behavior, e.g.:

1. We have a custom-endpoint (our own controller) where we use the mediator to execute SearchResourceRequests, but queries are not respected, the internal searches always returns ALL resources.
2. We have a pipeline-behavior on SearchResourceRequest where we do multiple internal searches (sequentially): The first search gives the expected outcome and the following searches gives the same result as the first one, even if the queries and expected outcome are different.

We are aware that this probably is a use-case that you have not intended, and we are considering moving this functionality into some sort of API-gateway in front of the fhir-server API. However, we would very much appreciate if you have some insight into what is happening and how we are able to fix this.

Thank you.

Edit: I believe I have resolved the issue. When doing these "internal-searches" the bundle's next-link only contains the continuation-token, not the initial query-parameters. The next-page will therefore have unexpected results. It has been my understanding that the continuation-token itself contained enough information, but that seems to not be the case.

**Comment by hansenms** [comment]
I am not sure I totally follow what you are doing here, but it does sound like some behavior you should really put in an API management layer instead of working it into the code like this. If for no other reason than it makes it hard for you to update your FHIR server code when it updates here and we may make some changes to the specific areas you have modified thus breaking your code. The only contract here is really the FHIR API, rest is an implementation detail.

Sounds like we might be able to close this for now? But I will let @brendankowitz comment first in case he has some thoughts on this.

**Comment by emyklebost** [comment]
> I am not sure I totally follow what you are doing here, but it does sound like some behavior you should really put in an API management layer instead of working it into the code like this. If for no other reason than it makes it hard for you to update your FHIR server code when it updates here and we may make some changes to the specific areas you have modified thus breaking your code. The only contract here is really the FHIR API, rest is an implementation detail.
> 
> Sounds like we might be able to close this for now? But I will let @brendankowitz comment first in case he has some thoughts on this.

You may close it since we've been able to resolve it. We would still appreciate some feedback from @brendankowitz.
 I totally agree that it would be better to have this functionality in a separate API-layer and the separation shouldn't be too difficult due to how the code is structured. However, the current solution works well enough and such a separation is therefore not a priority at the moment.

**Comment by brendankowitz** [comment]
Just to get a clearer picture, is your project forked from our repository, or are you using a new web project and importing the nuget packages?

I think feedback from your project is valuable to to learn how our FHIR Server is being used to build new solutions. Having said that, we would not be able to provide support for customizations to our code, including extending or modifying the behavior, unless there was a bug that can be reproduced with the unmodified code. Beyond this, we haven't 'officially' released our code packages as libraries, so internal dependencies may break and change over time. As Michael suggested above, the only contract we are committed to is the FHIR endpoint itself.

I'm happy to hear that you are able leverage this project to build a solution, but please be cautious of the above. I'm open to continuing to hear your feedback as I'm sure that there will continue to be community projects based on the code here.

**Comment by emyklebost** [comment]
> Just to get a clearer picture, is your project forked from our repository, or are you using a new web project and importing the nuget packages?

We're importing the nuget-pacakges. 

As you've might have figured out I'm part of the same team as @ellgre and I'll be happy to answer any further questions regarding our project by email.

**Comment by brendankowitz** [comment]
Closing this issue here for now
