### ISSUE TITLE
Using Cosmos DB graph database for Azure API for FHIR

### ISSUE THREAD

**Issue by yshin1209** [microsoft/fhir-server#1075]
As a developer, I want to implement and have access to CosmosDB graph database so that I can model FHIR resources as graphs.

**Comment by hansenms** [comment]
When running the OSS, you do have access to the Cosmos DB. Could you clarify what you are trying to do?

**Comment by yshin1209** [comment]
I would like to enjoy both the advantage of using managed Azure API for FHIR while accessing to the Cosmos DB directly using Gremlin API.

**Comment by hansenms** [comment]
We have no plans for providing direct access to the Cosmos DB in the Azure API for FHIR. We consider the database an implementation detail in that environment. Moreover, if you try to deploy the OSS version here with Cosmos DB, you can take a look at the database schema and it may not actually allow you to do what you need to do.

Have you tried using the gremlin API against the OSS server with Cosmos? Does that get you what you need?

**Comment by yshin1209** [comment]
I have not yet tried using the gremlin API against the OSS server with Cosmos DB. I'm building a patient data system using Cosmos DB(graph database), Azure Functions and Azure Event Grid and wondering if the Azure API for FHIR can be integrated with it. It would be great if the Azure API for FHIR becomes more open and flexible so that we can have graph database as a choice and also interoperable so that it can interact with other Azure managed services like Azure Functions and Azure Event Grid.

**Comment by hansenms** [comment]
It is a bit of a balance, when we run this as a managed service, we cannot allow arbitrary access to the database.

Could you maybe start by having a look at whether your integration is possible in OSS and then take it from there. It is about as "open and flexible" as it comes.

**Comment by yshin1209** [comment]
OK. I will try, Thank you.

**Comment by yshin1209** [comment]
OK. I will try. Thank you.

**Comment by CaitlinV39** [comment]
@yshin1209 I'm going to close this issue based on the back and forth with Michael but once you have tried the gremlin API with the open source if you have additional questions please let us know.
