### ISSUE TITLE
History and _at does not return what we expect

### ISSUE THREAD

**Issue by ellgre** [microsoft/fhir-server#1084]
**Describe the bug**
We expect the _at search parameter in combination with _history should give us any document that was valid at the provided date. It seems like we only get the correct document if we use the lastUpdated dates and not for any date between. Qualifiers like ge, le, eq are shown in the self link, but we do not think that they have been used since we get both version regardless of which date we have in input.

**To Reproduce**
1. We have a Patient which has a version updated 2020-06-12 and a version updated 2020-06.15
2. When searching with &_at=2020-06-12 we get version 1 as expected
3. When searching with &_at=2020-06-15 we get version 2 as expected.
4. When searching with &_at=2020-06-13 we get no documents
5. When searching with &_at=2020-06-16 we get no documents

**Expected behavior**
When searching with a date between June 12 and 14 we expect to get version 1, and when searching with June 15 or later we expect to get version 2. When we search with a date before June 12 we expect to get no documents.

**Actual behavior**
Only for searches with the _at=<lastUpdated> we get the expected document in return.
If we input a date qualifier (le, ge, eq) we get both versions regardless of which date we input.

**Comment by brendankowitz** [comment]
Hi @ellgre, in reading through the R4 spec against the current behavior, I think this is a bug

**Comment by ellgre** [comment]
Do you know when we can expect this bug to be solved? 

We get a lot of historic events that we need to react on, and have to get the version of Patient valid at that given point in time in order to use the correct attributes.

**Comment by rbans96** [comment]
@ellgre  Which database are you using? Is it SqlServer or Cosmosdb?

**Comment by ellgre** [comment]
It is Cosmosdb.

**Comment by CaitlinV39** [comment]
AB#74811

**Comment by CaitlinV39** [comment]
AB#75005

**Comment by CaitlinV39** [comment]
@ellgre given how long this has been open we're goign to close for now as won't fix. Please let us know if you are still struggling with this.
