### ISSUE TITLE
Capability statement must be exposed even if AAD is added to FHIR server

### ISSUE THREAD

**Issue by swapnilbjadhav** [microsoft/fhir-server#1093]
**User story**
I am looking for a complete FHIR server setup with API managent using terraform. So my use case is i am creating Azure FHIR Server using the Deployment template and adding the AAD login feature to it. But i want the API to be exposed using API management and thus I am creating it. But, to fetch the api from https://{fhirservername}.azurewebsites.net/metadata i am using the utility https://fhir2apim.azurewebsites.net/ provided by @hansenms  which works like a charm for FHIR API and it couldn't work in my case as the AAD is applied to FHIR server.

So i am looking for a solution wherein, i can access the capability statement like FHIR API or else a way to provide token and access the swagger from https://{fhirservername}.azurewebsites.net/

**Acceptance criteria**
1. When I do [A], then [B] happens.

**Comment by brendankowitz** [comment]
The `/metadata` endpoint is configured with Anonymous access by default. If you've generated a client then it would need to provide a token to call the API after this

**Comment by swapnilbjadhav** [comment]
For Azure FHIR API /metadata is anonymous without client and its token,it works but, for Azure FHIR Server it is not anonymous if client is generated

**Comment by hansenms** [comment]
The `/metadata` endpoint is anonymous on both the Azure API for FHIR and the OSS FHIR server for Azure. How did you enable auth for the OSS FHIR server. Did you by any chance use app service authentication or something like that instead of enabling auth with app settings on the web app?

**Comment by CaitlinV39** [comment]
@swapnilbjadhav I wanted to see if you had additional details based on Michael's questions or if your issues is resolved. Let us know how we can help. Thanks!
