### ISSUE TITLE
Error - while running from local machine directly

### ISSUE THREAD

**Issue by nagendra421** [microsoft/fhir-server#1094]
URL - https://localhost:44348/
It keep on showing loading and after sometime I get an error, can someone please help me.

SocketException: No connection could be made because the target machine actively refused it.

**Comment by brendankowitz** [comment]
It sounds like one of the dependencies is not running, check you have CosmosDB emulator, Azure Storage Emulator and SQL Server running

**Comment by brendankowitz** [comment]
I'm closing this for now, I've added some information to the wiki section (https://github.com/microsoft/fhir-server/wiki/Build-and-debug-locally) please see if this resolves the issue.
