### ISSUE TITLE
Page results for searches with reference chaining are incorrect after the first page (SQL)

### ISSUE THREAD

**Issue by 7opf** [microsoft/fhir-server#1095]
[repro-transaction.zip](https://github.com/microsoft/fhir-server/files/4831971/repro-transaction.zip)

**Describe the bug**

Page results for searches with reference chaining are incorrect after the first page (SQL).

**To Reproduce**
1. Create a search with `_count=x`, `_total=accurate` and a chained reference parameter e.g.
```
/Observation?patient.organization=Organization/123&_count=2&_total=accurate
```
2.  First page returns correct `Bundle.total` (ensure > x) and first page of results (x results). However following the link with relation "next" yields a page with only one entry in the bundle and no relation for "next" in `Bundle.link`.

**Expected behavior**

Following links with the continuation token should return the next set of results as per the chained query.

**Actual behavior**

Server returns a second page with one entry and no subsequent pages

**Comment by 7opf** [comment]
Added transaction to reproduce the issue

**Comment by anyname2** [comment]
Generated SQL query for the second page has a `SELECT DISTINCT TOP (@p6)` where `@p6` is set to `_count+1` (see `cte2` in the query below), which limits the results before the continuation token is applied.
```sql
DECLARE @p0 SmallInt = 200;
DECLARE @p1 SmallInt = 96;
DECLARE @p2 SmallInt = 103;
DECLARE @p3 SmallInt = 940;
DECLARE @p4 SmallInt = 100;
DECLARE @p5 VarChar(64) = '20489ae9-ee15-4805-8749-442f409bdbfe';
DECLARE @p6 Int = 3;
DECLARE @p7 BigInt = 5098295252858560160;

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

WITH cte0 AS
(
    SELECT ref.ResourceSurrogateId AS Sid1, r.ResourceSurrogateId AS Sid2
    FROM dbo.ReferenceSearchParam ref
    INNER JOIN dbo.Resource r
    ON ref.ReferenceResourceTypeId = r.ResourceTypeId
        AND ref.ReferenceResourceId = r.ResourceId
    WHERE ref.SearchParamId = @p0
        AND r.IsHistory = 0
        AND ref.IsHistory = 0
        AND ref.ResourceTypeId = @p1
        AND ref.ReferenceResourceTypeId = @p2
),
cte1 AS
(
    SELECT Sid1, ResourceSurrogateId AS Sid2
    FROM dbo.ReferenceSearchParam
    INNER JOIN cte0
    ON ResourceSurrogateId = Sid2
    WHERE IsHistory = 0
        AND SearchParamId = @p3
        AND ReferenceResourceTypeId = @p4
        AND ReferenceResourceId = @p5

),
cte2 AS
(
    SELECT DISTINCT TOP (@p6) Sid1, 1 AS IsMatch
    FROM cte1
    ORDER BY Sid1 ASC
)
SELECT r.ResourceTypeId, r.ResourceId, r.Version, r.IsDeleted, r.ResourceSurrogateId, r.RequestMethod, CAST(IsMatch AS bit) AS IsMatch, r.RawResource
FROM dbo.Resource r
INNER JOIN cte2
ON r.ResourceSurrogateId = cte2.Sid1
WHERE ResourceSurrogateId > @p7
  AND ResourceTypeId = @p1
ORDER BY r.ResourceSurrogateId ASC
OPTION(RECOMPILE)
```

**Comment by johnstairs** [comment]
Thanks for the bug report. You are right - we should be promoting the predicate on the ResourceSurrogateId column to an earlier CTE. The bug is we skip this because of the chaining.

Working on a fix.

**Comment by anyname2** [comment]
Just tested it on master 60f8975 - bug is fixed
