### ISSUE TITLE
Add Azure CosmosDB configuration for web/arm template for FHIR Server 

### ISSUE THREAD

**Issue by swapnilbjadhav** [microsoft/fhir-server#1096]
**User story**
I am following the link provided for Azure FHIR server setup which consists of SQL server configuration: https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FMicrosoft%2Ffhir-server%2Fmaster%2Fsamples%2Ftemplates%2Fdefault-azuredeploy-sql.json

What changes i need to do if i want it to be defaulted to Azure Cosmos DB instead of SQL Server?

**Acceptance criteria**
1. When I do [A], then [B] happens.

**Comment by brendankowitz** [comment]
The CosmosDB templates still exists (just remove the `-sql`): https://raw.githubusercontent.com/microsoft/fhir-server/master/samples/templates/default-azuredeploy.json
