### ISSUE TITLE
Link Next have issue 

### ISSUE THREAD

**Issue by ddst0111** [microsoft/fhir-server#1102]
**Describe the bug**
When a Encounter resource have more than 200+ mediciationRequest resource, query MedicationRequest using Encounter identifier cannot get all MedicationRequest

**To Reproduce**
1.1. the first query
 https://{{fhirserver}}/MedicationRequest?context:Encounter.identifier=12345673&_include=MedicationRequest:medication

will return the link like 
"link": [
        {
            "relation": "next",
            "url": "https://{{fhirserver}}/MedicationRequest?context%3AEncounter.identifier=12345673&_include=MedicationRequest%3Amedication&ct=NTA5ODI5MDk5NTI3NDUwMTM5Ng%3D%3D"
        },
        {
            "relation": "self",
            "url": "https://{{fhilserver}}/MedicationRequest?context%3AEncounter.identifier=12345673&_include=MedicationRequest%3Amedication"
        }
    ],

 
2. when use the "next" url returned from the first query, i.e., expecting the result will have a new "next" link
https://azurefhir-prod.azurewebsites.net/MedicationRequest?context%3AEncounter.identifier=12345673&_include=MedicationRequest%3Amedication&ct=NTA5ODI5MDk5NTI3NDUwMTM5Ng%3D%3D

**Expected behavior**
A clear and concise description of what you expected to happen, we expect the "next" link will have a new "ct", so can continue the navigation

**Actual behavior**
But the next link returned is the same as the 
"link": [
        {
            "relation": "next",
            "url": "https://{{fhirserver}}/MedicationRequest?_include=MedicationRequest%3Amedication&context%3AEncounter.identifier=12345673&ct=NTA5ODI5MDk5NTI3NDUwMTM5Ng%3D%3D"
        },
        {
            "relation": "self",
            "url": "https://{{fhirserver}}/MedicationRequest?_include=MedicationRequest%3Amedication&context%3AEncounter.identifier=12345673&ct=NTA5ODI5MDk5NTI3NDUwMTM5Ng%3D%3D"
        }
    ]

**Comment by ddst0111** [comment]
when query with the _summary=count can see the total is: 249
{
    "resourceType": "Bundle",
    "id": "3141835d-2989-40e8-8cc0-f796b7d67f0e",
    "type": "searchset",
    "total": 249
}

**Comment by johnstairs** [comment]
Potentially the same issue as #1095. Investigating....
