### ISSUE TITLE
Error with FHIR hosted on local IIS

### ISSUE THREAD

**Issue by only1sham** [microsoft/fhir-server#1110]
I was able to setup FHIR server on my local machine with SQL Express as data store. I tried publishing and hosting it on local IIS. However, the following error is displayed while accessing the web site hosted on my local IIS - 

crit: Microsoft.Health.SqlServer.Features.Schema.SchemaInitializer[0]
      There was no connection string supplied. Schema initialization can not be completed.
fail: Microsoft.Health.Fhir.Core.Features.Operations.Export.ExportJobWorker[0]
      Unhandled exception in the worker.
System.InvalidOperationException: The ConnectionString property has not been initialized.

I do see that the connection string is present in appSettings.json file after publish. The application runs fine when it is executed from Visual Studio, but throws the above error when run from CLI or IIS hosted website url. I'm suspecting some setup issue with local IIS or may be SQL Express. Kindly let me know what could be the issue here.

**Comment by brendankowitz** [comment]
Local IIS is not a typical scenario we are running or testing with. When launching from VS there are launch settings that are applied from (https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.R4.Web/Properties/launchSettings.json#L25) that override some settings and provide others not defined in appSettings.json, make sure all of these exist in your deployment

**Comment by only1sham** [comment]
Thank you @brendankowitz. I was able to run it after adding the required profile in launchSettings.json.
