### ISSUE TITLE
Restarting service when deployed from Release image automatically updates

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#1111]
**Describe the bug**
When a FHIR server is restarted and it was deployed as a docker container for the Release image the image will be pulled from the container store, updating the server to the most recent version with no user input or notification.

**To Reproduce**
1. Deploy a server using the docker template and use the Release image
2. Wait for a new version of the server to be released
3. Restart the server

**Expected behavior**
The server's version shouldn't change after the restart

**Actual behavior**
The server is updated to the most recent version

**Comment by CaitlinV39** [comment]
AB#76145

**Comment by CaitlinV39** [comment]
@rbans96 & @Ivanidzo4ka did we resolve this recently?

**Comment by Ivanidzo4ka** [comment]
I've never looked into it, so I can't comment.

**Comment by LTA-Thinking** [comment]
I haven't tested it recently, but we haven't done anything to fix this. This is a result of how the Azure Web App works, not something in our service. Given that MCR requires a latest tag there isn't an easy way to prevent this on our end. The best I can think of is to state it in our documentation as a risk of using the latest tag when setting up a service.

**Comment by CaitlinV39** [comment]
Thanks @LTA-Thinking! We were doing some backlog grooming and we weren't sure. I'll mark for a documentation update.

**Comment by CaitlinV39** [comment]
Closing since there are simple work arounds
