### ISSUE TITLE
Paged search results made with POST don't support subsequent GET  

### ISSUE THREAD

**Issue by holpit** [microsoft/fhir-server#1115]
**Describe the bug**
I'm using the https://github.com/FirelyTeam
When the result of search done with a POST request has more pages, a subsequent call to the next link raise an error

**To Reproduce**
1. Make a search with POST https://fhirserverxyz/ClinicalImpression/_search
with x-www-form-urlencoded parameters:
_include ClinicalImpression:subject
_count  5

2. The bundle has the next link:  "relation": "next", "url": "https://fhirserverxyz/ClinicalImpression/_search?ct=NTA5ODI4ODQ3NTQ4MzY4MDAyMA%3D%3D" 
3. Do a GET with the link to the next page returned throw the error :
`{
    "resourceType": "OperationOutcome",
    "id": "362fda35-053a-4d90-a2e8-9a67838bd245",
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "Id must be any combination of upper or lower case ASCII letters ('A'..'Z', and 'a'..'z'), numerals ('0'..'9'), '-' and '.', with a length limit of 64 characters. (This might be an integer, an un-prefixed OID, UUID, or any other identifier pattern that meets these constraints.)",
            "location": [
                "ResourceKey.Id"
            ]
        }
    ]
}`

**Expected behavior**
The next link must be executed with a GET request as reported in documentation:
http://hl7.org/fhir/http.html#paging
In the case of a search, the initial request may be made via a POST, but the follow up page requests will be made via GET requests. However servers SHOULD allow for a client to convert the follow up requests to be made via a POST.

**Actual behavior**
The next link works only if made with POST to the next url

**Comment by CaitlinV39** [comment]
AB#76144

**Comment by feordin** [comment]
Verified as fixed.
