### ISSUE TITLE
Support Postgre SQL as a datastore

### ISSUE THREAD

**Issue by anyname2** [microsoft/fhir-server#1117]
**User story**
As a sotware engineer, I want to use Postgre SQL as a datastore so that I can use Postgre SQL compatible managed SQL databases on other clouds (e.g. [Amazon Aurora](https://aws.amazon.com/rds/aurora/)).

**Acceptance criteria**
When I deploy FHIR Server I can connect it to a Postgre SQL based datastore.
All features supported by SQL Server datastore, should also be supported by Postgre SQL datastore.

**Additional info**
I have fully implemented support for Postgre SQL datastore for the FHIR Server. I would like to start a discussion, on whether you would be interested in pulling it upstream?

The current implementation basically replaces any references to SQL Server with Postgre SQL and is based on fairly old commit (f20c5b2e). A number of refactorings to existing SQL Server would be neccessary to support both flavours of SQL, but a significant portion of the code is reusable. Hence, before I start on any of that, I would like to know if you would be interested in such a PR.

**Comment by chgl** [comment]
This has been mentioned in previous issues before (https://github.com/microsoft/fhir-server/issues/808 and https://github.com/microsoft/fhir-server/issues/800). I'd be very much interested in Postgres support, especially if it were to also support Databases like YugaByte or CockroachDB which provide compatibility with Postgres clients.

I would absolutely support and help with your efforts if you need!

**Comment by CaitlinV39** [comment]
@anyname2 we don't plan to support Postgres in the future right now, but definitely see the value in doing some of the refactoring work to make it easy for you to use your own SQL datalayer that isn't SQL Server. No timing on when we would do this yet, but will leave this open for this work.

**Comment by CaitlinV39** [comment]
@CaitlinV39 I will actually plan to create a new issue for the refactorin work and close this issue.

**Comment by anyname2** [comment]
Sounds good!
