### ISSUE TITLE
Issue with fhir-server/samples/templates/default-azuredeploy-docker-sql.json

### ISSUE THREAD

**Issue by sethuraj** [microsoft/fhir-server#1119]
**Describe the bug**
The image Tag "release" is causing an issue when I deploy the Azure App service in my environment.

**To Reproduce**
![image](https://user-images.githubusercontent.com/933249/86563171-c3018b00-bf18-11ea-977a-f9dca26d3977.png)

**What fixed
I changed the line 233
From
"linuxFxVersion": "[concat('DOCKER|', variables('registryName'), '/', toLower(parameters('fhirVersion')), '_fhir-server',':', parameters('imageTag'))]"
To
"linuxFxVersion": "[concat('DOCKER|', variables('registryName'), '/', toLower(parameters('fhirVersion')), '_fhir-server')]",

**Shouldn't the tag be "latest" instead of "release".
The api site is now running fine for me and I see that it downloaded the latest image from the registry.

**Comment by brendankowitz** [comment]
@LTA-Thinking can you look at this issue?

**Comment by hansenms** [comment]
@sethuraj, thanks for bringing this to our attention. `latest` is not really the best tag because it could lead to some unexpected behavior, if the apps service restarts you could upgrade unexpectedly. We probably need to make some changes to snap to a specific release in the template. So we will take a look.

That said, the tag `release` should actually be there, but we have an issue with the release pipeline and it is not putting that tag out, so we will take a look at that too.

**Comment by LTA-Thinking** [comment]
Hi @sethuraj 
The `release` tag is meant to be the latest version of the fhir server that has been officially released. The issue with the `latest` tag is that this repository is used for PR testing, so the latest image sent to it could be a PR build and not a version of the master branch. 
We have had some issues with the release pipeline and as you saw there is currently no image with the `release` tag. We are working on remedying this. 
I'll update this when we have a release tag up.
In the meantime I would recommend using the tag `master-20200702-3`.

**Comment by LTA-Thinking** [comment]
There is now a `release` tag for each FHIR version, and the release pipeline has been fixed so it will update it whenever a new release is made.

**Comment by sethuraj** [comment]
> There is now a `release` tag for each FHIR version, and the release pipeline has been fixed so it will update it whenever a new release is made.

Great thanks, will try the release version. Thanks
