### ISSUE TITLE
FHIR Server open-source implementation

### ISSUE THREAD

**Issue by only1sham** [microsoft/fhir-server#1135]
The current FHIR server implementation has a persistence layer that is part of the architecture. If we go with an on-premise option and use the open-source code base as starting point, is it possible to bypass the built-in persistence layer and connect to a raw data store (non-FHIR format)? I understand that we will have to build an integration/aggregator layer on top of it to fetch the data from raw store and also handle data transformations. What I'm trying to figure out is can we use the FHIR server code as-is to cater this need with some config changes and a wrapper on top without modifying the actual source code?

If anyone has tried this style of implementation using Microsoft FHIR open-source code base, can you please share details on it?

**Comment by hansenms** [comment]
What you are describing here is really that you could implement your own persistence provider layer. It is "just" an interface that you would have to implement. But then you could use a suitable logic for your database schema. That said it is not a no-code solution.  So you could look at how the `SearchService` is implemented for CosmosDb (https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.CosmosDb/Features/Search/FhirCosmosSearchService.cs) or for SqlServer (https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.SqlServer/Features/Search/SqlServerSearchService.cs). If you also want CRUD operations then they have to be implemented as well.

**Comment by only1sham** [comment]
Thank you for the response @hansenms. I had a look at the file you mentioned. So what I infer based on my analysis is that apart from implementing the ISearchService interface, we will have to take care of couple more items like configuring the new DataStore in Startup.cs and also adding RegistrationExtensions for the new data store similar to 'FhirServerBuilderSqlServerRegistrationExtensions' correct?

**Comment by brendankowitz** [comment]
I had a fairly minimal example from a DevDays presentation: https://github.com/microsoft/fhir-server/compare/master...brendankowitz:feature/file-storage-provider slides are here: https://github.com/brendankowitz/FHIRDevDays/blob/master/2019/Amsterdam/DD19Adam_HackingFHIRServerForAzure.pdf. Also a sample provider for TableStorage: https://github.com/microsoft/fhir-server/compare/personal/bkowitz/tablestoragetest

**Comment by hansenms** [comment]
@only1sham yes, implementation of the interface would be the bulk of the work (the hard part) and then there would be a few housekeeping issues to instantiate the right provider, etc.
