### ISSUE TITLE
Required SqlServer compatibility mode

### ISSUE THREAD

**Issue by davidegiacometti** [microsoft/fhir-server#1173]
Hi,

I am trying to figure out what is the required compatibility mode.
In the `SqlServerFhirModel.cs` there is an `OPENJSON` used for the data seed and this is supported from [Sql Server 2016](https://docs.microsoft.com/en-us/sql/t-sql/functions/openjson-transact-sql?view=sql-server-ver15).
In attition to the initial data seed (that could be applied in another way) what is the required compatibility mode for FHIR Server?

Regards
Davide

**Comment by CaitlinV39** [comment]
@davidegiacometti we focus on SQL Azure right and the functionality there. We don't want to limit ourselves on a specific version of SQL desktop incase there is future functionality that we want to take advantage of that doesn't have backwards compatibility. Let me know if that helps!

**Comment by davidegiacometti** [comment]
Hi @CaitlinV39, thanks for the clarification.
