### ISSUE TITLE
Transaction error - cant find condition reference in bundle for search create

### ISSUE THREAD

**Issue by yochail** [microsoft/fhir-server#1175]
**Describe the bug**
I’m trying to use FHIR Bundle transaction to write multiple co-referenced resources to the server at once.
Any of those resources may or may not already be on the server. To address that I’m using “Condition update” with “Conditional References” features.
The bundle  have entries as follows:
“Organization” resource – update/create if none exist (PUT+ query)
“Location” resource” – update/create if none exist (PUT+ query)
“ResearchStudy” resource that contains a “Conditional References” to the organization and location resources – Update\Update as Create (PUT+ query)
 
This setup works if the Organization/Location are already created (they will only be updated) and the transaction will succeed.
however, if one of the **referenced resources** from one of the resources are need to be created, the transaction will fail
for the condition reference will not be found
 
Example: (full bundle attached)
Organization?name:exact=Janssen Sciences Ireland UC
ResearchStudy organization reference: Organization?name:exact=Janssen Sciences Ireland UC
Returning error:
{
    "resourceType": "OperationOutcome",
    "id": "fc8317ef-116d-4cbf-b95f-13fec60d6355",
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "Given conditional reference 'Organization?name:exact=Janssen Sciences Ireland UC' does not resolve to a resource."
        }
    ]
}

**To Reproduce**
[FHIRbug-put.txt](https://github.com/microsoft/fhir-server/files/4993285/FHIRbug-put.txt)
1. Post the attached file to fhir server

**Expected behavior**
the resource reference in a research study should be updated together with the resource creation

**Actual behavior**
the server can't find the conditional reference and returned an error

**Comment by yochail** [comment]
looking at the code, I can take a guess about the cause for this:
the method "PopulateReferenceIdDictionary" in "BundleHandler"
that start with:
 if (entry.Request.Method != HTTPVerb.POST)
 {
         continue;
}
this code doesn't address the possibility of an "update-create" scenario (where the method is "PUT" but the resource still should be created and added to the reference dictionary).

**Comment by brendankowitz** [comment]
Sounds like this issue: https://github.com/microsoft/fhir-server/pull/1044 which was merged recently

**Comment by yochail** [comment]
@brendankowitz jackpot!!
I will make sure that solves the bugs for me and close both bugs (this and #1174)
