### ISSUE TITLE
Access to FHIR Server through  external web app

### ISSUE THREAD

**Issue by Lanzadonii** [microsoft/fhir-server#1176]
Forgive me, I am very new to FHIR and still learning how things operate. I just stood up the PaaS solution and following the instructions https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir-paas-portal-quickstart I was able to register an app and connect to the FHIR API via postman no problem as well as stand up the sample web app without issue. My question is I was wondering if there is a way to "whitelist" a url/application external to azure to connect to the FHIR server. For example something like (https://lhncbc.github.io/lforms-fhir-app/) where you wouldnt have the ability to modify the code but you would still like for it to be able to read data from your FHIR API. 

I set the api permissions as application permission 

Under Authentication I added the URL for the site hoping that would whitelist it
![image](https://user-images.githubusercontent.com/60266434/88839582-45443e80-d1a9-11ea-8f0a-3b30609a5835.png)

Doing the above allows me to connect to the server but I get an authenication error trying to access the data.
![image](https://user-images.githubusercontent.com/60266434/88840136-05ca2200-d1aa-11ea-9dba-32dfe841df36.png)

**Comment by hansenms** [comment]
Not sure I fully follow. Are you asking to have the ability to grant a specific client application access to the FHIR API solely based on the the URL of the client application? That is probably not something that would be practical or secure. 

You client application should get a token to access the FHIR API. You can use service-to-service (a service client) authentication to obtain this token within your application.

I may be missing something here, but maybe you can add some details on what you are trying to achieve.

**Comment by CaitlinV39** [comment]
@Lanzadonii I'm going to close this item based on the suggestion Michael made but if you have more details or other questions feel free to reach out. Thanks!
