### ISSUE TITLE
Support searching for implicit group members

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#1179]
**User story**
As a users of the FHIR Server, I want to be able to search for Group members based on Group characteristics so that sets of resources can be defined by rules instead of explicit membership.

**Acceptance criteria**
1. When I search for a Group's members, I get members that match the Group's characteristics.

**Resources**
https://www.hl7.org/fhir/group.html
https://www.hl7.org/fhir/group-definitions.html#Group.characteristic

**Discussion**
The FHIR specification does not define what a characteristic is. It only says it must be a rule that can include or exclude members from a Group in a formal way.

How do we want to define characteristics and use them for testing for Group membership?

**Comment by LTA-Thinking** [comment]
@brendankowitz @namadabu FYI

**Comment by CaitlinV39** [comment]
AB#74401

**Comment by CaitlinV39** [comment]
Right now we aren't going to support this.
