### ISSUE TITLE
Consent management with Azure FHIR server

### ISSUE THREAD

**Issue by only1sham** [microsoft/fhir-server#1182]
Does Azure FHIR implementation provide any option for patient Consent management out of box? Or this has to be implemented separately?

**Comment by hansenms** [comment]
By consent management, I am assuming you mean things like a patient gives consent for somebody else to see their data? That is not built into the FHIR server, but we have some example architectures [here](https://github.com/Microsoft/health-architectures). Specifically, you can look the [FHIR Proxy](https://github.com/microsoft/health-architectures/tree/master/FHIR/FHIRProxy) as an example of how to implement more sophisticated flows.

**Comment by CaitlinV39** [comment]
@only1sham I am going to close this per Michael's response but if you have any additional questions please let us know.
