### ISSUE TITLE
Run search E2E tests in parallel

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#12]
Right now, the parallel execution is disabled because search test needs to setup the data (by deleting known resources first). This is invasive since it's deleting all Patients or all Observation resources and requires the tests to be executed serially. One thing we could do is to attach custom identifiers to the search tests and update the search tests to include this identifier in the search itself. The downside is that string search becomes string search + token search (for identifier) but it should speed up the tests and will not accidentally wipe off data if executed against wrong database.

**Comment by johnstairs** [comment]
IMO yes

**Comment by CaitlinV39** [comment]
AB#76158

**Comment by CaitlinV39** [comment]
Not prioritzed for now so were going to close.
