### ISSUE TITLE
Support for FHIR Release #5: Preview #3  v4.5.0

### ISSUE THREAD

**Issue by uxbridgeroad** [microsoft/fhir-server#1231]
User story
As a user I want my R4/R5 FHIR API to conform to the v4.5.0: Release 5 Preview #3 specification.

http://hl7.org/fhir/2020Sept/index.html  

Acceptance criteria

When I provision a FHIR API, then the CapabilityStatement should say FHIR version 4.5.0.

**Comment by CaitlinV39** [comment]
@uxbridgeroad we will update this as soon as the FHIR-NET-API nuget packages are available.

**Comment by uxbridgeroad** [comment]
@CaitlinV39 , just to confirm that this is one of the issue we were discussing earlier today with Marc and yourself.
We are planning for our next couple of sprints and it would be great to be able to align with an expected completion date for this.

**Comment by CaitlinV39** [comment]
@uxbridgeroad thank you so much for mentioning this. We are working on implementing this now in this PR #1743 We should have this merged in in the next couple of weeks, if not sooner.

**Comment by uxbridgeroad** [comment]
@CaitlinV39, I just want to clarify what happens once #1743  is merged.

1. Will FHIR Release #5: Preview #3 v4.5.0 be the default when R5 is chosen during the ARM deployment step?
2. The Microsoft.Health.Fhir.R5.* packages on main will only support R5 Preview #3 v4.5.0.?
3. Any further fixes to Microsoft.Health.Fhir.R5.* will not be available on R5  Preview #2?

Thanks,
