### ISSUE TITLE
_include with _tag and _id produce missing results

### ISSUE THREAD

**Issue by eladiw** [microsoft/fhir-server#1235]
**Describe the bug**
When using the _include_ operator and also filtering the matches based on __tag_ **and** __id_ at the same time => expected included items are not returned

**To Reproduce**

* **ASSUMING there is only 1 tag in the db....or that both queries return just 1 tag so the tag wont change the results**

0. find a match (patient for example) that has an include / revinclude item
1. consider the following query:
(id and tag to be changed to produce a valid match)
https://localhost:44348/Patient?_revinclude=Observation:subject&_id=186xxxa1c&_tag=774xxxce98

it might produce less items compared to this query:
https://localhost:44348/Patient?_revinclude=Observation:subject&_id=186xxxca1c

**Expected behavior**

both queries should produce the same results

**Actual behavior**
the query with both _tag and _id produce less results

when debugging this behavior I've noticed that adding _tag completely changes the generated query which in turn has an affect on the included statement.

_**With _id, Without _tag:**_
exec sp_executesql N'SET STATISTICS IO ON;
SET STATISTICS TIME ON;

WITH cte0 AS
(
    SELECT ResourceSurrogateId AS Sid1
    FROM dbo.**Resource**
    WHERE IsHistory = 0
        AND IsDeleted = 0
        AND ResourceTypeId = p0
        AND ResourceId = p1
    
),
cte1 AS
(
    SELECT DISTINCT TOP (p2) Sid1, 1 AS IsMatch, 0 AS IsPartial 
    FROM cte0
    ORDER BY Sid1 ASC
),
cte2 AS
(
    SELECT DISTINCT TOP (p3) refSource.ResourceSurrogateId AS Sid1, 0 AS IsMatch 
    FROM dbo.ReferenceSearchParam refSource
    INNER JOIN dbo.Resource refTarget
    ON refSource.ReferenceResourceTypeId = refTarget.ResourceTypeId
        AND refSource.ReferenceResourceId = refTarget.ResourceId
    WHERE refSource.SearchParamId = p4
        AND refTarget.IsHistory = 0
        AND refSource.IsHistory = 0
        AND refTarget.ResourceTypeId = p0
        AND refTarget.ResourceSurrogateId IN (SELECT TOP(p5) Sid1 FROM cte1)
),
cte3 AS
(
    SELECT DISTINCT TOP (p6) Sid1, IsMatch, CASE WHEN count(*) over() > p7 THEN 1 ELSE 0 END AS IsPartial 
    FROM cte2
),
cte4 AS
(
    SELECT Sid1, IsMatch, IsPartial 
    FROM cte1
    UNION ALL
    SELECT Sid1, IsMatch, IsPartial 
    FROM cte3
)
SELECT r.ResourceTypeId, r.ResourceId, r.Version, r.IsDeleted, r.ResourceSurrogateId, r.RequestMethod, CAST(IsMatch AS bit) AS IsMatch, CAST(IsPartial AS bit) AS IsPartial, r.RawResource
FROM dbo.Resource r
INNER JOIN cte4
ON r.ResourceSurrogateId = cte4.Sid1
ORDER BY r.ResourceSurrogateId ASC
OPTION(RECOMPILE)',N'p0 smallint,p1 varchar(64),p2 int,p3 int,p4 smallint,p5 int,p6 int,p7 int',p0=81,p1='186cxxxa1c',p2=11,p3=101,p4=822,p5=10,p6=100,p7=100

notice that the table in cte0 is Resource
two results:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/13205761/91726085-56b5a780-eba8-11ea-8b58-048630ef1081.png">

_**Without _id, With _tag:**_
exec sp_executesql N'SET STATISTICS IO ON;
SET STATISTICS TIME ON;

WITH cte0 AS
(
    SELECT ResourceSurrogateId AS Sid1
    FROM dbo.**_TokenSearchParam_**
    WHERE IsHistory = 0
        AND ResourceTypeId = p0
        AND SearchParamId = p1
        AND Code = p2
),
cte1 AS
(
    SELECT DISTINCT TOP (p3) Sid1, 1 AS IsMatch, 0 AS IsPartial 
    FROM cte0
    ORDER BY Sid1 ASC
),
cte2 AS
(
    SELECT DISTINCT TOP (p4) refSource.ResourceSurrogateId AS Sid1, 0 AS IsMatch 
    FROM dbo.ReferenceSearchParam refSource
    INNER JOIN dbo.Resource refTarget
    ON refSource.ReferenceResourceTypeId = refTarget.ResourceTypeId
        AND refSource.ReferenceResourceId = refTarget.ResourceId
    WHERE refSource.SearchParamId = p5
        AND refTarget.IsHistory = 0
        AND refSource.IsHistory = 0
        AND refTarget.ResourceTypeId = p0
        AND refTarget.ResourceSurrogateId IN (SELECT TOP(p6) Sid1 FROM cte1)
),
cte3 AS
(
    SELECT DISTINCT TOP (p7) Sid1, IsMatch, CASE WHEN count(*) over() > p8 THEN 1 ELSE 0 END AS IsPartial 
    FROM cte2
),
cte4 AS
(
    SELECT Sid1, IsMatch, IsPartial 
    FROM cte1
    UNION ALL
    SELECT Sid1, IsMatch, IsPartial 
    FROM cte3
)
SELECT r.ResourceTypeId, r.ResourceId, r.Version, r.IsDeleted, r.ResourceSurrogateId, r.RequestMethod, CAST(IsMatch AS bit) AS IsMatch, CAST(IsPartial AS bit) AS IsPartial, r.RawResource
FROM dbo.Resource r
INNER JOIN cte4
ON r.ResourceSurrogateId = cte4.Sid1
ORDER BY r.ResourceSurrogateId ASC
OPTION(RECOMPILE)',N'p0 smallint,p1 smallint,p2 varchar(128),p3 int,p4 int,p5 smallint,p6 int,p7 int,p8 int',p0=81,p1=1046,p2='774cxxxe98',p3=11,p4=101,p5=822,p6=10,p7=100,p8=100

Notice the table in cte0 is _TokenSearchParam_
this execution results in multiple items.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/13205761/91726238-954b6200-eba8-11ea-8650-f848c66141a3.png">

when combining the two, with _tag and with _id:
exec sp_executesql N'SET STATISTICS IO ON;
SET STATISTICS TIME ON;

WITH cte0 AS
(
    SELECT ResourceSurrogateId AS Sid1
    FROM dbo.TokenSearchParam
    WHERE IsHistory = 0
        AND ResourceTypeId = p0
        AND SearchParamId = p1
        AND Code = p2
),
cte1 AS
(
    SELECT DISTINCT TOP (p3) Sid1, 1 AS IsMatch, 0 AS IsPartial 
    FROM cte0
    ORDER BY Sid1 ASC
),
cte2 AS
(
    SELECT DISTINCT TOP (p4) refSource.ResourceSurrogateId AS Sid1, 0 AS IsMatch 
    FROM dbo.ReferenceSearchParam refSource
    INNER JOIN dbo.Resource refTarget
    ON refSource.ReferenceResourceTypeId = refTarget.ResourceTypeId
        AND refSource.ReferenceResourceId = refTarget.ResourceId
    WHERE refSource.SearchParamId = p5
        AND refTarget.IsHistory = 0
        AND refSource.IsHistory = 0
        AND refTarget.ResourceTypeId = p0
        AND refTarget.ResourceSurrogateId IN (SELECT TOP(p6) Sid1 FROM cte1)
),
cte3 AS
(
    SELECT DISTINCT TOP (p7) Sid1, IsMatch, CASE WHEN count(*) over() > p8 THEN 1 ELSE 0 END AS IsPartial 
    FROM cte2
),
cte4 AS
(
    SELECT Sid1, IsMatch, IsPartial 
    FROM cte1
    UNION ALL
    SELECT Sid1, IsMatch, IsPartial 
    FROM cte3
)
SELECT r.ResourceTypeId, r.ResourceId, r.Version, r.IsDeleted, r.ResourceSurrogateId, r.RequestMethod, CAST(IsMatch AS bit) AS IsMatch, CAST(IsPartial AS bit) AS IsPartial, r.RawResource
FROM dbo.Resource r
INNER JOIN cte4
ON r.ResourceSurrogateId = cte4.Sid1
WHERE ResourceId = p9
ORDER BY r.ResourceSurrogateId ASC
OPTION(RECOMPILE)',N'p0 smallint,p1 smallint,p2 varchar(128),p3 int,p4 int,p5 smallint,p6 int,p7 int,p8 int,p9 varchar(64)',p0=81,p1=1046,p2='774cxxxxe98',p3=11,p4=101,p5=822,p6=10,p7=100,p8=100,p9='186cxxxxa1c'

Only 1 result:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/13205761/91726721-5e298080-eba9-11ea-9968-78189c1573ca.png">

however the included item is not there..

Current assumption (not verified yet) is that since the filtering is now done only at the end (bottom) of the query, non relevant includes are passing the top / asc sorting / filtering and relevant includes get dropped, later those are filtered while the relevant includes are already dropped...

**Comment by CaitlinV39** [comment]
Addressed by #1273
