### ISSUE TITLE
ExpressionParser.ParseInclude creates new IncludeExpression with ResourceType (domain resource) and not the original type

### ISSUE THREAD

**Issue by limorl** [microsoft/fhir-server#1236]
**Describe the bug**
ExpressionParser.ParseInclude creates new IncludeExpression with ResourceType (domain resource) and not the original type. This works fine for correct queries.
However in the following example, where a wrong search parameter is used, I'd expect either an error or that parameter ignored:

**MedicationDispense?_include:MedicationRequest:medication** --> Here, the included medication is references by MedicationDispense, because both MedicationRequest and MedicationRequest has a 'medication' search parameter.
So the dispensed medications are returned and not the requested ones.  

In the following case, 'medication' is not a common search parameter of Patient and MedicationRequest.
**Patient?_include:MedicationRequest:medication** --> Only patient results are returned 

The problem is that a cte table is created for the wrong include parameter and evaluated, while the query is wrong. 
It's not a critical problem, but tables are created and evaluated for nothing. 

I observed a similar behavior in hapi server as well. 

**To Reproduce**
1. Create a MedicationRequest for medication A
2. Create a MedicationDispense referencing that MedicationRequest with medication substitue_A
3. Execute search: MedicationDispense?_include:MedicationRequest:medication
4. The returned medication will be A

**Expected behavior**
Either an error indication or that the wrong search parameter is ignored. I couldn't find any GHIR specification regarding this case 

**Actual behavior**
**MedicationDispense?_include:MedicationRequest:medication** --> Here, the included medication is references by MedicationDispense, because both MedicationRequest and MedicationRequest has a 'medication' search parameter.
So the dispensed medications are returned and not the requested ones.

**Comment by CaitlinV39** [comment]
Closing this as it was addressed in #1244
