### ISSUE TITLE
modifiers e.g. :exact not working on chained searches

### ISSUE THREAD

**Issue by bikubay** [microsoft/fhir-server#1237]
**Describe the bug**
When attempting to execute a chained search using search modifiers (:exact or :contains), error returned back in OSS SQL server 

**To Reproduce**
1.  Try this query - https://{{fhirserver}}/Appointment?date=gt2020-08-31&date=lt2020-09-02&actor:Practitioner.name:exact=nameofprovider

**Expected behavior**
return back all appointments for specific provider only [nameofprovider]

**Actual behavior**
{
    "resourceType": "OperationOutcome",
    "id": "xxxxxxxxxxxxxxxxxxx",
    "issue": [
        {
            "severity": "error",
            "code": "exception",
            "diagnostics": "There was an error processing your request."
        }
    ]
}

**Comment by CaitlinV39** [comment]
AB#76142

**Comment by Ivanidzo4ka** [comment]
I've test locally and it seems to work now. 
We also have tests for chained expression, and separately for string modifiers, and adding tests for both of them sounds like opening Pandora box for other possible combinations.

**Comment by CaitlinV39** [comment]
Thanks @Ivanidzo4ka 

@bikubay - Can you confirm if you are still having this issue? We aren't able to reproduce right now.
