### ISSUE TITLE
When using the _elements parameter mandatory fields aren't returned

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#1256]
**Describe the bug**
When a search is performed with the _elements parameter mandatory fields are not returned unless specified.

**To Reproduce**
1. Run the search ```/Observation?_elements=id```
2. Only ids are returned, but code and status are mandatory fields of Observation

**Expected behavior**
According to the spec "Clients SHOULD list all mandatory and modifier elements in a resource as part of the list of elements." [spec](https://www.hl7.org/fhir/search.html#elements)

**Actual behavior**
Only fields that are specified in the _elements parameter are returned.

**Comment by brendankowitz** [comment]
And also `Servers SHOULD mark the resources with the tag SUBSETTED to ensure that the incomplete resource is not actually used to overwrite a complete resource.`

**Comment by anyname2** [comment]
1. This is (probably) a bug in https://github.com/FirelyTeam/fhir-net-api
    FHIR Server only calls the API: [FhirJsonOutputFormatter.cs#L133](https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.Shared.Api/Features/Formatters/FhirJsonOutputFormatter.cs#L133)
    ```csharp
    _fhirJsonSerializer.Serialize(resource, jsonWriter, context.HttpContext.GetSummaryType(_logger), elementsSearchParameter);
    ```
2. > And also `Servers SHOULD mark the resources with the tag SUBSETTED to ensure that the incomplete resource is not actually used to overwrite a complete resource.`

    This is already done when the meta is present, but you need to have `_elements=meta` so that it is not excluded from the result (i.e. should be resolved when 1 is fixed).

**Comment by CaitlinV39** [comment]
I'm going to open a bug on the Firely side and then track from there.

**Comment by Ivanidzo4ka** [comment]
https://github.com/FirelyTeam/firely-net-sdk/issues/1653
It doesn't count as a bug.

I've created PR to add required fields to resource (and meta field)

**Comment by CaitlinV39** [comment]
AB#81256
