### ISSUE TITLE
Crash when calling /Patient?name=x&_sort=birthdate,-

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#1258]
```
GET /Patient?name=x&_sort=birthdate,-
```

```
Process terminated. Assertion failed.
paramName should not be null or whitespace.
   at Microsoft.Health.Fhir.Core.Features.Search.SearchParameterNotSupportedException..ctor(String resourceType, String paramName) in D:\repos\fhir-server\src\Microsoft.Health.Fhir.Core\Features\Search\SearchParameterNotSupportedException.cs:line 39
```

**Comment by brendankowitz** [comment]
@johnstairs is this data provider specific?

**Comment by johnstairs** [comment]
> @johnstairs is this data provider specific?

@brendankowitz, no it happens with Cosmos DB and SQL.

**Comment by CaitlinV39** [comment]
AB#76671

**Comment by cunninghamjc** [comment]
Opened an issue on fhir-net-api: https://github.com/FirelyTeam/fhir-net-api/issues/1531.  SearchParams is parsing "-" as a sort parameter with an empty name, which later fails a Debug.Assert in SearchParameterNotSupportedException.
