### ISSUE TITLE
Add Diagnostics.HealthChecks to SQL Provider

### ISSUE THREAD

**Issue by SychevIgor** [microsoft/fhir-server#1260]
**User story**
As an operation person, I want to have consistent monitoring/healthchech in both sql/cosmosdb providers so that my selection will not be based on Diagnostics.HealthChecks implemented or not.
Currently, only cosmosdb provided used Diagnostics.HealthChecks package, sql- no.
In SQL provider added Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions, but not uset (if package will be uninstalled- we still can build code)
![image](https://user-images.githubusercontent.com/578954/92931247-d6b2fb80-f44b-11ea-898a-cb0dbde0000a.png)

**Acceptance criteria**
1. When I do open source code->list of nuget packages, then I see Diagnostics.HealthChecks added to SQL provided and used in a code to check connectivity to SQL Server used.

**Comment by brendankowitz** [comment]
You should still be able to query the `/health/check` endpoint at runtime which tests connectivity with the SQL DB. We've been refactoring some common code that we're planning to use with other projects. `SqlServerHealthCheck` still exists in `Microsoft.Health.SqlServer.dll` and is currently being installed via nuget. This common codebase will be visible as open source again soon

**Comment by CaitlinV39** [comment]
@SychevIgor I am going to close this based on Brendan's feedback but if you have additional questions feel free to reopen.
