### ISSUE TITLE
Specifying a _count greater than Max should return OperationOutcome inside search Bundle instead of a BadRequest

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1263]
**Describe the bug**
Currently when specifying a _count greating than the max will result in a 400 and return an OperationOutcome. We should continue the search and put this OperationOutcome message and into the Bundle that is returned to specify that less results have been returned than requested.

**To Reproduce**
1. Specify ?_count=1000

**Expected behavior**
Search Bundle is returned that includes the OperationOutcome message

**Actual behavior**
Status code 400 with OperationOutcome

**Comment by CaitlinV39** [comment]
AB#76267
