### ISSUE TITLE
Will .net standard been used in a project instead of shared library

### ISSUE THREAD

**Issue by SychevIgor** [microsoft/fhir-server#1265]
It's not a story it's a question about roadmap.
For a few years microsoft advertising .net standard instead of shared libraries. I would assume that in this project shared library can be replace with .net standard without problem.
Do Microsoft has it in a roadmap?

**Comment by brendankowitz** [comment]
Although both .net standard and shared projects are helping solve the problem of compiling code across frameworks, this is not what we are using them for (all our projects are already .NET Core). We are currently leveraging the community (https://github.com/FirelyTeam/fhir-net-api) to support Stu3, R4 and R5. These base libraries currently have many classes in conflicting namespaces (e.g. models) so we are using Shared projects to cross compile against different versions of FHIR.

Going forward we may look to use lower level abstractions where which means we will be able to re-combine projects as a single .NET Core version.

**Comment by brendankowitz** [comment]
I hope the answer given provides some insight here, I'm going to close this out for now
