### ISSUE TITLE
FHIR Patch

### ISSUE THREAD

**Issue by uxbridgeroad** [microsoft/fhir-server#1268]
**User story**
As an MS FHIR Server user, I want use FHIR Patch so that as an alternative to updating an entire resource, clients can perform a patch operation. This can be useful when a client is seeking to minimize its bandwidth utilization, or in scenarios where a client has only partial access or support for a resource. T

http://hl7.org/fhir/http.html#patch

**Acceptance criteria**
1. When I do submit selected attributes on a resource, MS FHIR Server creates a new version of the resource which differs from the previous version only by the submitted attributes.

**Comment by CaitlinV39** [comment]
@uxbridgeroad thank you so much for sharing this. We have $Patch on our list of enhancements but don't have a timeline yet for when we would start development. We will keep you updated as we progress.

**Comment by uxbridgeroad** [comment]
@CaitlinV39 , this is great to hear. Is it possible to view the list of enhancements? As mentioned in (#695) Update Roadmap.md, it would be really useful to get a view on what is under consideration so we align our project features.

**Comment by anyname2** [comment]
I have a draft PR for Patch ready #1272. But need this: https://github.com/FirelyTeam/fhir-net-api/pull/1375 to be merged and back-ported to a version FHIR Server is using (which I've done too: [R4](https://github.com/anyname2/fhir-net-api/tree/feature/fhir-patch-1.7.0-r4) [R5](https://github.com/anyname2/fhir-net-api/tree/feature/fhir-patch-1.7.0-r5) [STU3](https://github.com/anyname2/fhir-net-api/tree/feature/fhir-patch-1.7.0-stu3)).

**Comment by CaitlinV39** [comment]
@uxbridgeroad as Michael mentioned in #695 we use open issues and PR to track features and give visibility into what we are releasing. We are thinking about how we can give more clarity into what we are releasing in upcoming months as well. If you'd like to jump on a call to share more ideas around this I'd love to hear them. Feel free to email me at cavoeg@microsoft.com

**Comment by appetere** [comment]
Would you update https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/fhir-features-supported to say that PATCH is not supported, please?  I spent several hours trying to get it working, whereas it doesn't appear to be implemented yet?

![image](https://user-images.githubusercontent.com/1777396/128353651-d1d1a2e6-415e-4ba1-b381-9e9b87eea04d.png)

**Comment by CaitlinV39** [comment]
I'm so sorry for the confusion. We will get the docs updated. This is available in open source on both offerings and will be int he managed service by the end of next week.

**Comment by brendankowitz** [comment]
FHIRPath patch has been merged
