### ISSUE TITLE
unclear address patient search behavior  

### ISSUE THREAD

**Issue by MathieuRietman** [microsoft/fhir-server#1271]
**Describe the bug**

**To Reproduce**
Using Azure FHIR API R4
1. Search on address-city or any address search criteria seams not to filter the result but gives back the whole patient bundles.
2. sample https://mrfhir.azurehealthcareapis.com/Patient?address-city=Seattle
    Self url says
       {
            "relation": "self",
            "url": "https://mrfhir.azurehealthcareapis.com/Patient?address-city=Seattle"
        }

**Expected behavior**
Only Bundles with that specific patient.address.city is sopported by the spec
http://www.hl7.org/fhir/patient.html#search

**Actual behavior**All patient Bundle

**Comment by brendankowitz** [comment]
We should add a specific regression test for this here (https://github.com/microsoft/fhir-server/blob/master/test/Microsoft.Health.Fhir.Shared.Tests.E2E/Rest/Search/BasicSearchTests.cs#L36)

**Comment by CaitlinV39** [comment]
AB#76140

**Comment by brendankowitz** [comment]
Hi @MathieuRietman, I've added an E2E test for this (https://github.com/microsoft/fhir-server/pull/1279/files) can you review to see if it aligns with your scenario? The test currently passes.

**Comment by MathieuRietman** [comment]
Looks good to me that the result only should patient 0 2 4.  The test should fail is one of the other records are in the result set.

**Comment by brendankowitz** [comment]
Thanks @MathieuRietman. If you see different behavior in your instance would it be possibly to provide us with some sample data that can replicate the issue? If not we'll keep this e2e test and close the issue

**Comment by CaitlinV39** [comment]
@MathieuRietman I'm going to close this based on Brendan's comment but please let us know if you have other questions or issues!
