### ISSUE TITLE
Deployment Error following quickstart instructions

### ISSUE THREAD

**Issue by robwafle** [microsoft/fhir-server#1274]
**Describe the bug**
Deployment Error following quickstart instructions

**To Reproduce**
1.  Follow the quickstart instructions here: https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir-oss-portal-quickstart

**Expected behavior**
No deployment errors.  I'm able to start quickly following the quick start instructions.

**Actual behavior**
Deployment Error of: "Cannot find ServerFarm with name *serverfarm-name-from-template-input*.  Click here for details ->" was returned.

**Comment by robwafle** [comment]
Looks like this was the issue.

App Service Plan Resource Group and App Service Plan are OPTIONAL, and could perhaps be renamed to be prefixed with "Use Existing" in the field name to make template use a bit more straightforward.   I was able to figure this out using the tool tip text, but it was not immediately obvious. 

Thx

Rob

**Comment by robwafle** [comment]
Also, I'd like to mention that it has been 8 minutes since the deployment, and the /metadata endpoint is not responding.  Eight minutes seems a bit longer than "a minute or so" as described on the quickstart page.  So, either something has still gone wrong, or maybe it takes longer for this to warm up.   I deployed to the default size on the template of S1.

**Comment by CaitlinV39** [comment]
@robwafle thank you for reporting this. I have started making some updates to the quickstart guide to make it more clear and will let you know once its updated.

**Comment by CaitlinV39** [comment]
AB#76139

**Comment by CaitlinV39** [comment]
@robwafle I have included the QuickStart guide in our OSS Documentation now and added some updates that will hopefully make it clearer. Let me know if you have any additional questions!

https://github.com/microsoft/fhir-server/blob/master/docs/QuickstartDeployPortal.md
