### ISSUE TITLE
Following Quickstart instructions yields non-functional deployment.

### ISSUE THREAD

**Issue by robwafle** [microsoft/fhir-server#1276]
**Describe the bug**
Following Quickstart instructions yields non-functional deployment.

**To Reproduce**
1. Follow the quickstart instructions here: https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir-oss-portal-quickstart

**Expected behavior**
https://SERVICENAME.azurewebsites.net/metadata should return a capability statement.

**Actual behavior**
https://SERVICENAME.azurewebsites.net/metadata returns ERR_INVALID_RESPONSE.

Looking inside of app insights, I see this error:
```The MetadataAddress or Authority must use HTTPS unless disabled for development by setting RequireHttpsMetadata=false```
 
But, I am using https for my request.  Does something inside the service need to use https?  If so, shouldn't https be used by default, so the template works as-is?  

I haven't made any configuration changes.

**Comment by robwafle** [comment]
I was able to get a successful deployment after many tries.

It seems if I don't check the last option, "Sql Schema Auto Updates Enabled" SQL tables are missing and I get: HTTP Error 500.30 - ANCM In-Process Start Failure when trying to access the /metadata endpoint.

It seems if I specify Security Authentication Authority, Security Authentication Audience and Enable Aad Smart On Fhir Proxy, that's when I get the ERR_INVALID_RESPONSE and The MetadataAddress or Authority must use HTTPS unless disabled for development by setting RequireHttpsMetadata=false in the logs.

**Comment by CaitlinV39** [comment]
AB#76138

**Comment by CaitlinV39** [comment]
@robwafle thank you so much for identifying this. We are updating Sql Schema Auto Updates Enabled to be a required field and also updating our help text to address this. In a production scenario you would set this to false and use our Schema Migration tool but in a test/dev environment true should be fine. I will post here once this is resolved. We can also add more details into our OSS guide to help with the optional fields.

**Comment by CaitlinV39** [comment]
@robwafle I'm updating the documentation to make sure that this is more clear. I'm going to close this as a duplicate against the other issue but will combine all doc issues from this as well into that update.
