### ISSUE TITLE
DB schema is not creating automatically

### ISSUE THREAD

**Issue by eladiw** [microsoft/fhir-server#1297]
**Describe the bug**
using latest build (stu3_fhir-server:build-20200912-1) on a new AKS cluster + new,empty DB does not create the DB schema and pods fail to start

**To Reproduce**
1.) Create an empty database
2.) Deploy the Fhir Server image with tag stu3_fhir-server:build-20200912-1, using environment variables:
SqlServer__AllowDatabaseCreate: true
SqlServer__ConnectionString: empty-db-conn-string
3.) The container fails to start. See screenshot attachment showing StackTrace

4.) To work around the issue, we deploy an older image tag stu3_fhir-server:build-20200819-1 and the schema is created
![image](https://user-images.githubusercontent.com/13205761/94113477-9beb9300-fe4f-11ea-880d-1e19969eda4b.png)

**Expected behavior**
DB schema is expected to be created automatically

**Actual behavior**
pods fail to start. using a workaround we managed to get the pods to work (started with lower version and upgraded)

**Comment by brendankowitz** [comment]
@eladiw thanks for highlighting this. I think there is a second setting `SqlServer__SchemaOptions__AutomaticUpdatesEnabled` which is now required for the schema updates to run. We'll use this ticket to track cleaning this up

**Comment by CaitlinV39** [comment]
AB#76268

**Comment by balteravishay** [comment]
FYI, this issue is also affecting the standard deployment to Azure of FHIR server OSS. 
the ARM template sets this parameter to false, causing the solution to initially be at at a fault state, until the config is changed and the app is restarted.

https://github.com/microsoft/fhir-server/blob/7fab70ab5c350926a420e29f56a7046c57c50037/samples/templates/default-azuredeploy.json#L149

**Comment by rbans96** [comment]
> FYI, this issue is also affecting the standard deployment to Azure of FHIR server OSS.
> the ARM template sets this parameter to false, causing the solution to initially be at at a fault state, until the config is changed and the app is restarted.
> 
> https://github.com/microsoft/fhir-server/blob/7fab70ab5c350926a420e29f56a7046c57c50037/samples/templates/default-azuredeploy.json#L149

The default value for sqlSchemaAutomaticUpdatesEnabled is false only for CosmosDB server and for SQL Server, the default value is null so that we can choose true/false value as per our requirement.

**Comment by CaitlinV39** [comment]
The resolution for this has been merged so closing this item.
