### ISSUE TITLE
PartialDateTime not considered partial if fractional seconds specified.

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#1300]
**Describe the bug**
If an equality search expression is done over a datetime search parameter, we do not consider the give value to implicitly be a range if fractional seconds are specified.

**To Reproduce**
If I parse this search expression: 

```csharp
expressionParser.Parse("Patient", "_lastUpdated", "2020-09-24T12:00:00Z");
```

I get the following tree:
```
(Param 
    _lastUpdated 
    (And 
        (FieldGreaterThanOrEqual DateTimeStart 2020-09-24T12:00:00.0000000+00:00) 
        (FieldLessThanOrEqual DateTimeEnd 2020-09-24T12:00:00.9999999+00:00)))
```

Note that the range covers the entire day

However if I parse this expression:
```csharp
expressionParser.Parse("Patient", "_lastUpdated", "2020-09-24T12:00:00.500Z");
```

I get this tree:
```
(Param 
    _lastUpdated 
    (And 
        (FieldGreaterThanOrEqual DateTimeStart 2020-09-24T12:00:00.5000000+00:00) 
        (FieldLessThanOrEqual DateTimeEnd 2020-09-24T12:00:00.5000000+00:00)))
```

This is will only patch the exact datetime 2020-09-24T12:00:00.5000000+00:00.

**Expected behavior**
I get this tree:
```
(Param 
    _lastUpdated 
    (And 
        (FieldGreaterThanOrEqual DateTimeStart 2020-09-24T12:00:00.5000000+00:00) 
        (FieldLessThanOrEqual DateTimeEnd 2020-09-24T12:00:00.5009999+00:00)))
```

This expression would find datetimes like 2020-09-24T12:00:00.5001000+00:00

**Comment by CaitlinV39** [comment]
AB#76264

**Comment by Ivanidzo4ka** [comment]
Considering fractions is decimal, it's a bit tricky to bump it from 0.5 to 0.5009999 (and why not 0.5999999?) in general case. How many digits we need to care about? (I mean it can be 0.5 or 0.58 or 0.567 do we need to handle all of them, or we should stop at some point?)

Can we ignore fractions of second and do search in seconds range? I mean for this example to have 
```
(Param 
    _lastUpdated 
    (And 
        (FieldGreaterThanOrEqual DateTimeStart 2020-09-24T12:00:00.0+00:00) 
        (FieldLessThanOrEqual DateTimeEnd 2020-09-24T12:00:00.99999+00:00)))
        )
```

**Comment by Ivanidzo4ka** [comment]
_lastUpdated says it should use date:
https://www.hl7.org/fhir/search.html#date
It says it can be one of the three thing: 
>Technically, this is any of the date, dateTime, and instant data types.

type| description
-- | --
date | The range of the value is the day, month, or year as specified
dateTime | The range of the value as defined above; e.g. For example, the date 2013-01-10 specifies all the time from 00:00 on 10-Jan 2013 to immediately before 00:00 on 11-Jan 2013
instant | An instant is considered a fixed point in time with an interval smaller than the precision of the system, i.e. an interval with an effective width of 0

Date is just date.
Datetime:

>A date, date-time or partial date (e.g. just year or year + month) as used in human communication. The format is YYYY, YYYY-MM, YYYY-MM-DD or YYYY-MM-DDThh:mm:ss+zz:zz, e.g. 2018, 1973-06, 1905-08-23, 2015-02-07T13:28:17-05:00 or 2017-01-01T00:00:00.000Z. If hours and minutes are specified, a time zone SHALL be populated. **Seconds must be provided due to schema type constraints but may be zero-filled and may be ignored at receiver discretion**.

No mention of fractions.
Instant:
>An instant in time in the format YYYY-MM-DDThh:mm:ss.sss+zz:zz
this one has fractions, but in same time: An instant is considered **a fixed point** in time with an interval smaller than the precision of the system, i.e. an interval with an effective width of 0

I think we doing right thing by not providing bigger range and this is what spec wants from us.

**Comment by CaitlinV39** [comment]
We should likely either throw an error that we don't accept fractions or we should evaluate them. Ignoring them (or dropping the fractions) could result in unintended behavior.

**Comment by Ivanidzo4ka** [comment]
From my interpretation of spec, it sound like if user pass fractions it should be treated as **exact** time, which we do right now.
If no fractions provided it should be treated as interval, which we also do.
