### ISSUE TITLE
Ready-to-use data persistence provider for Azure Cosmos DB Configuration guide or docs

### ISSUE THREAD

**Issue by emeria** [microsoft/fhir-server#1307]
**User story**
As a developer, I want documentation for the "ready-to-use data persistence provider for Azure Cosmos DB" so that I know how to configure FHIR Server to use CosmosDb instead of SQL.

**Acceptance criteria**
1. When I query my FHIR Server, then the resources are stored and accessed from CosmosDb and not SQL.

**Comment by brendankowitz** [comment]
Hi @emeria, are you referring to deploying into Azure?
We switched the default to the SQL provider as it contains more features. We still have the deployment template that you can use for CosmosDB (https://github.com/microsoft/fhir-server/blob/master/samples/templates/default-azuredeploy.json)

**Comment by emeria** [comment]
@brendankowitz Thanks, I will give this a try!
