### ISSUE TITLE
Server URL is wrong when running behind reverse-proxy

### ISSUE THREAD

**Issue by petermicuch** [microsoft/fhir-server#1317]
**Describe the bug**
When I run ms fhir-server in kubernetes environment behind reverse-proxy/ingress then the self/previous/next URL in the returned bundles is wrong and displays proxied URL instead of public URL.

I.e. I have service `ms-fhir-server-stu3` running inside AKS cluster in the namespace `test-fhir`. This fhir server is reachable from outside at let's say `https://fhirtest.com/stu3` which is internally proxied by reverse-proxy to `ms-fhir-server-stu3.test-fhir.svc.cluster.local`.

Returned patient bundle looks like this:
```
// 20201001102017
// https://fhirtest.com/stu3/Patient?_format=json

{
  "resourceType": "Bundle",
  "id": "827eb97f-2e2e-4584-82d8-7e1f6eae2373",
  "meta": {
    "lastUpdated": "2020-10-01T08:20:17.5014569+00:00"
  },
  "type": "searchset",
  "link": [
    {
      "relation": "self",
      "url": "http://ms-fhir-server-stu3.test-fhir.svc.cluster.local/Patient?_format=json"
    }
  ]
}
```

But expectation is to look like this:
```
// 20201001102017
// https://fhirtest.com/stu3/Patient?_format=json

{
  "resourceType": "Bundle",
  "id": "827eb97f-2e2e-4584-82d8-7e1f6eae2373",
  "meta": {
    "lastUpdated": "2020-10-01T08:20:17.5014569+00:00"
  },
  "type": "searchset",
  "link": [
    {
      "relation": "self",
      "url": "http://fhirtest.com/stu3/Patient?_format=json"
    }
  ]
}
```

I.e. there should be configuration option to set base-url for fhir server, otherwise links that are proxied are wrong and do not work for user in the browser.

**To Reproduce**
1. Have your fhir server running in AKS behind ingress or reverse-proxy (i.e. use nginx)
2. Try to access it using public URL that will reach your reverse proxy/ingress
3. Returned json/xml displays wrong url in self/previous/next link.

**Expected behavior**
URLs in the returned FHIR bundles should display correct public URLs and not internal URLs of fhir service known only inside AKS (or any K8S cluster in general).

**Actual behavior**
Wrong internal URLs as described above. Event protocol is wrong since outside of AKS you have to use https but internal traffic is using http.

**Comment by anyname2** [comment]
There are 2 issues here:
- Missing prefix: should be fixed, when #1200 is merged (@brendankowitz )
- You need to enable forwared headers: set `ASPNETCORE_FORWARDEDHEADERS_ENABLED` to `true`
   And configure the reverse proxy to **not** rewrite the host before forwarding the request.
   Otherwise you need to change [Startup.cs#L50-L51](https://github.com/microsoft/fhir-server/blob/0a886338c27f083f8f7dba1fb2882d1701463880/src/Microsoft.Health.Fhir.Shared.Web/Startup.cs#L50-L51)
    ```diff
     services.Configure<ForwardedHeadersOptions>(options =>
     {
    -    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor |
    -        ForwardedHeaders.XForwardedProto;
    +    options.ForwardedHeaders = ForwardedHeaders.All;

         // Only loopback proxies are allowed by default.
         // Clear that restriction because forwarders are enabled by explicit
         // configuration.
         options.KnownNetworks.Clear();
         options.KnownProxies.Clear();
     });
    ````

**Comment by brendankowitz** [comment]
Thanks @petermicuch, @anyname2. It's good that have this use case. I think we should be ok to merge that PR as it's only active with configuration.
I'd like to ideally also have some e2e tests against this setup to ensure everything is working correctly, I'll open a separate issue to track this

**Comment by dlouwers** [comment]
This bug is a dealbreaker for us using Azure API for FHIR service. Any idea when this will be available/fixed there?

**Comment by CaitlinV39** [comment]
@dlouwers - Have you tried the step above (I copied it here as well).

You need to enable forwared headers: set ASPNETCORE_FORWARDEDHEADERS_ENABLED to true
And configure the reverse proxy to not rewrite the host before forwarding the request.
Otherwise you need to change Startup.cs#L50-L51
 services.Configure<ForwardedHeadersOptions>(options =>
 {
-    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor |
-        ForwardedHeaders.XForwardedProto;
+    options.ForwardedHeaders = ForwardedHeaders.All;

     // Only loopback proxies are allowed by default.
     // Clear that restriction because forwarders are enabled by explicit
     // configuration.
     options.KnownNetworks.Clear();
     options.KnownProxies.Clear();
 });

**Comment by dlouwers** [comment]
I am using the managed Azure API for FHIR service. I do not have access to environment variables and definitely cannot edit the code.

**Comment by CaitlinV39** [comment]
@dlouwers I'm so sorry for the delay. If you are having issues with the managed service, definitely feel free to open a ticket through the portal and it can be routed. We have a solution for the open source but support may be able to help you work through your specific example with the Azure API For FHIR.
