### ISSUE TITLE
Missing SQL migration script for v5? 

### ISSUE THREAD

**Issue by anyname2** [microsoft/fhir-server#1318]
[Microsoft.Health.Fhir.SqlServer.csproj#L10-L11](https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.SqlServer/Microsoft.Health.Fhir.SqlServer.csproj#L10-L11) refers to `5.sql` and `5.diff.sql`, which do not exist in [Features/Schema/Migrations/](https://github.com/microsoft/fhir-server/tree/master/src/Microsoft.Health.Fhir.SqlServer/Features/Schema/Migrations)
```csproj
    <None Remove="Features\Schema\Migrations\5.diff.sql" />
    <None Remove="Features\Schema\Migrations\5.sql" />
```

Were they supposed to be committed as part of #1178?

**Comment by brendankowitz** [comment]
@rbans96 or @rotodd can you investigate this?

**Comment by rbans96** [comment]
These couple of lines got committed as part of some local testing. So will remove 5.sql and 5.diff.sql entry from Microsoft.Health.Fhir.SqlServer.csproj.

**Comment by brendankowitz** [comment]
Thanks @rbans96

**Comment by brendankowitz** [comment]
This should be resolved now
