### ISSUE TITLE
Error on _include query

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#1342]
**Describe the bug**
Error when handling simple include query.

**Data provider?**
SQL Server

**To Reproduce**
1. `GET https://localhost:44348/MedicationRequest?_include=MedicationRequest:patient`

**Expected behavior**
A result set

**Actual behavior**
A 400 with body
``` json
{
  "resourceType": "OperationOutcome",
  "id": "581b4b6c-9eec-4700-a725-40ff58f2d4a1",
  "issue": [
    {
      "severity": "error",
      "code": "invalid",
      "diagnostics": "Expected an expression that evaluates to true. (Parameter 'expressions')"
    }
  ]
}
```
Note also that this should be a 500 and not a 400.

**Comment by CaitlinV39** [comment]
@CaitlinV39 create a user story

**Comment by CaitlinV39** [comment]
AB#76269

**Comment by CaitlinV39** [comment]
@johnstairs I think you merged a fix for this. Is this still open?

**Comment by johnstairs** [comment]
Closing.
