### ISSUE TITLE
Not able to deploy SQL schema

### ISSUE THREAD

**Issue by davidegiacometti** [microsoft/fhir-server#1373]
**Describe the bug**
Not able to deploy SQL schema (Build 20201014-1)

**FHIR Version?**
R5

**Data provider?**
SQL Server

**To Reproduce**
1. Create a new Database
2. Apply src/Microsoft.Health.Fhir.SqlServer/Features/Schema/Migrations/4.sql

**Expected behavior**
Script executed successfully

**Actual behavior**
_Msg 208, Level 16, State 1, Line 10
Invalid object name ‘dbo.SchemaVersion’._

Same problem applying diff script since 1.sql has been removed.
Last working build with 1.sql was Build 20200829-1.

**Comment by CaitlinV39** [comment]
@CaitlinV39 to link guides

**Comment by CaitlinV39** [comment]
@davidegiacometti we did release an update so that the schema is not automatically updated. You can see two documents that might help with this

1. https://github.com/microsoft/fhir-server/blob/master/docs/SchemaMigrationGuide.md - This is the overall guide on Schema Migration
2. https://github.com/microsoft/fhir-server/blob/master/docs/SchemaMigrationTool.md - This walks through how you can do the Schema upgrade on demand

Let me know if you have additional questions!

**Comment by davidegiacometti** [comment]
Hi @CaitlinV39,

I have read the guides but it didn't help.

What I am trying to achieve is deploy the schema without using automatic schema upgrade or schema migration tool from **Build 20201014-1**.

I think I have 2 options:

1. Apply the script 4.sql but it fails with error
**Msg 208, Level 16, State 1, Line 10
Invalid object name ‘dbo.SchemaVersion’.**

2. Apply the following scripts
1.sql
2.diff.sql
3.diff.sql
4.diff.sql
**But 1.sql has been removed**

**Comment by rbans96** [comment]
@davidegiacometti Could you confirm when are you seeing this error - on the server startup/metadata endpoint or while running the tool?
Could you try switching the below flag to true
![image](https://user-images.githubusercontent.com/57157506/96794695-85cfe480-13b3-11eb-9112-63b9c8421eb4.png)

**Comment by brendankowitz** [comment]
To give some more information regarding this:

> 2\. Apply the following scripts
>     1.sql
>     2.diff.sql
>     3.diff.sql
>     4.diff.sql
>     **But 1.sql has been removed**

Our strategy is that we provide Snapshot scripts, so applying 4.sql is all that is needed for a new install. The migration pathway using .diff scripts is only needed for existing databases.

**Comment by davidegiacometti** [comment]
@brendankowitz then [4.sql](https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.SqlServer/Features/Schema/Migrations/4.sql) is broken for a fresh install since the first statement is 
```
INSERT INTO dbo.SchemaVersion
VALUES
    (4, 'started')
```
but table SchemaVersion doesn't exists.

**Comment by brendankowitz** [comment]
These scripts are now all based on a shared migration framework which was moved to https://github.com/microsoft/healthcare-shared-components/tree/master/src/Microsoft.Health.SqlServer/Features/Schema/Migrations.

The migration tool and the fhir server should automatically apply this.

//cc @rbans96

**Comment by CaitlinV39** [comment]
@davidegiacometti let me know if Brendan's updates resolve your issue or if you still have questions. We are going to continue to look at ways to optimize in the future.

**Comment by davidegiacometti** [comment]
I have been able to deply the schema using https://github.com/microsoft/healthcare-shared-components/tree/master/src/Microsoft.Health.SqlServer/Features/Schema/Migrations.

Thanks
