### ISSUE TITLE
FHIR database are missing all tables. Deployment done using deployment template

### ISSUE THREAD

**Issue by sethuraj** [microsoft/fhir-server#1378]
I have earlier created an FHIR server SQL using the docker json and that's what I have been using for development.
Now for test I used the Azure deployment template to deploy the FHIR server:
https://github.com/Microsoft/fhir-server/blob/master/docs/DefaultDeployment.md
I have created all security credentials including SMART enabled
msdeployPackageUrl This was kept blank to use teh default

Installed properly, but was getting a 503 for metadata url. It seems like database FHIR does not have any tables. Is this because of the security or did I miss any db script: 

![image](https://user-images.githubusercontent.com/933249/96691333-a3f8fe80-1339-11eb-807f-7070bb087e31.png)

![image](https://user-images.githubusercontent.com/933249/96691445-c0953680-1339-11eb-8b98-f89d3a4fb365.png)

**Comment by CaitlinV39** [comment]
@sethuraj we recently made a change so that schema upgrade is not automatically completed. This is ideal in production scenarios. You can read more about it here: https://github.com/microsoft/fhir-server/blob/master/docs/SchemaMigrationGuide.md

You can run the schema migration tool on demand to get the updates here: https://github.com/microsoft/fhir-server/blob/master/docs/SchemaMigrationTool.md

Let me know if you have additional questions

**Comment by brendankowitz** [comment]
This setting is mentioned in the docs above, but does this happen even with Enable Schema Updates set to true?
![image](https://user-images.githubusercontent.com/197221/96752112-e135ae80-1382-11eb-8931-a25a72864d12.png)

**Comment by sethuraj** [comment]
Automatic Update was set to false, as I saw that as a recommended way to do it, I saw the schema migration guide. Was wondering whether there was any other option. 
I could remove the entire environment and set the Sql Schema Automatic Updates ENabled to true and create again. Let me try that.
Thanks !

**Comment by sethuraj** [comment]
Sql Schema Automatic Updates enabled , set as True.
Still the tables were not created, same result as able

I will follow the schema migration guide.
Thanks

**Comment by davidegiacometti** [comment]
Hi @sethuraj 
I am experiencing the same problem applying scripts manually: https://github.com/microsoft/fhir-server/issues/1373

**Comment by brendankowitz** [comment]
Thanks for confirming, we'll look into this

**Comment by sethuraj** [comment]
Hi @CaitlinV39  
Tried to run this from Visual studio after setting up the package resource as mentioned in SchemaMigrationTool.md. But is giving me an error
dotnet tool install -g Microsoft.Health.SchemaManager --version [latestversion]
Specified version '[latestversion]' is not a valid NuGet version range.

Is there a version number that I can try? Thanks

**Comment by sethuraj** [comment]
This worked!
 dotnet tool install -g Microsoft.Health.SchemaManager --version 1.0.0-microsoft-data-sqlclient-20200929-1
C:\Windows\System32>schema-manager --version
1.0.0-microsoft-data-sqlclient-20200929-1+faeecc06c82503e60742651c8508ca18a8cda03e

**Comment by sethuraj** [comment]
@CaitlinV39 @brendankowitz 
I was able to use the Schema-Manager tool to update by database. I see the schema version as 4 and is able to access the metadata url.
The only issue was when I tried to install the tool [latestversion] it gave an error.  but then the exception gave me a nearby version, and I could use that.
Thanks for your help!

**Comment by CaitlinV39** [comment]
@sethuraj Sounds great! Let us know if you need anything else!
