### ISSUE TITLE
Support DevContainers - Cosmos version

### ISSUE THREAD

**Issue by eladiw** [microsoft/fhir-server#1380]
**User story**
As a software engineer / code contributer, I want to be able to use dev container with vscode so that developer environment will be easier to set up

**Acceptance criteria**
1. When I do 'run  in a container' I am able to run the code (with cosmos db) and debug it. without installing additional components locally

**Comment by CaitlinV39** [comment]
We aren't aware of a way that we could do this in cosmos so going to close
