### ISSUE TITLE
Comma escaping not working per spec

### ISSUE THREAD

**Issue by CaitlinV39** [microsoft/fhir-server#1389]
**Describe the bug**
Comma escaping not working per spec: https://www.hl7.org/fhir/search.html#escaping 

**FHIR Version?**
Stu3/R4

**Data provider?**
SQL (may also be in Cosmos)

**To Reproduce**
https://{{fhirserver}}/Practitioner?name=KEBER MD`\`,BARBARA A ; 

**Expected behavior**
Should return **Keber MD, Barbara A**

**Actual behavior**
It is searching for **Kerber MD** and **Barbara A** as two entries

**Comment by CaitlinV39** [comment]
@brendankowitz  - FYI

**Comment by CaitlinV39** [comment]
@Ivanidzo4ka  - Created AB#77071 for this for you

**Comment by brendankowitz** [comment]
Verified using a few scenarios using the following, it looks to be generating the correct queries in these situations and returning the expected results.
-  `/Patient?name:exact=KEBER MD\, BARBARA A`
-  `/Patient?name:exact=KEBER MD, BARBARA A`
-  `/Patient?name:exact=KEBER MD`
-  `/Patient?name=KEBER MD`
-  `/Patient?name=KEBER MD, BARBARA A`
