### ISSUE TITLE
Investigate Semver via GitVersion library

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1402]
**User story**
As a developer, I want to have an assembly and package versioning that uses semver so that releases are unique and make it easy to identify breaking changes and branch or hotfixes.

A simple powershell build task might also suffice, bit this library looks to be build specifically for Git alignment 
https://gitversion.net/docs/configuration#branch-configuration

**Comment by CaitlinV39** [comment]
Goal: Move away from versioning with dates

**Comment by CaitlinV39** [comment]
AB#77726
