### ISSUE TITLE
CICD setup in the local "Azure DevOps Server 2020" 

### ISSUE THREAD

**Issue by IoTFier** [microsoft/fhir-server#1409]
**Question**

Hello @brendankowitz and Azure FHIR team, greetings !

I am running a _**Azure DevOps server 2020**_ locally to build few OSS Repos that include Azure FHIR Server & Azure DICOM Server.

In my local Azure DevOps server instance, I have - a> clone repo of Microsoft/fhir-server as well as b> a clone repo of the forked copy of Microsoft/fhir server. Similarly, that of Microsoft DICOM server (and DICOM Cast).

**1.** Is there a way to automate a pull request against my forked copy (my remote) of the Microsoft /FHIR-Server (origin) to keep my forked copy up to date with the Microsoft / fhir-server ?

**2.** Is there a documentation that will help me set up a local build and release whenever -
     1a. there is a commit in the Microsoft / fhir-server master branch ? or
     1b. there my forked repo is brought in sync with Microsoft / fhir-server (via CI or manual PR) ?

I would appreciate your guidance that will also include which sequence of .yml files and variables to be set up from the build folder to setup my local CICD pipeline.

Thank you for your help.

Thanks.

* Is your question answered in our documentation? - https://docs.microsoft.com/azure/healthcare-apis/

* Our team also monitors the FHIR Community chat @ http://chat.fhir.org

**Description**
If you cannot find the answer at one of the sites above, please provide a detailed description of your question.

**Comment by IoTFier** [comment]
Hi @CaitlinV39 , @brendankowitz  - any thoughts ? 
I would appreciate your help.

Thank you.

**Comment by brendankowitz** [comment]
I think there are a number of articles that could provide the steps for point 1, e.g. https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork. I think this could be done with a scheduled task.

For point 2. CI usually has integration with the repository and needs something like Webhook notifications to fire the build off. You won't be able to set these up against the official github repository.
If the clones exist in DevOps you should be able to setup CI builds against your repositories.

I don't have instructions or guidance replicating our CI environment, but in principal we deploy a template (https://github.com/microsoft/fhir-server/tree/master/samples/templates) to create the environment, build and package the artifacts to update the site, then run tests against it. Our PR environments are self-contained, but our CI is long-lived and has a few other processes built-into such as releases, so also might not be the best example to follow.

An entry-point yaml is: https://github.com/microsoft/fhir-server/blob/master/build/pr-pipeline.yml I believe right now the only variable defined on the server is `enableAks`, everything else is self-contained.
Perhaps focus on getting just the basics first:
Build & Test: https://github.com/microsoft/fhir-server/blob/master/build/jobs/build.yml
Package: https://github.com/microsoft/fhir-server/blob/master/build/jobs/package.yml

**Comment by IoTFier** [comment]
Hi @brendankowitz , I appreciate your input. 

I will work thru your input and get back to you.

In the meantime, are there any specific input for setting up the same for FHIR DICOM and DICOMCast locally ?

Thank you.

**Comment by CaitlinV39** [comment]
@StevenBorg @moiradillon12 for input on FHIR DICOM/DICOMCast

**Comment by CaitlinV39** [comment]
@IoTFier I'm going to close this per Brendan's updates above. I have also opened an issue for you in the DICOM repo where you can engage on questions for DICOM: https://github.com/microsoft/dicom-server/issues/443
