### ISSUE TITLE
Crucible tests run concurrently with other E2E tests and cause test instabilities

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#1410]
Our CI tests run Crucible tests in the background, while the E2E tests execute. This causes instabilities because many tests assume exclusive access to the FHIR server.

See https://microsofthealthoss.visualstudio.com/FhirServer/_build/results?buildId=6653&view=logs&j=e8dae5a1-9466-5eaf-6e12-4a7c123a87b8&t=cd3406d1-7e57-58b1-5267-50c955114b8b&l=724

**Comment by CaitlinV39** [comment]
AB#77966

**Comment by CaitlinV39** [comment]
Closing for now because we dont plan to leverage crucible moving forward.
