### ISSUE TITLE
notation of search parameters

### ISSUE THREAD

**Issue by felixwimmer** [microsoft/fhir-server#1413]
We discovered a difference between the VONK FHIR Server and the Microsoft FHIR Server regarding the notation of search parameters (with or without '\_').

For example we want to select all "Conditions" for a specific patient ("subject").
For the VONK FHIR Server the search parameter has to be „subject:Patient“ (without '\_') and for the Microsoft FHIR Server it has to be „\_subject:Patient“ (with '\_').
 
Can you explain this difference? For us it is important because we want evaluate the interchangeability of these two products.

**Comment by brendankowitz** [comment]
Hi @felixwimmer, 

Can you expand the example search string, i.e. are you using `/Condition?subject:Patient=abc`?

In general, only the built-in global or special search types have `_`, e.g. `_id`.
