### ISSUE TITLE
Conformance statement requires the .date field

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1428]
**Describe the bug**
From inferno.healthit.gov:

Invalid CapabilityStatement: CapabilityStatement: Profile http://hl7.org/fhir/StructureDefinition/CapabilityStatement, Element 'CapabilityStatement.date': minimum required = 1, but only found 0

**Comment by CaitlinV39** [comment]
AB#77728

**Comment by CaitlinV39** [comment]
AB#77728
