### ISSUE TITLE
Search for fetching all Encounters for a Patient not working as expected.

### ISSUE THREAD

**Issue by ronyv** [microsoft/fhir-server#1433]
Hi guys,

I've recently implemented the Fhir-Server using Azure app service with cosmos db and imported some data generated from the Synthea project. Data has been posted mainly to the following resources,  Patient, Encounter, Condition etc. The following are the 2 critical issues that i observed once the data import is done.

1. The 'id' present in the resource json was not the one the which was stored in the db. While fetching the resources, i could see that the id was different from what was there in the data which i imported. Does the fhir server generates, own resource id ? 

2. I was simply trying to fetch all the Encounter for a particular patient using the url query https://<fhir-server-url>/Encounter?subject=Patient/<patient-resource-id>. But was not getting any results even though the patient resource id was present in the server.

Can anyone help me to understand why is this so. I am kind of stuck with understanding these basic aspects of fhir server without which i wont be able to proceed any further. Any help on this will be much appreceated.

cheers.

**Comment by Ivanidzo4ka** [comment]
1. https://www.hl7.org/fhir/resource.html#id 
The logical id is unique within the space of all resources of the same type on the same server. Once assigned by the server, the id is never changed
Yes, according to standard id is something server specific, which we override as soon as resource get posted.
If you want to find your original id, you can either have mapping somewhere, but most of the time, you can just do search by attributes to get back patient.

2. If you know id of patient on a server you can do `https//server/Encounter?subject=id` or `https//server/Encounter?subject=Patient/id`

For debugging purposes, you can query all Encounters as `https//server/Encounter` and check what patient ids you have and try to use them as filters.

**Comment by ronyv** [comment]
@Ivanidzo4ka Thanks for your response. This was a new knowledge to me. My understanding was that the server will autogenerate an id value only if a value/ id field is not present in the body json. Anyways, now my problem that i am facing is, due to this auto generation of id's, my subject reference mapping between Patient id and other resources are getting screwed up. I am inserting synthea data resource by resource into its own resource endpoints. Due to this, the Patient resource upon insertion will get a new resource id. but all the other resources related to the same patient will have the old patient id in their respective subject references. 

I can maintain a mapping between old and new Patient id's , but since it requires additional work, i am  a bit reluctant towards this. Is there a better approach ? If i insert the whole synthea bundle into the bundle resource, it should solve my issue. But i am not sure of how to make use of the bundle resource properly. For eg. to get the list of Patients resources alone or get list of Encounter resources alone from the Bundle. Is that even possible ? Is it a good practice to insert data into Bundle resources as adding data as Bundles and individual resources can cause data redundancy ?

Any advice on this will be greatly appreciated!

Thanks,
Rony

**Comment by Ivanidzo4ka** [comment]
In my limited knowledge,  bundle sounds like way to go.
If you using SQL server, you can just take json file from Synthea and post it against your server
https://server/,POST, content-type:"application/json" body = Synthea content,  and it should take care of everything. System would ingest data, and return you back new ids for all resources present in bundle.

It's a bit trickier for Cosmos, you can check samples project which monitors storage account and upload data to server:
https://github.com/microsoft/fhir-server-samples/blob/master/src/FhirImporter/FhirBundleBlobTrigger.cs

Considering what Synthea breaks data by patients, you have independent bundles of data, so it's ok to just push them one by one.

But I would assume if you break that bundles in sub-bundles, same patient in sub-bundles could end up presented as multiple different patients.

Even if you post same resource multiple times, it would register different resources with different ids, so optimal solution is to do resource search according to resource specific parameters, (For patient it can be combination of name and DOB, Synthea also provide list of identifiers for patients)

**Comment by CaitlinV39** [comment]
@ronyv please let us know if you have any additional questions!
