### ISSUE TITLE
Synthea data bundle has subject reference id's prefixed with "urn:uuid:"

### ISSUE THREAD

**Issue by ronyv** [microsoft/fhir-server#1442]
Hi Team,

i've recently spun up a fhir-server instance and loaded data generated from synthea project. One thing i noticed after loading the data is that the subject reference of the synthea json data has "urn:uuid:" prefixed which is causing issue while doing the basic search operations. For eg.

```
{
    "resourceType": "Encounter",
    "id": "xxxxxx-xxx",
    ....
    "subject": {
        "reference": "urn:uuid:5f339d06-b1d0-366b-8578-1dffecfe4f07",
        "display": "Mr. John Doe"
    }
}
```
I was expecting something like `Patient/5f339d06-b1d0-366b-8578-1dffecfe4f07` as the value of the field `reference`. As a result of this, i am not able to fetch Encounters for a patient using the url's `https://server/Encounter?subject=<patient id>` or `https://server/Encounter?subject=Patient/<patient id>`. Can anyone help me to figure out how exactly to get rid of this situation.

Thanks,
Rony

**Comment by CaitlinV39** [comment]
Hi @ronyv did you load this via a bundle or some other way? Thanks!

**Comment by ronyv** [comment]
@CaitlinV39 For now, i am handling this programmatically using a custom script written by me for data ingestion. This script basically resolve all "urn:uuid" strings and replace it with appropriate resourcetype values.

**Comment by brendankowitz** [comment]
If loaded with a Transaction Bundle I believe this should resolve, note that we only support Transactions with the SQL data provider.

If loaded with a Batch bundle then I think the current behavior is correct, see https://www.hl7.org/fhir/http.html#brules.
> References within a Bundle.entry.resource to another Bundle.entry.resource that is being created within the batch are considered to be non-conformant.

**Comment by CaitlinV39** [comment]
@ronyv I'm going to close this issue based on Brendan's feedback but please let us know if you need anything else!
