### ISSUE TITLE
Migrate to .NET 5

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1448]
**User story**
Migrate codebase to use .NET 5

- https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio
- https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0

**Comment by CaitlinV39** [comment]
AB#77730

**Comment by brendankowitz** [comment]
Requires support from https://github.com/microsoft/healthcare-shared-components/pull/133

**Comment by chgl** [comment]
Do you have/plan on adding performance benchmarks for the server? A before/after comparison for this migration would be neat.

**Comment by CaitlinV39** [comment]
This has been completed so closing this issue.
