### ISSUE TITLE
Split request telemetry

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1453]
**User story**
We should further break-out and investigate the following in request telemetry:

- Conditional-Update as its own sub-type
- Conditional-Create as its own sub-type
- Capabilities as its own sub-type
- Do we double-log? `Bundle-post` + `transition`/`batch`
- Can we log RUs in call

**Comment by CaitlinV39** [comment]
AB#77729

**Comment by CaitlinV39** [comment]
AB#77729
