### ISSUE TITLE
Allow deploying the server via Helm using an existing SQL Server as the database

### ISSUE THREAD

**Issue by chgl** [microsoft/fhir-server#1455]
**User story**
As an operator, I want to deploy the FHIR Server via Helm chart using an existing SQL Server so that I can use infrastructure present in on-premise deployments.

The Helm chart does not allow specifying a custom connection to an existing (potentially out-of-cluster) SQL Server. Currently, only an AzureSqlServer can be configured.

**Acceptance criteria**
1. When I configure the chart's values.yaml, then I can specify host, port, username, password of an existing SQL server.

I can create a PR for this, if the addition seems reasonable.

**Comment by CaitlinV39** [comment]
@chgl no issue on our side if you want to put up a PR. Thanks!
