### ISSUE TITLE
405 error while executing transaction Bundle by POST data to the fhir server endpoint

### ISSUE THREAD

**Issue by ronyv** [microsoft/fhir-server#1467]
**Describe the bug**
I am trying to import Synthea data bundles into the fhir-server. I learned that, in order to get the Synthea bundle data inserted into corresponding resource tables, i need to execute a transaction or a batch, by POST it to the server's 'root' endpoint, not the Bundle endpoint. While posting it to the servers root endpoint, i am getting "405 method not allowed" error message.

Any idea how to achieve this.

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
1. POST transaction bundle data to fhir server endpoint (ie. https://<server name>)
2. Getting 405 method not allowed message as response

**Expected behavior**
each resources in the bundle should have got inserted into respective tables.

**Actual behavior**
Getting 405 method not allowed message as response

**Comment by CaitlinV39** [comment]
@ronyv transaction is currently not supported on CosmosDB. If you want to use a transaction bundle, you can use the SQL FHIR Server, otherwise you will need to use a Batch Bundle.

**Comment by ronyv** [comment]
@CaitlinV39 Thanks for the response.

Tried to import as Batch Bundle and its working as expected, only to an extend. The issue now i am facing is that since Fhir-Server autogenerates and replaces the resource id's upon insertion, my references from one resource to another is getting broke. 

For eg. 
Relation between Patient and Encounter is Patient.id === Encounter.subject.reference.
In this case, my Patient id is getting replaced with the id generated by fhir server. But the value of Encounter.subject.reference is still having the id of the old patient id. 

Hope my explanation is clear. Any help to tackle this issue will be greatly appreciated.

**Comment by CaitlinV39** [comment]
@ronyv to be able to specify your own ID, you would need to use a PUT when writing the bundle to the database. A POST will always set an ID. Let me know if that helps.

**Comment by ronyv** [comment]
Tried to PUT the data into the fhir server endpoint (ie. https://fhir-server). And got the following error response from the server.

```
{
    "resourceType": "OperationOutcome",
    "id": "42ad2e60-5ae0-493c-975d-f68ba30df1e1",
    "issue": [
        {
            "severity": "error",
            "code": "not-found",
            "diagnostics": "The requested route was not found."
        }
    ]
}
```

**Comment by CaitlinV39** [comment]
@ronyv - You can only POST to the root so you were correct in POST-ing the bundle. But you will need to have PUT requests within the Bundle to maintain the ID. If this doesn't resolve your issue, please send us the bundle you are using and we can take a look.
