### ISSUE TITLE
Implement $everything operation roadmap

### ISSUE THREAD

**Issue by holpit** [microsoft/fhir-server#1470]
**User story**
As a user, I want to retrieve all resources related to a Patient

**Acceptance criteria**
1. When I call https://{fhirserver}/Patient/{resourceId}/$everything
2. I receive a bundle with all resources that have the patient id as subject reference

Fhir documentation:
https://www.hl7.org/fhir/operationdefinition.html
https://www.hl7.org/fhir/patient-operation-everything.html

Working example:
https://try.smilecdr.com/baseR4/Patient/1565/$everything?_count=100&_format=json

I would like to know when this functionality will be released.

Thank you.

**Comment by CaitlinV39** [comment]
@holpit we don't have an ETA on when we expect to support this but will update this issue as we make timing decisions. In the meantime, you can make two API calls to get all the details. First you can grab the patient record using /Patient/<ID> and then a second call to retrieve all the patient data using /PAtient/<ID>/*

**Comment by brendankowitz** [comment]
Some more context from implementers was discussed here: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/.24everything.20with.20_type

**Comment by CaitlinV39** [comment]
We have this implemented now: https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/patient-everything
