### ISSUE TITLE
When using $export?_format=foo an unformatted error message is returned

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1474]
**Describe the bug**
When using $export?_format=foo an unformatted error message is returned.

**To Reproduce**
1. Use a _format option that is not valid, e.g. `$export?_format=foo`

**Expected behavior**
OperationOutcome with error message of missing format

**Actual behavior**
The OperationOutcome still has text placeholder
```
  "resourceType": "OperationOutcome",
  "id": "4248cdfb-e657-4b26-affa-67aff4a01b22",
  "issue": [
    {
      "severity": "error",
      "code": "invalid",
      "diagnostics": "The format '{0}' could not be found."
    }
  ]
}
```

Related to #1422

**Comment by CaitlinV39** [comment]
AB#77963

**Comment by CaitlinV39** [comment]
AB#77963
