### ISSUE TITLE
As an Azure API for FHIR user I want to be able to configure the service to use any hostname for resources without using the host header

### ISSUE THREAD

**Issue by dlouwers** [microsoft/fhir-server#1481]
**User story**
As an Azure API for FHIR user I want to be able to configure the service to use any hostname for resources without using the host header so that I can run the Azure API for FHIR SaaS behind any reverse proxy usign our own domain name.
The specific use-case that we are running into is using our own SMART on FHIR proxy and making sure that resource links are referring to our domain name that we expose. We can achieve this using the open source version by changing the host header to be whatever we want, but since the host header is being used to identify the tenant in the SaaS version this is not an option.
From what I see it would make most sense to use the X-Forwarded-Host header for this in the hope it would not break current mechanics in the SaaS version but would allow users to set their own resource locations.

**Acceptance criteria**
1. When I set the X-Forwarded-Host header in a request to the FHIR API this header will be used as the hostname for any resources being stored or queried.

**Comment by CaitlinV39** [comment]
AB#77955

**Comment by emyklebost** [comment]
Support for X-Forwarded-PathBase and X-Forwarded-Proto is also applicable to this issue.

**Comment by CaitlinV39** [comment]
AB#77955

**Comment by CaitlinV39** [comment]
Closing as we deprioritized
