### ISSUE TITLE
FHIR OSS Server deployed successfully but the server didn't work.

### ISSUE THREAD

**Issue by zxue** [microsoft/fhir-server#1482]
The deployment (R4) was successful through the portal, but the server returned the error below in Postman when querying the meta. The same error occurred whether or not the authentication was enabled or disabled.

{
    "resourceType": "OperationOutcome",
    "id": "e994affb-5221-447f-adb1-e138096f5856",
    "issue": [
        {
            "severity": "fatal",
            "code": "exception",
            "diagnostics": "There was an error processing your request."
        }
    ]
}

**Comment by CaitlinV39** [comment]
@zxue based on the email with Brendan I'm going to close this as resolved. Let me know if you have other questions!
