### ISSUE TITLE
Large history results in many physical-partitions and slow\expensive queries.

### ISSUE THREAD

**Issue by emyklebost** [microsoft/fhir-server#1488]
Because resource versioning is implemented using the document versioning pattern where a new copy is created for every change, the majority of documents and storage space will consist of historical data. When using the CosmosDB backend this will result in many physical partitions and a lot of expensive cross-partition queries, even if the current data (not historical) is small enough to fit within few or even a single physical partition. Is there any plans to improve on this design? E.g. to move historical documents to seperate partitions in order to optimize queries on current data.

**Comment by CaitlinV39** [comment]
@emyklebost we don't have any plans to update right now. Are you already experiencing issues? If you have more details please feel free to share here or I'd be happy to have a separate call to discuss.

**Comment by emyklebost** [comment]
We estimate that the number of resources in our fhir-store will stabilize around 30-40 million within a couple of months. After that the historical data will keep increasing as resources are modified and most of it must be kept for decades. We have made some effort to reduce the number of updates:

1. Resources without actual changes won't be updated (PUT is idempotent).
2. Execute multiple changes to a document within the same update (when possible).

We are concerned that as the size of the history increases so does the number of physical partitions, with the current design this will both increase cost and reduce performance (in our use-cases).
The majority of our use-cases consists of queries on current-data of the same resource-type, e.g. `/Patient?identifier=test`. Historical data is only requested for a single resource at a time, e.g `/Patient/{logical-id}/_history.`

I respect the elegance of using the logical-ID of the fhir-resource as partition-key, thereby having all the history of that resource within the same partition and gaining the ability to use transactions when dealing with both current and historical data of the same fhir-resource. While writing this I also discovered that doing queries across history of different resources is [supported by the fhir-standard](https://www.hl7.org/fhir/http.html#history), something that the current design will scale well with, but is not applicable to our use-cases.

**Comment by brendankowitz** [comment]
Looks like you've done some good exploration. The conversation of hot/cold data has come up a few times, but something we'll defer on implementing. In early versions of the FHIR Server we even trimmed the search index on history objects to save space, but, there were also cases where search across historic versions is needed, so now its stored as-is.
With the amount of functionality we're still looking to bring in, I don't think we'll be approaching this problem in the near term.

**Comment by brendankowitz** [comment]
Closing the issue for now
