### ISSUE TITLE
Query doesn't work

### ISSUE THREAD

**Issue by felixwimmer** [microsoft/fhir-server#1490]
We are currently evaluating the MS FHIR Server and have found that it does not support the following query:
Condition?subject:Patient=PATIENT_RESOURCE_ID

But this query should be allowed according to https://www.hl7.org/fhir/search.html:
"This searches for any observations where the subject refers to the patient resource with the logical identifier "23". A modifier is also defined to allow the client to be explicit about the intended type:
GET [base]/Observation?subject:Patient=23"

In the case of MS FHIR Server the following error occurs:
{
    "resourceType": "OperationOutcome",
    "id": "4dd9c962-1312-4e6a-a70e-20a11fae05f7",
    "issue": [
        {
            "severity": "error",
            "code": "forbidden",
            "diagnostics": "Modifier 'Patient' is not supported for search parameter 'subject'."
        }
    ]
}

**Comment by CaitlinV39** [comment]
@felixwimmer we don't currently support resource types as modifiers but are working to support this in an upcoming sprint. We have a duplicate issue with #48 so I am going to close this one as duplicate.
