### ISSUE TITLE
Provenance in header for PUT and POST

### ISSUE THREAD

**Issue by ellgre** [microsoft/fhir-server#1500]
**Question**

According to the hl7 documentation it should be possible to use the header of a PUT or POST in order to create a provenance resource linked to the updated resource see https://www.hl7.org/fhir/provenance.html#header. I have tried to use the x-provenance as described but I cannot find a provenance being generated.

Is this functionality supported in the OSS cosmos solution? If yes could you please provide me with an example of how to do it? If no, do you have any plans to implement the functionality?

**Comment by brendankowitz** [comment]
Hi @ellgre, sorry we don't currently support this header

**Comment by CaitlinV39** [comment]
AB#79231

**Comment by CaitlinV39** [comment]
@ellgre - We recently merged support for this header. Please let us know if you have any additional questions!
