### ISSUE TITLE
ArgumentNullException thrown on GET request

### ISSUE THREAD

**Issue by rotodd** [microsoft/fhir-server#1503]
**Describe the bug**
We are seeing [this](https://jarvis-west.dc.ad.msft.net/ADD23BA6) exception in the logs.

The end of the stack trace points to [here](https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.CosmosDb/Features/Storage/ResourceTypeAndId.cs), which indicates this could be due to a bug in how the query is constructed for the _include functionality that was added in #1426.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB

**Comment by CaitlinV39** [comment]
@johnstairs I think you resolved this. Can we close?
