### ISSUE TITLE
Authorization mechanism implementation in FHIR server

### ISSUE THREAD

**Issue by Ivanidzo4ka** [microsoft/fhir-server#1507]
**Question**

This is design question.
I'm going through PR, and I notice we put authorization process inside mediator handlers or validator. Which I find a bit weird, for me validation and authorization is two orthogonal processes (same for mediator handler).
Example: 
https://github.com/microsoft/fhir-server/blob/119307bbf2c1bb5b19a6068f63d64b8275fbf07f/src/Microsoft.Health.Fhir.Core/Features/Compartment/SearchCompartmentHandler.cs#L49

ASP.NET provides authorization mechanism out of box (you can obviously customize it to for your need) 
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-5.0
Is there are reason why we don't use it?

Wouldn't be easier to put attribute on top of contorller action?

```
public class FhirController: Controller
{
  [Authorize(Roles = "Read")]
  public async Task<IActionResult> Search()
}
```

* Is your question answered in our documentation? No

* Our team also monitors the FHIR Community chat @ http://chat.fhir.org

**Comment by brendankowitz** [comment]
I don't mind the checks being done at the handler level. There are also composite actions/handlers:
https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.Shared.Core/Features/Resources/Create/ConditionalCreateResourceHandler.cs

A good point in this case, it does check both read|write, but it might not need to. This handler only needs to check `read` as the `write` will be checked only if create is needed.

Validation is mostly handled by Mediatr message interceptors now (https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.Shared.Core/Features/Resources/Create/ConditionalCreateResourceValidator.cs), similar to a filter.

**Comment by Ivanidzo4ka** [comment]
I've look through the code and it's one pattern everywhere:
```
            if (await _authorizationService.CheckAccess({Roles}) != {Roles})
            {
                throw new UnauthorizedFhirActionException();
            }
```

I just not sure it's worth to repeat that line in all handlers if you can just drop condition on top of controller action.


For validator case it's coming from this PR: https://github.com/microsoft/fhir-server/pull/1449/files#diff-eee3e94352c1ddb57665856e586418597ff19474af5470fd2fc8018abf79da04R29

I somewhat understand desire to check authorization before you do anything, so that's why it's been put in validator (since you don't want to do anything unless user have rights for that, and that's why [Authorize] filter is first in line to be executed).
@feordin

**Comment by johnstairs** [comment]
We originally were using MVC authorization but moved away from it. The main reasons were that we wanted to decouple authorization from MVC, and wanted to support cases where auth decisions in would be made deeper in the stack. Basically, we would need to use [imperative authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-5.0#use-imperative-authorization) but we did not want the controller driving auth enforcement.

**Comment by CaitlinV39** [comment]
@Ivanidzo4ka Right now we aren't planning to make any changes so I'm going to close but we can revisit in the future.
