### ISSUE TITLE
Issue with custom IPipelineBehavior

### ISSUE THREAD

**Issue by giacomodeliberali** [microsoft/fhir-server#1538]
**Describe the bug**

We added a custom `IPipelineBehavior` that appends the _tenantId_ in the `meta.security` property.

```csharp
public class AddTenantIdBehavior : IPipelineBehavior<CreateResourceRequest, UpsertResourceResponse>
    {
        private readonly IMediator _mediator;
        private readonly ResourceDeserializer _deserializer;

        public AddTenantIdBehavior(
            IMediator mediator,
            ResourceDeserializer deserializer)
        {
            _mediator = mediator;
            _deserializer = deserializer;
        }

        public async Task<UpsertResourceResponse> Handle(CreateResourceRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<UpsertResourceResponse> next)
        {
            // just a simplification of what we are doing
            var deviceId = observation.Device.Reference.Split("/")[1];
            var resourceElement = await _mediator.GetResourceAsync(new ResourceKey(ModelInfo.GetFhirTypeNameForType(typeof(Device)), deviceId), cancellationToken);
            var device = resourceElement.ToPoco<Device>(_deserializer);

            var tenant = device.Meta.Security.Find(c => c.System == "our-tenant-system");
            observation.Meta.Security.Add(tenant);

            return await next();
        }
    }
```

The creation of the resource randomly fails throwing a null pointer exception at line 53 of `BaseResourceHandler` when trying to generate a new GUID:

https://github.com/microsoft/fhir-server/blob/77dd1cc76ca7e3fea0756631589832b7e5af1aae/src/Microsoft.Health.Fhir.Shared.Core/Features/Resources/BaseResourceHandler.cs#L49-L54

The `Create` property that should return the lambda that generates the GUID does seem to return null:

![create-null](https://user-images.githubusercontent.com/4717227/102875361-fe026700-4443-11eb-83aa-203b1774864a.png)

If we replace the DI registration type of the `ResourceIdProvider` 

https://github.com/microsoft/fhir-server/blob/77dd1cc76ca7e3fea0756631589832b7e5af1aae/src/Microsoft.Health.Fhir.Shared.Api/Modules/PersistenceModule.cs#L28

to `AddTransient` the issue never happend again. 

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
It randomly happens after we added the new pipeline middleware 😕 

**Expected behavior**
The resource should awlays be created.

**Actual behavior**
The resource is not getting created as the GUID generations randomly fails.

**Comment by brendankowitz** [comment]
Thanks @giacomodeliberali.
There could be a subtle bug in there, possibly the use of `ResourceIdProvider`'s AsyncLocal and having a Scoped lifetime. So at a guess it might be possible for AsyncLocal to go out of context, while the IoC's scoped instance of ResourceIdProvider is still around.

I know the BundleHandler relies on `ResourceIdProvider` to set IDs, so any fix would need to ensure we don't break this.

**Comment by CaitlinV39** [comment]
AB#79320

**Comment by brendankowitz** [comment]
@giacomodeliberali we have merged a PR that should have addressed this, can you verify if this is resolved for you?

**Comment by CaitlinV39** [comment]
@giacomodeliberali  I'm going to close this but please let us know if you have any additional questions
