### ISSUE TITLE
Search fails with empty _type parameter

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#1562]
**Describe the bug**
When the _type parameter is included in a search but the value is left blank an uncaught error is returned to the user.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. Run the search `/?_type=`

**Expected behavior**
A 400 Bad Request operation outcome is returned.

**Actual behavior**
A 500 raw text error is returned.

**Comment by CaitlinV39** [comment]
AB#78775

**Comment by CaitlinV39** [comment]
AB#78775
