### ISSUE TITLE
Invalid URL returns raw error

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#1563]
**Describe the bug**
When creating a SearchParameter if the url is not formatted correctly an uncaught error is returned.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. POST this SearchParameter to /SearchParameter
```
{
    "resourceType": "SearchParameter",
    "url": "invalid",
    "name": "invalidtest",
    "status": "draft",
    "description": "test",
    "code": "text",
    "base": ["DomainResource"],
    "type": "string",
    "expression": "DomainResource.text",
}
```

**Expected behavior**
A 400 Bad Request operation outcome is returned.

**Actual behavior**
A 500 raw text error is returned.

**Comment by CaitlinV39** [comment]
@CaitlinV39 add this into custom search Epic

**Comment by CaitlinV39** [comment]
AB#79321
