### ISSUE TITLE
Reindex fails on bad type

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#1564]
**Describe the bug**
If a reindexed search parameter references a FHIR type that doesn't exist when the reindex job runs it will get a null ref error in the search option factory line 116. This is the same issue as export ran into in #1560. 

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. Create a SearchParameter for an invalid type
2. Run a reindex job

**Expected behavior**
Gracefully handle the issue. Either ignore it and continue with other search parameters, or record a useful error in the reindex job record.

**Actual behavior**
An unhelpful error of 'Object reference not set to an instance of an object.' is recorded to the job record.

**Comment by CaitlinV39** [comment]
AB#78774

**Comment by CaitlinV39** [comment]
AB#78774
