### ISSUE TITLE
Using $convert-data operation with Azure API for FHIR

### ISSUE THREAD

**Issue by gwatson86** [microsoft/fhir-server#1582]
I am attempting to use the [$convert-data operation](https://github.com/microsoft/fhir-server/blob/main/docs/ConvertDataOperation.md) to convert HL7V2 to FHIR through Postman. I have verified that I can hit the Patient endpoint, so my authorization is OK. But when I try to use the convert data operation, I can only get a 404 response back. I've tried to ensure that my endpoint URI and request body match the structure provided in the documentation.

![image](https://user-images.githubusercontent.com/42220448/104383659-cb550700-54f5-11eb-86c6-c223e6b675df.png)

![image](https://user-images.githubusercontent.com/42220448/104383721-e58ee500-54f5-11eb-972c-e447d0b8566d.png)

I see that the documentation indicates that $convert-data must be enabled on the FHIR server, but I only see that option when setting up FHIR Server for Azure, not Azure API for FHIR.

So is it that I'm setting up my request and/or URI incorrectly? Is $convert-data disabled on Azure API for FHIR? Is there something else I'm missing?

**Comment by brendankowitz** [comment]
@ranvijaykumar, @moria97 can you help with this

**Comment by ranvijaykumar** [comment]
Currently, $convert-data operation is only available in FHIR Server for Azure. We are expecting it to be available in Azure API for FHIR by the end of this month. Can you point us to the documentation that indicates that it is also available in Azure API for FHIR? We will fix that.

**Comment by gwatson86** [comment]
@ranvijaykumar Thank you for the update. Here is where we were led to believe that the operation was available in Azure API for FHIR. The mixed messaging in the documentation led to our confusion.

![image](https://user-images.githubusercontent.com/42220448/104509323-21d24c00-55af-11eb-868e-0b4f75d57653.png)

![image](https://user-images.githubusercontent.com/42220448/104509355-2dbe0e00-55af-11eb-9127-967f3a2bd7a6.png)

**Comment by ranvijaykumar** [comment]
Thanks. I have created a PR in the converter repo to update the documentation. https://github.com/microsoft/FHIR-Converter/pull/182

**Comment by ranvijaykumar** [comment]
@gwatson86 , the $convert-data is available on Azure API for FHIR now. You can see the documentation here: https://docs.microsoft.com/en-us/azure/healthcare-apis/convert-data

**Comment by sushil-clearsense** [comment]
@ranvijaykumar This link no longer works. Is this functionality still there?

**Comment by ranvijaykumar** [comment]
> @ranvijaykumar This link no longer works. Is this functionality still there?

Thanks for highlighting. Updated the link in the comment above.

**Comment by bkoprivica** [comment]
How do we "enable" $convert-data in Azure API for FHIR? The document is nowhere to be seen?!

**Comment by ranvijaykumar** [comment]
It is enabled by default. Here is the relevant documentation: https://learn.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/convert-data
