### ISSUE TITLE
Resource load performance significantly decreases as SQL database grows

### ISSUE THREAD

**Issue by jeanluc-morin** [microsoft/fhir-server#1604]
We observed that the number of resources per minute we can import decreases as the SQL Server database size increases. We are importing patients resources and as the number of patient increases, performance goes down significantly. Initially, we imported more than 1,500 resources/min but now, we are down to 100 resources/min. Is it normal? Is there any tricks to support larger set of data?

I saw some data volume measures when using CosmoDB but nothing with SQL Server. Is there some numbers available somewhere?

**Comment by johnstairs** [comment]
How large is your database (approximate GB and number of resources)? Are you performing sequential or parallelized inserts? Is this running in Azure SQL and if so, what SKU?
We have plans to improve insert throughput by providing a bulk import capability, optimizing transactional bundles, and also adjusting some of the database indexes. These will address the primary bottleneck that we have encountered, which is page latch contention under concurrent writes.

We don't have numbers published yet on SQL performance.

**Comment by jeanluc-morin** [comment]
DB size: 430MB
A little less than 400,000 resources (2/3 are history)
We have a process picking data from a file and converting it into FHIR resources and then calling the FHIR-server to add it. It's done sequentially as the order is important. 
We removed most of the search params to keep the amount of data imported and database size as minimal as possible

In this specific scenario, we came from 1,500 resources/min initially to 300/min now. 
 
Based on basic investigation, it seems that as the number of resources (and searchParams) is increasing, the time spent in the upsertResource procedure increases. The procedure query plan shows that most of the time is spent toggling the rows to isHistory=1. 

Refreshing database statistics on a regular basis helps a bit but not much.

On our journey to import a few tens of millions of resources, would you have any advice to speed up the process?

**Comment by johnstairs** [comment]
I see. The update scenario is admittedly one we have not optimized for. I will take a look at this and see what we can do. Thanks for raising the issue.

**Comment by jeanluc-morin** [comment]
Thanks for the quick response John.

In case it could help, We added an extra index on the Resource table with the ResourceId, ResourceTypeId, IsHistory columns. It helped with the stored procedure trying to find if the resource already exists.

**Comment by johnstairs** [comment]
Hi @jeanluc-morin, I think I may need some more information from you. I have a database running locally here with 58 million resources and `PUT` operations measured from the client are taking 30-50ms. I haven't made any changes to indexes.
This is all running on my local development workstation, so of course the numbers would be different running in the cloud, depending on specs. 
Are you finding a difference between updates and creates? Perhaps your data distribution is quite a bit different from what we are testing with, which is Synthea data.

**Comment by EXPEkesheth** [comment]
@jeanluc-morin - this is an old issue and we have made added support for import operation in Azure Health Data Services, which allows to ingest records in FHIR service at high throughput. Documentation : [Import Operation](https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/import-data).

I am closing the issue but feel free to reactivate / open another issue for questions related to import operation.
