### ISSUE TITLE
SQL Server Connection string is not valid error starting in version 1.0.753

### ISSUE THREAD

**Issue by chgl** [microsoft/fhir-server#1623]
**Describe the bug**

When upgrading from version `1.0.732` to `1.0.753` a `Microsoft.Data.SqlClient.SqlException (0x80131904)` is thrown stating that the previously working connection string is invalid (`provider: TCP Provider, error: 25 - Connection string is not valid`). See [fhir-server-sqlexception.txt](https://github.com/microsoft/fhir-server/files/5898798/fhir-server-sqlexception.txt)

The server is deployed using a [Helm chart](https://github.com/chgl/charts/tree/master/charts/fhir-server) and is connecting to an on-premise SQL Server version `14.00.3356`.

The env var `SqlServer__ConnectionString` looks like this: 

`Server=tcp:$(DATABASESERVERNAME),$(DATABASESERVERPORT);Initial Catalog=$(DATABASENAME);Persist Security Info=False;User ID=$(DATABASEUSERNAME);Password=$(DATABASEPASSWORD);MultipleActiveResultSets=False;Connection Timeout=30`

To be more precise, here are the slightly anonymized values that should end up in the placeholders:

`Server=tcp:db.example.com\INSTANCE1,1533;Initial Catalog=FHIR;Persist Security Info=False;User ID=fhir;Password=password123;MultipleActiveResultSets=False;Connection Timeout=30`

**FHIR Version?**
R4

**Data provider?**
SQL Server (14.00.3356)

**To Reproduce**
1. Install the fhir-server version `build/20201113-3`
2. try upgrading to `1.0.788`
3. the error above should occurr
4. move through the releases, downgrading until you find a version that does not throw the above exception
5. the last "good" version is `1.0.732`

**Expected behavior**
The fhir-server should run with the new version using the previously set-up SQL server database

**Actual behavior**
A `Microsoft.Data.SqlClient.SqlException (0x80131904)` is thrown stating that the previously working connection string is invalid (`provider: TCP Provider, error: 25 - Connection string is not valid`).

**Comment by brendankowitz** [comment]
@rbans96, @johnstairs can you look into this?

**Comment by rbans96** [comment]
I am able to deploy 1.0.754 tag in aks using the below steps:
1. Provision Azure Kubernetes Cluster
2. Run the following commands:
$SQL_PASSWORD = <password>
Import-AzAksCredential -ResourceGroupName <rg-name> -Name <cluster-name>
3. Follow the instructions here to deploy a SQL container:
https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-ver15
4. Run the following command. This assumes you used the default names provided in the SQL deployment instructions.
helm upgrade --install --set database.sql.schema.automaticUpdatesEnabled=true --set database.dataStore=ExistingSqlServer --set database.existingSqlServer.password=$SQL_PASSWORD --set database.existingSqlServer.serverName=mssql-deployment.default fhir-server fhir-server/samples/kubernetes/helm/fhir-server/
5. To connect to your server run: kubectl port-forward service/fhir-server 8080:80

I tried to use @chgl charts repo to install fhir-server but I am getting some other error so could not follow your steps.
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "AzureSqlDatabase" in version "azure.microsoft.com/v1beta1", unable to recognize "": no matches for kind "AzureSqlFirewallRule" in version "azure.microsoft.com/v1beta1", unable to recognize "": no matches for kind "AzureSqlServer" in version "azure.microsoft.com/v1beta1"]

**Comment by chgl** [comment]
Thank you @rbans96 !

It's starting to look like an SQL-Server issue on my side, the following *should* reproduce the issue but doesn't:

```sh
helm repo add chgl https://chgl.github.io/charts
helm repo add stable https://charts.helm.sh/stable
helm repo update

# using kindest/node:v1.20.2
kind create cluster

helm install mymssql stable/mssql-linux \
    --set acceptEula.value=Y \
    --set edition.value=Developer \
    --set image.repository=mcr.microsoft.com/mssql/server \
    --set image.tag=2017-CU22-ubuntu-16.04 \
    --set sapassword="UU8Z-gYKv"


helm install fhir-server chgl/fhir-server \
    --set image.tag=build-20201113-3 \
    --set database.dataStore="ExistingSqlServer" \
    --set database.sql.schema.automaticUpdatesEnabled="true" \
    --set database.existingSqlServer.serverName="mymssql-mssql-linux.default" \
    --set database.existingSqlServer.password="UU8Z-gYKv"

# upgrade to 1.0.753
helm upgrade fhir-server chgl/fhir-server \
    --set image.tag=1.0.753 \
    --set database.dataStore="ExistingSqlServer" \
    --set database.sql.schema.automaticUpdatesEnabled="true" \
    --set database.existingSqlServer.serverName="mymssql-mssql-linux.default" \
    --set database.existingSqlServer.password="UU8Z-gYKv"
```

I still can't explain why it would suddenly happen. I see that 1.0.753 updated the SqlClient library ([Bump Microsoft.Data.SqlClient from 2.0.1 to 2.1.1](https://github.com/microsoft/fhir-server/releases/tag/release%2F1.0.753)) but there are no breaking changes noted.

Maybe it's related to the `\INSTANCE1` instance specification in the connection string, which I only add for the "actual" on-premise SQL Server used.

**Comment by chgl** [comment]
Not sure if it's good or bad news, but it seems like it is in fact related to the `Microsoft.Data.SqlClient 2.0.1 -> 2.1.1` update. I've downgraded the dependency and build and deployed the image (from the latest commit) and it works without issues. See https://github.com/microsoft/fhir-server/compare/main...chgl:downgraded-sql-client?expand=1, the image is `ghcr.io/chgl/fhir-server:downgraded-sql-client`

I'll raise an issue over at https://github.com/dotnet/SqlClient. Thank you for your help!
