### ISSUE TITLE
Empty Group exports all Patients

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#1634]
**Describe the bug**
When performing a Group export, if the Group has no members then all Patients are exported.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. Insert an empty group:
```
{
	"resourceType": "Group",
	"type": "person",
	"actual": false
}
```
2. Perform a Group export: `/Group/<id>/$export`

**Expected behavior**
No resources are exported.

**Actual behavior**
All Patients and resources in their compartments are exported.

**Comment by CaitlinV39** [comment]
AB#79361
