### ISSUE TITLE
Export job hangs if storage account connection fails

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#1640]
**Describe the bug**
When an export job is run and the initial connection to the storage account fails the job will hang, never reaching a terminal state. 

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. Setup a server with invalid storage account connection properties
2. Run an export job
3. Check the job record in the database.

**Expected behavior**
The job fails with an error stating it failed to connect.

**Actual behavior**
The job is left in a running state so it continues to be picked up by the worker and rerun.

**Comment by LTA-Thinking** [comment]
This is caused because when the job attempts to update the record to report the failure it hits a null ref with the request context. This is because the request context is created after the initial storage account connection (ExportJobTask, line 129 & 132).

**Comment by CaitlinV39** [comment]
AB#79393
