### ISSUE TITLE
Unable to deploy ARM template using FhirServerSqlServer

### ISSUE THREAD

**Issue by cashman04** [microsoft/fhir-server#1660]
If I use the template found [here](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FMicrosoft%2Ffhir-server%2Fmaster%2Fsamples%2Ftemplates%2Fdefault-azuredeploy.json) either through powershell or manually in the portal, I get the following error if I set the solutionType to FhirServerSqlServer:

    Deployment template validation failed: 'Template parameter JToken type is not valid. Expected 'Boolean'. Actual 'String'. Please see https://aka.ms/resource-manager-parameter-files for usage details.'. (Code: InvalidTemplate)

This used to work and let me deploy with sqlserver and not cosmosdb.

**Comment by cashman04** [comment]
After more testing: This seems to be an issue with the latest version of the ARM template when CosmosDB was added.  I can go back to an earlier template before CosmosDB and it works fine.

**Comment by brendankowitz** [comment]
I think there is a bug here, it looks like it might be caused by one of the required parameters not having the value set properly:
![image](https://user-images.githubusercontent.com/197221/108130444-8710d580-7064-11eb-8579-c9508f663b65.png)

**Comment by cashman04** [comment]
Yes, that is the offending line.  It seems like the first half of an if statement was set that returns a bool of false, but the else isn't set which then returns a string.  I have fixed this by running a local copy of the template and just hard coding a false value.

**Comment by CaitlinV39** [comment]
AB#79894

**Comment by Ivanidzo4ka** [comment]
In case of the SQL deployment we want you to make deliberate choice of how to handle schema updates, that's why it fails during validation.

**Comment by CaitlinV39** [comment]
@cashman04 let us know if you have any additional questions. I'm going to close for now but we can reopen if there are still open items.
