### ISSUE TITLE
The FHIR element 'canonical' is not supported.

### ISSUE THREAD

**Issue by ellgre** [microsoft/fhir-server#1667]
We are running on a version of Microsoft FHIR server from July last year due to some issues upgrading the server since we were not running on Azure. We are now running on Azure with the old version for the Fhir server.

Now we have an issue we only see in production. We are getting a lot of warnings with the following text **_"The FHIR element 'canonical' is not supported."_** when we are running webJobs searching/updating a lot of Persons/Patients/Practitioners at the same time. It seems like the error message is coming from either TypedElementSearchIndexer or SearchIndexer in your code.

We also see that all searches take up to 3 seconds in the SearchIndexer module in your code. On similar data in our test environment we do not see these issues at all if there is sufficient CPU. In production we are running on 30% CPU so we have not seen any improvement after increasing CPU.

We do not know if these things are related, but we need to know if there is anything we can do, except upgrading which we have plans for doing, to avoid these warnings and to speed up the solution in production?

Thank you in advance for your help.

**Comment by CaitlinV39** [comment]
@ellgre Thank you so much for sending this. Can you provide a bit more details? When did you start seeing this issue? Did you make any changes around that time? We're trying to make sure we follow the chain of events to help figure out where this would have come from. Thanks!

**Comment by ellgre** [comment]
We started seeing these issues as soon as we started using the webJobs in Azure in January this year, and we see the warning for all of them. One webJob is securing that 25.000 practitioners are updated daily, another is adding persons and patients from our national registry, another is keeping the persons and patients updated. There is appoximately 10 million persons and patients in the database.

In application insights we can in transaction search see that while the jobs are running we get a lot of these warnings. Our data is sampled, but we have over 12.000 warnings with "canonical" in 24 hours. I will send you detailed information about a warning.

For the issue with performance we have run the profiler in Azure and we find the following pattern.
![image](https://user-images.githubusercontent.com/49271431/108207904-a40edc80-7128-11eb-9523-517c66d14f5f.png)
This is from a test environment running on low CPU. In production we see 3 seconds as time used for the SearchIndexer.

Please do not hesitate to ask should you need more details.

**Comment by brendankowitz** [comment]
I'd say you most likely have resources with `Meta.profile` fields. When the search indexer finds a datatype where it can't convert from the model type (`Canonical`) to the search type (`Uri`) then the warning you are seeing is generated (`The FHIR element 'canonical' is not supported.`). We [recently](https://github.com/microsoft/fhir-server/releases/tag/release%2F1.0.800) merged support for canonical.

In regards to `TypedElementSearchIndexer` and `SearchIndexer`. `SearchIndexer` is based on POCO objects and will be removed in the future, the `TypedElementSearchIndexer` is based on a lower level interface and FHIR Path, so it is more agnostic across FHIR versions. At some point last year we updated our configuration to [default to the new implementation](https://github.com/microsoft/fhir-server/blob/effeb936cfeeece9fb20922fe1c31a5119edd55b/src/Microsoft.Health.Fhir.Core/Configs/CoreFeatureConfiguration.cs#L28).

Unless you are using the newer code that implements canonical, to avoid these messages you may have to raise the minimum level for log messages above warning, or edit the code to remove this message.

**Comment by ellgre** [comment]
You are correct that we have meta.profile fields. Thank you for your advice we will look into which alternativ we prefer.
