### ISSUE TITLE
Documentation on how to configure fhir-server with cosmosdb

### ISSUE THREAD

**Issue by luckyluc74** [microsoft/fhir-server#1708]
Where can I find documentation on how to configure fhir-server (not Azure Fhir service) with Azure cosmosdb?

In my case I currently run microsoft fhir-server as micoservice in azure aks (kubernetes) configured to sqlserver, but I would like to configure it using Azure cosmosdb.

**Comment by CaitlinV39** [comment]
@luckyluc74 This guide will give details on deploying on Azure in the portal: https://github.com/microsoft/fhir-server/blob/main/docs/QuickstartDeployPortal.md

The template allows for you to select SQL or Cosmos so you can fill in the Cosmos requirements and ensure that the **Solution Type** field is set to FhirServerCosmosDB

Let me know if you have additional questions.
