### ISSUE TITLE
Support for multi-tenant applications

### ISSUE THREAD

**Issue by furyd** [microsoft/fhir-server#1714]
**User story**
As a provider of services, I want the capacity to select a data store on a per-request basis so that multiple tenants may use the same service whilst maintaining separate data stores.

**Acceptance criteria**
1. When users from clients A and B both make a request to the same endpoint, A's request should use datastore ADatabase and B's BDatabase.
2. When the service starts up, initial and background tasks should not error and operate as expected according to the relevant feature flags.

**Comment by CaitlinV39** [comment]
@furyd It sounds like Azure Traffic Manager might be the solution you are looking for. You can read more about that here: https://docs.microsoft.com/en-us/azure/traffic-manager/

We also have a team that has built a proxy that can help with some pre-processing steps outside of the actual FHIR server. You can read more about their solution here: https://github.com/microsoft/health-architectures/tree/master/FHIR/FHIRProxy

I'm going to close this for now as any other development on this is not on our roadmap right now but if you have additional questions please let me know.

**Comment by furyd** [comment]
Hi @CaitlinV39, thank you for responding - I may not have explained myself very well (lack of sleep!)

What we're looking at is providing a single FHIR server, backed by several SQL databases - one per customer - so we have data isolation.

Which database is determined at time-of-request, however the current codebase expects a single database as there are non-request based activities (e.g. init and health checks.)

I appreciate that you've no plans to go down that route currently though.
