### ISSUE TITLE
X-Correlation-ID request-header is not respected

### ISSUE THREAD

**Issue by emyklebost** [microsoft/fhir-server#1725]
**User story**
As an API-consumer, I want the fhir-server to use the x-correlation-id header I include in my requests so that I can use it to track requests across systems and logs.

The fhir-server's current behavior is to generate a new random correlation-id on every request-handling regardless of the incoming request's x-correlation-id header.
[Link to current correlation-id provider](https://github.com/microsoft/fhir-server/blob/163f389525839506ea4b776064e27781f0dde879/src/Microsoft.Health.Fhir.Shared.Api/Modules/FhirModule.cs#L132).
[Link to where it is set](https://github.com/microsoft/fhir-server/blob/ac70f53c8919156b5e994c60450a2c4ad211281e/src/Microsoft.Health.Fhir.Api/Features/Context/FhirRequestContextMiddleware.cs#L43).

**Acceptance criteria**
1. When I add a x-correlation-id header to my requests, then that value should be used in the fhir-server's logs, metrics and responses containing a correlation-id.

**Comment by brendankowitz** [comment]
The `X-Request-Id` is always assigned by the server in a response.

The spec outlines:
**X-Request-Id**: A unique id to for the request/response assigned by either client or server. Request: assigned by the client. Response: assigned by the server
**X-Correlation-Id**: A client assigned request id echoed back in the response

References:
- https://www.hl7.org/fhir/http.html#custom
- Example: https://github.com/microsoft/fhir-server/commit/bee49f01ad26bbbb0dc30ffa3fd7b45f32056fb1

**Comment by emyklebost** [comment]
I see that the fhir-specification does not define the use of correlation-id like I'm used to using it.
I was not aware the mentioned custom-headers-in-log feature, I will have to look into that, combined with x-request-id it seems to suitable for our use case.

However, I'm not able to get the x-request-id header to work as described, am I missing something?
![image](https://user-images.githubusercontent.com/2029260/110367767-670f7900-8048-11eb-8c5e-b90eb5d6e597.png)

**Comment by CaitlinV39** [comment]
@emyklebost - We just merged a resolution for this. Please let us know if there is anything else that you need! For now I will close but we can always reopen.

**Comment by emyklebost** [comment]
> @emyklebost - We just merged a resolution for this. Please let us know if there is anything else that you need! For now I will close but we can always reopen.

Hi, I'll mention it here before instead of opening a new issue.
As suggested by @brendankowitz I'm trying to add a custom-header with information  expect to appear in the ms-fhir-server audit logs. However, I'm unable to get this to work. If i set a breakpoint in the AuditLogger and inspect the request's headers I can confirm that my custom-header is received, but it does not appear in the logs as expected. This is using [latest main](https://github.com/microsoft/fhir-server/tree/9e63809758de0e1b8351bd9b4f1d2c8285c879f1).

![image](https://user-images.githubusercontent.com/2029260/111028835-9ed84100-83f9-11eb-9aa4-805861950983.png)

**Comment by emyklebost** [comment]
> > @emyklebost - We just merged a resolution for this. Please let us know if there is anything else that you need! For now I will close but we can always reopen.
> 
> Hi, I'll mention it here instead of opening a new issue.
> As suggested by @brendankowitz I'm trying to add a custom-header with information, expecting it to appear in the ms-fhir-server audit logs. However, I'm unable to get this to work. If i set a breakpoint in the AuditLogger and inspect the request's headers I can confirm that my custom-header is received, but it does not appear in the logs as expected. This is using [latest main](https://github.com/microsoft/fhir-server/tree/9e63809758de0e1b8351bd9b4f1d2c8285c879f1).
> 
> ![image](https://user-images.githubusercontent.com/2029260/111028835-9ed84100-83f9-11eb-9aa4-805861950983.png)
> 
> EDIT: I see that the custom-headers are [not mentioned in the audit-message-format,](https://github.com/microsoft/fhir-server/blob/ac70f53c8919156b5e994c60450a2c4ad211281e/src/Microsoft.Health.Fhir.Api/Features/Audit/AuditLogger.cs#L25) is this a bug?

tagging @CaitlinV39 , hoping this gets attention

**Comment by Ivanidzo4ka** [comment]
https://github.com/microsoft/fhir-server/blob/ac70f53c8919156b5e994c60450a2c4ad211281e/src/Microsoft.Health.Fhir.Api/Features/Audit/AuditLogger.cs#L25
>            "StatusCode: {StatusCode}" + Environment.NewLine +
>            "CorrelationId: {CorrelationId}" + Environment.NewLine +
 >            "Claims: {Claims}";

that sadge :(

**Comment by CaitlinV39** [comment]
@emyklebost - We have merged a PR that allows you to write a custom header to the audit log. Let us know if there is any other issue!

**Comment by Brainstorm300** [comment]
This all-in-one and its replacement cartridges are designated for sale in: / Cet appareil tout-en-un et ses cartouches de rechange sont destinés à la vente dans les pays suivants: / Esta impresora muitifuncional y
sus cartuchos de repuesto están destinados para la venta en:
US, CA
Product specifications and other information on this packaging are subject to change without prior notice. All HP products are intended for legal use only. Product color, design, and screen appearance may vary. /
Les spécifications du produit et tout autre renseignement apparaissant sur cet emballage peuvent être modifiés sans préavis. Tous les produits HP sont destinés é un usage légal seulemeht. L'aspect de l'écren, la
conception et la couleur du produit peuvent varier. / Las especificaciones de productos y otra información presentada en este paquete están sujetas a cámbios sin aviso previo. Todos los productos HP han sido
diseñados únicamente para usos legales. El color, el diseño y la apariencia de la pantalla del producto pueden variar.
iPad, iPhone, and iPod, are trademarks of Apple Inc., registered in the U.S. and other countries. App Store is a service mark of Apple Inc. AirPrint and the AirPrint logo are trademarks of Apple Inc. iBeacon is a
trademark of Apple Inc. / iPad, iPhone et iPod sont des marques de commerce d'Apple Inc., déposées aux États-Unis et dans d'autres pays. App Store est une marque de service d'Apple Inc. AirPrint et AirPrint logo
sont des marques de commerce d'Apple Inc. et Beacon est une marque de commerce d'Apple Inc. / iPad, ¡Phone y iPod son marcas comerciales de Apple Inc., registradas en los Estados Unidos y en otros palsies.
App Store es una marca de servicio de Apple Inc. AirPrint y el AirPrint logo son marcas comerciales de Apple Inc. ¡Beacon es una marca comercial de Apple Inc.
e
Use of the Made for Apple and Works with Apple Beacon badges means that an accessory has been designed to connect specifically to the Apple products) identified in the Made for Apple badge and to work.
specifically with the technology identified in the Works with Apple badge, and has been certified by the developer to meet Apple performance standards. Apple is not responsible for the opergtion of this device or
its compliance with safety and regulatory standards. / L'utilisation de l'insigne Made for Apple et Works with Apple Beacon signifie qu'un accessoire est conçu pour se connecter spécifiquement aux produits Apple
indiqués sur l'insigne Made for Apple et fonctionnent spécifiquement ave la technologie signalée sur l'insigne Works with Apple et démontre que les produits sont certifiés par le concepteur conforme aux norte
en performance de Apple. Apple ne put étre tenu responsable pour le fonctionnement de cet appareil ni de sa conformité aux normes de sécurité et de réglementation. / El uso de los distintivos Made for Apple
Works with Apple Beacon significa que un accesorio ha sido diseñado para conectarse especificamente a los productos Apple identificados en el distintivo Made for Apple y para funcioner especificamente cof ta
tecnologia identificada en el distintivo Works wfth Apple, y que ha sido certificado por el desarrollador para cumplir con los estándares de rendimiento de Apple. Apple no es responsable por la operación de estl
dispositivo ni por su cumplimiento de los estándares de seguridad y normativos.
Wi-Fi® is a registered trademark of Wi-Fi Alliance®. The Wi-Fi CERTIFIED'* logo is a trademark of Wi-Fi Alliance®. / Wi-Fi® est une marque déposée de Wi-Fi Alliance®. Le logo
Wi-FI CERTIFIED'* est une marque de Wi-Fi Alliance®. / Wi-Fi® es una marca comercial registrada de Wi-Fi Alliance®. El logo de Wi-Fi CERTIFIED™ es una marca comercial de Wi-Fi Alliance®
Android and Google Play are trademarks of Google Inc. Google and the Google Logo are registered trademarks of Google Inc. / Android et Google Play sont des marquês de commerce de Google Inc. Google et le lo
Google sont des marques déposées de Google Inc. / Android y Google Play son marcas comerciales registradas de Google Inc. Google y el logotipo de Google son marcas comerciales registradas de Google Inc,
The Bluetooth trademarks are owned by their proprietor and used by HP Inc. under license. / Les marques de commerce Bluetooth appartiennent à leur propriétaire et sont utilisées sous licence par HP Inc. /
Las marcas comerciales Bluetooth pertenecen a sus propietarios y HP Inc. las utiliza bajo licencia.
Amazon, Alexa, and all related logos are trademarks of Amazon.com, Inc. or its affiliates. / Amazon, Alexa, et tous les logos associés sont des marques de commerce 'Amazon.com, Inc. ou ses sociétésSiffilides
Amazon, Alexa y todos los logotipos relacionados son marcas registradas de Amazon.com, Inc. y sus filiales.
Impresora con seguridad dinámica activada. Solo se prevé su so con cartuchos que utilicen un chip original de HP. Es posible que los cartuchos que utilicen un chip que no sea de HP no funcionen, y que los qui
funcionan hoy dejen de hacerlo en el futuro. Obtenga más información en:
www.hp.com/go/learnaboutsupplies
