### ISSUE TITLE
Support for handling=strict/lenient in Prefer header

### ISSUE THREAD

**Issue by emyklebost** [microsoft/fhir-server#1726]
**User story**
As an API consumer, I want to be able to force strict handling of unknown or unsupported parameters so that queries don't result in unexpected results or behavior, e.g. due to typos by the user.

This is an optional feature of the FHIR specification, [see section about Unknown and unsupported parameters](https://www.hl7.org/fhir/search.html#errors).

**Acceptance criteria**
1. When I do a query with unknown or unsupported parameters and the Prefer header is set to 'strict', then the fhir-server should return BadRequest with a descriptive OperationOutcome body.

**Comment by brendankowitz** [comment]
Thanks @emyklebost. This is already in our backlog #1050, we do intent to support this, however I'm not sure which milestone this will make it in.

**Comment by emyklebost** [comment]
duplicate #1050
