### ISSUE TITLE
Remove legacy SearchIndexer classes

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#1738]
**User story**
We have moved to the [TypedElementSearchIndexer](https://github.com/microsoft/fhir-server/blob/main/src/Microsoft.Health.Fhir.Core/Features/Search/TypedElementSearchIndexer.cs), which is now used by default. It is time to remove the old [SearchIndexer](https://github.com/microsoft/fhir-server/blob/main/src/Microsoft.Health.Fhir.Shared.Core/Features/Search/SearchIndexer.cs), related [Converters](https://github.com/microsoft/fhir-server/tree/main/src/Microsoft.Health.Fhir.Shared.Core/Features/Search/Converters), Unit tests and [feature flag](https://github.com/microsoft/fhir-server/blob/main/src/Microsoft.Health.Fhir.Core/Configs/CoreFeatureConfiguration.cs#L28).

**Comment by CaitlinV39** [comment]
@Ivanidzo4ka  - Can we close this issue?

**Comment by Ivanidzo4ka** [comment]
Yes, we can!
