### ISSUE TITLE
CarePlan doesn't support the search params activity-goal, activity-outcomereference and activity-medicaldevice

### ISSUE THREAD

**Issue by sasireha** [microsoft/fhir-server#1742]
**Describe the bug**
When we retrieve CarePlan resource using the following query 
```
GET [base]/CarePlan?_include=CarePlan:activity-goal:Goal
&_include=CarePlan:activity-outcomereference:Observation
&_include=CarePlan:activity-medicaldevice:DeviceUseStatement
```
Fhir server does not support the following search parameters
- activity-goal
- activity-outcomereference
- activity-medicaldevice

**FHIR Version?**
Stu3

**Data provider?**
SQL Server

**Expected behavior**
Should be able to retrieve CarePlan with the above listed search params.

**Actual behavior**
Throws forbidden error.

`{
    "resourceType": "OperationOutcome",
    "id": "08438bba-ac22-4acb-af15-f031fd976aec",
    "issue": [
        {
            "severity": "error",
            "code": "forbidden",
            "diagnostics": "The search parameter 'activity-goal' is not supported for resource type 'CarePlan'."
        }
    ]
}`

**Comment by CaitlinV39** [comment]
@sasireha These search parameters are not standard search parameters for the CarePlan type. You can find the list here: http://hl7.org/fhir/STU3/careplan.html#search

We are working to support defining your own search parameters, and once that feature is available you could add these to your database. We are tracking that in issue #768 

I'm going to close this for now, but if you have additional questions please let us know.
