### ISSUE TITLE
IFhirAuthorizationService CheckAccess does not allow for a CancellationToken

### ISSUE THREAD

**Issue by CaitlinV39** [microsoft/fhir-server#1758]
**User story**
Currently CheckAccess in the OSS implementation is simply with no dependencies, thus has no need for a CancellationToken. 

However, the interface may be implemented in ways that do have downstream dependencies, such as in the managed service, where we use Azure RBAC.  These calls need a CancellationToken, and our interface should be updated to accept it.

**Acceptance criteria**
Interface is updated to allow for a CancellationToken

**Comment by CaitlinV39** [comment]
AB#78978

**Comment by Ivanidzo4ka** [comment]
There is https://github.com/microsoft/healthcare-shared-components/blob/ded04df9f10df5160941956e12b7560f76b2120e/src/Microsoft.Health.Core/Features/Security/Authorization/IAuthorizationService.cs interface so it's better to switch to it instead of specific one for this project.
