### ISSUE TITLE
Impossible to use DELETE in Bundle with Azure FHIR API

### ISSUE THREAD

**Issue by DevWantJustHaveFun** [microsoft/fhir-server#1765]
**Describe the bug**
I'm using Azure FHIR API, I try to do a batch DELETE using BUNDLE like described in the FHIR documentation
http://www.hl7.org/FHIR/bundle.html

**FHIR Version?**
R4

**Data provider?**
Azure FHIR API

**To Reproduce**
I'm doing this:

```

tokenFIHR=$(curl -s -X POST "https://login.microsoftonline.com/${tenant_id}/oauth2/v2.0/token" -d "client_id=${client_id}&client_secret=${client_secret}&grant_type=client_credentials&scope=https://{azure-tenant-id}.azurehealthcareapis.com/.default" | sed -n 's|.*"access_token":"\([^"]*\)".*|\1|p')

 curl -X POST -H "Authorization: Bearer $tokenFIHR"  -H "Content-Type: application/fhir+json; charset=utf-8"  -d '{"resourceType":"Bundle","id":"bundle-transaction","meta":{"lastUpdated":"2021-03-11T11:22:16Z"},"type":"transaction","entry":[{"request":{"method":"DELETE","url":"Patient/1234567890"}}]}' https://{azure-tenant-id}.azurehealthcareapis.com
```
  

 
**Expected behavior**
 I expected this response (with the type "transaction-response"):

```
{
  "entry": [
    {
      "response": {
        "status": "200 OK"
      }
    }
  ],
  "resourceType": "Bundle",
  "type": "transaction-response"
}
```

**Actual behavior**

But I get this response (with same type "type":"transaction"")

```
{"resourceType":"Bundle","id":"7f555118-0cdb-40f7-9f97-aa6db06e28fe","meta":{"versionId":"1","lastUpdated":"2021-03-23T16:57:08.433+00:00"},"type":"transaction","entry":[{"request":{"method":"DELETE","url":"Patient/1234567890"}}]}
```

and my data was not deleted, any idea what I'm doing wrong ?

**Comment by CaitlinV39** [comment]
@DevWantJustHaveFun - Right now we don't support transaction bundles on the Azure API for FHIR, only batch bundles.

**Comment by brendankowitz** [comment]
If posting to the `https://server/` endpoint in Azure API for FHIR, then I would expect that you would receive an error when `"type":"transaction"`

If posting to the `https://server/Bundle` endpoint you would store the Bundle as a Resource, so it would be echoed back like in the example above.

**Comment by DevWantJustHaveFun** [comment]
@CaitlinV39  @brendankowitz  thanks for your responses, that's helped 

the trick was to POST the bundle to "https://server/" and use the "type":"batch"

I get a successful response when I call the Azure FHIR API this way:

```
curl -X POST -H "Authorization: Bearer $tokenFHIR" -H "Content-Type: application/json" -d '{"resourceType":"Bundle","id":"bundle-batch","meta":{"lastUpdated":"2018-03-11T11:22:16Z"},"type":"batch","entry":[{"request":{"method":"DELETE","url":"Patient/1234567890"}}]}' https://{azure-tenant-id}.azurehealthcareapis.com/ 
```

Can you confirm that, now I can delete my patient and all this dependency (for example observation) in one bundle (one http call :tada: ) but there is no guarantee about the data consistency if some bundle entry are failing in between right ?

**Comment by brendankowitz** [comment]
Correct, all calls within a bundle are treated independently. In the batch bundle response you can inspect the status of each of the request outcomes

**Comment by CaitlinV39** [comment]
@DevWantJustHaveFun let us know if you have additional questions!

**Comment by DevWantJustHaveFun** [comment]
@CaitlinV39 only one question, when the "transaction" will be supported ? :)
