### ISSUE TITLE
Database of Azhure FHIR 

### ISSUE THREAD

**Issue by remyahalza** [microsoft/fhir-server#1777]
which is the database of Azure FHIR APi, By default where the data is stored?
Is it possible to configure fhir api with custom database?

**Comment by CaitlinV39** [comment]
@remyahalza - If you are using the managed Azure API for FHIR, you do not have access to the underlying datastore. It is backed by Cosmos DB. If you want to have access to the underlying data, you can use either the Cosmos DB or SQL deployment of the FHIR Server in this repo. Let me know if that answers the question.
