### ISSUE TITLE
Get FHIR Server Version

### ISSUE THREAD

**Issue by davidegiacometti** [microsoft/fhir-server#1778]
**User story**
Add an API to retrieve FHIR server version corresponding to the GitHub release that is deployed.

**Comment by Ivanidzo4ka** [comment]
https://www.hl7.org/fhir/capabilitystatement-definitions.html#CapabilityStatement.software
CapabilityStatement.software.version sounds like a good candidate to output that information. 

We should probably put release information into that field.

**Comment by Ivanidzo4ka** [comment]
We actually using that field and populate it with Assembly.Version value.
Which we populate with `AssemblySemVer`  see https://gitversion.net/docs/reference/variables

problem its not descriptive enough.
>Suitable for .NET AssemblyVersion. Defaults to Major.Minor.**0.0** to allow the assembly to be hotfixed without breaking existing applications that may be referencing it.

@brendankowitz Can we switch to `AssemblySemFileVer` instead?

Our first minor upgrade happened 3 days ago, so all versions looks like `1.0.0.0`

**Comment by brendankowitz** [comment]
We set it here for the nuget packages and webdeploy files, but I don't think it gets set properly in the docker build.

https://github.com/microsoft/fhir-server/blob/473baa53043441996ed5391081da183daa2372ab/build/jobs/build.yml#L14-L15

Our strategy is configured slightly differently atm in that we're only requiring recompilation on Major increments.

**Comment by Ivanidzo4ka** [comment]
>nuget packages
![image](https://user-images.githubusercontent.com/1523833/113748090-ed0cf700-96bc-11eb-9da7-681b5015ac75.png)

Can we switch that build command to use `assemblySemFileVer`  instead of `assemblySemVer` or maybe change assignment of `assemblySemVer` to same assignment we have for `assemblySemFileVer`

**Comment by Ivanidzo4ka** [comment]
Another option is not to use AssemblyVersion in capability statement, and use FileVersion instead.

**Comment by CaitlinV39** [comment]
@davidegiacometti we added this in PR #2294
