### ISSUE TITLE
Guidance of use of POST search parameters

### ISSUE THREAD

**Issue by ellgre** [microsoft/fhir-server#1783]
I have tried to find documentation on how to create search parameters by using POST search parameters but have not been successful. Do you have a user's manual that I can use?

Is it possible for you to provide me with an example on how to create a search parameter for Practitioner -> Qualification -> Code, and for an extension it would be very helpful. I have tried to create some based on existing search parameters but I have not achieved much so far.

**Comment by CaitlinV39** [comment]
@ellgre we actually are still working to release this functionality. It should be available in SQL in the next couple of weeks and I can follow up on this post once we do. You can look through the closed PRs and see some of the details, but you will need to not only create the new search parameter, but reindex your data (which isn't available yet in SQL).

**Comment by ellgre** [comment]
We are using cosmosdb. Is is available for us?

**Comment by Ivanidzo4ka** [comment]
As @CaitlinV39 said it's not yet set in stone and we still working on this, but I think it's OK to provide some information considering we close to finish that feature. But please read things below with idea in mind what things can change.

So first you need to create SearchParameter.

```
{
    "resourceType": "SearchParameter",
    "id": "example",
     "extension": [
        {
            "url": "http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status",
            "valueCode": "trial-use"
        }
    ],
    "url": "http://hl7.org/fhir/SearchParameter/Practitioner-qualification-code",
    "version": "4.0.1",
    "name": "qualification-code",
    "status": "draft",
    "experimental": false,
    "date": "2019-11-01T09:29:23+11:00",
    "publisher": "Your royal highness",
    "contact": [
        {
            "telecom": [
                {
                    "system": "email",
                    "value": "cat@cat.com"
                }
            ]
        }
    ],
    "description": "Code for practitioner qualification",
    "code": "qualification-code",
    "base": [
        "Practitioner"
    ],
    "type": "token",
    "expression": "Practitioner.qualification.code",
    "xpath": "f:Practitioner/f:qualification/f:code",
    "xpathUsage": "normal"
}
```

You need to post that resource on your server.

After it been posted all new resources  should be proceeded with that search parameter and values would be extracted. If you want to reindex already posted resources, you need to run $reindex job for Practitioner resource.

So let's post some resource. For example this one: https://www.hl7.org/fhir/practitioner-example.json.html

Now let's see do search:

I'm doing GET request https://localhost:44348/Practitioner/?qualification-code=BS
It wouldn't return you back results by default because we haven't reindex all resources and we consider that search parameter not completely supported, but that behavior can be overridden if you add header: `x-ms-use-partial-indices` with value `true`.

Now if I issue same GET request I would get my practitioner example back!
I can also do https://localhost:44348/Practitioner/?qualification-code:text=Bachelor of Science to search by text or 
https://localhost:44348/Practitioner/?qualification-code=http://terminology.hl7.org/CodeSystem/v2-0360/2.7|BS if I want to use system as well.

**Comment by ellgre** [comment]
Thank you. 
It seems like I have entered the wrong url when I tried to set this up, and I am not able to remove or update the search parameter. I get the following error message
{
  "resourceType": "OperationOutcome",
  "id": "e348db12-0b46-478d-b68a-f0f8c84a614a",
  "issue": [
    {
      "severity": "error",
      "code": "not-supported",
      "diagnostics": "The search parameter with definition URL 'http://helsedirektoratet.no/SearchParameter/Practitioner-qualification-code' is not supported."
    },
    {
      "severity": "error",
      "code": "exception",
      "diagnostics": "An error occurred updating the custom search parameter.  The issue must be resolved and the update resubmitted to be applied."
    }
  ]
}

Is there something I can to to get rid of the search parameter?

I get the following error when I try to use the search parameter:
{
  "resourceType": "OperationOutcome",
  "id": "d026aa64-d2c6-47f7-b4c0-e87949cf9788",
  "meta": {
    "lastUpdated": "2021-03-25T21:58:46.9888653+01:00"
  },
  "issue": [
    {
      "severity": "error",
      "code": "invalid",
      "diagnostics": "'qualification-code' The parameter is unknown or not supported."
    }
  ]
}

I have tried using your example, but it seems like the one I had already created is causing trouble.

**Comment by Ivanidzo4ka** [comment]
You can always delete that search parameter. You can do GET `http://helsedirektoratet.no/SearchParameter` to see what's the id of your search parameter and then do DELETE `http://helsedirektoratet.no/SearchParameter/{id}`.

I would also suggest to restart server after that, just to make sure that search parameter wouldn't be in memory (ofc, if that's possible)

Also as you could probably notice I did all my changes locally, and there is lag between this repository and PaaS service, so there is chance some bugs which already fixed are still present in azure service.

**Comment by ellgre** [comment]
Thank you for your quick response.
I have tried the delete and even though my search parameter now looks like this
{
  "resourceType": "SearchParameter",
  "id": "5ad1342a-2977-49db-9f0f-a6a6919a0c3a",
  "meta": {
    "versionId": "9",
    "lastUpdated": "2021-03-25T21:01:28.866+00:00"
  },
  "url": "http://hl7.org/fhir/SearchParameter/Practitioner-qualification-period",
  "version": "4.0.1",
  "name": "qualification-period",
  "status": "draft",
  "experimental": false,
  "date": "2020-03-12T09:29:23+00:00",
  "description": "Yrkesgruppe knyttet til en qualification",
  "code": "qualification-period",
  "base": [
    "Practitioner"
  ],
  "type": "token",
  "expression": "Practitioner.qualification.period",
  "xpath": "f:Practitioner/f:qualification/f:periode",
  "xpathUsage": "normal"
}

I still get the error message regarding the url I had before when I try to delete it.

![image](https://user-images.githubusercontent.com/49271431/112545845-f8a51780-8db8-11eb-8782-5439c7003af1.png)

**Comment by Ivanidzo4ka** [comment]
@feordin  for visibility.
As Caitlin said,  this is in feature in development, and we not even claim it's working right now, but we getting closer, so sorry about bumpy road.

I've tried to post that resource and delete it from server and current master branch and https://github.com/microsoft/fhir-server/releases/tag/release%2F1.0.854 (I assume that's what we have in azure right now) works fine with deletion.

If that's your server, and you have access to cosmos db, I can help you with writing query to clean SearchParameters table.
Or if you know what version of code you using can be helpful to debug that as well.

**Comment by ellgre** [comment]
We are running 854 and I have access to the query window in CosmosDb. I am not used to generating queries in cosmosdb.

**Comment by ellgre** [comment]
I could delete it now. Just needed to wait for a while.

**Comment by Ivanidzo4ka** [comment]
As I said we still working on this feature, and it looks like currently it works only if server holds searchParameter in memory, so if you restart your server searchParameter wouldn't be loaded. So if you restarted server at any moment, that could be reasonable explanation. 

There is PR to address that: https://github.com/microsoft/fhir-server/pull/1782 

You can try to play with it by deleting searchParameter and uploading it again, but I would just wait for a new release, it should be more polished experience than right now.

**Comment by ellgre** [comment]
Thank you. We will wait for the final solution.
