### ISSUE TITLE
Resource cleanup is lacking for failed PRs.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [microsoft/fhir-server#1803]
Pick any failed PR.
https://microsofthealthoss.visualstudio.com/FhirServer/_build/results?buildId=10072&view=results as example.
We create resources in azure, but we don't clean them if PR failed somewhere.

There is few outcomes for such PR:
1. Someone push new version or retry failed job. It succeeded and we clean resources in azure.
2. Something blocking PR and no one retry failed job. Like this one: https://github.com/microsoft/fhir-server/pull/1702 Resources would remain in azure until retry or new iteration.
3. PR get closed. Maybe it's dependabot found newer version, maybe whole purpose of PR to run tests and see what would happen. As example: https://github.com/microsoft/fhir-server/pull/1625  Resources in azure would remain until someone would delete them manually.

In case of 2 and 3 we just waste resources. Which can be costly.

I would advocate to cleanup resources even in case of test failures.

As alternative we can add workflow for closing PR and do cleanup in that [workflow](https://github.com/brennerm/github-actions-pr-close-showcase/blob/master/.github/workflows/pr-close.yml). That would solve case 3 (2nd case would still be problematic)

**Comment by CaitlinV39** [comment]
AB#81259
