### ISSUE TITLE
Evaluate if we can remove analyzer with .NET 6

### ISSUE THREAD

**Issue by Ivanidzo4ka** [microsoft/fhir-server#1848]
I've checked in https://github.com/microsoft/fhir-server/tree/main/tools/FhirAnalyzer analyzer and it would be nice to move it into https://github.com/microsoft/healthcare-shared-components repository and use it as external nuget instead of local tool.

**Comment by CaitlinV39** [comment]
AB#84440

**Comment by brendankowitz** [comment]
This was done
