### ISSUE TITLE
Update CachedHealthCheck in HealthCareSharedComponents to allow multiple requests

### ISSUE THREAD

**Issue by CaitlinV39** [microsoft/fhir-server#1868]
**User story**
Currently the CachedHealthCheck class uses a semaphore to allow only 1 thread of execution to check and possibly update the healthcheck result.  If one thread blocks and retains the semaphore for a long period of time, manyother healthcheck calls will fail.

We should allow multiple request to access the cached result at once, and perhaps only block if the result needs to be updated.

**Acceptance criteria**
multiple clients/threads can run healthcheck simultaneously

**Comment by Ivanidzo4ka** [comment]
>We should allow multiple request to access the cached result at once, and perhaps only block if the result needs to be updated.

https://github.com/microsoft/healthcare-shared-components/blob/78be139e52a6c5fed6a0fd83ee7463210057d44f/src/Microsoft.Health.Api/Features/HealthChecks/CachedHealthCheck.cs#L42
```
  public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)
        {
            if (_lastChecked >= ExpirationWindow)
            {
                return _lastResult;
            }
```
It's been like that for awhile. Is there is something else we need to do?

**Comment by CaitlinV39** [comment]
@brendankowitz is this still something we need to do?

**Comment by v-kulkarnipa** [comment]
Could the Olympus team provide details on how to reproduce it and clarify exactly what we should focus on?
Is this still something we need to do?

**Comment by evachen96** [comment]
@EXPEkesheth I think this can be closed, team was unable to repro
