### ISSUE TITLE
Schema management tool should indicate initialization time to user

### ISSUE THREAD

**Issue by CaitlinV39** [microsoft/fhir-server#1871]
**User story**
In some schema upgrade scenarios that rely on the schema management tool (see the yellow highlighted boxes here), initialization methods in the FHIR model can take up to 1 minute to be triggered. It would be good to have an info message to let the user know.

**Acceptance criteria**
The user is notified when initialization is delayed

**Comment by PTaladay** [comment]
@CaitlinV39 I don't see any attached screenshots indicating "(see the yellow highlighted boxes here)". Can we list out some of the scenarios that tend to take the most time for a frame of reference? Thanks

**Comment by CaitlinV39** [comment]
Initial Running Schema Version | Automatic Updates | Intermediate Schema Version | Schema Tool Action | Final Schema Version | Schema Upgraded Notification Fired From: | Upgrade Script | Notes
-- | -- | -- | -- | -- | -- | -- | --
5 | Disabled | 5 | apply --next | 6 | SchemaJobWorker | 6.diff.sql | SqlServerFhirModel initialization could be delayed up to 1 min
null | Disabled | N/A | apply --latest | 6 | SchemaJobWorker | 6.sql | SqlServerFhirModel initialization could be delayed up to 1 min






</div>

**Comment by CaitlinV39** [comment]
@PTaladay - Sorry about that! I added details in the comments

**Comment by v-kulkarnipa** [comment]
This is an old issue. Shall we still look into it? Also can you please provide the reproduction steps for the same.

**Comment by evachen96** [comment]
@EXPEkesheth I think this one can be closed, there was no repro
