### ISSUE TITLE
Is there any breaking changes from versjon 1.3.32 to 2.0.13?

### ISSUE THREAD

**Issue by ebjornset** [microsoft/fhir-server#1915]
**Question**

Is there any breaking changes from versjon 1.3.32 to 2.0.13?

**Description**
I presume you use semantic versioning, so there is a breaking change between versjon 1.3.32 to 2.0.13? I've looked at the change log, but I'm not able to see what this change might be. Can anyone point me to the issues or PRs that are considered as braking changes?

**Comment by brendankowitz** [comment]
If you are using sql then read #1876

**Comment by ebjornset** [comment]
Ok, we uses CosmosDB, so I take this as no breaking changes should affects us? Great 👍
