### ISSUE TITLE
Microsoft.Health.Fhir.R4.Web v 2.0.18 crashes during start with an System.ArgumentOutOfRangeException "The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')" from SearchParameterStatusManager.ctor

### ISSUE THREAD

**Issue by ebjornset** [microsoft/fhir-server#1916]
**Describe the bug**
The server crashes during start with an System.ArgumentOutOfRangeException "The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')" from SearchParameterStatusManager.ctor

**FHIR Version?**
R4, release 2.0.18

**Data provider?**
CosmosDB

**To Reproduce**
1. Compile the source 
2. Run Microsoft.Health.Fhir.R4.Web on a machine in time zone before GMT, e.g. GMT+2

**Expected behavior**
Normal server startup

**Actual behavior**
The server crashes during start with an System.ArgumentOutOfRangeException "The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')" 
[Microsoft.Health.Fhir.R4.Web.2.0.18-System.ArgumentOutOfRangeException.txt](https://github.com/microsoft/fhir-server/files/6434092/Microsoft.Health.Fhir.R4.Web.2.0.18-System.ArgumentOutOfRangeException.txt)

**Comment by ebjornset** [comment]
I forgot to mention that if I change the line where it crashes  (line 46 in Microsoft.Health.Fhir.Core.Features.Search.Registry.SearchParameterStatusManager) 
`_latestSearchParams = DateTime.MinValue;`
to
`_latestSearchParams = DateTime.MinValue.ToUniversalTime();`
then the server starts as expected. But I don't know enough about the expected behavior to say if this is in fact the proper fix...

**Comment by CaitlinV39** [comment]
We resolved this in this release: https://github.com/microsoft/fhir-server/releases/tag/release%2F2.0.19

**Comment by ebjornset** [comment]
We've tested the release, and the fix works as expected. Thanks!
