### ISSUE TITLE
Chained search limited or not allowed for Encounter

### ISSUE THREAD

**Issue by cunninghamb505** [microsoft/fhir-server#1917]
**Question**
When trying to run a chained query below I get an error saying its not allowed. I am just trying to search for all locations where the facility equals xyz

https://TESTTEST.azurehealthcareapis.com/Encounter?location.name=FACILITY A

Error 
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "The chained parameter is not supported."

**Comment by cunninghamb505** [comment]
Here is an example from HAPI that works 
 http://hapi.fhir.org/baseR4/Encounter?location.name=Ward 1, Room 63f646cb-bd4d-4087-8f3c-7d77d2841d0f, Bed 1

**Comment by CaitlinV39** [comment]
@cunninghamb505 have you tried the same syntax that you used for HAPI? I think the issue is with the subject: piece since subject refers to a patient or group, not a location

**Comment by cunninghamb505** [comment]
@CaitlinV39 Hi thanks. Sorry i forgot to update my query but similar error about chained support
https://myserver.azurehealthcareapis.com/Encounter?location.name=FACILITY A
  "severity": "error",
            "code": "not-supported",
            "diagnostics": "Chained expression is not supported."

**Comment by Ivanidzo4ka** [comment]
I talked with @feordin  two days ago while he worked on new release to PaaS and we found what chained search wasn't turned on by default.

New release which @feordin worked on Monday should have it turned on, but I don't know exact dates when it will hit production.

As workaround you can add "x-ms-enable-chained-search" header with value "true" to your request and it should enable chained search.

**Comment by brendankowitz** [comment]
@cunninghamb505 we were gathering feedback on this feature's behavior and performance in the managed service prior to making it generally available, which is the reason for the feature flag here. You should be able to use it now with the feature flag as @Ivanidzo4ka pointed out
