### ISSUE TITLE
Error prone practice of deleting resources in tests.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [microsoft/fhir-server#1936]
**Describe the bug**
Take this build: https://microsofthealthoss.visualstudio.com/FhirServer/_build/results?buildId=10960&view=logs&j=89b5186a-1c3e-5f03-4558-881d5bfbff1f&t=144284e4-be57-5c18-634d-684b6afd7165
In test we create 50 resources and we validate what we have 50 resource.

Unfortunately there https://github.com/microsoft/fhir-server/blob/9c6e6ffe700ca41dee6f310bb1e2e81be537f30c/src/Microsoft.Health.Fhir.Shared.Client/FhirClientExtensions.cs#L18 method which we use, for example in https://github.com/microsoft/fhir-server/blob/a2eb81ddf251555d5cc72ddf568945163875daf9/test/Microsoft.Health.Fhir.Shared.Tests.E2E/Rest/Search/QuantitySearchTestFixture.cs#L26

so it's quite possible while we creating 50 observations in one test we can start delete them all in another parallel running test.

I think whole practice of `DeleteAllResource` is quite  prone to error, so I would advocate for removal of that method and isolate tests to work with resources under certain tag value.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
Run tests in parallel and hope some tests would fail.

**Expected behavior**
No more DeleteAllResources calls. Instead deleting resources and posting new one, we should just post resources with random guid and filter search with that guid.

**Comment by CaitlinV39** [comment]
AB#82457
