### ISSUE TITLE
launch.json does not have correct name of the .NET version folder

### ISSUE THREAD

**Issue by abiisnn** [microsoft/fhir-server#1939]
**Describe the bug**
[Building and debugging locally](https://github.com/microsoft/fhir-server/wiki/Build-and-debug-locally)  is not working as is expected. **Updating launch.json file is required.**

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
1.  Follow steps of [Building and debugging locally](https://github.com/microsoft/fhir-server/wiki/Build-and-debug-locally), after ensure that the Cosmos DB Emulator and Azure Storage Emulator are running.
2.  Open Microsoft.Health.Fhir.sln, set Microsoft.Health.Fhir.R4.Web (or Microsoft.Health.Fhir.Stu3.Web) as StartUp Project, and press F5.

**Expected behavior**
A web page shows a HTTP 401 error, that is expected. As long as you are able to hit the metadata endpoint (https://localhost:44348/metadata) it means that the server is running.

**Actual behavior**
Now, you are getting a Visual studio Code error window, **"Microsoft.Health.Fhir.R4.Web.dll does not exist"**. We have to update the name of the folder to **Net.5.0** instead of **netcoreapp3.1** in **launch.json** file.

**Comment by CaitlinV39** [comment]
@abiisnn - Are we good to close this issue now?

**Comment by abiisnn** [comment]
Yes :)
