### ISSUE TITLE
Exception: Type checking the data: Encountered unknown element 'masterIdentifier' at location 'Resource.masterIdentifier[0]' while parsing

### ISSUE THREAD

**Issue by YazanMSFT** [microsoft/fhir-server#1953]
**Describe the bug**
The following test is failing in R5:

Microsoft.Health.Fhir.Tests.E2E.Rest.Search.BasicSearchTests(CosmosDb, Json).GivenASearchRequest_WhenExceedingMaxCount_ThenAnOperationOutcomeWarningIsReturnedInTheBundle

@feordin Dug into it and discovered that 'masterIdentifier' has been removed in R5. We'll need to update the existing test data to the latest that does not have this problem.

**FHIR Version?**
R5

**Data provider?**
CosmosDB

**To Reproduce**
1. Run the E2E tests for R5
2. 
3. 

**Expected behavior**
Tests pass

**Actual behavior**
Test fails

**Comment by CaitlinV39** [comment]
AB#82456
