### ISSUE TITLE
Chained search error encounter and patient

### ISSUE THREAD

**Issue by camila8** [microsoft/fhir-server#1961]
I tried to use the chain example that is in your documents and get that it is not supported.

![image](https://user-images.githubusercontent.com/23110570/119163105-b696fb80-ba20-11eb-81fb-3fa13b3efd58.png)

![image](https://user-images.githubusercontent.com/23110570/119163254-d9291480-ba20-11eb-92e4-3e3ea1e8c62b.png)
****

**Comment by CaitlinV39** [comment]
@camila8 - I will get the documentation updated but use birthdate (lower case d instead of birthDate) and the search will work. Thanks so much for pointing this out!

**Comment by camila8** [comment]
![image](https://user-images.githubusercontent.com/23110570/119192546-f45a4b00-ba45-11eb-8378-50503a9154a2.png)

I think the result is too long..

**Comment by CaitlinV39** [comment]
@camila8 - This is just an example so you may need to modify based on what is in your database. You can see the note that explains this in the documentation here: https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/search-samples#reverse-chain-search

You will need to make the search more specific in your database. 


Note

In the Azure API for FHIR and the open-source FHIR server backed by Cosmos, the chained search and reverse chained search is an MVP implementation. To accomplish chained search on Cosmos DB, the implementation walks down the search expression and issues sub-queries to resolve the matched resources. This is done for each level of the expression. If any query returns more than 100 results, an error will be thrown. By default, chained search is behind a feature flag. To use the chained searching on Cosmos DB, use the header x-ms-enable-chained-search: true.

**Comment by camila8** [comment]
Ya thats why I added the count = 10 to make it smaller.

**Comment by CaitlinV39** [comment]
_count doesn't limit the search, it limits the number of results per page. This means that with count=10, you would get 10 results per page but you would still have access to the full set of results through the continuation token. The total results (across all pages) needs to meet the limitations above.

**Comment by camila8** [comment]
ok got it thanks
