### ISSUE TITLE
Link to "Postman to test the FHIR server" in bash instructions is not working.

### ISSUE THREAD

**Issue by abiisnn** [microsoft/fhir-server#1968]
**Describe the bug**
"Postman to test the FHIR server" link is not working in bash instructions, instead, you get a 404 not found.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1.  Enter to Github repository,  [Fhir-Server/docs/BashDeployment](https://github.com/microsoft/fhir-server/blob/main/docs/BashDeployment.md#deploying-the-fhir-server-template)
2. It says: "You can use [Postman to test the FHIR server.](https://github.com/microsoft/fhir-server/blob/main/docs/PostmanTesting.md)"
3. Click to hyperlink: [Postman to test the FHIR server.](https://github.com/microsoft/fhir-server/blob/main/docs/PostmanTesting.md).

**Expected behavior**
You should be able to see how to test FHIR server with Postman.

**Actual behavior**
You are getting a **404 Page not found**.

![image](https://user-images.githubusercontent.com/33185677/119578058-6e117200-bd81-11eb-8a27-dd402ce3bcb8.png)

**Comment by CaitlinV39** [comment]
@abiisnn Thanks for catching! I figured it :)
