### ISSUE TITLE
[Regression] Sorting DocumentReference by date is no longer supported

### ISSUE THREAD

**Issue by giacomodeliberali** [microsoft/fhir-server#1973]
**Describe the bug**
Sorting _DocumentReference_ by `date` was supported (tested in `1.0.800`) but no longer work in the last version (`2.0.41`).

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
1. Run query `DocumentReference?_sort=date` 

**Expected behavior**
Should sort resources by date asc

**Actual behavior**
Does not sort resources and include the outcome

```json
        {
            "resource": {
                "resourceType": "OperationOutcome",
                "id": "2c773592-90a1-4393-b327-ddfcc5c753ac",
                "issue": [
                    {
                        "severity": "warning",
                        "code": "not-supported",
                        "diagnostics": "Sorting by the 'date' parameter is not supported."
                    }
                ]
            },
            "search": {
                "mode": "outcome"
            }
        }
```

**Comment by CaitlinV39** [comment]
@giacomodeliberali thank you so much for sharing this. While this may have worked in the past, we didn't technically support for date on DocumentReference and so it was not included in our testing. However, we are working on a full implementation of _sort on all strings and dates in SQL which will be available by the end of June and that should resolve this issue.

Thanks!

**Comment by CaitlinV39** [comment]
AB#82462

**Comment by giacomodeliberali** [comment]
Hi @CaitlinV39 , any news on this? In which version a "full implementation of _sort on all strings and dates in SQL" should be available?

**Comment by CaitlinV39** [comment]
Our goal is to have this merged by end of next week, but it may get pushed one week.

**Comment by CaitlinV39** [comment]
We are still merging the feature branch. Goal is middle of August now.

**Comment by Alyyc85** [comment]
Hello,
any news about this issue and its relative milestone?
Thank you

**Comment by CaitlinV39** [comment]
Hi @Alyyc85 I just updated the milestone, we have the PR up and are planning to merge in the next couple of days.

**Comment by CaitlinV39** [comment]
> Hi @Alyyc85 I just updated the milestone, we have the PR up and are planning to merge in the next couple of days.

Just an update that we are still working on merging. We've had some competing priorities so will continue to update the linked PR.

**Comment by CaitlinV39** [comment]
@Alyyc85 @giacomodeliberali This just merged and is main now.
