### ISSUE TITLE
Paging through results for queries with multiple _type parameters returns 500

### ISSUE THREAD

**Issue by namadabu** [microsoft/fhir-server#1985]
**Describe the bug**
For search requests that have multiple _type parameters (_type=resource1,resource2,...) we get 500 responses in certain situations. It happens when we are paging through results for the last resource type that is returned.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
SQL Server

**To Reproduce**
1. Assuming starting from a blank fhir-server, POST 5 patients and 5 observations (can be any resources) to the server.
2. Do the following search: GET <fhir-server>/_type=Patient,Observation&_count=6 and follow the continuation token.
3. When following the continuation token, we get a 500 response.

**Expected behavior**
200 response with resources.

**Actual behavior**
500 response.

**Comment by CaitlinV39** [comment]
@namadabu - Can this be closed?
