### ISSUE TITLE
OSS repo build fails in VS 16.10.0

### ISSUE THREAD

**Issue by IoTFier** [microsoft/fhir-server#1994]
**Describe the bug**
OSS repo build fails in VS 16.10.0
[ This is a similar situation as reported in https://github.com/microsoft/dicom-server/issues/614 ]

**FHIR Version?**
Stu3/R4/R5 - For all version

**Data provider?**
CosmosDB/SQL Server | **SQL Server**

**To Reproduce**
1. Build the latest repo in Visual Studio 16.10.0 (commit - d0c1225 - Create DaVinciFormulary_Sample_Resources.http file for testing (#1978))
2. In the Package Manager Console, run the command dotnet --list-sdks
3. It will how you the latest installed sdk as -
    5.0.300 [C:\Program Files\dotnet\sdk] 
3. Update Global.json to point .Net sdk to 5.0.300
4. Run the build
If not Visual Studio, then, 
5. build the solution using MSBuild using following command - 
6. MSBuild.exe {LocalPath}\fhir-server\Microsoft.Health.Fhir.sln -ds -graph:True -v:n -clp:Summary 

**Expected behavior**
All projects in the FHIR solutions to be compiled successfully.

**Actual behavior**
Build fails with following errors - 
"{local path}\fhir-server\src\Microsoft.Health.Fhir.R5.Core\Microsoft.Health.Fhir.R5.Core.csproj" (GetTargetFrameworks;Build;GetNativeManifest;GetCopyToOutputDirectoryItems;GetTargetFrameworksWithPlatformForSingleTargetFramework target)(10) ->
(CoreCompile target) ->  {local path}\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Features\Search\BundleFactory.cs(63,40): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.R5.Core\Microsoft.Health.Fhir.R5.Core.csproj]

"{local path}\fhir-server\src\Microsoft.Health.Fhir.Stu3.Core\Microsoft.Health.Fhir.Stu3.Core.csproj" (GetTargetFrameworks;Build;GetNativeManifest;GetCopyToOutputDirectoryItems;GetTargetFrameworksWithPlatformForSingleTargetFramework target) (11) ->
  {local path}\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Features\Search\BundleFactory.cs(63,40): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.Stu3.Core\Microsoft.Health.Fhir.Stu3.Core.csproj]

"{local path}\fhir-server\src\Microsoft.Health.Fhir.R4.Core\Microsoft.Health.Fhir.R4.Core.csproj" (GetTargetFrameworks;Build;GetNativeManifest;GetCopyToOutputDirectoryItems;GetTargetFrameworksWithPlatformForSingleTargetFramework target)(20) ->
  {local path}\fhir-server\src\Microsoft.Health.Fhir.Shared.Core\Features\Search\BundleFactory.cs(63,40): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.R4.Core\Microsoft.Health.Fhir.R4.Core.csproj]

"{local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Microsoft.Health.Fhir.SqlServer.csproj" (GetTargetFrameworks;Build;GetNativeManifest;GetCopyToOutputDirectoryItems;GetTargetFrameworksWithPlatformForSingleTargetFramework target) (25) ->
  {local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Storage\TvpRowGeneration\TokenSearchParameterV1RowGenerator.cs(33,46): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Microsoft.Health.Fhir.SqlServer.csproj]
  {local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Storage\TvpRowGeneration\ReferenceSearchParameterV2RowGenerator.cs(23,52): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Microsoft.Health.Fhir.SqlServer.csproj]
  {local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\Expressions\Visitors\UntypedReferenceRewriter.cs(136,61): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Microsoft.Health.Fhir.SqlServer.csproj]
  {local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Storage\TvpRowGeneration\BulkTokenSearchParameterV1RowGenerator.cs(34,46): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Microsoft.Health.Fhir.SqlServer.csproj]
  {local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Storage\TvpRowGeneration\BulkReferenceSearchParameterV1RowGenerator.cs(24,52): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Microsoft.Health.Fhir.SqlServer.csproj]
  {local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Features\Search\Expressions\Visitors\ResourceColumnPredicatePushdownRewriter.cs(43,107): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.SqlServer\Microsoft.Health.Fhir.SqlServer.csproj]

"{local path}\fhir-server\src\Microsoft.Health.Fhir.CosmosDb\Microsoft.Health.Fhir.CosmosDb.csproj" (GetTargetFrameworks;Build;GetNativeManifest;GetCopyToOutputDirectoryItems;GetTargetFrameworksWithPlatformForSingleTargetFramework target) (29) ->
  {local path}\fhir-server\src\Microsoft.Health.Fhir.CosmosDb\Features\Storage\CosmosExceptionExtensions.cs(56,19): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.CosmosDb\Microsoft.Health.Fhir.CosmosDb.csproj]
  {local path}\fhir-server\src\Microsoft.Health.Fhir.CosmosDb\Features\Storage\RetryExceptionPolicyFactory.cs(39,19):error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.CosmosDb\Microsoft.Health.Fhir.CosmosDb.csproj]
  {local path}\fhir-server\src\Microsoft.Health.Fhir.CosmosDb\Features\Storage\Registry\SearchParameterStatusExtensions.cs(20,77): error IDE0004: Cast is redundant. [{local path}\fhir-server\src\Microsoft.Health.Fhir.CosmosDb\Microsoft.Health.Fhir.CosmosDb.csproj]

    0 Warning(s)
    12 Error(s)

Time Elapsed 00:01:13.51

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>

**Comment by Ivanidzo4ka** [comment]
I've update code to remove unnecessary casts. main branch should be compilable now.

**Comment by IoTFier** [comment]
@Ivanidzo4ka , thank you.
