### ISSUE TITLE
FHIR release 5 (v4.6.0)

### ISSUE THREAD

**Issue by luisgmgouveia** [microsoft/fhir-server#2001]
Can you provide me a macro-estimate for the release-date of support to the new FHIR Release 5 (now v4.6.0) ?

If not, based on the previous delays between the FHIR version releases and the fhir-server releases, when do you think this will happen?

This is very important to me and my team as we depend on evolutions that came-up in this new release.

Thank you very much!

**Comment by Ivanidzo4ka** [comment]
Firely libraries on which we base our code updated to 4.6.0 release in 3.3.0 version 2 days ago.
There is [PR](https://github.com/microsoft/fhir-server/pull/1998) from dependabot which switches to that version, but there is few changes in code we need to make.

@brendankowitz  @CaitlinV39  What's our priority on this?

**Comment by CaitlinV39** [comment]
@luisgmgouveia - We will scope the effort for the work next week and then can provide an update on when this will be in place.

**Comment by CaitlinV39** [comment]
AB#82653

**Comment by luisgmgouveia** [comment]
Hi @CaitlinV39 , thanks a lot for your answer! I will wait for those details. By the way, congratulations for the work you've done so far, this project seems to be a great help. The fact that Microsoft is backing it came as no surprise. Have a nice week!

**Comment by Ivanidzo4ka** [comment]
[New release ](https://github.com/microsoft/fhir-server/releases/tag/release%2F2.0.99) contains 4.6 version for R5.
