### ISSUE TITLE
Release Version Query

### ISSUE THREAD

**Issue by FesterCluck** [microsoft/fhir-server#2019]
I have deployed the managed service, but I need to check the release version of the underlying API. Is there a query I can use to check this?

**Comment by brendankowitz** [comment]
To clarify, do you mean the FHIR version? You can use:

```
https://{{hostname}}/$versions
content-type: application/json
```

Or do you mean our OSS release version?

**Comment by CaitlinV39** [comment]
I'm going to close this issue but please let us know if you need anything else.
