### ISSUE TITLE
latest Server build: not able to send Compose.LockedDate  for ValueSet (STU3)

### ISSUE THREAD

**Issue by devcs21** [microsoft/fhir-server#2021]
**Describe the bug**
after migration to latest build that is using HL7 3.2.0 Nuget package I've got problem with creting ValueSets  (this problem didn't happen before).

when I try to create a ValueSet (STU3)
it fails on server side.
```
...
fhirRequest.Compose.LockedDateElement = new Date(2021, 06, 14);
...

```

with exception:

`ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request. Hl7.Fhir.ElementModel.StructuralTypeException: Type checking the data: Literal '2021-06-14T00:00:00.0000000' cannot be parsed as a date. (at ValueSet.compose[0].lockedDate[0])`

**FHIR Version?**
Stu3

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. create a simple xunit test where you try to create simpliest in the world ValueSet
```
            ValueSet fhirRequest = new ValueSet();
            fhirRequest.Url = $"test_{Guid.NewGuid().ToString()}";
            fhirRequest.Compose = new ValueSet.ComposeComponent();
            fhirRequest.Compose.LockedDateElement = new Date(2021, 06, 14);
```
populate additional fields if required

```
  var _fhirClient = new FhirClient(_msFhirServerUrl);
  var respponse = _fhirClient.Create<ValueSet>(fhirRequest);
```

2.  run MS FHIR Server in STU3 mode
3.  run xunit test

**Expected behavior**
ValueSet must be successfully created because of STU3 FHIR Specification:
https://hl7.org/fhir/STU3/datatypes.html#date
```
date :
A date, or partial date (e.g. just year or year + month) as used in human communication. 
```
**There is no time zone**. `Dates SHALL be valid dates`

`union of xs:date, xs:gYearMonth, xs:gYear`

`A JSON string - a union of xs:date, xs:gYearMonth, xs:gYear`

but it's trying to consider it as date with Time Zone that is definitely an error regarding specification

**Actual behavior**
The exception about bad date format.

P.S. Example of json- what fails an exception (and it was OK on old version of MS FHIR Server)

`{
    "resourceType": "ValueSet",
    "meta": {
        "versionId": "705f3097-aaf7-4416-9e54-9e6428e79c9c",
        "lastUpdated": "2021-06-14T10:28:02.1258522+03:00"
    },
    "implicitRules": "bdee97cd-e37b-4029-895b-4c587bed9a76",
    "language": "no-NO",
    "text": {
        "status": "additional",
        "div": "<div>Some Narrative/div>"
    },
    "url": "test_685e0b5e-42a7-40b6-91ce-862a06fb111e",
    "identifier": [
        {
            "use": "official",
            "type": {
                "coding": [
                    {
                        "system": "MR",
                        "version": "ver2",
                        "code": "MR",
                        "display": "Medical record number"
                    }
                ],
                "text": "text44"
            },
            "system": "http://hl7.org/fhir/v2/0203",
            "value": "MR",
            "period": {
                "start": "2021-06-11T10:28:02.0549310",
                "end": "2021-07-04T10:28:02.0549310"
            }
        }
    ],
    "version": "some string 2 string data759",
    "name": "some string 2 string data759",
    "title": "some string 2 string data759",
    "status": "active",
    "experimental": true,
    "date": "2021-06-14T10:28:02.0549310+03:00",
    "publisher": "some string 2 string data759",
    "contact": [
        {
            "id": "78511",
            "name": "Test Name",
            "telecom": [
                {
                    "value": "valcpp1",
                    "period": {
                        "start": "2021-03-06T10:28:02.1413286",
                        "end": "2021-06-14T10:28:02.1413658"
                    }
                }
            ]
        }
    ],
    "description": "value 71",
    "_description": {
        "id": "78511"
    },
    "jurisdiction": [
        {
            "coding": [
                {
                    "system": "sys1",
                    "version": "28969fc5-",
                    "code": "reminder",
                    "display": "Reminder"
                }
            ],
            "text": "text4"
        }
    ],
    "immutable": true,
    "purpose": "value 71",
    "_purpose": {
        "id": "78511"
    },
    "copyright": "value 71",
    "_copyright": {
        "id": "78511"
    },
    "compose": {
        "lockedDate": "2021-06-14",
        "inactive": true
    },
    "expansion": {
        "identifier": "http://example.com",
        "timestamp": "2021-06-14T10:28:02.0549310+03:00",
        "total": 77,
        "offset": 77
    }
}`

**Comment by Ivanidzo4ka** [comment]
Before we switch to 3.2 version of nuget date fields were ok with accepting time values. Which was a bug.
As you pointed out `Compose.LockedDateElement` is of type of `date` and `date` shouldn't have minutes, seconds, timezone, etc.
```
Type checking the data: Literal '2021-06-14T00:00:00.0000000' cannot be parsed as a date. (at ValueSet.compose[0].lockedDate[0]
```
so this exception is a good thing. We shouldn't accept it this format for the date. Correct value should be `2021-06-14`

Question is how we get this extra information...

I've test locally on my main branch and I can't reproduce it. I don't get seconds when we serialize date. There is chance what `FhirClient` object in your setting is still referencing old nuget 1.9 and it produces seconds.

Any chance you can either create a branch on top of our source code or just attach zip file with your solution, because I can't reproduce it.

I also started STU3 from main branch and posted json file, it works for me.
![image](https://user-images.githubusercontent.com/1523833/122121410-738e3500-cde0-11eb-940f-2339cd84db62.png)
I'm not saying it's not work for you, but in order to figure out why it's not working for you, can you provide information about what build did you use? Did you mean latest release? Or you just checkout main branch?

**Comment by devcs21** [comment]
The problem has been resolved. May be it was wrong git pull. I've physically removed  ms fhir's folder and clone the project again. Now it's OK.  May be this is a problem of transition branches' naming  from "master" to "main" or so....

**Comment by CaitlinV39** [comment]
@devcs21 - We're glad to hear that it is resolved. Please let us know if you have any other issues.
