### ISSUE TITLE
Which database for which use case?

### ISSUE THREAD

**Issue by Lukas1v** [microsoft/fhir-server#2025]
**Question**

Should I use CosmosDB or SQL server as database? Are there particular use cases for each type?

**Description**
We are currenty deploying the FHIR server on Azure and have to choose either CosmosDB or SQL Server as the backend database, but have no clue which one would be the most optimal. From the documentation and sample deployments, it seems that SQL server is more used, but does that imply that SQL server would be better in general?

What we see as the benefits of the two:

- CosmosDB:
  -  Cheaper for small workloads
  -  Can scale infinitely 
  - Document database looks more natural for FHIR 
- SQL Server:
  - More familiar
  - Can also be deployed locally or on another cloud
  - Easier to access from desktop via e.g. DBeaver
  - Easier to manually backup and restore

Is there anything we are missing?

**Comment by CaitlinV39** [comment]
@Lukas1v - From a functionality perspective, SQL will support transaction bundles (https://www.hl7.org/fhir/http.html#transaction) on FHIR and has slightly more robust support for chained/reverse chaining search. The Cosmos DB has support for $patient-everything but SQL will eventually.

**Comment by brendankowitz** [comment]
The trade-offs only start to matter at much higher load/scale (i.e. Cosmos has Autoscale and also transparently manages physical data partitions), the Cosmos provider is what is used in Azure API for FHIR today.
SQL will require a little more maintenance (i.e. schema upgrades, and as you mentioned, some DBA work such as backups). However, SQL has a more capable query engine and transactions, thus more FHIR features in general can be supported. I think SQL would make sense unless you have reasons to believe you'll be scaling to many TB very quickly.
