### ISSUE TITLE
Bundle.response missing required field "status"

### ISSUE THREAD

**Issue by mosiermt** [microsoft/fhir-server#2026]
**Describe the bug**
According to the FHIR R4 documentation for a Bundle ( https://www.hl7.org/fhir/bundle.html ), if a response object is provided, it Must have the "status" string representing the status code of the response. When a bundle is returned in the paas, it does not return this field. 

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
1. Send a search-type, history-type, or history-instance request to the PaaS with or without search parameters
2. Inspect items in Bundle.entry.*.response
3. Status field is seen as not present

**Expected behavior**
This field should represent the status code returned by that particular response with the text of the status code optionally provided (i.e. "401 Unauthorized" or "200")

**Actual behavior**
The actual result only includes an "etag" and "lastModified" field in the response object.

**Comment by CaitlinV39** [comment]
AB#82981
