### ISSUE TITLE
Persistence Layer - Common Data Service

### ISSUE THREAD

**Issue by johngrace** [microsoft/fhir-server#203]
Are Microsoft looking to add a Persistence Layer  for the  Common Data Service? If not yet could we get it added to the roadmap?

https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/data-platform-intro

**Comment by johnstairs** [comment]
Thanks for the suggestion, @johngrace. Do you have particular scenarios in mind for this, or thoughts on how you would like to see the FHIR resources persisted to CDS? As normalized CDS entities?

**Comment by johngrace** [comment]
As normalized CDS entities, as then you get all the benefits of the Power Platform.

Even if you just provided a working code example of here is an entity in CDS with 10 fields and show how the Persistence layer mapping details work, that would be a great help.

**Comment by johnstairs** [comment]
We're talking with the CDS team about this.

**Comment by CaitlinV39** [comment]
labeling won't fix for now.
