### ISSUE TITLE
IdToTokenSearchValueConverter doesn't sound right

### ISSUE THREAD

**Issue by Ivanidzo4ka** [microsoft/fhir-server#2040]
**Describe the bug**
https://www.hl7.org/fhir/datatypes.html#id states what `id` is type of `xs:string`, why our converter maps it to token search value, it doesn't make much sense to me.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Comment by Ivanidzo4ka** [comment]
https://microsofthealth.visualstudio.com/Health/_workitems/edit/82998

**Comment by brendankowitz** [comment]
The search definition is token: https://www.hl7.org/fhir/resource.html#search.
In search, Token by default an exact match where string defaults to StartsWith.
