### ISSUE TITLE
Update e2e test category on long running anonymizer tests

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#2102]
**Describe the bug**
We need to separate out potentially long running tests in `AnonymizedExportTests.cs` with the same test category used in https://github.com/microsoft/fhir-server/blob/main/test/Microsoft.Health.Fhir.Shared.Tests.E2E/Rest/ExportLongRunningTests.cs.
These are then run in a separate 'long running' pipeline.

AB#101798

**Comment by CaitlinV39** [comment]
@ranvijaykumar - Do you think your group could take a look at this? @namadabu would be able to weigh in as well.

**Comment by CraigP68** [comment]
AB#87252

**Comment by ranvijaykumar** [comment]
@qiwjin for his inputs

**Comment by EXPEkesheth** [comment]
@fhibf - can you please confirm if these tests were categorized?

**Comment by EXPEkesheth** [comment]
Closing this ask, as the anonymizer tests were categorized. Thanks @fhibf
