### ISSUE TITLE
Custom Search not working.  

### ISSUE THREAD

**Issue by Sameer2810** [microsoft/fhir-server#2113]
**Question**

I have get the latest code from release 2.0.99 and I wanted to add custom search I followed this link https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/how-to-do-custom-search  but it gives following error 

{
    "resourceType": "OperationOutcome",
    "id": "e41fdc27-da5f-45c2-a5eb-6d3dfc37d7d6",
    "issue": [
        {
            "severity": "error",
            "code": "not-supported",
            "diagnostics": "Search parameter status information should not be null."
        },
        {
            "severity": "error",
            "code": "exception",
            "diagnostics": "An error occurred creating the custom search parameter.  The issue must be resolved and the parameter resubmitted to become functional."
        }
    ]
}

I posted the same json you mentioned in custom search link
https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/how-to-do-custom-search

We always appreciate your feedback, but we ask that before posting your question, please check to see if we already have the information you need:

* Is your question answered in our documentation? - https://docs.microsoft.com/azure/healthcare-apis/

* Our team also monitors the FHIR Community chat @ http://chat.fhir.org

**Description**
If you cannot find the answer at one of the sites above, please provide a detailed description of your question.

**Comment by CaitlinV39** [comment]
Can you validate what you have in the "status": field? I just copied directly from our documentation and was able to submit. If you can share the json for the body of the searchparameter we can take a look and see if we can find the differences.

**Comment by Sameer2810** [comment]
Following is my json. It is the same json from https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/how-to-do-custom-search

{
  "resourceType" : "SearchParameter",
  "id" : "us-core-race",
  "url" : "http://hl7.org/fhir/us/core/SearchParameter/us-core-race",
  "version" : "3.1.1",
  "name" : "USCoreRace",
  "status" : "active",
  "date" : "2019-05-21",
  "publisher" : "US Realm Steering Committee",
  "contact" : [
    {
      "telecom" : [
        {
          "system" : "other",
          "value" : "http://www.healthit.gov/"
        }
      ]
    }
  ],
  "description" : "Returns patients with a race extension matching the specified code.",
  "jurisdiction" : [
    {
      "coding" : [
        {
          "system" : "urn:iso:std:iso:3166",
          "code" : "US",
          "display" : "United States of America"
        }
      ]
    }
  ],
  "code" : "race",
  "base" : [
    "Patient"
  ],
  "type" : "token",
  "expression" : "Patient.extension.where(url = 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-race').extension.value.code"
}

**Comment by CaitlinV39** [comment]
Hi Sameer - 

A couple more questions as I'm still not able to reproduce. 

1. Are you able to hit the metadata endpoint on your FHIR server? 
2. Are you using Cosmos DB or SQL?
3. Are you using R4 or STU3 version of the FHIR server?

We did just release a new package as well, but I'm not aware of any issues with search parameters on 2.0.99. We did make some updates to a few other bugs in 2.0.99 so I would recommend using 2.0.121

**Comment by Sameer2810** [comment]
Hi Caitlin, 

Answer to your questions

1.  Yes I am able to hit metadata endpoint on FHIR server
2.  I am using SQL
3.  I am using R4 version of FHIR server

**Comment by Sameer2810** [comment]
Do I need to go for new release 2.0.121? Can this solve the problem

**Comment by CaitlinV39** [comment]
Hi @Sameer2810 - I still haven't been able to reproduce on my side so yes, please try the next release and let me know if you are still having issues.

**Comment by Sameer2810** [comment]
@CaitlinV39 - It is working with release 2.0.121
