### ISSUE TITLE
Microsoft FHIR Server - SMART support Scopes?

### ISSUE THREAD

**Issue by btsetworks** [microsoft/fhir-server#2125]
Hey Microsoft and Contributors,

I am doing research on Microsoft FHIR Server and SMART.

Does your SMART Proxy support scopes at all?  Like: patient/Patient.read patient/Observation.write.

Or is just basic support for the ability to authenticate via SMART?  Essentially just passing the appropriate url / responses.

I don't think the SMART Proxy support scopes at this time.  Just wanted to clarify.

Thanks for the time.

-Blake

**Comment by btsetworks** [comment]
It does seem that the FHIR Proxy is what was intended to do SMART scope filtering:
https://github.com/microsoft/fhir-proxy

Is that correct?  Is this what you intend people to use to accomplish this?

Thanks

Blake

**Comment by CaitlinV39** [comment]
@btsetworks can you open this issue on the FHIR proxy? https://github.com/microsoft/fhir-proxy

Thanks!
Caitlin
