### ISSUE TITLE
Access RBAC enabled server through Postman and more description on RBAC

### ISSUE THREAD

**Issue by viku85** [Microsoft/fhir-server#213]
I am having a confusion related to authorization based on RBAC and I am not able to make a call to FHIR server when security is enabled.

Let me explain what all things were done to make a call through Postman:
1. Created all required instances based on Azure FHIR template. Which created AD apps, services, database etc.
2. AD apps are having roles based on the AD template [Default deployment](https://github.com/Microsoft/fhir-server/blob/master/docs/DefaultDeployment.md) for admin,nurse,patient.
3. Just to make sure, I am not messing with anything with roles, I have given role permission to AD App as well as User too.
4. Based on [Postman Testing](https://github.com/Microsoft/fhir-server/blob/master/docs/PostmanTesting.md), I am able to get **access-token** successfully.
5. As per this, [Features](https://github.com/Microsoft/fhir-server/blob/master/docs/Features.md) bearer token should have roles specified. I cross checked token with [JWT Validator](https://jwt.io/). The role is coming fine as **admin**.

Even after all the above steps, I am getting this response along with 401 status.
`{
    "resourceType": "OperationOutcome",
    "id": "<guid code>",
    "issue": [
        {
            "severity": "error",
            "code": "login",
            "diagnostics": "Authentication failed."
        }
    ]
}`

On checking  the postman console, I am getting 
`WWW-Authenticate:"Bearer error="invalid_token", error_description="The token is expired""`

**NOTE**: I have already made sure I am accessing through correct AD Client app.

The above mentioned item is a major problem for me to access the application after security is enabled. The second is more of all confusion.

Based on [Roles](https://github.com/Microsoft/fhir-server/blob/master/docs/Roles.md), my understanding is we can control ResourceAction (read, write, harddelete) but what is the significance. I presume it is not talking about FHIR Resources protection but general read, write, delete for all FHIR Resources. Is this just a concept for future release related to [RBAC](https://github.com/Microsoft/fhir-server/blob/master/docs/Roadmap.md)?.

Apologies, if I am missing anything basic here.

**Comment by hansenms** [comment]
It says your token is expired. Did you check it, in jwt.io. Sometimes postman doesn't pick the latest token when you say use, you have to explicitly pick the latest one from the dropdown.

**Comment by viku85** [comment]
Oh! I see now, silly of me. I was clicking on **Use Token** button from the Postman but seem like was not getting selected, like you said. I deleted all of them and it worked fine. Thanks a lot.

Can you please clarify on RBAC system. From the documentation, all I can see is how to configure, but how it really works. What I understand is a role having read, write and delete permission. Does it gets applied to all FHIR Resources? As of **FhirController** I can see these are just based on read, write, delete policies for all FHIR resource. Am I missing anything here, any documentation would be really great. If It is just based on read, write, delete, how can we configure based on FHIR Resources?

**Comment by hansenms** [comment]
As we describe in the features (https://github.com/Microsoft/fhir-server/blob/master/docs/Features.md#role-based-access-control). The settings are currently global on the API. There is also a link to how we plan on implementing a much more granular system (resource level and below), but it has not been implemented yet. If you need features like that immediately, you could add Azure API Management in front and implement policies.

**Comment by viku85** [comment]
Thank you for the quick reply. 
So I can use Azure API Management and block FHIR Service Instance with Cors or IP Restriction so that no one can hit my backend application directly.

**Comment by hansenms** [comment]
Yes, you can use the IP filtering rules (firewall) on the web app to only allow access from the API Management instance. I made a tool for setting up API Management for FHIR endpoint (https://aka.ms/fhir2apim). You can use that to get started.

**Comment by viku85** [comment]
Okay, sure. Thank you for all clarifications.
