### ISSUE TITLE
Fhir server doesn't support _include:recurse search parameter

### ISSUE THREAD

**Issue by sasireha** [microsoft/fhir-server#2137]
**Description**
Fhir server does not support **_include:recurse** search parameter.
I have tested with the latest version 2.0.121

`GET [base]/Observation?_include:recurse=Observation:related-target`

**FHIR Version**
Stu3

**Data provider**
CosmosDB

**Expected behavior**
Should be able retrieve the resources with **_include:recurse** param

**Actual behavior**
Returns the following response.
`{
    "resourceType": "OperationOutcome",
    "id": "347458f3-1859-4a11-8a1f-cabdf93d215b",
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "_include:iterate and _revinclude:iterate are not supported."
        }
    ]
}`

**Comment by CaitlinV39** [comment]
This is a known limitation of using _include & _revinclude on Cosmos DB. We don't have the work prioritized but will keep it open for tracking. 

https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/overview-of-search

**Comment by CaitlinV39** [comment]
AB#84437

**Comment by Xal3ph** [comment]
If this can be prioritized, we'd use it right away.

**Comment by paulsohal1981** [comment]
We're waiting for this too.  🙏 Please priortize it.

**Comment by johnbigley** [comment]
It has been almost a year since this was reported. Please fix.

**Comment by GieblerGary** [comment]
Please fix this as soon as possible.

**Comment by liamwilson-kainos** [comment]
Is there any update on this functionality please? I am trying to achieve a similar query 

https://<host>/Location?_include:recurse=Location:partof&_id=006b7615-7f41-47af-af1d-c4299924f224

**Comment by EXPEkesheth** [comment]
@liamwilson-kainos - Are you provisioned on Azure API for FHIR/ using Cosmos DB as a persistence layer? :iterate modifier is supported on Azure Health Data Services/ SQL as a persistence layer. Thanks !

**Comment by EXPEkesheth** [comment]
@liamwilson-kainos, the issue will be closed in a week, if no response is received.

**Comment by Xal3ph** [comment]
> This is a known limitation of using _include & _revinclude on Cosmos DB. We don't have the work prioritized but will keep it open for tracking.
> 
> https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/overview-of-search

Has this been resolved?  If so, can you tell use the version, so we know what to update to?

**Comment by EXPEkesheth** [comment]
@Xal3ph 
:iterate modifier is supported in Azure Health Data Services / SQL persistence layer. We do not support in Azure API for FHIR/ Cosmos persistence layer and do not plan to add. 

For SQL persistence layer, this capability has been added while back. You can use latest FHIR application code version.

**Comment by EXPEkesheth** [comment]
Closing as :iterate modifier is supported in Azure Health Data Services / SQL persistence layer. We do not support in Azure API for FHIR/ Cosmos persistence layer and do not plan to add.
