### ISSUE TITLE
SMART well-known configuration endpoints are missing

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#2138]
**User story**
As a SMART Developer the FHIR Server should respond to the `.well-known/smart-configuration` endpoint so that I can easily authenticate.

AB#101797

**Comment by CaitlinV39** [comment]
AB#84436

**Comment by meet-alikhan** [comment]
When using the smart-launcher and launching the URL, it fails with below error. Isn't this related to this same issue?

Failed to fetch the well-known json "https://localhost:44348/.well-known/smart-configuration

**Comment by conkman** [comment]
Is there an update on this issue?  I am using the FHIR Service PaaS offering within Azure and I am not able to find the .well-known/smart-configuration endpoint.

**Comment by EXPEkesheth** [comment]
@conkman - This link provides detail about SMART on FHIR capability using OSS samples. https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/smart-on-fhir.

Let us know if you have additional questions for SMART on FHIR capability.
