### ISSUE TITLE
Modifier added in R4 working in STU3 version

### ISSUE THREAD

**Issue by Ivanidzo4ka** [microsoft/fhir-server#2150]
**Describe the bug**
Certain modifiers like: :ofType or :identifier been added in R4 and not present in STU3.
if I do search with them in STU3 they work fine, but they should return modifier not supported message.

Our `ExpressionParser` class are not version aware.

**FHIR Version?**
Stu3

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. send Patient?identifer:ofType=la|la|la

**Expected behavior**
Message what unknown modifier been used.

**Actual behavior**
Search happens.

**Comment by CaitlinV39** [comment]
AB#84434
