### ISSUE TITLE
set PathBase from Environment Variable

### ISSUE THREAD

**Issue by Lukas1v** [microsoft/fhir-server#2152]
**User story**
As a user, I want to be able to set PathBase from an Environment Variable so that I can run the FHIR server under a custom path (eg /fhir) that is provided when deploying as a docker container.

**Acceptance criteria**
1. When I set an environment variable PATH_BASE, it sets the PathBase from #1200 

I already implemented a quick fix by defining a method in FhirServerConfiguration:

```c#
namespace Microsoft.Health.Fhir.Api.Configs
{
    public class FhirServerConfiguration : IApiConfiguration
    {
        public string PathBase { get; set; } = GetPathBase();

       ///...

        private static string GetPathBase()
        {
            string pathBase = Environment.GetEnvironmentVariable("PATH_BASE");
            return pathBase;
        }
    }
}
```

But as I am relatively new to both .NET and contributing to open source projects, I was looking for some feedback on the quality of this solution before initiating a PR.

**Comment by brendankowitz** [comment]
This should already be able to be set from an Environment Variable. See: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#naming-of-environment-variables

**Comment by CaitlinV39** [comment]
@Lukas1v - Let us know if you still have issues. I'm going to close but feel free to reopen if you need!
