### ISSUE TITLE
FHIR Server - Cosmos Transaction Support?

### ISSUE THREAD

**Issue by btsetworks** [microsoft/fhir-server#2162]
Hey Microsoft Team & Contributors,

Do you have Cosmos support for resource bundle transactions?  From my initial testing, it does not look like this is supported.

Do you plan to add support for this?  Or is there another way to turn this on?

I can get bundle transactions to work with the SqlServer data source, just not Cosmos.  I was hoping to take advantage of the advanced processing with Cosmos.

Thanks for the help.

Blake Theiss

**Comment by CaitlinV39** [comment]
@btsetworks Unfortunately we cannot support transactions on the Cosmos DB. If you need transaction support, you will need to use the SQL backend. Let us know if you have other questions!
