### ISSUE TITLE
Put with no id is confusing

### ISSUE THREAD

**Issue by Ivanidzo4ka** [microsoft/fhir-server#2168]
**Describe the bug**
```
PUT {yoururl}/FhirType

{
"resourceType":"FhirType",
...
}
```

return back 400 bad request and 
```
{
    "resourceType": "OperationOutcome",
    "id": "29792a65ac9fe440b1eedf5a826596f7"
}
```
**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**
Tell me what you looking for id after {yoururl}/FhirType

**Actual behavior**
A clear and concise description of what actually happened.

**Comment by brendankowitz** [comment]
This is probably the conditional PUT route

**Comment by CaitlinV39** [comment]
Missing that you need the ID or a search for conditional

**Comment by Ivanidzo4ka** [comment]
Yes, it's conditional PUT and we eat validation message.
If we don't supress validation message output looks like this:

{
    "resourceType": "OperationOutcome",
    "id": "889f0d30-e733-40c7-baf9-3f47cf35b0f7",
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "Operation was not attempted because search criteria was not selective enough.",
            "location": [
                "ConditionalParameters"
            ]
        }
    ]
}
