### ISSUE TITLE
ADB2C registration is giving authentication / authorization failed when accessing my FHIR server api

### ISSUE THREAD

**Issue by sethuraj** [microsoft/fhir-server#2191]
The FHIR application that I am building is using ADB2C for authentication and authorization.
FHIR Server is installed in my Active Directory tenant where I have my subscription.
I have registered the FHIR server and a "postman callback” client with ADB2C APP registration,
I have added admins roles by editing manifest and added one of the ADB2C user as the "globalAdmin" role.
All permissions are set.

From PostMan I am able to login via ADB2C and generate token, but authentication seems  to fail. I am wondering this has to do with my audience and authority configuration.
Authority The url  the ADB2C tenant and useflow combination"
Audience : I gave the Application ID URI   (In ADB2C it starts with "https://<tenantname>.onmicrosoft.com" . It gave audience invalid error. So I gave the GUID value of the client. then I received the forbidden error

{"resourceType":"OperationOutcome","id":"fa1b5ca8-29e6-4573-8379-4c725b2ff605","issue":[{"severity":"error","code":"forbidden","diagnostics":"Authorization failed."}]}

I don't see any documentation on using ADB2C in FHIR. I would assume most of the patient facing apps will need ADB2C authentication to FHIR than the through Azure AD.

Any help is appreciated

**Comment by sethuraj** [comment]
Any comment @CaitlinV39 ? Is FHIR API be secured with ADB2C app registration?

**Comment by CaitlinV39** [comment]
@sethuraj - Sorry for the delay. This is a known limitation and we don't have plans to resolve. Please see issue #774 for more details. We recommend leveraging the Microsoft open-source FHIR proxy (https://aka.ms/fhirproxy) to assist in this scenario.
