### ISSUE TITLE
OperationOutcome uses location (which has been deprecated) instead of expression

### ISSUE THREAD

**Issue by fmeira** [microsoft/fhir-server#2195]
**Question**

According to https://hl7.org/fhir/operationoutcome.html, the field "location" has been deprecated and the field "expression" should be used instead. Is there an estimation for when this update should be implemented?

**Comment by CaitlinV39** [comment]
AB#85283

**Comment by EXPEkesheth** [comment]
Marking this issue closed, as it the question is addressed,
