### ISSUE TITLE
$reindex not working, never complets

### ISSUE THREAD

**Issue by tomjscrypt** [microsoft/fhir-server#2200]
To reproduce:
1. Create new Fhir Service.
2. Run $reindex on {{fhir-url}}.
3. Check status of job it is:
`{
            "name": "totalResourcesToReindex",
            "valueDecimal": 0.0
        },
        {
            "name": "resourcesSuccessfullyReindexed",
            "valueDecimal": 0.0
        },
        {
            "name": "progress",
            "valueDecimal": 0.0
        },
        {
            "name": "status",
            "valueString": "Queued"
        },`

4. wait hour or to next day.
5. Check status:
`{
            "name": "totalResourcesToReindex",
            "valueDecimal": 0.0
        },
        {
            "name": "resourcesSuccessfullyReindexed",
            "valueDecimal": 0.0
        },
        {
            "name": "progress",
            "valueDecimal": 0.0
        },
        {
            "name": "status",
            "valueString": "Queued"
        },`

So in point 3. and 5. status is same, hence job is suspended and never completes.
This makes one unable to use custom SearchParameters feature.

**Comment by CaitlinV39** [comment]
@rotodd @Ivanidzo4ka 

@tomjscrypt - A couple of questions. Are you deploying open-source or managed service version? If open-source, is it SQL or Cosmos? If managed service is it Azure API for FHIR or the Azure Healthcare APIs?

**Comment by tomjscrypt** [comment]
@CaitlinV39 thank you for quick response,
Problem is when I create FHIR service in Azure Healthcare APIs (all created with default settings according to documentation).
I tried same thing on Azure API for FHIR and it is working there as expected i.e. job is completed and I get following:

`
        {
            "name": "output",
            "part": [
                {
                    "name": "Informational",
                    "valueString": "No resources were found matching the type of the updated search parameters needing to be reindexed.  ReindexJob marked completed."
                }
            ]
        },
`

`        {
            "name": "status",
            "valueString": "Completed"
        },
`

**Comment by CaitlinV39** [comment]
@tomjscrypt we recently resolved an issue in the Azure Healthcare APIs where the reindex job wouldn't complete. Can you validate that it still isn't working for you? If it isn't, if you can open a support ticket from the product so we can get information about your database we will investigate. Thanks so much! @LTA-Thinking @feordin FYI

**Comment by LTA-Thinking** [comment]
@tomjscrypt The fix @CaitlinV39 mentions will be part of our next release, it is not currently available. That release should be available next week.

**Comment by CaitlinV39** [comment]
@tomjscrypt this should be resolved. Please let us know if you are still having issues.
