### ISSUE TITLE
nbsp character raises an invalid result due to regex mismatch

### ISSUE THREAD

**Issue by fmeira** [microsoft/fhir-server#2203]
**Describe the bug**
Sending a nbsp character (0x00a0 (160)) in a text (string) field (for Dosage resource) raises an invalid regex parsing.

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
1. Send in a bundle resource with a medication-statement that has dosing.text with a nbsp character in it, ex: "1 000 mL 2 TIMES DAILY Max Daily Amount: 10 000 mg"

**Expected behavior**
The validation should not fail.

**Actual behavior**
An OperationOucome is returned with a validation error, such as:
```xml
<OperationOutcome xmlns="http://hl7.org/fhir">
	<id value="94f44a68-007a-4a41-806c-90ce1ee9b6c4" />
	<issue>
		<severity value="error" />
		<code value="invalid" />
		<diagnostics value="Value '1 000 mL 2 TIMES DAILY Max Daily Amount: 10 000 mg' does not match regex '[ \r\n\t\S]+'" />
		<location value="Parameters.Parameter[0].Resource.Entry[28].Resource.MedicationStatement.dosage[0].text[0]" />
	</issue>
</OperationOutcome>
```

**Comment by Ivanidzo4ka** [comment]
https://github.com/FirelyTeam/firely-net-sdk/issues/1563

We use firely library under the hood to do validation, and they did had that issue in the past, but for current release of our service we use 3.4 version which suppose to have right fixes.

I also have trouble to reproduce it locally. Sending MedicationStatement with dosage.text like that:
`"text": "Df sd\u00a0в",`
ends in creation of resource.

Any chance you can provide small json file with problematic content and version of your service?

**Comment by fmeira** [comment]
Thanks for your reply @Ivanidzo4ka.
I see I forgot to mention an important detail, which is the version of the fhir-server we are using.
As we are still running .net 3.1, we are using the latest version of fhir-server that supports it, that is from Feb 21st.
If I am not mistaken, that version still uses the v1.9 firely library, which still has this problem.

I can then assume that when we upgrade to the latest, this problem will be solved.
I am then closing this issue.
