### ISSUE TITLE
Deployment Guide for Dummies

### ISSUE THREAD

**Issue by TMAHS** [microsoft/fhir-server#2207]
I am new to this GITHUB and FHIR stuff, but am learning.

When we were deploying our FHIR server to Azure using the guidance at https://github.com/Microsoft/fhir-server/blob/main/docs/DefaultDeployment.md and a few other resources we were able to get the server deployed, but if you documentation could including something along the lines of "if you select a SQL database deployment with the Scheme Update set to TOOL, you will need to run the SQL migration tool immediately following the successful deployment.  This was not immediately clear to us.  We did find on the Azure Deployment screen a small informational icon that alerted us to the fact, but it would have been nice to have that in the documentation.

I don't know that this is a question, but not sure it is an issue either.

Thanks.

**Comment by v-kulkarnipa** [comment]
We have checked that whether it is true case that we have to run sql schema migration tool after setting "Tool" option in deployment, and it is correct. So question to Olympus team is shall we update deployment document with this note ?
