### ISSUE TITLE
Prefer handling doesn't applied to sort

### ISSUE THREAD

**Issue by Ivanidzo4ka** [microsoft/fhir-server#2208]
**Describe the bug**
Query /Patient?_sort=family with header
`Prefer` `handling=strict`

I expect BadRequest but I get 200 with operation outcome.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**Expected behavior**
400 error.

**Actual behavior**
200 with operation outcome.
```
"resource": {
                "resourceType": "OperationOutcome",
                "id": "cf173395-e168-40a7-bf19-25cae93edc73",
                "issue": [
                    {
                        "severity": "warning",
                        "code": "not-supported",
                        "diagnostics": "Sorting by the 'family' parameter is not supported."

```

**Comment by CaitlinV39** [comment]
AB#85282
