### ISSUE TITLE
deploy fhir server with authentication

### ISSUE THREAD

**Issue by tomjscrypt** [microsoft/fhir-server#2211]
How to add authentication to fhir-server?

I try to follow:
https://github.com/microsoft/fhir-server/blob/main/docs/QuickstartDeployPortal.md

and I cannot find how to set up the authentication, if one leaves default values, the server has no authentication.

**Comment by CaitlinV39** [comment]
@tomjscrypt We need to work on the flow of our documents a bit, but here are the details:

https://github.com/microsoft/fhir-server/blob/main/docs/Authentication.md
https://github.com/microsoft/fhir-server/blob/main/docs/Register-Resource-Application.md
https://github.com/microsoft/fhir-server/blob/main/docs/Register-Client-Application.md

**Comment by tomjscrypt** [comment]
Thank you for your answer, I have some further questions:

https://github.com/microsoft/fhir-server/blob/main/docs/Authentication.md - is this guide for fhir-server running locally or in Azure?

Do I need to add Identity provider to resource application?  

During deployment, do I need to set "Enable Aad Smart on Fhir Proxy" to true, set "Security Authentication Audience" and "Security Authenticaiton Authority"?

Is adding Authentication to fhir-server any different than adding OAuth 2.0 to any other Azure App Service?

**Comment by CaitlinV39** [comment]
@tomjscrypt for a couple of your questions, you don't need to enable the SMART on FHIR proxy for authentication. That is to use SMART on FHIR. You will need to set the Authentication Audience and Authority.

**Comment by feordin** [comment]
@tomjscrypt 
For the question about adding an identity provider to the resource application:  registering a resource application, and then a client application is the process by which you can use Azure Active Directory as your identity provider.  The Azure Active directory tenant that you registered your applications in will have a url that you add to the FHIR server security settings.

There are built in methods on azure app services to add authentication, but adding authentication to the FHIR server is different, and is done by setting the url to the authority in settings.
