### ISSUE TITLE
Resource identifier does not work if uppercase is used for the id

### ISSUE THREAD

**Issue by mmacagno** [microsoft/fhir-server#2218]
**Describe the bug**
Trying to get resources with uppercase GUID/ID returns 404.

I am not sure if this is by design.

**FHIR Version?**R4

**Data provider?**
CosmosDB

**To Reproduce**
1. Create a resource (e.g. an encounter), obtain the resulting object with id (e.g. 09f0d9fd-f4fa-4e0b-86bd-027d84097df0)
2. Try to fetch the resource with uppercased id (e.g. https://{fhir_server}/encounter/09F0D9FD-F4FA-4E0B-86BD-027D84097DF0

**Expected behavior**
The encounter resource is returned

**Actual behavior**
404 Resource not found is returned.

**Comment by Ivanidzo4ka** [comment]
https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Case.20sensitivity.20of.20Resource.20IDs
Is there are reason to believe Id should be case insensitive?

**Comment by vneilley** [comment]
IDs are case sensitive - this is not a bug, this is expected behavior from a FHIR resource ID (as noted in the FHIR chat sent above)

**Comment by mmacagno** [comment]
I think I was tricked by my own implementation. We use GUIDs for IDs and assumed casing should not matter.
Closing this.
