### ISSUE TITLE
Join Devices on Procedure

### ISSUE THREAD

**Issue by kamyh** [microsoft/fhir-server#2229]
**Describe the bug**
There is no way to use _include or _revinclude to join the device on a procedure

**FHIR Version?**
R4

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
curl -X GET -H "Authorization: Bearer $tokenFIHR" -H "Content-Type: application/json" "<URL>/Practitioner?_revinclude=PractitionerRole:practitioner&_count=1000" > ./fhir-out-practitioner-and-role.json
curl -X GET -H "Authorization: Bearer $tokenFIHR" -H "Content-Type: application/json" "<URL>/Procedure?_include=Procedure:focalDevice&_count=1000" > ./fhir-out-procedure-with-devices.json
curl -X GET -H "Authorization: Bearer $tokenFIHR" -H "Content-Type: application/json" "<URL>/Device?_revinclude=Procedure:focalDevice&_count=1000" > ./fhir-out-procedure-with-devices.json

**Expected behavior**
Join devices on a procedure call

**Comment by CaitlinV39** [comment]
@kamyh Can you update this to include what the actual behavior you are getting is?
