### ISSUE TITLE
Profiling in FHIR not working

### ISSUE THREAD

**Issue by Sameer2810** [microsoft/fhir-server#2245]
Hi, I have created Extension and try adding it in the Patient Resource. I want to make that extension mandatory. I have added StrctureDefinition url in Profile section under Patient Resource see json as belows

{
  "resourceType": "Patient",
  "meta":{
      "profile":[
          "https://example.org/fhir/StructureDefinition/MyPatientOrganizationId"
      ]
  },
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">\n      \n      <p>Patient John Doe, M, 27-May 1956. ID: 89765a87b</p>\n    \n    </div>"
  },
  "identifier": [
    {
      "use": "usual",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "MR"
          }
        ]
      },
      "system": "urn:oid:1.2.3.4.5",
      "value": "89765a87b"
    }
  ],
  "active": true,
  "name": [
    {
      "family": "Doe",
      "given": [
        "John"
      ]
    }
  ],
  "gender": "male",
  "birthDate": "1956-05-27",
  "address": [
    {
      "line": [
        "100 Main St"
      ],
      "city": "Metropolis",
      "state": "Il",
      "postalCode": "44130",
      "country": "USA"
    }
  ],
  "managingOrganization": {
    "reference": "Organization/2"
  }  
}

Now I want that this gives validation error but it is not giving any error because I want it as mandatory. I use Forge to create extension on Patient Resource and I make it's cardinality 1...1.  What I am missing?
I am using CosmosDB

**Comment by CaitlinV39** [comment]
@Sameer2810 - Can you share the extension you saved into the FHIR server?

**Comment by Sameer2810** [comment]
Hi CaitlinV39,

Following is the extension

   

{​​​​​​
"resourceType": "StructureDefinition",
"url": "https://example.org/fhir/StructureDefinition/OrganizationId",
"name": "OrganizationId",
"status": "draft",
"fhirVersion": "4.0.1",
"kind": "complex-type",
"abstract": false,
"context": [
    {​​​​​​
"type": "element",
"expression": "Patient"
    }​​​​​​
  ],
"type": "Extension",
"baseDefinition": "http://hl7.org/fhir/StructureDefinition/Extension",
"derivation": "constraint",
"differential": {​​​​​​
"element": [
      {​​​​​​
"id": "Extension.url",
"path": "Extension.url",
"fixedUri": "https://example.org/fhir/StructureDefinition/OrganizationId"
      }​​​​​​,
      {​​​​​​
"id": "Extension.value[x]",
"path": "Extension.value[x]",
"slicing": {​​​​​​
"discriminator": [
            {​​​​​​
"type": "type",
"path": "$this"
            }​​​​​​
          ],
"rules": "open"
        }​​​​​​,
"min": 1,
"type": [
          {​​​​​​
"code": "string"
          }​​​​​​
        ]
      }​​​​​​
    ]
  }​​​​​​
}​​​​​​

**Comment by CaitlinV39** [comment]
Hey @Sameer2810 - changing cardinality is controlled by a profile which will reference this extension. You will need to create using $validate against the profile that defines the rules you want.

**Comment by Sameer2810** [comment]
Hi @CaitlinV39,

I have validated against the Patient resource which I created earlier. It is giving following error

{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "details": {
                "coding": [
                    {
                        "system": "http://hl7.org/fhir/dotnet-api-operation-outcome",
                        "code": "1003"
                    }
                ],
                "text": "Instance of type 'Patient' is incompatible with the stated profile 'https://example.org/fhir/StructureDefinition/OrganizationId' which is constraining constrained type 'https://example.org/fhir/StructureDefinition/OrganizationId'"
            },
            "location": [
                "Patient"
            ]
        }
    ]
}
