### ISSUE TITLE
Pagination broken - Next URL more than 2Kb

### ISSUE THREAD

**Issue by shahedaAnsari** [microsoft/fhir-server#2250]
**Describe the bug**
The "next" url in the link section of a Bundle resource results in a 404 response. I believe this is related to the URL specified as "next" and its length is greater than 4kb. 
We are using the Azure API for FHIR.

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
1. This occurs when we get all resource example- suppose we get list of patient then in next link we get very long string for parameter "ct"

**Expected behavior**
Able to navigate to other pages using next link

**Actual behavior**
Not able to navigate to next link we get following error

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

Screenshot for the same

![CosmosDBNextLinkTooLong](https://user-images.githubusercontent.com/40784469/135620736-85ca25fc-fef8-4a59-b388-c952ff0f33bc.PNG)

**Comment by CaitlinV39** [comment]
@shahedaAnsari A couple quick questions. Are you using a proxy in front of the FHIR service or hitting it directly? In addition, are you on the open-source version of the FHIr service or using the Azure API for FHIR? If the open-source version, can you tell me which release you are running?

**Comment by shahedaAnsari** [comment]
> @shahedaAnsari A couple quick questions. Are you using a proxy in front of the FHIR service or hitting it directly? In addition, are you on the open-source version of the FHIr service or using the Azure API for FHIR? If the open-source version, can you tell me which release you are running?

I am directly hitting the API and I am using the open source which has the version 2.0.172

**Comment by shahedaAnsari** [comment]
> @shahedaAnsari A couple quick questions. Are you using a proxy in front of the FHIR service or hitting it directly? In addition, are you on the open-source version of the FHIr service or using the Azure API for FHIR? If the open-source version, can you tell me which release you are running?

I am directly hitting the API, and I am using the open source which has the version 2.0.172

**Comment by CaitlinV39** [comment]
AB#86024

**Comment by Sameer2810** [comment]
Still facing same issue with new build 2.1.22
