### ISSUE TITLE
Invalid Content-Type could cause NullReferenceException

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#229]
**Describe the bug**

NullReferenceException is thrown under certain scenarios when the Content-Type specified is invalid.

System.NullReferenceException: Object reference not set to an instance of an object.    at Hl7.Fhir.Rest.ContentType.GetMediaTypeFromHeaderValue(String mediaHeaderValue)    at Hl7.Fhir.Rest.ContentType.GetResourceFormatFromContentType(String contentType)    at Microsoft.Health.Fhir.Api.Features.Filters.ValidateContentTypeFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Builder.StatusCodePagesExtensions.<>c__DisplayClass6_0.<<UseStatusCodePagesWithReExecute>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

**To Reproduce**
1. Post a Patient resource with Content-Type: "application/fhir+json as the header

**Expected behavior**
- An OperationOutcome should be returned indicating that the Content-Type is unsupported.

**Actual behavior**
- An OperationOutcome is returned with internal server error.

**Comment by johnstairs** [comment]
@poadhika, this looks like the issue you were looking at.

**Comment by poadhika** [comment]
Yes this is. I have already made the change to handle this exception and the pull request for develop branch is already approved.
