### ISSUE TITLE
Audit tests failure

### ISSUE THREAD

**Issue by ghost** [microsoft/fhir-server#2311]
When running tests Microsoft.Health.Fhir.R4.Tests.E2E, following 4 tests fail:

1. Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests(CosmosDb, Json).GivenARequest_WhenInvalidAuthorizationTokenIsSupplied_ThenAuditLogEntriesShouldBeCreated
2. Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests(CosmosDb, Json).GivenARequest_WhenNoAuthorizationTokenIsSupplied_ThenAuditLogEntriesShouldBeCreated
3. Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests(CosmosDb, Json).GivenARequest_WhenValidAuthorizationTokenWithInvalidAudienceIsSupplied_ThenAuditLogEntriesShouldBeCreated
4. Microsoft.Health.Fhir.Tests.E2E.Rest.Audit.AuditTests(SqlServer, Json).GivenATransactionBundleWithValidEntries_WhenSuccessfulPost_ThenAuditLogEntriesShouldBeCreated

FHIR Version R4 (maybe other versions as well)

Data provider? CosmosDB/SQL Server, see above for each test.

To Reproduce:
1. Fresh new install, follow step https://github.com/microsoft/fhir-server/wiki/Build-and-debug-locally (Use latest version of .NET 5.0.402)
2. Run tests in Microsoft.Health.Fhir.R4.Tests.E2E

Expected behavior: Tests should not fail.

Actual behavior: 4 tests fail.

**Comment by CaitlinV39** [comment]
AB#86422
