### ISSUE TITLE
Pagination broken 

### ISSUE THREAD

**Issue by Sameer2810** [microsoft/fhir-server#2313]
**Describe the bug**
Next link is not working when we publish FHIR api on app service. However I observe that it will work on locally but when we publish api then it gives error. 
Also when data is less on live environment then next link works but when data size increases then it gives error
Continuation Token length is very big it is greater than 2kb
We are using open source  Fhir api version 2.1.22

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**Comment by brendankowitz** [comment]
Another option you have is to specify a lower number for the max size of the token provided by CosmosDB:

https://github.com/microsoft/fhir-server/blob/38603406b0dec6eeb3521c658f59c9ca45d0d289/src/Microsoft.Health.Fhir.Shared.Web/appsettings.json#L133

Some additional questions:
1. Roughly how big is the database you're using?
2. Was there a decrease in token size with 2.1.22?

**Comment by CaitlinV39** [comment]
@Sameer2810 have you had a chance to review Brendan's questions?

**Comment by Sameer2810** [comment]
@brendankowitz  to answer your question

1. We are using CosmosDB Database which has throughput autoscale and it has 4000 RU/s
2. There is no decrease in the token size with 2.1.22

**Comment by Sameer2810** [comment]
@brendankowitz and @CaitlinV39  also even after I set  "ContinuationTokenSizeLimitInKb": 1, still getting very large Continuation token

Following is the screenshot

![ContinutaionToken](https://user-images.githubusercontent.com/38692494/141073709-a294be1d-7eb8-4419-9570-22f181069d29.JPG)

**Comment by Sameer2810** [comment]
Hi, Is there any update?

**Comment by Sameer2810** [comment]
Hi, Is there any update?

**Comment by brendankowitz** [comment]
@Sameer2810 are you able to paste the continuation token a text here that is over the limit?

If the URI is too long, another workaround might be to convert these parameters to a POST based _Search, i.e. 

```
POST  [base]/[type]/_search
Content-Type: application/x-www-form-urlencoded

param1=value&param2=value
```

**Comment by CaitlinV39** [comment]
@Sameer2810 - Are you using the Azure API for FHIR or deployed in open-source?

**Comment by Sameer2810** [comment]
Hi @brendankowitz  - I tried with Post method using _search parameter and followed following approach but still facing same issue

POST  [base]/[type]/_search
Content-Type: application/x-www-form-urlencoded

param1=value&param2=value

Now we get the continuation token invalid error

{
    "resourceType": "OperationOutcome",
    "id": "4df24646-130c-42df-9272-c9ee019b6969",
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "The continuation token is invalid."
        }
    ]
}

**Comment by CaitlinV39** [comment]
@Sameer2810 - @brendankowitz and I might need a bit more information to continue to troubleshoot. Could you email me directly at cavoeg@microsoft.com? We can dig into specific details from there and then come back to this issue with an update.

**Comment by CaitlinV39** [comment]
@Sameer2810 - were you able to send me an email or are you still having the issue?

**Comment by CaitlinV39** [comment]
@Sameer2810 - I'm going to close for now but please feel free to email me if you have more details and we can reopen.
