### ISSUE TITLE
How can I search on Patient Identifier by substring? (:contains)

### ISSUE THREAD

**Issue by EMellau** [microsoft/fhir-server#2315]
When searching Patients by identifier I would like to be able to search by part of it.  Exactly like :contains

Is there a way of doing this? Where can I find the documentation for it?

here what I tried:

`curl -X GET -H "Authorization: Bearer $tokenFIHR" -H "Content-Type: application/json" "$azureFhirURL/Patient?identifier:contains=33221" > res.json`

`curl -X GET -H "Authorization: Bearer $tokenFIHR" -H "Content-Type: application/json" "$azureFhirURL/Patient?identifier=ap33221" > res.json`

`curl -X GET -H "Authorization: Bearer $tokenFIHR" -H "Content-Type: application/json" "$azureFhirURL/Patient?identifier=urn:33221" > res.json`

**Comment by brendankowitz** [comment]
Currently `:contains` isn't implemented for Token type searches (https://github.com/microsoft/fhir-server/blob/main/src/Microsoft.Health.Fhir.Core/Features/Search/Expressions/Parsers/SearchValueExpressionBuilderHelper.cs#L261)

String searches do work for this, e.g. `GET {{hostname}}/Patient?address:contains=Meadow`

**Comment by EMellau** [comment]
> Currently `:contains` isn't implemented for Token type searches (https://github.com/microsoft/fhir-server/blob/main/src/Microsoft.Health.Fhir.Core/Features/Search/Expressions/Parsers/SearchValueExpressionBuilderHelper.cs#L261)
> 
> String searches do work for this, e.g. `GET {{hostname}}/Patient?address:contains=Meadow`

Thanks brendankowitz, then how should I search by a sub-string on a Token type?

**Comment by JoanaGodinho** [comment]
@EMellau were you able to solve this issue?

**Comment by clarotech** [comment]
As stated the 'identifier' type does not support ':contains' within the FHIR standard, as such I suspect the FHIR server should not implement it.

If this is a hard requirement for the implementation, then it would be possible to introduce a custom search index of type 'string' which would then allow a search using the ':contains' construct.

**Comment by EXPEkesheth** [comment]
@EMellau - Please let us know if your question is answered. No response in a week, the issue will be closed.
