### ISSUE TITLE
QuickstartDeployCLI with solutionType=FhirServerSqlServer fails

### ISSUE THREAD

**Issue by jdanyow-alt** [microsoft/fhir-server#2326]
I was trying to use Sql Server in [QuickstartDeployCLI.md](https://github.com/microsoft/fhir-server/blob/main/docs/QuickstartDeployCLI.md). Encountered a few issues:

1. Examples reference the master branch- project has migrated to the main branch (not a blocker, just a heads up, bunch of issues like this in the repo).
2. Attempting to run the command with the addition of `solutionType=FhirServerSqlServer` results in:
   ```
   az deployment group create --resource-group fhir --template-uri https://raw.githubusercontent.com/Microsoft/fhir-server/main/samples/templates/default-azuredeploy.json --parameters serviceName=$servicename solutionType=FhirServerSqlServer
   {"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The provided value '' for the template parameter 'sqlSchemaAutomaticUpdatesEnabled' at line '163' and column '29' is not valid. The parameter value is not part of the allowed value(s): 'auto,tool'.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":163,"linePosition":29,"path":"parameters.sqlSchemaAutomaticUpdatesEnabled.allowedValues"}}]}}
   ```
3. Adding `sqlSchemaAutomaticUpdatesEnabled=auto` results in:
   ```
   az deployment group create --resource-group fhir --template-uri https://raw.githubusercontent.com/Microsoft/fhir-server/main/samples/templates/default-azuredeploy.json --parameters serviceName=$servicename solutionType=FhirServerSqlServer sqlSchemaAutomaticUpdatesEnabled=auto
   {"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource 'Microsoft.Sql/servers/fhir/databases/FHIR' cannot reference itself. Please see https://aka.ms/arm-template-expressions/#reference for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":0,"linePosition":0,"path":""}}]}}
   ```
   ![image](https://user-images.githubusercontent.com/93845191/140625864-7df4f270-7037-43e3-aa28-cf5eba86971f.png)

Is there a way to deploy the project using SQL server?

cc @jdanyow

**Comment by brendankowitz** [comment]
Thanks for raising this, the documentation page is a little stale. The deployment worked for me when also providing the "sqlAdminPassword" parameter which is required for the SQL Server template.
On top of this I'd recommend using the "default-azuredeploy-docker.json" template.
