### ISSUE TITLE
deleting related resources in one transaction

### ISSUE THREAD

**Issue by tomjscrypt** [microsoft/fhir-server#2337]
I would like to delete resources which are related to each other by one REST call using 1 transaction but I get 400 Bad request:

"Bundle contains multiple entries that refers to the same resource <someResource>"

Is it expected behaviour? I would prefer to execute such deletion in one attempt so I am sure there are no leftovers left behind.

**Comment by CaitlinV39** [comment]
@tomjscrypt This should work. Would you be able to provide a sample bundle with synthetic data that shows what you're doing?

**Comment by tomjscrypt** [comment]
@CaitlinV39 indeed it works when relation is 1 level deep, like: 
Observation <- Observation
Then I can delete all two Observations.

If it is more than 1 level deep:
Observation123 -> Observation345 -> Observation678
Then I get 400 and:
"diagnostics": "Bundle contains multiple entries that refers to the same resource 'Observation345', I reference them via "focus".

**Comment by CaitlinV39** [comment]
Hey Tom - If you can send me a full sample of the request you are making with synthetic data (either attach here or email me at cavoeg@Microsoft.com), we need a bit more details to troubleshoot.

**Comment by CaitlinV39** [comment]
@tomjscrypt - I'm going to close but if you're able to email me more information we can reopen
