### ISSUE TITLE
Sorting on patient resource error

### ISSUE THREAD

**Issue by EMellau** [microsoft/fhir-server#2344]
# When calling Fhir with `_sort=` and  `organization.identifier=` on Patient resource get, it bugs.

Using azurehealthcareapis

**Description**
When using the parameter _sort on Patient resource at the same time than filtering by organization it bugs.

All of them i use curl to test 
`curl -X GET -H "Authorization: Bearer $tokenFIHR" -H "Content-Type: application/json" "https://fhir-xx-xxxx-xxxx.azurehealthcareapis.com`

 _This one gives not sorted results of an organization(As expected)_
```
/Patient?organization.identifier=000000&_count=30
```

_This one gives sorted results, has some patients from the org we were searching before(Showing that there is indeed patients on that organization with a birthdate)_
```
Patient?_sort=birthdate&_count=30
```

 _This one gives no results (But it should)_
```
/Patient?organization.identifier=000000&_sort=birthdate&_count=30
```

_This one gives not sorted results (As expected)_
```
/Patient?organization.identifier=000000&_sort=&_count=30
```

_Not working neither (We can not sort by identifier OR FullName)_
```
/Patient?_sort=identifier&_count=30
```

**Comment by brendankowitz** [comment]
Thanks for reporting this @EMellau, we are looking into it

**Comment by CaitlinV39** [comment]
AB#86544

**Comment by brendankowitz** [comment]
In the above, you can't sort on all search parameters, when not supported these are returned in the search bundle as OperationOutcomes, e.g.:

```
{
        "resourceType": "OperationOutcome",
        "id": "54fc2239-45df-4e93-8abc-c96c5522ff7c",
        "issue": [
          {
            "severity": "warning",
            "code": "not-supported",
            "diagnostics": "Sorting by the 'identifier' parameter is not supported."
          }
```

**Comment by EMellau** [comment]
> In the above, you can't sort on all search parameters, when not supported these are returned in the search bundle as OperationOutcomes, e.g.:
> 
> ```
> {
>         "resourceType": "OperationOutcome",
>         "id": "54fc2239-45df-4e93-8abc-c96c5522ff7c",
>         "issue": [
>           {
>             "severity": "warning",
>             "code": "not-supported",
>             "diagnostics": "Sorting by the 'identifier' parameter is not supported."
>           }
> ```

Agree but _birthdate_ is supported right?

**Comment by CaitlinV39** [comment]
@EMellau - Thank you so much for identifying this. We have identified the fix and it is merged into the open-source code and will ship to the managed service during the month of December. If you'd like to follow up at all feel free to email me: cavoeg@microsoft.com.
