### ISSUE TITLE
Querying string search parameter could consumes large RUs under certain circumstance

### ISSUE THREAD

**Issue by jackliums** [Microsoft/fhir-server#235]
**Describe the bug**

We have a report from customer that simple query /Patient?given=Bob was not returning any data. Upon some investigation, the query was consuming large number of RUs which causes the query to return empty results.

Investigating further, this is because we have Hash index on string by default but we actually need Range index because Hash index works for equality checks but not for comparison checks and Cosmos DB was doing full scan because the index was not being utilized.

This issue did not come up during testing because we had variety types of resources created within our test. But for this customer, almost all of the resources were Patient and therefore the almost every query resulted in full scan.

**Comment by poadhika** [comment]
Verified that with the change the total number of required RU's  dropped down from 1178.14 to  3.66
