### ISSUE TITLE
More than 1k patients for an organization its not possible?

### ISSUE THREAD

**Issue by EMellau** [microsoft/fhir-server#2352]
### More than 1000 patients for an organization its not possible?

When calling a resource using Sub-queries  that involve patients, even if we add a `_count` it return the following error:

`"Sub-queries in a chained expression cannot return more than 1000 results, please use a more selective criteria."`

This happens once an organization have more than 1000 patients. I believe that 1000 patients for one organization is something usual and would be a pity not be able to use Sub-queries on that case.

Here I let some screenshots replicating the error:

Practitioner on an Organization with less than 1k patients
![PATIENTS_ORG2](https://user-images.githubusercontent.com/45633709/141310073-2535fd5c-3e90-45b6-b937-16f16a873434.png)

Practitioner on an Organization with more than 1k patients
![PATIENTS_ORG1](https://user-images.githubusercontent.com/45633709/141310076-a077e008-4534-4db4-a4a7-255fe7dec4aa.png)

Practitioner on an Organization with less than 1k patients performing get on encounters
![ENCOUNTERS_200](https://user-images.githubusercontent.com/45633709/141310081-8ac67924-baba-4da1-ae36-2b8f7fe038cd.png)

Practitioner on an Organization with more than 1k patients performing get on encounters
![ENCOUNTERS_403](https://user-images.githubusercontent.com/45633709/141310079-0396d699-9757-465f-8d9e-1bca4451e6ee.png)

The work around We found with my college is dirty but it works, **we would love to avoid it but it works**, here the following:

1. Search all patients of our organization (Doing pagination since we have more than 1000)
2. Collect all the Identifiers
3. Create a post search to Fhir with parameters: `subject` as value we add all the Identifiers separated by commas.
4. This returns us the desired list, being a list of encounters for an organization.
5. We still need to paginate it manually since the pagination URL provided on the response is to big (We convert the get provided to a Post)

![WORK_AROUND](https://user-images.githubusercontent.com/45633709/141311339-b7b6b8b6-d68b-44e8-9b8d-cdbf2516063e.png)

**Comment by CaitlinV39** [comment]
@EMellau Due to performance considerations, chained search is limited to 1000 results on the Cosmos DB implementation. The SQL implementation of the FHIR server has more robust chained search. This is the documentation (although it says 100 right now which needs to be updated to 1000).

https://docs.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/overview-of-search#chained--reverse-chained-searching

**Comment by lclaudon-owt** [comment]
@CaitlinV39 This is comprehensible but is a huge drawback for the scalability of FHIR solutions.
Do you think this particular limitation (which seems to be a configuration) could be configurable as part of the ARM templates of a FHIR Service? or increased to a more flexible value?

**Comment by CaitlinV39** [comment]
@lclaudon-owt - The best option would be to leverage the SQL backed FHIR service or the FHIR service in the Azure Healthcare APIs which doesn't have this limitation. We've been experimenting and recently increased from 100 to 1000.

**Comment by LKShankarKarthik** [comment]
@lclaudon-owt - As I understand "Microsoft FHIR Server (OSS)" is used for both "API for FHRHIR" and "Azure Healthcare APIs". Is there a way to know in which release this bug was fixed ?
