### ISSUE TITLE
fhir-server users cannot use arbitrary emails

### ISSUE THREAD

**Issue by tomjscrypt** [microsoft/fhir-server#2359]
From what we found in the documentation the only way to use arbitrary emails in azure is by using B2C, and B2C tokens do not work with fhir-server. This forces users to use long and unfamiliar emails  to login which causees very poor user experience right at the beginning of using the app. Inviting users as external users is very lengthy process and has even worse user experience. Is there any solution for that?

**Comment by CaitlinV39** [comment]
@tomjscrypt Right now we don't support B2C in the FHIR server. Our best alternative is to leverage the FHIR Proxy open-source project which you can find here: https://github.com/microsoft/fhir-proxy

**Comment by EXPEkesheth** [comment]
@tomjscrypt  - Azure B2C integration is supported with FHIR service, please refer to the [documentation](https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/azure-ad-b2c-setup?tabs=powershell) for more details.
Note this support is available only on Azure Health Data Services.

**Comment by EXPEkesheth** [comment]
@tomjscrypt - Closing the issue as B2C support is added per the comment above
