### ISSUE TITLE
Support conditional updates

### ISSUE THREAD

**Issue by jmehlbrech** [microsoft/fhir-server#236]
**User story**
As a [source] FHIR-server that needs to sync FHIR resources to target FHIR-servers, I want to be able to update resources in the microsoft-FHIR server - using identifiers, not having to use ids. The benefit is that the the source is not required to store the ids returned by microsoft/fhir server.

**Acceptance criteria**
1. When I do http PUT [base]/Condition?identifier=system|code,
     then the relevant FHIR resource is updated from the FHIR resource in the request body

Thanks! Best regards, Joerg Mehlbrech

**Comment by matjazl** [comment]
We had it on our issue list internally, but did not document it on our roadmap on GitHub. 

We are planning to support this in the future.

Thank you

Matjaz

**Comment by matjazl** [comment]
I would estimate in next 6 months we should have support for it. Stay tuned.

**Comment by courtenayparserr** [comment]
Hi @matjazl,

Has this been done yet by any chance? Doesn't seem so?

**Comment by hansenms** [comment]
Hi @courtenayparserr,

We are working on it. Don't have an ETA yet.

**Comment by brandonpollett** [comment]
@brendankowitz should this issue now be closed?

**Comment by brendankowitz** [comment]
Yes, closing as this has been verified //cc @namadabu
