### ISSUE TITLE
Add support for POST-ing of Transactions

### ISSUE THREAD

**Issue by villyg** [microsoft/fhir-server#237]
@**User story**
As a Client, I want to be able to POST data in a FHIR Transaction so that I can have immediate consistency.

**Acceptance criteria**
1. When I POST a Bundle with type Transaction, then all resources are handled using the spec here https://www.hl7.org/fhir/http.html AND
Transaction Integrity is honored AND
Conditional Reference logic is supported.

**Comment by matjazl** [comment]
We currently don't support bundles with type transaction or batch. it is something that we plan to support in the future.

**Comment by firechicago** [comment]
Is this still a priority? We're currently trying to use this as a CDR and this is a major blocker for us.

**Comment by hansenms** [comment]
Yes it is, we are building it right now.

**Comment by Lovkeshgoyal** [comment]
I am able to process batch undle request but transaction bundle is still not supported.
When would it be built?

**Comment by hansenms** [comment]
It should be available on the SQL backed version of the server. It will not be available on Cosmos DB.

**Comment by Lovkeshgoyal** [comment]
I have deployed directly fhir server to Azure which is creating Cosmos DB automtically. How can I make SQL up for DB?

**Comment by Lovkeshgoyal** [comment]
@hansenms , I still tried with SQL DB but not able to store transaction bundle as below -
![image](https://user-images.githubusercontent.com/38222036/71711873-f14ac480-2e28-11ea-8e35-a8aac4c1000b.png)

**Comment by hansenms** [comment]
Did you enable batch and transaction (it is behind feature flags). You need to set the following app settings:

`FhirServer:CoreFeatures:SupportsBatch` = `true`
`FhirServer:CoreFeatures:SupportsTransaction` = `true`

**Comment by Lovkeshgoyal** [comment]
It works.. Thanks :+1:
