### ISSUE TITLE
Upgrade to .NET 6.0

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#2379]
**User story**
As a developer, I want .NET 5 projects to be updated to .NET 6.0, so that we are aligned with the latest .NET release

**Acceptance criteria**
1. .NET5 projects are upgraded
2. The managed service FHIR services must also have a PR ready to support this

**Comment by CraigP68** [comment]
AB#87195

**Comment by EXPEkesheth** [comment]
This work is completed.
