### ISSUE TITLE
Deployment to Azure App Service

### ISSUE THREAD

**Issue by dustinmoris** [microsoft/fhir-server#2386]
Heya,

Sorry to bother you again with a question, but I tried to deploy the FHIR server from a fork of the latest `main` branch in this repository to an Azure AppService plan and it fails with a runtime exception because my Azure CI pipeline built the project with the .NET SDK `5.0.402` as it is specified in the `global.json` file of this repository, but Azure AppServices only support the .NET runtime `5.0.9` which comes with the `5.0.400` SDK.

Weirdly, even though [your global.json](https://github.com/microsoft/fhir-server/blob/main/global.json#L3) demands the `5.0.402` SDK, you are contradicting yourself by requiring the `5.0.12` ASP.NET Core runtime in [your build props](https://github.com/microsoft/fhir-server/blob/main/Directory.Build.props#L28). Not sure why this is specified at this version? Especially because the [`5.0.12` runtime only comes with the `5.0.403` SDK](https://versionsof.net/core/5.0/), which is neither what you specified in the `global.json` nor what is supported on Azure AppServices - one of the recommended deployment options according to the docs.

Given that the runtime version is dictated by Azure AppServices I changed the `global.json` to `5.0.400` but now my Azure CI pipeline throws an error because something in the MSBuild toolchain seems to have a hard reference to ASP.NET Core `5.0.11` which is as already established a higher version.

This is the error I am getting:

```
C:\Users\VssAdministrator\.nuget\packages\microsoft.sourcelink.common\1.0.0\build\Microsoft.SourceLink.Common.targets(52,5): warning : Source control information is not available - the generated source link is empty. [D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Microsoft.Health.Fhir.SqlServer.csproj]
  It was not possible to find any compatible framework version
  The framework 'Microsoft.NETCore.App', version '5.0.11' was not found.
    - The following frameworks were found:
        5.0.9 at [C:\hostedtoolcache\windows\dotnet\shared\Microsoft.NETCore.App]
  
  You can resolve the problem by installing the specified framework and/or SDK.
  
  The specified framework can be found at:
    - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.11&arch=x64&rid=win10-x64
##[error]C:\Users\VssAdministrator\.nuget\packages\microsoft.health.extensions.buildtimecodegenerator\3.2.38\build\netstandard2.0\Microsoft.Health.Extensions.BuildTimeCodeGenerator.targets(21,9): Error MSB3073: The command "dotnet "C:\Users\VssAdministrator\.nuget\packages\microsoft.health.extensions.buildtimecodegenerator\3.2.38\build\netstandard2.0\../../tools/net5.0/Microsoft.Health.Extensions.BuildTimeCodeGenerator.dll" --generator-name "ImmutableSqlModelGenerator" --output-file "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Model\ImmutableTypes.Generated.cs" --namespace "Microsoft.Health.Fhir.SqlServer.Features.Schema.Model" "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Migrations\6.sql" "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Migrations\7.sql" "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Migrations\13.sql" "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Migrations\17.sql" "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Migrations\21.sql"" exited with code -2147450730.
C:\Users\VssAdministrator\.nuget\packages\microsoft.health.extensions.buildtimecodegenerator\3.2.38\build\netstandard2.0\Microsoft.Health.Extensions.BuildTimeCodeGenerator.targets(21,9): error MSB3073: The command "dotnet "C:\Users\VssAdministrator\.nuget\packages\microsoft.health.extensions.buildtimecodegenerator\3.2.38\build\netstandard2.0\../../tools/net5.0/Microsoft.Health.Extensions.BuildTimeCodeGenerator.dll" --generator-name "ImmutableSqlModelGenerator" --output-file "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Model\ImmutableTypes.Generated.cs" --namespace "Microsoft.Health.Fhir.SqlServer.Features.Schema.Model" "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Migrations\6.sql" "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Migrations\7.sql" "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Migrations\13.sql" "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Migrations\17.sql" "D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Migrations\21.sql"" exited with code -2147450730. [D:\a\1\s\src\Microsoft.Health.Fhir.SqlServer\Microsoft.Health.Fhir.SqlServer.csproj]
```

Looks like `Microsoft.Health.Extensions.BuildTimeCodeGenerator` is looking for `5.0.11` but due to the downgrade of the SDK to `5.0.400` the build machine only has `5.0.9` available, hence the error:

<img width="1473" alt="image" src="https://user-images.githubusercontent.com/4580714/144245582-7e487ae8-fda0-41ec-9b86-0c7b97e6447f.png">

I had a look at the `.target` file in my `.nuget` cache folder and I didn't see anything there which explains this error to me. Would you be able to assist me with this issue? I know nothing about `Microsoft.Health.Extensions.BuildTimeCodeGenerator`, what it is, what it's meant to do and why it could possibly have a hard dependency on ASP.NET Core `5.0.11`.

Also perhaps someone could clean up the version mismatch in this solution?

**Comment by brendankowitz** [comment]
These should all be in sync, but possibly the `Directory.build.props` was updated with a dependabot PR.

The global.json should be in sync with the deployment template: https://github.com/microsoft/fhir-server/blob/main/samples/templates/default-azuredeploy.json#L336.
If you are deploying to AppService, I'd use the template to setup the environment first, Azure Pipelines should have an MS Deploy step to upload your build after this. 

The problem you are describing here is a reason we moved to docker images in our own build pipelines.
