### ISSUE TITLE
Change error codes for unsupported and invalid search parameters

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#24]
Proposal: 

Invalid search syntax:
/Observation?component-value-quantity=http://loinc.org|8480-6$lt107|http://unitsofmeasure.org|mm[Hg]$ (invalid trailing $) => 400 (current is 403)

Invalid search parameter name: /Observation?xyz=http://loinc.org|8480-6$lt107|http://unitsofmeasure.org|mm[Hg] => 400 (current is 200 with ignored parameter as reflected in self link)

/DiagnosticReport?subject.name=peter => 403 (which is the current behavior)

**Comment by CaitlinV39** [comment]
@brendankowitz Is this still an issue?

**Comment by brendankowitz** [comment]
@CaitlinV39, sounds similar to ab#73598

**Comment by CaitlinV39** [comment]
@feordin  I assigned this to you because it is similar to a user story assigned to you in S46

**Comment by CaitlinV39** [comment]
@feordin - I think we resolved this. Can you confirm?
