### ISSUE TITLE
Multitenant support in FHIR Api using Cosmos DB

### ISSUE THREAD

**Issue by shahedaAnsari** [microsoft/fhir-server#2402]
**Question**

We have multiple database and each database has multiple container, so how to achieve multitenancy in Open source.

**Comment by brendankowitz** [comment]
Can you give us a little more information on the scenario you are trying to solve? By design, FHIR Server for Azure has process and database isolation of Health data

**Comment by shahedaAnsari** [comment]
We want to connect to multiple databases 1 FHIR api. 

example - suppose  we have 

1. database1
- container1
- conatiner2
- container3
and so on.............

2. database2
- container1
- conatiner2
- container3
and so on.............

3. database3
- container1
- conatiner2
- container3
and so on...........

So can we connect to these database through single FHIR api and if yes can it is only setting that needs to be change or we need to modify FHIR api code. 

We want connect to database dynamically at run time based on request

**Comment by brendankowitz** [comment]
Currently the FHIR Server is not designed to do this. The [CosmosContainerProvider](https://github.com/microsoft/fhir-server/blob/main/src/Microsoft.Health.Fhir.CosmosDb/Features/Storage/CosmosContainerProvider.cs) might be the most obvious place to start, but the effects and testing would compound to every component that relies on the Container object

**Comment by brendankowitz** [comment]
Solutions requiring this type of setup have used Proxies such as [API Management](https://azure.microsoft.com/en-us/services/api-management/) to perform this top level routing
