### ISSUE TITLE
Migrate fhir data from sql to cosmos

### ISSUE THREAD

**Issue by AnsariShaheda** [microsoft/fhir-server#2410]
**Question**

how to migrate SQL FHIR data to cosmos FHIR?

**Comment by LTA-Thinking** [comment]
Hi @AnsariShaheda 
I would recommend using the system level Export operation to get NDJSON files of your resources. Once you have those you can use the [Bulk FHIR Loader](https://github.com/microsoft/fhir-loader) to ingest those files into a new server.
Here are the docs on [Bulk Export](https://github.com/microsoft/fhir-server/blob/main/docs/BulkExport.md)
The FHIR Loader has setup instructions in its repo.
I'm happy to answer any question on Export and @daemel can help with the FHIR Loader.
