### ISSUE TITLE
List of resource Types and Models

### ISSUE THREAD

**Issue by fasteddys** [microsoft/fhir-server#2415]
Hello where are the models and all the resourcetype for the payloads listed. I was not able to find any help or documentation around this.

**Comment by brendankowitz** [comment]
I'd recommend starting with the official documentation: https://www.hl7.org/fhir/resourcelist.html, example payloads are also provided in the downloads section: https://www.hl7.org/fhir/downloads.html
I would say our documentation supplements the official documentation with specific examples for Azure, i.e.  https://docs.microsoft.com/en-us/azure/healthcare-apis/using-rest-client

The community has good support with FHIR client libraries in most common languages.

**Comment by fasteddys** [comment]
@brendankowitz thanks for that it was helpful!

I am little lost, can you please guide me, a) is there a schema diagram for the Database or a SQL file to run to build the schema. b) I see the code gen / expansion sets, but was not able to find the help on customizing/expanding

**Comment by fasteddys** [comment]
Hello I was following the samples, but there is no way to save data from a resource query after I get a bundle package.

Can you please tell me where is the schema to CRUD the query results.

**Comment by fasteddys** [comment]
it looks like sql server is unable to handle the json data store from FHIR server based on your responses... 

I can try to switch over to postgres

**Comment by fasteddys** [comment]
@CaitlinV39 @brendankowitz  can you tell us how to model the resources in SQL server database..

**Comment by CaitlinV39** [comment]
@fasteddys this question is a bit out of scope for this project. I would recommend checking with the FHIR community or digging into some FHIR for developer tutorials. Gino from Microsoft has some great tutorials that he's put up: https://www.youtube.com/channel/UCwEwk15U0TXZWosH6Gq6THQ
