### ISSUE TITLE
How to deploy FHIR for Azure in Kubernetes

### ISSUE THREAD

**Issue by msmtctaiwan** [microsoft/fhir-server#2422]
After executing samples/kubernetes/deploy-aks.sh, two pod statuses remain CrassLoopBackOff

To reproduce:
1. clone this repo
2. cd samples/kubernetes/
(Since there are some bugs in the script, we modify to run the script)
3. modify line150 to "--kubernetes-version 1.21.7"
4. modify line 164 to "helm repo add stable https://charts.helm.sh/stable"
5. execute bash ./deploy-aks.sh --name <my-environment> --resource-group-name <my-rg-name> --location westus2
6. On Azure Portal, check the pod name and namespace of the pods that are still not deployed successfully
7. kubectl logs -f -n <namesapce> pod/<your pod name> --previous

Instead of using the provided script, how can I deploy FHIR server in kubernetes?
Is there any reference or documentation? 
Thanks.

**Comment by EXPEkesheth** [comment]
This is not an area we would be investing at this time and hence closing the item
