### ISSUE TITLE
All of a sudden, query results are split

### ISSUE THREAD

**Issue by mmacagno** [microsoft/fhir-server#2433]
**Question**

OSS FHIR Server with CosmosDB.

I have 52 PractitionerRole entries in the system.
Up to sometime today, a query to: GET /PractitionerRole?_count=100 
would return all records.

All of a sudden, I am getting only 26 items in the first _count=100 query, and the remainder 36 in the next query.

Corollary:
a query per specific practitioner:
GET /PractitionerRole?practitioner=Practitioner/04e5941e-114e-44d9-b1e2-791ba2dc230d 

returns an empty bundle (with next link), with the actual practitionerRole returned only on the next query.

Is any of this expected/possible to happen? On what conditions?
Thanks

**Comment by mmacagno** [comment]
This seems to be true for all entities with less than 100 records. Practitioner, Organization, etc. All with less than 100 records, and the results are split in multiple pages.

**Comment by CaitlinV39** [comment]
@mmacagno we have seen this behavior once your Cosmos DB database hits a specific size. We can do a bit more digging in the future, but its a leaking abstraction from Cosmos DB.

**Comment by mmacagno** [comment]
I guess that size is 50GB.
This basically doubles the throughput consumption of CosmosDB queries. My bill went up 2x just like that.

**Comment by brendankowitz** [comment]
50GB is the max size of a physical partition (https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview#physical-partitions). Currently the FHIR server will return if it finds at least 50% of the requested page size, this is likely fulfilled by the first partition

**Comment by CaitlinV39** [comment]
@mmacagno I'm going to close this for now but please let me know if there are additional questions.
