### ISSUE TITLE
SQL: Saving an Observation with multiple Quantity value components throws PrimaryKey violation error if quantity value is the same

### ISSUE THREAD

**Issue by almostchristian** [microsoft/fhir-server#2437]
**Describe the bug**
A primary key violation is thrown when inserting an Observation resource with multiple quantities when the quantity has the same value with differing unit codes in the SQL Server provider schema version 25.

**FHIR Version?**
R4

**Data provider?**
SQL Server

The offending search parameters are http://hl7.org/fhir/SearchParameter/Observation-component-value-quantity and http://hl7.org/fhir/SearchParameter/Observation-combo-value-quantity. Since I'm currently working with a fork of this repo, I just disabled these search parameters via code as mitigation, but I've been able to replicate this in a local build of microsoft fhir server with sql server schema version 25.

The observation looks something like below:
```json
{
  "resourceType": "Observation",
  "component": [
    {
      "code": {
        "coding": [
          {
            "system": "http://loinc.org",
            "code": "20564-1",
            "display": "Oxygen saturation in blood"
          }
        ],
      },
      "valueQuantity": {
        "value": 20,
        "unit": "%",
        "system": "http://unitsofmeasure.org",
        "code": "%"
      }
    },
    {
      "code": {
        "coding": [
          {
            "system": "http://loinc.org",
            "code": "8310-5",
            "display": "Body temperature"
          }
        ],
      },
      "valueQuantity": {
        "value": 20,
        "unit": "C",
        "system": "http://unitsofmeasure.org",
        "code": "Cel"
      }
    }
  ]
}
```

The exception does not happen if the value of the quantities are different, or if the unit codes are the same.

I was able to insert the same resource on a public fhir server
http://test.fhir.org/r4/Observation/b0ec10af-0e34-4ba8-b7ff-2f86cc56e3

**To Reproduce**
1.  Create an observation resource with the payload above.

**Expected behavior**
Save successfully

**Actual behavior**
```
Violation of PRIMARY KEY constraint 'PK_QuantitySearchParam'. Cannot insert duplicate key in object 'dbo.QuantitySearchParam'. The duplicate key value is (96, 952, 2.000000, 2.000000, 5102246811473040440).
```
![image](https://user-images.githubusercontent.com/2035340/149886185-711d9776-6083-40d5-9236-cb2db9042ef9.png)

**Comment by CraigP68** [comment]
AB#88454

**Comment by almostchristian** [comment]
The change #2466 has resolved this error

**Comment by CaitlinV39** [comment]
Great thanks!
