### ISSUE TITLE
Profile support for Australia

### ISSUE THREAD

**Issue by unruledboy** [microsoft/fhir-server#2477]
**Question**

Does FHIR Server support Australia profile?

**Description**

According to http://fhir.org/guides/registry/ , Australia has its own profile (R4 based http://build.fhir.org/ig/hl7au/au-fhir-base/ ). Firely supports importing specific profile into their system.

I was wondering if FHIR Server supports so?

**Comment by CaitlinV39** [comment]
We do support loading profiles and validating against them. You can read more about storing profiles here: https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/store-profiles-in-fhir
