### ISSUE TITLE
Support for Media and Attachments

### ISSUE THREAD

**Issue by dustinmoris** [microsoft/fhir-server#2492]
Hi, I have a very quick question.

Does this FHIR Server implementation support [media](https://www.hl7.org/fhir/media.html) and [attachment](https://www.hl7.org/fhir/datatypes.html#Attachment) types?

Many thanks!

**Comment by CaitlinV39** [comment]
@dustinmoris we have full support for all the resource types in STU3 and R4. Let us know if you have other questions
