### ISSUE TITLE
Hangs / stalls in Cosmos.Direct

### ISSUE THREAD

**Issue by klimkjar** [microsoft/fhir-server#2496]
**Describe the bug**

We are running MS fhir-server 2.2.82 scaled to two instances with a CosmosDB backend (direct connection mode). We are occasionally seeing hangs / stalls in one or both instances, sometimes resolving by themselves after 5-10 mins, other times triggering autoheal and application restart after 15 minutes.

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
1. Run fhir-server normally for a while
2. ???
3. incoming requests eventually start timing out, until fhir-server starts responding again or is restarted automatically by Azure auto-heal

**Expected behavior**
fhir-server does not stop responding unless requests are causing load beyond what the application is scaled to handle

**Actual behavior**

Once in every 3-14 days, we see hangs in fhir-server that do not seem to be tied to resource exhaustion. This happens with the most current version (2.2.82) as well as previous versions. We have not been able to identify any particular usage pattern before these hangs in our environment, and they happen even at times where memory, CPU, and CosmosDB RU usage are low (5-10%).

The last time this happened one instance kept running without issue, with response times around 25 ms, while the other instance timed out for simple GET requests (/Patient/{id}, /RelatedPerson/{id} etc). There were no particularly resource-consuming requests logged before this, and it responded normally to all the requests in the minutes leading up to the timeouts, typically within 10-50 ms. CPU percentage for the app service was around 10-15% and memory percentage around 25%.

Stack trace from Azure diagnostics:

```
This thread is calling Task.Result and synchronously waiting on a Task object. The caller function identified for the maximum number of threads is Microsoft.Azure.Documents.Rntbd.SystemUsageMonitor.RefreshLoopAsync.

HelperMethodFrame_1OBJ
System.Threading.ManualResetEventSlim.Wait
System.Threading.Tasks.Task.SpinThenBlockingWait
System.Threading.Tasks.Task.InternalWaitCore
System.Threading.Tasks.Task.Wait
Microsoft.Azure.Documents.Rntbd.SystemUsageMonitor.RefreshLoopAsync
Microsoft.Azure.Documents.Rntbd.SystemUsageMonitor.<Start>b__20_0
System.Threading.Tasks.Task.InnerInvoke
System.Threading.Tasks.Task+<>c.<.cctor>b__277_0
System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop
System.Threading.Tasks.Task.ExecuteWithThreadLocal
System.Threading.Tasks.Task.ExecuteEntryUnsafe
System.Threading.Tasks.Task.ExecuteFromThreadPool
System.Threading.ThreadPoolWorkQueue.Dispatch
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback
DebuggerU2MCatchHandlerFrame
```

**Comment by klimkjar** [comment]
Another hang just now, only 3 days after the previous one. Around 12 minutes of downtime, resolved by triggering manual restart of app service. Similar stack trace to the one above, in addition this one:

```
HelperMethodFrame
Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextMiddleware+<Invoke>d__2.MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextMiddleware+<Invoke>d__2, Microsoft.Health.Fhir.Api]]
Microsoft.Health.Fhir.Api.Features.Context.FhirRequestContextMiddleware.Invoke
Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke
Microsoft.Health.Api.Features.Headers.BaseHeadersMiddleware+<Invoke>d__2.MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Health.Api.Features.Headers.BaseHeadersMiddleware+<Invoke>d__2, Microsoft.Health.Api]]
Microsoft.Health.Api.Features.Headers.BaseHeadersMiddleware.Invoke
Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke
Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1+<ProcessRequestAsync>d__2[[System.__Canon, System.Private.CoreLib]].MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1+<ProcessRequestAsync>d__2[[System.__Canon, System.Private.CoreLib]], Microsoft.AspNetCore.Server.IIS]]
Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1[[System.__Canon, System.Private.CoreLib]].ProcessRequestAsync
Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext+<HandleRequest>d__180.MoveNext
System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext+<HandleRequest>d__180, Microsoft.AspNetCore.Server.IIS]]
Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.HandleRequest
Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Execute
System.Threading.ThreadPoolWorkQueue.Dispatch
DebuggerU2MCatchHandlerFrame
```

**Comment by CaitlinV39** [comment]
@klimkjar - We haven't seen this in our own managed service version and so can't reproduce to troubleshoot more. Did you have a previous version that didn't hang?

**Comment by klimkjar** [comment]
Hi @CaitlinV39  - we have had unexplained hangs since the start, partially mitigated by scheduling a weekly automatic restart. Our production instance has been running an older release and we attributed this as the most likely cause, however after upgrading the hangs persist - if anything they seem more frequent now. 

Here is a fresh example from yesterday (now running on 2.2.95):
![image](https://user-images.githubusercontent.com/11939107/156132752-dfc6e76c-baf8-4045-a121-bc364041b371.png)

**Comment by CaitlinV39** [comment]
@klimkjar Unfortunately what you're sending us doesn't get called from our code base so there isn't much we're going to be able to do to help troubleshoot this. I'm going to close for now as can't reproduce.

**Comment by klimkjar** [comment]
Hi Caitlin, revisiting this. The Cosmos provider seems to have been a red herring. We've been working with Microsoft Azure Support to help debug this with the help of some memory dumps captured while the stalls are occurring. As per their analysis,

> ...the problem seems to be a huge number of configuration elements that are cached by IIS configuration reader system. Once the cache size is exceeded and the configuration reader tries to reduce that size by getting rid of stalled configuration data, All HTTP request traffic execution within the application is blocked until the cache is cleaned.

This cleanup stalls all incoming requests, typically for 5-15 minutes. The configuration elements are from the `/RelatedPerson` and `/Patient` controllers, which are the resources we have the most traffic on.

Attaching the dump analysis as well.

[dump_analysis.txt](https://github.com/microsoft/fhir-server/files/8925391/dump_analysis.txt)
