### ISSUE TITLE
Guidance on creating composite parameters for supporting chaining on group of conditions.

### ISSUE THREAD

**Issue by Devereux-Henley** [microsoft/fhir-server#2501]
**Question**

How do we define custom composite search parameters, and can it solve the following use case?

**Description**

We are currently seeing an issue trying to find a way to query on groups of joined parameters in search. Normally this is handled by the `_filter` parameter in FHIR services, but per https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir/overview-of-search#common-search-parameters this is not currently supported. 

Expectation:
There is a way to group `address-use=home` and `address-postalcode=66226`, such that returned results have an address that is BOTH a home address and in postalcode 66226.

Reality:
The following query string `{{baseUrl}}/ServiceRequest?_include=ServiceRequest:patient&subject:Patient.address-use=home&subject:Patient.address-postalcode=66208` results in all service requests that have an address that has EITHER `address-use=home` OR `address-postalcode=66226`.

 While this is working as intended, we are looking for a way to achieve our expected behavior without `_filter`.
 
per https://hl7.org/FHIR/search.html#chaining - the other method for handling this is to define a composite search parameter - in this case one that involves narrowing on the `address` field for Patient.
 
 Is there an example of how we would define a composite search parameter for `address` on `Patient` that can be used in search chaining?

**Comment by brendankowitz** [comment]
This looks possible using a custom search parameter. Following the same format for composite such as below:

```json
{
    "resourceType" : "SearchParameter",
    "id" : "Patient-address-use-postcode",
    "extension" : [{
      "url" : "http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status",
      "valueCode" : "trial-use"
    }],
    "url" : "http://hl7.org/fhir/SearchParameter/Patient-address-use-postcode",
    "version" : "4.0.1",
    "name" : "address-use-postcode",
    "status" : "draft",
    "experimental" : false,
    "date" : "2019-11-01T09:29:23+11:00",
    "publisher" : "Health Level Seven International (Orders and Observations)",
    "contact" : [{
      "telecom" : [{
        "system" : "url",
        "value" : "http://hl7.org/fhir"
      }]
    },
    {
      "telecom" : [{
        "system" : "url",
        "value" : "http://www.hl7.org/Special/committees/orders/index.cfm"
      }]
    }],
    "description" : "Code and quantity value parameter pair",
    "code" : "address-use-postcode",
    "base" : ["Patient"],
    "type" : "composite",
    "expression" : "Patient",
    "xpathUsage" : "normal",
    "multipleOr" : false,
    "component" : [{
      "definition" : "http://hl7.org/fhir/SearchParameter/individual-address-use",
      "expression" : "address.use"
    },
    {
      "definition" : "http://hl7.org/fhir/SearchParameter/individual-address-postalcode",
      "expression" : "address.postalCode"
    }]
}
```

The caveat at the moment is that I see [SearchParameterOperations](https://github.com/microsoft/fhir-server/blob/ac69f9bee3d3625efcdd84e05b96185033d85e3e/src/Microsoft.Health.Fhir.Core/Features/Search/Parameters/SearchParameterOperations.cs) isn't resolving the composite components in Custom Search Parameters (so it will fail validation on create).

It worked when I tested with the following, I think we can get this change in to support this scenario.
```csharp
var searchParameterWrapper = new SearchParameterWrapper(searchParam);
var searchParameterInfo = new SearchParameterInfo(searchParameterWrapper);

if (searchParameterInfo.Component?.Any() == true)
{
    foreach (SearchParameterComponentInfo c in searchParameterInfo.Component)
    {
        c.ResolvedSearchParameter = _searchParameterDefinitionManager.GetSearchParameter(c.DefinitionUrl.OriginalString);
    }
}

(bool Supported, bool IsPartiallySupported) supportedResult = _searchParameterSupportResolver.IsSearchParameterSupported(searchParameterInfo);
```

Search queries would look like:
`GET https://{{hostname}}/Patient?address-use-postcode=home$74047`

**Comment by Devereux-Henley** [comment]
Awesome! Following question is about Azure Healthcare APIs - if this is the wrong place for those questions can direct this to Azure support.

This looks like the validation part of this would be blocking. Looks like versioned releases to the Azure Healthcare APIs service are rather infrequent (at least in visible versions in the portal). Would we need to move to an OSS deployment to accept this change? This, and a couple of other composite parameters are blockers for us.

**Comment by brendankowitz** [comment]
You could test in OSS first. We package every 2 weeks, managed deployments usually follow 2-3 weeks after

**Comment by Devereux-Henley** [comment]
Thank you so much! Will test in OSS when that merges!

**Comment by CraigP68** [comment]
AB#89147
