### ISSUE TITLE
Procedure cannot be found (FHIR search) intermittently (5 - 10m intervals) while writing to it

### ISSUE THREAD

**Issue by Dinand01** [microsoft/fhir-server#2566]
**Describe the bug**

We are using Azure API for FHIR, I assume this is based on this repo and uses CosmosDb as the underlying datastore, please correct me if I am mistaken. 

We have an ongoing procedure where we keep updating [extensions](https://www.hl7.org/fhir/extensibility.html), these extensions are used to optimize read performance of the application and contains things like the count of certain types of observations. This means that we need to update the procedure continuously while it is in progress (1 - 10 days), for this we have a queue with multiple workers (Azure function). We ensure no data is lost by applying a distributed lock through Azure Cache for Redis when updating the procedure (lock is scoped to a particular procedure).

In the mean time people (practitioners) can use the portal to view the ongoing procedure, the problem is that our query doesn’t return the ongoing procedure at random intervals. 
The result is that the ongoing procedure is intermittently not visible in the web portal (5 minutes visible,  5 minutes not, repeat). When we stop writing to the procedure via our functions the same search query always returns the procedure.

We use [Search](https://www.hl7.org/fhir/search.html) for querying the procedure and some related entities like the performer and the subject (we also have a filter on the subject).

I assume this has something to do with the consistency levels of cosmos db, the current behavior is to not return the data at all which is a problem for us, is there any way to work around this issue?

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
1. Write to the procedure record (continuous updates)
2. Use search to find the procedure by subject (different process)

**Expected behavior**
The procedure is always returned in the search result (data can be behind)

**Actual behavior**
The procedure is not returned for 5 - 10 minutes at the time, then it is returned for 5 - 10 minutes, then not, ....

[AB#93710](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/93710)

**Comment by brendankowitz** [comment]
Hi @Dinand01, if this is happening in Azure API for FHIR I’d recommend opening a support ticket so we can triage and inspect the telemetry to see what might be going on. 
When you mention not being returned, is it that there is an error/timeout or that the expected resource isn’t in the results?

**Comment by Dinand01** [comment]
Hi @brendankowitz , thank you for the reply.

The expected resource is not in the results, no error or timeout. 
We have no indication that writing fails, this is only happening for the search (getting the procedure via its id is no issue).

**Comment by EXPEkesheth** [comment]
Thanks for reporting the issue @Dinand01. Closing the issue, as it is resolved. Please feel free to reach out for any additional questions.
