### ISSUE TITLE
Dead link in the readme file

### ISSUE THREAD

**Issue by bmartell** [microsoft/fhir-server#2577]
**Describe the bug**
In the readme file, the link "https://microsoft.github.io/health-architectures/" gives a 404 error

**FHIR Version?**
Stu3/R4/R5

**To Reproduce**
1. go to https://github.com/microsoft/fhir-server 
2. search "Health Architectures" under the "Tutorials & How-to Guides" section
3. click

**Expected behavior**
visualization of the document

**Actual behavior**
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

**Comment by mikaelweave** [comment]
Thanks @bmartell. @LTA-Thinking, this site was removed as we are unifying our documentation locations with the rest of Azure.
