### ISSUE TITLE
error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.

### ISSUE THREAD

**Issue by mattkoch614** [Microsoft/fhir-server#262]
**Describe the bug**
After cloning this project locally, when building the ``Microsoft.Health.Fhir.Web`` project on a Mac using Visual Studio 2019 preview, I receive the following error:

``error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.``

**To Reproduce**
1. Clone Repo
2. Build
3. Error occurs

**Expected behavior**
No build errors occur.

**Actual behavior**
A build error occurs.

I'm not exactly sure what this error refers to.

**Comment by brendankowitz** [comment]
This is caused by the `Microsoft.SourceLink.GitHub` package, there are references to an open issue around: https://github.com/dotnet/sourcelink/issues/155
