### ISSUE TITLE
XML Output

### ISSUE THREAD

**Issue by HughGlover** [microsoft/fhir-server#2651]
Until about 10 days ago my FHIR Server could generate XML output, now it produces a 500 internal server error.  Jason output is generated as before.  This prevents one of our client apps from parsing the output.  Is this a bug or do I need to change a setting?

**Comment by brendankowitz** [comment]
Are there any more details about the error you can share? Was there a response message also?

**Comment by HughGlover** [comment]
I didn't realise my last comment wasn't formatted correctly - I've fixed it now.

This problem is a significant issue for our project since we have people starting to build content, but unable to view the content in a formatted way.  Any suggestions anyone?  Is it a server issue, or do I need to enable something on the server?  What has changed on the server recently that could do this.  I notice the AngleSharp component was upgraded - could it be to do with that?

**Comment by HughGlover** [comment]
Mystery solved - the server has been upgraded to R5 Snapshot 1 but contains resources that validate to R4.6.  The failure happens when there is a mismatch between the spec for the two releases
