### ISSUE TITLE
Json size is greater than 2 MB

### ISSUE THREAD

**Issue by shahedaAnsari** [microsoft/fhir-server#2652]
**Question**

we are using cosmos DB and its size limit is 2MB for one document.
what will happen if my data crosses the 2MB size?
can you please explain this in details

[AB#93709](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/93709)

**Comment by brendankowitz** [comment]
The FHIR Server will error with an Http 413, request entity too large. There is an E2E test case for this: 

https://github.com/microsoft/fhir-server/blob/befce04476d80f8a5d937fd9c42706fc40363ca9/test/Microsoft.Health.Fhir.Shared.Tests.E2E/Rest/CreateTests.cs#L81-L101

**Comment by shahedaAnsari** [comment]
Is FHIR Api handle json size which is greater than 2 MB OR we need to provide json which is less than 2 MB?
How to handle Json which has size greater than 2 MB?

**Comment by brendankowitz** [comment]
Hi @shahedaAnsari, when using the CosmosDB provider the per-item limit is 2mb. If you need to store items larger than 2mb then you should use the SQL Provider

**Comment by EXPEkesheth** [comment]
@shahedaAnsari - Closing the issue as the question is answered. Please feel free to contact us for any further assistance.
