### ISSUE TITLE
Understanding FhirPath Expression Support for Search Parameters

### ISSUE THREAD

**Issue by Devereux-Henley** [microsoft/fhir-server#2664]
**Question**

I would like to understand how much builtin fhirpath support there is for search parameters, especially composite search parameters.

**Description**
I have been referring to http://www.hl7.org/fhir/fhirpath.html to understand the functions available for fhirpath selection in search parameters.

One of the pieces I have been having trouble getting to work is using the `resolve()` function for searching on a reference in a composite parameter. I wanted to know if using the functions defined in the fhirpath specification is possible in composite search parameters.

The specific components I was trying to combine - 

```json
{
  "components": [
    { "definition": "http://hl7.org/fhir/SearchParameter/individual-address-state", "expression": "subject.resolve().address.state" },
    { "definition": "http://my-extension-url", "expression": "extension.where(url = 'http://my-extension-url').value" }
  ]
}
```

AB#101792

**Comment by brendankowitz** [comment]
Hi @Devereux-Henley, we've implanted a "lightweight" resolve function, take the example:

```
Account.subject.where(resolve() is Patient)
```

In this case the `resolve()` function will create a FHIR model from the data found in `subject`, when we're evaluating references its usually just `ResourceType` and `Id`. This is enough to satisfy the evaluation context and determine if the referenced `subject` is of type `Patient`.

**Comment by Devereux-Henley** [comment]
Is it possible for composite parameters to chain to a related resource? i.e. to access `subject.address.state`?

The larger problem I'm trying to solve is having a search that can union the following sets in one paged search:
`ServiceRequest where code value is A and subject.address.state is in some list`
`ServiceRequest where code value is B`

It seemed like composites were the right path to go down since `_query` and `_filter` aren't currently supported. Is there a feature that we could utilize to achieve this goal, or does this need to be handled in downstream application code?

**Comment by brianpos** [comment]
That's not a composite index, that's just regular chaining.
Even if the fhirpath resolve DID drill into the other resource, I wouldn't recommend using it in search parameters as that would be storing that value in the index, and if it subsequently changes in the referenced resource, the index would not be updated, however using regular chaining, that is fine.

**Comment by mchaabaoui** [comment]
c'est corrigé
"contact": [
    {
      "name": "monserviceclient.annuaire@esante.gouv.fr"
    }
  ],

**Comment by EXPEkesheth** [comment]
This can lead to inefficient performance, closing as we do not plan to implement.
Please feel free to reopen if you have questions/concerns
