### ISSUE TITLE
History returns items in the wrong order

### ISSUE THREAD

**Issue by rmeoc** [microsoft/fhir-server#2689]
**Describe the bug**
The versions returned when retrieving history are sorted from old to new, while they should be from new to old. See the following section of the FHIR Specification (from http://hl7.org/fhir/http.html#history):

> The return content is a [Bundle](http://hl7.org/fhir/bundle.html) with [type](http://hl7.org/fhir/bundle-definitions.html#Bundle.type) set to history containing the specified version history, sorted with oldest versions last, and including deleted resources.

**FHIR Version?**
Stu3

**Data provider?**
I don't know. I have encountered the bug with the Azure Health Data Services FHIR service. I don't know what Data provider is used by that service. 

**To Reproduce**
1.  Invoke the history interaction, e.g. `GET [base]/[type]/[id]/_history`

**Expected behavior**
A bundle is returned containing the version history sorted with oldest versions _last_.

**Actual behavior**
A bundle is returned containing the version history sorted with oldest versions _first_.

[AB#93193](https://microsofthealth.visualstudio.com/f8da5110-49b1-4e9f-9022-2f58b6124ff9/_workitems/edit/93193)

**Comment by EXPEkesheth** [comment]
@rmeoc Thanks for reporting the issue. The issue is fixed.
Reach out for any additional questions.
