### ISSUE TITLE
Audience interpreted as string instead of URI

### ISSUE THREAD

**Issue by hansenms** [Microsoft/fhir-server#269]
**Describe the bug**
Audience is interpreted as a string not an URI. If `FhirServer:Security:Authentication:Audience = https://fhir-server/` and a token is presented with `aud=https://fhir-server`, the token is rejected. AAD interprets the SPN/IdentifierUri as a URI and will grant a token with either `aud=https://fhir-server` or `aud=https//fhir-server/`

**To Reproduce**
1. Deploy server with trailing slash in Audience
2. Request a token without slash
3. Search Patient

**Expected behavior**
`aud=https://fhir-server` or `aud=https://fhir-server/` should be equivalent

**Actual behavior**
`aud=https://fhir-server` or `aud=https://fhir-server/` are effectively different audiences.

**Comment by brandonpollett** [comment]
This is per the spec found here: https://tools.ietf.org/html/rfc7519#section-4.1.3

The applicable portion is: `In the general case, the "aud" value is an array of case-
   sensitive strings, each containing a StringOrURI value.`

The code that actually does the validation is found: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/Validators.cs

We could address this by either allowing the configuration to have multiple audiences or we could attempt to guess what the other valid audiences are. I would rather do the former than the latter.

**Comment by hansenms** [comment]
Closing. Opened #271 and #272 to address.
