### ISSUE TITLE
How to create a custom resource ?

### ISSUE THREAD

**Issue by mohrmz** [microsoft/fhir-server#2791]
Is it possible to add custom resources outside of the known resources in FHIR? Or is there a way to add custom fields to resources that don't exist in the resource without using an extension?

AB#95081

**Comment by feordin** [comment]
The answer to both questions is no.  The FHIR server only accepts the known resource types, and to add a new field, you must add it as an extension.

**Comment by EXPEkesheth** [comment]
@mohrmz - Closing the issue as question is answered. Please let us know if you have any additional questions. Thanks !
