### ISSUE TITLE
How to load conformance resources?

### ISSUE THREAD

**Issue by vadi2** [microsoft/fhir-server#2793]
**Question**

I'm creating a FHIR IG with a whole set of conformance resources - how can implementers using this FHIR server load all of them easily?

Other FHIR servers support loading in a FHIR package, but I haven't found support for that in documentation.

AB#95116

**Comment by brendankowitz** [comment]
Hi @vadi2, I don't have a good answer for this right now, but it is on the radar. 

@mikaelweave, @EXPEkesheth - I think we should leave this ticket open for tracking.

**Comment by LandonReilly** [comment]
Hi, we are looking to load the Australian Base Implementation Guide http://hl7.org.au/fhir/4.0.0/downloads.html into the Microsoft FHIR server. 

As per Vadims question, is there currently a way to load these resources into the Micrsoft Fhir Server.

Thank you.

**Comment by EXPEkesheth** [comment]
@LandonReilly  and @vadi2 to load Australian Base IG into Microsoft FHIR server, please go to simplifier.net or npm (you can replace uscore here with the package name
npm --registry https://packages.simplifier.net/ install [hl7.fhir.us.core@3.1.1](mailto:hl7.fhir.us.core@3.1.1)
) to download the package for the Australian base IG, then follow the remaining steps in that tutorial. [fhir-loader/uscore_README.md at fhir-loader-cli · microsoft/fhir-loader (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Ffhir-loader%2Fblob%2Ffhir-loader-cli%2Fsrc%2FFhirLoader.Tool%2Fuscore_README.md&data=05%7C01%7CKetki.Sheth%40microsoft.com%7C32153f90fa004979dbbc08db1c3e9d91%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638134827481223177%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xNqzDS0FIO8RZ%2BgqnK4v%2BCzFKWp5dLEg5e%2BiAFCkUso%3D&reserved=0)

@vadi2 - this tool support loading profile into form of package , into FHIR server

Let us know if you have any questions,
