### ISSUE TITLE
Expose Admin/Control Plane API

### ISSUE THREAD

**Issue by brandonpollett** [Microsoft/fhir-server#280]
**User story**
As an admin, I want to manage control plane information through an API so that it can be done at runtime.

As a guideline for implementation refer to: https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md

Versioning should be able to be accomplished via https://github.com/Microsoft/aspnet-api-versioning

**Acceptance criteria**
- [ ] Authorization on control plane is enforced
- [ ] APIs for exposing CRUD on Identity Provider, Roles, and Role Membership are available
- [ ] Results of API calls are enforced
- [ ] Appropriate logging is in place

**Comment by garamamo** [comment]
This user story is broken down into the below smaller user stories.

https://app.zenhub.com/workspaces/fhir-server-5bc977684b5806bc2bedca39/issues/microsoft/fhir-server/321
https://app.zenhub.com/workspaces/fhir-server-5bc977684b5806bc2bedca39/issues/microsoft/fhir-server/322
https://app.zenhub.com/workspaces/fhir-server-5bc977684b5806bc2bedca39/issues/microsoft/fhir-server/323
https://app.zenhub.com/workspaces/fhir-server-5bc977684b5806bc2bedca39/issues/microsoft/fhir-server/324

**Comment by cunninghamjc** [comment]
Moving work item tracking to Azure DevOps.
