### ISSUE TITLE
Not able to search with newly created extension

### ISSUE THREAD

**Issue by nehaghub** [microsoft/fhir-server#2804]
Hi Team,

I am new to FHIR. I just updated my FHIR data with the below extension,
extension: [
    {
      url: 'http://example.com/fhir/StructureDefinition/MY_TEST',
      valueString: 'TEST.2022-09-14T10:09:47.724Z.1952-01-01T00:00:00.000+05:30_2021-01-01T00:00:00.000+05:30'
    }
  ]
Now, I want to find out number of patients updated with this extension.

I am not able to find the solution for the same. Please help me regarding this issue.

Thanks!
Neha

AB#95491

**Comment by EXPEkesheth** [comment]
Thanks @nehaghub - After you add a search parameter, you will need to add /update patients with parameter specific data and perform search. Documentation here provides details on custom search parameters: https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/how-to-do-custom-search 

Hope this helps. Thanks!
