### ISSUE TITLE
Store role membership in datastore

### ISSUE THREAD

**Issue by brandonpollett** [Microsoft/fhir-server#281]
**User story**
As an admin, I want to persist role membership so that user access and be managed at runtime.

**Acceptance criteria**
- [ ] Role membership information is pulled from datastore
- [ ] Service accepts new role membership
- [ ] Service allows you to update role membership
- [ ] Service allows you to remove role membership
- [ ] Appropriate logging is in place

**Comment by cunninghamjc** [comment]
Moving work item tracking to Azure DevOps.
