### ISSUE TITLE
Metadata Operations should have correct canonical Urls

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#2810]
**Describe the bug**

In /metadata the Validate endpoint has the url of: `https://www.hl7.org/fhir/operation-resource-validate.html`,
but should have `http://hl7.org/fhir/OperationDefinition/Resource-validate` as is listed as the canonical url on the spec's website.

**FHIR Version?**
Stu3/R4/R5

AB#95637

**Comment by EXPEkesheth** [comment]
@brendankowitz and @brianpos - Closing the issue as addressed with latest OSS release.
