### ISSUE TITLE
Seeking to understand caching

### ISSUE THREAD

**Issue by akatakritos** [microsoft/fhir-server#2819]
**Question**

I'm trying to understand what caching might be in place from the FHIR Server. We see most searches that take 4-6 seconds, but then when the same parameters are sent again, it comes back under 300ms. 

Is that because the URL's exactly match and the FHIR API is leveraging something like `[OutputCache]`? It does seem that the order in which the parameters are included in the query string influence cache hit or cache miss. If its using something like [OutputCache] -- i'm curious what the cache eviction strategy is?

My ultimate goal is mostly to understand whats going on and see if theres anything we can do on our app side to reduce that initial search time.

**Description**
If you cannot find the answer at one of the sites above, please provide a detailed description of your question.

AB#95715

**Comment by akatakritos** [comment]
Think it might be due to this code:

```cs
  if (Parameters.HasParametersToHash)
            {
                // Add a hash of (most of the) parameter values as a comment.
                // We do this to avoid re-using query plans unless two queries have
                // the same parameter values. We currently exclude from the hash parameters
                // that are related to TOP clauses or continuation tokens.
                // We can exclude more in the future.

                StringBuilder.Append("/* HASH ");
                Parameters.AppendHash(StringBuilder);
                StringBuilder.AppendLine(" */");
            }
```

When the search parameters are the same, SQL Server can reuse the query plan, which is apparently expensive to calculate?

I added a Stopwatch to SqlServerSearchService and found this:

![image](https://user-images.githubusercontent.com/3689068/191803972-472582d8-2eb7-479a-95ca-0853827aa01e.png)



```
Looping over results done 4065
info: Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService[0]
      SQL message: Table 'Worktable'. Scan count 0, logical reads 0, physical reads 0, page server reads 0, read-ahead reads 0, page server read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob page server reads 0, lob read-ahead reads 0, lob page server read-ahead reads 0.
info: Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService[0]
      SQL message: Table 'ReferenceSearchParam'. Scan count 3, logical reads 0, physical reads 0, page server reads 0, read-ahead reads 0, page server read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob page server reads 0, lob read-ahead reads 0, lob page server read-ahead reads 0.
info: Microsoft.Health.Fhir.SqlServer.Features.Search.SqlServerSearchService[0]
      SQL message: 
       SQL Server Execution Times:
         CPU time = 11 ms,  elapsed time = 10 ms.
```

On subsequent search, I get log `Looping over results done 13`

**Comment by EXPEkesheth** [comment]
@akatakritos Thanks for reporting the issue, we will look into this and get back.

**Comment by feordin** [comment]
We have recently made two different changes to the SQL query generation specifically designed to avoid long query plan generation times, and having SQL choose a poor query plan.

First is the addition of a hint to SQL when we are using certain search parameters, which we have seen avoids certain instances when SQL chooses a poor plan, and spends a long time generating the plan.

The second change looks at the complexity of the query, and alters the SQL code based on that, or if SQL throws an exception related to query plan generation.

We are hopeful that these changes resolve this issue.
