### ISSUE TITLE
Azure FHIR guidelines to build

### ISSUE THREAD

**Issue by mclacore** [microsoft/fhir-server#2821]
**Question**

We always appreciate your feedback, but we ask that before posting your question, please check to see if we already have the information you need:

* Is your question answered in our documentation? - https://docs.microsoft.com/azure/healthcare-apis/

* Our team also monitors the FHIR Community chat @ http://chat.fhir.org

**Description**
If you cannot find the answer at one of the sites above, please provide a detailed description of your question.

I'm an engineer for a PaaS company that builds out cloud infrastructure templates for companies to easily deploy cloud resources without being an expert in the cloud (think smaller companies with limited resources). I'm currently working on building out a template for Azure FHIR service (and Azure Healthcare Workspaces). Not being an expert in FHIR, or ever used it, I'm trying to figure out the best way to approach this problem. Maybe it's clear to experts/daily users of FHIR in Azure:

I've noticed that Azure Healthcare Workspaces has 3 services available: FHIR, DICOM, and MedTech. Is it required to have a single workspace with multiple FHIR services, and maybe paired with a DICOM service or MedTech service? Or would it be acceptable to have a single Azure Healthcare Workspace for each instance of FHIR, DICOM, etc.?

Also, are there any required add-on resources for FHIR? Thinking in terms of Azure Container Registry, Azure Data Lake Storage, Storage Accounts, or monitoring using diagnostic settings? Any of those listed services considered optional as opposed to required? 

AB#95716

**Comment by EXPEkesheth** [comment]
Thanks for reaching out @mclacore 
Here is the link to documentation for Azure Health Data Services: https://learn.microsoft.com/en-us/azure/healthcare-apis/healthcare-apis-overview that should help answer your question. 
Depending on your scenarios, Azure resources will be needed. Above documentation will help with the same.

**Comment by EXPEkesheth** [comment]
Documentation shared, closing the issue. Please feel free to reach out with any questions that are not answered in the documentation.
