### ISSUE TITLE
Less than N resources returned in paged dataset when searching with _count=N

### ISSUE THREAD

**Issue by moloneyd-draeger** [microsoft/fhir-server#2827]
**Describe the bug**
When performing certain queries with `_count=1000` and more than 1000 records matching the search criteria, less than 1000 records are returned. 

- The number of records returned per page is variable, but is generally between 900 and 1000 records.
- When paging over the dataset, the full set of records is returned. Records are not being dropped or excluded - this bug is not critical, just annoying :)

We would like to understand (and report) this behaviour, as this does not match our expectations.

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**To Reproduce**
(this example uses `Procedure` and `Observation` resources, but this has been observed with other searches as well)

1. Load several hundred [`Procedure`](https://www.hl7.org/fhir/procedure.html) resources into the FHIR database. In the below example from one of our test datasets, `len(procedures)=552`.
2. For each procedure resource, load several [`Observation`](https://www.hl7.org/fhir/observation.html) resources. In this example, the reference is held in the [`.partOf`](https://www.hl7.org/fhir/observation-definitions.html#Observation.partOf) element. In our example, `len(observations)=41071`. 
3. Search for all observations, with `_count=1000` and `part-of=<procedure_ids>` (join all the Procedure id elements with the `,` (OR) search separator). NB: The `POST /Observation/_search` endpoint must be used as a GET URL would be too long.
4. Check the number of returned resources. We regularly see less than 1000 resources. (If 1000, page through the dataset and check the contents of all response Bundles). 

**Expected behavior**
If >=N resources exist on the server that satisfy a query with `_count=N`, we expect N resources to be returned in each page of a paged dataset.

**Actual behavior**
Less than 1000 resources are regularly seen. Here is a (sanitised) python script with the output from the example above. The internal FhirServerConnection class isn't doing anything "clever" with FHIR here - it is a wrapper for auth, paging, proxy and retrying http requests. If required I can remove it and provide an alternative script.... but it's a little useless without this source data anyway!

```python
# open-source libraries
import requests
from fhir.resources.bundle import Bundle
from fhir.resources.encounter import Encounter
from fhir.resources.observation import Observation
from fhir.resources.procedure import Procedure

# utility classes used internally
# I have added a debug statement in FhirServerConnection to log the number of returned resources per query, see output
from fhir_connector.fhir_server_connection import FhirServerConnection
from fhir_connector.auth_providers import AccessKeyAuthProvider

FHIR_API_BASE_URL = "censored"
ACCESS_KEY = "censored"
FHIR_SERVER_PROXIES = {}  # censored

fhir_server_connection = FhirServerConnection(
    fhir_server_address=FHIR_API_BASE_URL,
    fhir_server_auth_provider=AccessKeyAuthProvider(access_key=ACCESS_KEY),  # handles auth, please ignore :)
    user_agent="foo/1.2.3",
    fhir_server_proxies=FHIR_SERVER_PROXIES
)

###########
# Data model for this example
# 
# Encounter
#   └─ 1:1 ─ Procedure
#              └─ 1:0..N ─ Observation
###########

###########
# examples using our library, see output below
encounters = fhir_server_connection.get_resources(
    resource_type=Encounter.get_resource_type(),
    search_parameters={}  # get me everything!
)
print(f"{len(encounters)=}")  # 552 encounters found

procedures = fhir_server_connection.get_resources(
    resource_type=Procedure.get_resource_type(),
    search_parameters={
        "encounter": ','.join([encounter.id for encounter in encounters])
    },
    http_method="POST"  # required due to query length (exceeds URL length limit)
)
print(f"{len(procedures)=}") # 552 procedures found (expected behaviour)

observations = fhir_server_connection.get_resources(
    resource_type=Observation.get_resource_type(),
    search_parameters={
        "part-of": ','.join([procedure.id for procedure in procedures])
    },
    http_method="POST"  # required due to query length (exceeds URL length limit)
)
print(f"{len(observations)=}")  # 41071 Observations found 

###########
# example using requests library
observation_search_response = requests.post(
    f"{FHIR_API_BASE_URL}/Observation/_search",
    headers={"Authorization": f"Access-Key {ACCESS_KEY}"},
    data={
        "_count": 1000,
        "part-of": ','.join([procedure.id for procedure in procedures])
    },
    proxies=FHIR_SERVER_PROXIES
)

observation_bundle = Bundle.parse_raw(observation_search_response.text)
print(f"{len(observation_bundle.entry)=}")  # almost always less than 1000
```

```
Search bundle contains 552 resources!
len(encounters)=552
Search bundle contains 552 resources!
len(procedures)=552
Search bundle contains 976 resources!
Search bundle contains 995 resources!
Search bundle contains 950 resources!
Search bundle contains 999 resources!
Search bundle contains 985 resources!
Search bundle contains 989 resources!
Search bundle contains 929 resources!
Search bundle contains 941 resources!
Search bundle contains 950 resources!
Search bundle contains 961 resources!
Search bundle contains 937 resources!
Search bundle contains 936 resources!
Search bundle contains 939 resources!
Search bundle contains 964 resources!
Search bundle contains 965 resources!
Search bundle contains 933 resources!
Search bundle contains 959 resources!
Search bundle contains 947 resources!
Search bundle contains 933 resources!
Search bundle contains 937 resources!
Search bundle contains 972 resources!
Search bundle contains 932 resources!
Search bundle contains 968 resources!
Search bundle contains 947 resources!
Search bundle contains 956 resources!
Search bundle contains 951 resources!
Search bundle contains 947 resources!
Search bundle contains 951 resources!
Search bundle contains 965 resources!
Search bundle contains 955 resources!
Search bundle contains 948 resources!
Search bundle contains 952 resources!
Search bundle contains 947 resources!
Search bundle contains 935 resources!
Search bundle contains 931 resources!
Search bundle contains 978 resources!
Search bundle contains 978 resources!
Search bundle contains 921 resources!
Search bundle contains 936 resources!
Search bundle contains 921 resources!
Search bundle contains 953 resources!
Search bundle contains 919 resources!
Search bundle contains 936 resources!
Search bundle contains 147 resources!
len(observations)=41071
len(observation_bundle.entry)=962
``` 

AB#95813

**Comment by brendankowitz** [comment]
Hi @moloneyd-draeger, this behavior is expected in when Cosmos starts using more than one physical partition. Once this happens we start getting results from each individual partition, so there is no longer a guarantee of exactly 1000 (unless a single partition returned this, or add up to this coincidentally when aggregating from multiple). 

The behavior we have in place (for Cosmos) is to attempt to return no less than 0.5 * _count and no more than _count. The FHIR Spec is more worded around servers never returning more than the limit so we've added strategies with the sequential and fan-out queries to ensure this.

**Comment by EXPEkesheth** [comment]
Closing the issue, as question is answered above. 
Please let us know if you have additional questions
