### ISSUE TITLE
member-match returns 422 No Matches when there is too much data

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#2831]
**Describe the bug**
When a member match operation is run and there is too much data returned by the reverse chained query it uses to find Patients the result returned to the user is a 422 No Matches found.
This is caused because in MemberMatchService on line 89 we are only looking for Results, not Issues, so we are missing this error. When this issue is hit no results are returned, so it looked like the No Match case for member match.

**FHIR Version?**
Stu3/R4/R5

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. Have a database where more than 1000 results will be returned for the reverse chained query used by member match
2. Send a member match request

**Expected behavior**
An error message stating that too many results were found.

**Actual behavior**
A 422 that says no matches were found.

AB#95860

**Comment by EXPEkesheth** [comment]
Issue is fixed. Thanks @LTA-Thinking .
