### ISSUE TITLE
Why do bundles with entries not have "total" node?

### ISSUE THREAD

**Issue by sayomakinwa** [microsoft/fhir-server#2837]
**Describe the bug**
Fhir bundles generated by this fhir server do not have "total" property on the json.

Here's an example gotten from /Patient endpoint on the server
![image](https://user-images.githubusercontent.com/15688168/193039384-67c2ec91-1ebd-4c43-8bb9-af004c8e0239.png)

AB#95959

**Comment by brendankowitz** [comment]
Hi @sayomakinwa, since calculating the total is more work we've left this as optional. To get the total you can include `_total=accurate` in the querystring

**Comment by EXPEkesheth** [comment]
Closing with question answered above,
