### ISSUE TITLE
Bootstrap RBAC Info into control plane

### ISSUE THREAD

**Issue by brandonpollett** [Microsoft/fhir-server#295]
**User story**
As an admin, I want to be able to bootstrap my RBAC configuration so that on initial load I can manage my service.

**Acceptance criteria**
- [ ] Configuration has a section for entering initial bootstrap of RBAC configuration
- [ ] Identity provider, role, and role membership can be bootstrapped
- [ ] Bootstrapping only occurs once
- [ ] Changes to the bootstrap configuration is not persisted to the datastore

**Comment by cunninghamjc** [comment]
Moving work item tracking to Azure DevOps.
