### ISSUE TITLE
Migration of fhir data from one cosmodb container to another cosmodb container 

### ISSUE THREAD

**Issue by Sameer2810** [microsoft/fhir-server#2957]
I have cosmoDB container in which I have fhir records now I want to migrate that data to another cosmoDB container which is in different database. In that migration process I don't want to change _lastUpdated field. Is there any way I can achieve that.

AB#98440

**Comment by EXPEkesheth** [comment]
Thanks for raising the question @Sameer2810 .Today, there is no solution available on migrating without updating _lastUpdated field. We will add this item in our backlog.

**Comment by EXPEkesheth** [comment]
This question is duplicate of previous question https://github.com/microsoft/fhir-server/issues/2450 and hence closing the issue
