### ISSUE TITLE
UpsertResourceHandler does not resolve resource references

### ISSUE THREAD

**Issue by ArnautS** [microsoft/fhir-server#2970]
In the class CreateResourceHandler, the following line is executed to resolve resource references:

`await _referenceResolver.ResolveReferencesAsync(resource, _referenceIdDictionary, resource.TypeName, cancellationToken);`

In the class UpsertResourceHandler, this line is missing. Is there a specific reason to not resolve resource references here, or simply an oversight?

Fhir version: all (Microsoft.Health.Fhir.Share.Core)

To reproduce: 
PUT baseurl/Patient/{id}

body includes: 
```
"generalPractitioner": [
    {
    "reference": "Organization?identifier=http://fhir.nl/fhir/NamingSystem/agb-z|{agb_code}"
    }
],
```

Expected result: general practitioner is updated

Current result: general practitoner is not updated

**Comment by brendankowitz** [comment]
Thanks @ArnautS. I think most of this was added for bundle processing then refactored a few times, this is probably just an oversight.

**Comment by EXPEkesheth** [comment]
@ArnautS the issue is fixed. Thanks for your patience, as we worked on the issue . 
Please reach out for any questions/ comments
