### ISSUE TITLE
Error while parsing XHTML in the narrative

### ISSUE THREAD

**Issue by alesyasheremet** [microsoft/fhir-server#2979]
**Describe the bug**
The FHIR resource narrative does not allow to have self-closed html elements. 

**FHIR Version?**
Stu3

**Data provider?**
CosmosDB/SQL Server

**To Reproduce**
1. Make a POST request to the FHIR server to save a resource with a narrative that contains self-closed div tag `<div />`.

`
{
    	"resourceType": "Encounter",
				"meta": {
					"profile": [
						"http://nictiz.nl/fhir/StructureDefinition/gp-Encounter"
					]
				},
				"text": {
					"status": "extensions",
					"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table><caption>Contact. Subject: Anoniem. Id: 25729fcb-a56f-4b17-9634-3f610a0c11cd (urn:oid:2.16.840.1.113883.2.4.3.118.2.4), Status: voltooid</caption><tbody><tr><th>Type contact</th><td><div /><span title=\"Onbekend (UNK - nhg-tabel-14-contactwijze)\">Onbekend</span></td></tr><tr><th>Periode</th><td>03:49:00, 16 december 2020 - 16 december 2020</td></tr><tr><th>Participant</th><td><div><span title=\"Performer (PRF - v3/ParticipationType)\">Performer</span> - W.K. DRS TEST</div></td></tr></tbody></table></div>"
				},
				"identifier": [
					{
						"system": "urn:oid:2.16.840.1.113883.2.4.3.118.2.4",
						"value": "25729fcb-a56f-4b17-9634-3f610a0c11cd"
					}
				],
				"status": "finished",
				"class": {
					"extension": [
						{
							"url": "http://nictiz.nl/fhir/StructureDefinition/code-specification",
							"valueCodeableConcept": {
								"coding": [
									{
										"system": "https://referentiemodel.nhg.org/tabellen/nhg-tabel-14-contactwijze",
										"code": "UNK",
										"display": "Onbekend"
									}
								]
							}
						},
						{
							"url": "http://hl7.org/fhir/StructureDefinition/iso21090-nullFlavor",
							"valueCode": "OTH"
						}
					]
				},
				"type": [
					{
						"coding": [
							{
								"system": "https://referentiemodel.nhg.org/tabellen/nhg-tabel-14-contactwijze",
								"code": "UNK",
								"display": "Onbekend"
							}
						]
					}
				],
				"subject": {
					"reference": "urn:uuid:afc94aad-6994-11ed-1592-005056bc2505",
					"display": "Anoniem"
				},
				"episodeOfCare": [
					{
						"identifier": {
							"system": "urn:oid:2.16.840.1.113883.2.4.3.118.2.9",
							"value": "f0112257-a2aa-47bb-8489-57b135192c5c"
						},
						"display": "Episode: f0112257-a2aa-47bb-8489-57b135192c5c 2.16.840.1.113883.2.4.3.118.2.9"
					}
				],
				"participant": [
					{
						"type": [
							{
								"coding": [
									{
										"system": "http://hl7.org/fhir/v3/ParticipationType",
										"code": "PRF",
										"display": "Performer"
									}
								]
							}
						],
						"individual": {
							"extension": [
								{
									"url": "http://nictiz.nl/fhir/StructureDefinition/practitionerrole-reference",
									"valueReference": {
										"reference": "urn:uuid:afc945de-6994-11ed-1592-005056bc2505",
										"display": "W.K. DRS TEST GP"
									}
								}
							],
							"reference": "https://test.nl/1.5.0/fhir/stu3/Practitioner/2.16.840.1.113883.2.4.6.1-01020467",
							"display": "W.K. DRS TEST"
						}
					}
				],
				"period": {
					"start": "2020-12-16T03:49:00+01:00",
					"end": "2020-12-16"
				}
}
`

2. FHIR server returns HTTP status code 400 with the error message  

`Error while parsing XHTML: The given end tag does not match the current node. Line: 1 Col: 332.`

**Expected behavior**
No error message should be returned, the resource can be saved in the FHIR store. In XHTML, any tag can be self-closed by the ending slash <… />.

**Actual behavior**
OperationOutcome is returned

`{
    "resourceType": "OperationOutcome",
    "id": "36279759-7d80-4465-8991-406885ef456b",
    "meta": {
        "lastUpdated": "2022-11-22T10:11:49.5396862+00:00"
    },
    "issue": [
        {
            "severity": "error",
            "code": "structure",
            "diagnostics": "Error while parsing XHTML: The given end tag does not match the current node. Line: 1 Col: 332.",
            "location": [
                "Encounter.text.div // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"
            ],
            "expression": [
                "Encounter.text.div"
            ]
        }
    ]
}`

**Comment by michael-wilson-au** [comment]
My understanding is this may not be a bug as <div> is not declared as an EMPTY element in the XHTML DTD https://www.w3.org/TR/xhtml1/dtds.html

In XHTML for non-empty elements, end tags are required. 
XML does not allow end tags to be omitted. All elements other than those declared in the DTD as EMPTY must have an end tag. Elements that are declared in the DTD as EMPTY can have an end tag or can use empty element shorthand
https://www.w3.org/TR/xhtml1/diffs.html#h-4.3
