### ISSUE TITLE
The "_pretty" parameter is ignored for the read operation

### ISSUE THREAD

**Issue by sghino** [microsoft/fhir-server#3010]
**Describe the bug**
The response of a read operation like /Patient/patent-example?_pretty=true is not properly printed.

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
1. Create a Patient with the id patent-example
Ex: PUT /Patient/patent-example
2. Read the patient with the id patent-example adding the query parameter _pretty=true
Ex GET /Patient/patent-example?_pretty=true

**Expected behavior**
The Expected response should be pretty printed 

**Actual behavior**
The actual response is printed in a single line

**Other information**
the pretty print works fine with search like /Patient?_id=patent-example&_pretty=true and also for the OperationOutcome (for example if you try to read an inexistent resource like /Patient/inexistent-example?_pretty=true)

AB#101528

**Comment by brendankowitz** [comment]
Looks like a good up for grabs :) Output formatter is missing the check for `pretty` on single resources

https://github.com/microsoft/fhir-server/blob/cefd094c683316969809b0f4e599b15a8d485e16/src/Microsoft.Health.Fhir.Shared.Api/Features/Formatters/FhirJsonOutputFormatter.cs#L117-L127

**Comment by EXPEkesheth** [comment]
Closing as change is merged 
@idrisfl - thankyou for fixing the issue !
