### ISSUE TITLE
Does the Open-Source version of FHIR-Server supports Managed Identity?

### ISSUE THREAD

**Issue by jmarti326** [microsoft/fhir-server#3026]
**Question**

Does this version of FHIR support managed identity or only client id and secret?

**Comment by EXPEkesheth** [comment]
@jmarti326 Yes, please refer to the documentation associated with same https://github.com/Microsoft/fhir-server/blob/main/docs/DefaultDeployment.md. Please feel free to reach out to us for any further questions,

**Comment by EXPEkesheth** [comment]
@jmarti326 Closing the issue as the question is answered. Please feel free to reopen if you need additional information. Thanks !
