### ISSUE TITLE
Support for R4 and R5 both

### ISSUE THREAD

**Issue by shahedaAnsari** [microsoft/fhir-server#3033]
**Question**

Is it possible Open Source of Fhir api support both R4 and R5? If yes then what changes needs to be done?

**Description**
Currently we are using the open source R4 Fhir Api 
Database is cosmos DB

**Comment by LTA-Thinking** [comment]
Hi @shahedaAnsari 
It is not possible to have a FHIR server that support multiple versions of the FHIR standard. Because of differences between the versions of FHIR servers are setup to only support one version.

**Comment by EXPEkesheth** [comment]
Closing the git issue, with answered question.
