### ISSUE TITLE
_format=html and _format=html/json are not supported in Search

### ISSUE THREAD

**Issue by Efreeto** [microsoft/fhir-server#304]
**Describe the bug**
_format=html and _format=html/json are not supported in Search

**To Reproduce**
1. Create and run a working query from a web browser. For example, http://xyz.com/Patient/123
2. Put "?_format=html" at the end and run it again.

**Expected behavior**
Browser shows a nice formatted json, as in a https://r3.smarthealthit.org/Patient/smart-897185?_format=html/json

**Actual behavior**
An error is shown with "The requested "_format" parameter is not supported."

**Comment by brendankowitz** [comment]
`?_format=html` should work if you change `"SupportsUI": true` in https://github.com/Microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.Web/appsettings.json.

The UI needs some improvement, which is why it's currently off by default.

**Comment by Efreeto** [comment]
Thank you for the comment. I can try this flag for the time being.
