### ISSUE TITLE
"_include" and "_revinclude" are not supported in Search

### ISSUE THREAD

**Issue by Efreeto** [microsoft/fhir-server#306]
**User story**
As a server provider, I want _include and _revinclude in Search (https://www.hl7.org/fhir/search.html#revinclude) feature so that clients can run the query on the server such as "http://xyz.com/Patient?_revinclude=*".

**Acceptance criteria**
1. When clients run do "http://xyz.com/Patient?_revinclude=*", along side the resulting patients, other resource types referenced by resulting patients are returned.

Before edit:
> **Describe the bug**
> "_include" and "_revinclude" are not supported in Search
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Put a Patient on server
> 2. Put an Observation that has a reference to the patient from above
> 3. Run the query on the server such as "http://xyz.com/Patient?_revinclude=*"
> 
> **Expected behavior**
> Both the Patient and the Observation are returned in a Bundle
> https://www.hl7.org/fhir/search.html#revinclude
> 
> **Actual behavior**
> Only the Patient is returned in a Bundle

**Comment by hansenms** [comment]
These are features that are on our roadmap. We would probably qualify this as a "feature request" rather than a bug and add it to the backlog. Could I ask that you edit the issue to reflect this. We are working on the feature.

**Comment by Efreeto** [comment]
@hansenms I have edited my original comment as you requested. Please feel free to make further edits to ease your process such as adding tags.

**Comment by Efreeto** [comment]
Are we still in backlog?

**Comment by ElYusubov** [comment]
@jackliums is there any progress on this feature?

**Comment by hansenms** [comment]
https://github.com/microsoft/fhir-server/commit/ced75d779ce8cbb7cb90330d820f148e5cf9bd8d

**Comment by hansenms** [comment]
Include for SQL server has been merged.

**Comment by ElYusubov** [comment]
> Include for SQL server has been merged.

@hansenms is there a timeline for "_revinclude" support?

**Comment by ellgre** [comment]
Is there a timeline for cosmosdb support?

**Comment by hansenms** [comment]
`_revinclude` for SQL is on the backlog, we will pick it up after some other items (like transactions), but we have no current plans to implement `_include` or `_revinclude` for Cosmos. We could consider `_include` for SQL, but we have no current plans.

**Comment by ellgre** [comment]
Will your focus be on SQL in the future or will you also develop for cosmosdb? Do you have updated roadmaps for the two databases available online? In case cosmosdb will be lagging behind, will it be easy to convert from cosmosdb to SQL?

**Comment by hansenms** [comment]
There are just some things that are hard to implement in one some types of databases. We don't have that all listed, but when we pick up a certain feature, e.g. `_include` there may not be a good implementation (at the moment) in some database, but we will not hold all versions back because one lacks features. So it is something we look at on a case by case basis.

**Comment by ellgre** [comment]
Is GraphDefinition on your roadmap for cosmosdb? As far as I can understand, this is an alternative to _include and _revinclude.

**Comment by hansenms** [comment]
I am not sure I would think of `GraphDefinition` as an alternative to `_include`. You could use a GraphDefinition to lay out the same part of a graph that you see with include or reverse include, but GraphDefinition would be a superset of include, so if it is hard, in general, to support include and reverse include for Cosmos.....it would be even harder with GraphDefinition. So don't expect GraphDefinition to be there before include.

That said, at the moment, we don't have GraphDefinition on the immediate roadmap. We would like to take a look at it if we see a lot of requests, but it is not a frequent ask.

**Comment by ellgre** [comment]
I was thinking about what HL7 has written in the following https://www.hl7.org/fhir/graphdefinition.html#fetch when I said it is an alternative to _include and _revinclude. 

We just have to hope that others have the similar need as us to fetch patients with connected relatedPersons, and Practitioners with connected PractitionerRole, Organization, healthcareService and Location.

**Comment by hansenms** [comment]
I think lots of user have similar needs to do what is essentially joins across the resources whether it be using `_include` or `GraphDefinition`. That is what of the main motivators for working on the SQL server persistence provider. So we are working on that functionality, and may get to the GraphDefinition too in that process, however, I do not see that being fully supported on the Cosmos implementation.

**Comment by mcbeauch** [comment]
Is _contained or _containedType supported for sql?

**Comment by hansenms** [comment]
@mcbeauch, we do not. And unfortunately, we have a bug (or misinterpretation of the spec) that I noticed while testing this. Chained searches are (apparently) supposed to reach into contained searches and we don't do that. I have added an issue (https://github.com/microsoft/fhir-server/issues/762) to track this.

**Comment by emanzanoaxa** [comment]
Any news about _revinclude support?

**Comment by hansenms** [comment]
`_revinclude` is still on the backlog. We have some more urgent priorities at the moment, so I cannot give you any timelines.
