### ISSUE TITLE
Images for recent releases not uploaded to container registry

### ISSUE THREAD

**Issue by tswelsh** [microsoft/fhir-server#3065]
The latest images available at mcr.microsoft.com appear to be from release 3.3.53, whereas the latest release at the time of writing is 3.3.70.  See e.g. https://mcr.microsoft.com/en-us/product/healthcareapis/stu3-fhir-server/tags.  We would like to upgrade to the latest release, but in particular 3.3.58 which contains some memory usage improvements.

**Comment by PTaladay** [comment]
Thanks you we are looking into it.

**Comment by PTaladay** [comment]
@tswelsh We have resolved the issue with the image publishing.

**Comment by tswelsh** [comment]
Thanks @PTaladay - now able to get the latest version 3.3.88.
