### ISSUE TITLE
DocumentClientInitializer.InitializeDataStore takes over 6 minutes to exception when no localhost cosmos db exists.

### ISSUE THREAD

**Issue by meikeric** [microsoft/fhir-server#312]
**Describe the bug**
There is a bug in Microsoft.Azure.DocumentDB.Core in IDocumentClient.CreateDatabaseIfNotExistsAsync as called by DocumentClientInitializer.InitializeDataStore.  InitializeDataStore takes a long time to timeout if target host for cosmos db is not running/listening.

**To Reproduce**
1. Do NOT install Cosmos DB Emulator
2. Run any of the Microsoft.Health.Fhir.Tests.Integration.Persistence.CosmosDbStorageTests tests that exercise InitializeDataStore downstream.

**Expected behavior**
An exception should be thrown almost instantaneously as Cosmos DB emulator will not be running on the local machine.

**Actual behavior**
It takes > 6 minutes to finally throw an exception: 'System.Net.Http.HttpRequestException' in System.Private.CoreLib.dll

I have added to the already filed bug on the azure cosmos db dotnet issue log at https://github.com/Azure/azure-cosmos-dotnet-v2/issues/604

I created an issue here for tracking as this is a real bug I ran into while working on setting up fhir-server for development.

**Comment by CaitlinV39** [comment]
Please reopen an issue if you are having issues with the new Cosmos SDK.
