### ISSUE TITLE
POST {resource_type}/_search returns 415 (Unsupported Media Type) if a query parameter is duplicated in URL and request body

### ISSUE THREAD

**Issue by moloneyd-draeger** [microsoft/fhir-server#3156]
**Describe the bug**
When using the POST {resource_type}/_search endpoint to query resources, the server returns 415 Unsupported Media Type when repeating a query parameter in the URL query string and the request body.

The [FHIR search specification](https://www.hl7.org/fhir/http.html#search) states
> Note that in the POST variant, parameters may appear in both the URL and the body. Parameters have the same meaning in either place. Since parameters can repeat, putting them in both places is the same as repeating them (which is valid for some parameters and not for others).

It is expected that when a query parameter is repeated in the URL and the body:
1. The server does not reject the request (assuming it is otherwise well-formed) and returns a Bundle as per the normal search specification
2. All query parameters from both the URL and the body are used as inputs to the the search operation

**FHIR Version?**
R4

**Data provider?**
CosmosDB

**Workaround**
When using the POST /_search endpoint, clients must send all query parameters in the request body and leave the URL query parameters empty.

**To Reproduce**
1. Create a patient resource to show successful results in later examples.
```
POST /Patient HTTP/1.1
Host: <removed>.azurehealthcareapis.com
Content-Type: application/fhir+json
Authorization: <removed>

{
    "resourceType": "Patient",
    "identifier": [
        {
            "system": "http://example.com/fhir/post_search_bug",
            "value": "id_value_1"
        },
        {
            "system": "http://example.com/fhir/post_search_bug",
            "value": "id_value_2"
        }
    ],
    "active": true,
    "birthDate": "2001-02-03",
    "gender": "female"
}
```

Receive `201 Created` with the following body
```json
{
    "resourceType": "Patient",
    "id": "d5f35698-4981-4aca-af0e-2819df79c633",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2023-03-03T15:35:59.78+00:00"
    },
    "identifier": [
        {
            "system": "http://example.com/fhir/post_search_bug",
            "value": "id_value_1"
        },
        {
            "system": "http://example.com/fhir/post_search_bug",
            "value": "id_value_2"
        }
    ],
    "active": true,
    "gender": "female",
    "birthDate": "2001-02-03"
}
```

2. (❌ Unexpected Behaviour) Demonstrate example search with POST /_search endpoint, with **overlapping** query parameters in both the URL and the body. More successful examples are provided below to show that the key condition appears to be duplicating a query parameter in the URL and the body.
```
POST /Patient/_search?active=true&gender=female&birthdate=2001-02-03&identifier=http://example.com/fhir/post_search_bug|id_value_1 HTTP/1.1
Host: <removed>.azurehealthcareapis.com
Content-Type: application/x-www-form-urlencoded
Authorization: <removed>
Content-Length: 61

identifier=http://example.com/fhir/post_search_bug|id_value_2

```

Receive 415 Unsupported Media Type with the following OperationOutcome. The error message states that the Content-Type header is not supported, but the content-type (`application/x-www-form-urlencoded`) is exactly the same as in the later successful requests to POST /_search. 
```json
{
    "resourceType": "OperationOutcome",
    "id": "fca8e1ee698d5664933a0063efa8cb1f",
    "meta": {
        "lastUpdated": "2023-03-03T15:59:37.6032741+00:00"
    },
    "issue": [
        {
            "severity": "error",
            "code": "not-supported",
            "diagnostics": "Value supplied for the \"Content-Type\" header is not supported."
        }
    ]
}
```

3. (✔ Correct Behaviour) Demonstrate example search operation with GET /Patient endpoint (using URL only)
```
GET /Patient?active=true&gender=female&birthdate=2001-02-03&identifier=http://example.com/fhir/post_search_bug|id_value_1&identifier=http://example.com/fhir/post_search_bug|id_value_2 HTTP/1.1
Host: <removed>.azurehealthcareapis.com
Content-Type: application/fhir+json
Authorization: <removed>
```

Receive `200 OK` with the following response Bundle 
```json
{
    "resourceType": "Bundle",
    "id": "1c2d5ff1e631403a36dd3e6dbb0de164",
    "meta": {
        "lastUpdated": "2023-03-03T15:48:25.5211147+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://<removed>.azurehealthcareapis.com/Patient?active=true&gender=female&birthdate=2001-02-03&identifier=http%3A%2F%2Fexample.com%2Ffhir%2Fpost_search_bug%7Cid_value_1&identifier=http%3A%2F%2Fexample.com%2Ffhir%2Fpost_search_bug%7Cid_value_2"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://<removed>.azurehealthcareapis.com/Patient/d5f35698-4981-4aca-af0e-2819df79c633",
            "resource": {
                "resourceType": "Patient",
                "id": "d5f35698-4981-4aca-af0e-2819df79c633",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2023-03-03T15:35:59.78+00:00"
                },
                "identifier": [
                    {
                        "system": "http://example.com/fhir/post_search_bug",
                        "value": "id_value_1"
                    },
                    {
                        "system": "http://example.com/fhir/post_search_bug",
                        "value": "id_value_2"
                    }
                ],
                "active": true,
                "gender": "female",
                "birthDate": "2001-02-03"
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}
```

4. (✔ Correct Behaviour) Demonstrate example search with POST /_search endpoint, using body only
```
POST /Patient/_search HTTP/1.1
Host: <removed>.azurehealthcareapis.com
Content-Type: application/x-www-form-urlencoded
Authorization: <removed>
Content-Length: 170

active=true&gender=female&birthdate=2001-02-03&identifier=http://example.com/fhir/post_search_bug|id_value_1&identifier=http://example.com/fhir/post_search_bug|id_value_2
```

Receive `200 OK` with the following response Bundle 
```json
{
    "resourceType": "Bundle",
    "id": "26af93b6dba4596c41fc145f365d2b90",
    "meta": {
        "lastUpdated": "2023-03-03T15:55:54.23725+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://<removed>.azurehealthcareapis.com/Patient?active=true&gender=female&birthdate=2001-02-03&identifier=http%3A%2F%2Fexample.com%2Ffhir%2Fpost_search_bug%7Cid_value_1&identifier=http%3A%2F%2Fexample.com%2Ffhir%2Fpost_search_bug%7Cid_value_2"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://<removed>.azurehealthcareapis.com/Patient/d5f35698-4981-4aca-af0e-2819df79c633",
            "resource": {
                "resourceType": "Patient",
                "id": "d5f35698-4981-4aca-af0e-2819df79c633",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2023-03-03T15:35:59.78+00:00"
                },
                "identifier": [
                    {
                        "system": "http://example.com/fhir/post_search_bug",
                        "value": "id_value_1"
                    },
                    {
                        "system": "http://example.com/fhir/post_search_bug",
                        "value": "id_value_2"
                    }
                ],
                "active": true,
                "gender": "female",
                "birthDate": "2001-02-03"
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}
```

5. (✔ Correct Behaviour) Demonstrate example search with POST /_search endpoint, with **non-overlapping** query parameters in both the URL and the body.
```
POST /Patient/_search?active=true&gender=female&birthdate=2001-02-03 HTTP/1.1
Host: <removed>.azurehealthcareapis.com
Content-Type: application/x-www-form-urlencoded
Authorization: <removed>
Content-Length: 123

identifier=http://example.com/fhir/post_search_bug|id_value_1&identifier=http://example.com/fhir/post_search_bug|id_value_2
```

Receive `200 OK` with the following response Bundle 
```json
{
    "resourceType": "Bundle",
    "id": "7c9bf9813cb77d170863729465db00f1",
    "meta": {
        "lastUpdated": "2023-03-03T15:57:32.200619+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://<removed>.azurehealthcareapis.com/Patient?active=true&gender=female&birthdate=2001-02-03&identifier=http%3A%2F%2Fexample.com%2Ffhir%2Fpost_search_bug%7Cid_value_1&identifier=http%3A%2F%2Fexample.com%2Ffhir%2Fpost_search_bug%7Cid_value_2"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://<removed>.azurehealthcareapis.com/Patient/d5f35698-4981-4aca-af0e-2819df79c633",
            "resource": {
                "resourceType": "Patient",
                "id": "d5f35698-4981-4aca-af0e-2819df79c633",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2023-03-03T15:35:59.78+00:00"
                },
                "identifier": [
                    {
                        "system": "http://example.com/fhir/post_search_bug",
                        "value": "id_value_1"
                    },
                    {
                        "system": "http://example.com/fhir/post_search_bug",
                        "value": "id_value_2"
                    }
                ],
                "active": true,
                "gender": "female",
                "birthDate": "2001-02-03"
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}
```

**Expected behavior**
As per the FHIR Search specification, all search parameters from the URL query string and the request body should be used as inputs to the search operation when using the POST {resource_type}/_search endpoint.

**Actual behavior**
FHIR server returns `415 Unsupported Media Type` when a query parameter is duplicated in the URL and the body. The search appears to work as expected when query parameters do not collide between the URL query string and the POST body.

AB#101268

**Comment by moloneyd-draeger** [comment]
Hi, while discussing this with my team and experimenting with the current implementation, we realised the current implementation has several "search" scenarios that are probably unintended. It appears all `POST /{x}/_search` requests are being rewritten as `GET /{x}` internally, which leads to the following examples.

### Workaround
Explicitly block these additional requests through url filtering/pattern matching in our api gateway. (For us, only `POST /_history/_search` represented any potential security risk in multi-tenanted environments)

### Examples
(taken from https://hl7.org/fhir/http.html#summary)

| original request | rewritten as | intended? | risk? |
| -- | -- | -- | -- |
| `POST /{type}/_search?a=b` | `GET /{type}?a=b` | ✔ | - |
| `POST /_search` | `GET /` | ❌ |  |
| `POST /metadata/_search` | `GET /metadata` | ❌ |  |
| `POST /_history/_search` | `GET /_history` | ❌ | query parameters are not applied to the history search, so can return/leak data unexpectedly! |
| `POST /_history//{type}/_search` | `GET /_history/{type}` | ❌ | query parameters are not applied to the history search, so can return/leak data unexpectedly! |
| `POST /_history//{type}/{id}/_search` | `GET /_history/{type}/{id}` | ❌ | query parameters are not applied to the history search, so can return/leak data unexpectedly! However, clients must know the resource id already. |

**Comment by EXPEkesheth** [comment]
@moloneyd-draeger - this issue is resolved with PR https://github.com/microsoft/fhir-server/pull/3232. Let us know if you have any additional questions.
