### ISSUE TITLE
FHIR Search `_count=0` should be same as `_summary=count`

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/fhir-server#3230]
**Describe the bug**
When running a FHIR query with `_count=0`, I get a HTTP 400 response. This is not expected according to the FHIR spec.

`http://<redacted>.azurewebsites.net/Encounter?_count=0`

**FHIR Version?**
Found on R4, possibly applicable to all.

**Data provider?**
Found on SQL, possibly applicable to all.

**To Reproduce**
1. Load a FHIR Server with encounter data.
2. Run a `_count=0` on encounters (`http://<redacted>.azurewebsites.net/Encounter?_count=0`)

**Expected behavior**
According to the FHIR Spec, `_count=0` should be the same as `_summary=count`.

![CleanShot 2023-04-13 at 10 10 19](https://user-images.githubusercontent.com/753437/231834279-e807403b-b48b-4646-bf7d-a2a2c7282477.png)

**Actual behavior**
HTTP 400 response.

![CleanShot 2023-04-13 at 10 11 27](https://user-images.githubusercontent.com/753437/231834577-51b6e26e-8239-4bc5-b7dc-104079912ef9.png)

AB#102605

**Comment by LTA-Thinking** [comment]
This is a bug on the Firely library. Their SearchParam validator requires _count to be >0.
https://github.com/FirelyTeam/firely-net-sdk/blob/develop/src/Hl7.Fhir.Base/Rest/SearchParams.cs#L117

We need to add a filter to remove the _count param and replace it with the _summary param before this line: https://github.com/microsoft/fhir-server/blob/main/src/Microsoft.Health.Fhir.Shared.Core/Features/Search/SearchOptionsFactory.cs#L193

**Comment by LTA-Thinking** [comment]
I think this is a good first issue. The fix should be limited to one file, is easy to test manually, and easy to add a unit test for.

**Comment by brendankowitz** [comment]
Done
