### ISSUE TITLE
Error on Deployment 

### ISSUE THREAD

**Issue by FrancisChristy** [microsoft/fhir-server#3261]
When i try deploying the project to aws EC2, it is throwing 500 internal server error. Is azure subscription a prerequisite for deploying this FHIR server project? Can someone please help me with the deployment process.
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/58290900/234512611-ed9fae95-f44b-49df-ba8e-16bc3846a587.png)

AB#102950

**Comment by EXPEkesheth** [comment]
@FrancisChristy - Thanks for reaching out . Closing the issue and feel free to provide inputs as you use MSFT FHIR service.
