### ISSUE TITLE
Create test auth environment fails with AAD guest account

### ISSUE THREAD

**Issue by hansenms** [microsoft/fhir-server#337]
**Describe the bug**
If the AAD administrator used to create the test auth environment is a guest user in the AAD tenant (e.g. a Microsoft Live account), then the code to retrieve the `currentObjectId` (https://github.com/Microsoft/fhir-server/blob/master/release/scripts/PowerShell/FhirServerRelease/Public/Add-AadTestAuthEnvironment.ps1#L83)

Fails.

**To Reproduce**
1. Deploy test auth environment with guest account 

**Expected behavior**
We should find the user object id through other mechanism, e.g.:

```
    $currentUser = Get-AzureRmADUser -UserPrincipalName $azureRmContext.Account.Id

    #If this is guest account, we will try a search instead
    if (!$currentUser) {
        $currentUser = Get-AzureRmADUser -SearchString $azureRmContext.Account.Id
    }

    $currentObjectId = $currentUser.Id
```

**Actual behavior**
Script fails.

**Comment by CaitlinV39** [comment]
Not planning to fix right now. Will reopen if we hear a demand for the resolution.
