### ISSUE TITLE
Application Insights instrumentation keys are being deprecated

### ISSUE THREAD

**Issue by tswelsh** [microsoft/fhir-server#3376]
**User story**
As a user, I want to be able to use Application Insights connection strings to ingest telemetry so that I don't have to use the deprecation instrumentation key approach.

**Acceptance criteria**
1. When I supply an application insights connection string via configuration, then the application insights telemetry uses it over any instrumentation key present.

Application insights telemetry is added here: https://github.com/microsoft/fhir-server/blob/44b342ee1d24f4ea4c9f6306fa728a9f45a29f08/src/Microsoft.Health.Fhir.Shared.Web/Startup.cs#L177.  This explicitly looks for an InstrumentationKey specified in configuration.  However ingestion based on instrumentation keys is being phased out; see e.g. https://azure.microsoft.com/en-gb/updates/technical-support-for-instrumentation-key-based-global-ingestion-in-application-insights-will-end-on-31-march-2025/.  Therefore we'd like the option to use an application insights connection string ready for the transition.

AB#104859

**Comment by EXPEkesheth** [comment]
@tswelsh - We are actively working on migrating to OTEL provider. The configurations will be updated soon to map to OTEL.

**Comment by EXPEkesheth** [comment]
@tswelsh to use the connection string with Application Insights, update the Telemetry section in appsettings.json 
Below are the details on the attributes used in telemetry section

- Provider : Telemetry provider is “ApplicationInsights” or “OpenTelemetry”, or “None” for disabling telemetry logging. 
- InstrumentationKey : The instrumentation key of your Application Insights resource. 
- ConnectionString : The connection string of your Application Insights resource. 

Note : 

1. Technical support for instrumentation key-based logging in Application Insights will end in [March 2025](https://azure.microsoft.com/en-us/updates/technical-support-for-instrumentation-key-based-global-ingestion-in-application-insights-will-end-on-31-march-2025/). 
2. When the instrumentation key and connection string are provided in appsettings.json for ApplicationInsights provider, the instrumentation key will be used.

Let us know if you have any further questions

**Comment by EXPEkesheth** [comment]
@tswelsh closing the issue as there is no further action. Please open another issue for any questions.
