### ISSUE TITLE
Capability statement does not list _count as a search parameter

### ISSUE THREAD

**Issue by hansenms** [microsoft/fhir-server#338]
**Describe the bug**
Capability statement does not list `_count` as a search parameter

**To Reproduce**
1. Deploy server
2. `GET /metadata`
3. Look at list of search parameters for say 'Patient'
 
**Expected behavior**
`_count` should be listed as a search parameter.

**Actual behavior**
`_count` is not listed as search parameter.

**Comment by mmacagno** [comment]
Can anybody comment on this? Is _count supported but not present in the capability statement, or rather _count is not currently supported?

**Comment by mmacagno** [comment]
It seems like somewhat works, although it has some upper limit < 100
For example I got different records for _count=10 and _count=100, but same results for _count=10000 (I have more than 100 records for that query).

what is the limit?

**Comment by CaitlinV39** [comment]
https://www.hl7.org/fhir/capabilitystatement-definitions.html#CapabilityStatement.rest.resource.searchParam

**Comment by CaitlinV39** [comment]
AB#76064
