### ISSUE TITLE
Install and Build Instructions are Missing important steps

### ISSUE THREAD

**Issue by keithboone** [microsoft/fhir-server#3387]
**Describe the bug**
Following https://github.com/microsoft/fhir-server/wiki/Build-and-debug-locally instructions fails in VSCode because the build requires an earlier runtime .  After downloading the code, 
global.json contains the following:
{
    "sdk": {
        "version": "7.0.304"
    }
}

However, this seem to be at odds with the version the project requires.
I originally installed .NET SDK 7.0.305 with the 7.0.8 Runtimes.

**FHIR Version?**
R4

**Data provider?**
CosmosDB/SQL Server
Cosmos DB Emulator and SQL Server Developer

**To Reproduce**
1. Install the necessary dependencies
2. Select Microsoft.Health.Fhir.R4.Web and press F5

**Expected behavior**
The build should finish normally.

**Actual behavior**
The build reports the following error after following instructions:
  App: C:\Users\<user>\.nuget\packages\microsoft.health.extensions.buildtimecodegenerator\6.2.103\tools\net6.0\Microsoft.Health.E 
  xtensions.BuildTimeCodeGenerator.dll
  Architecture: x64
  Framework: 'Microsoft.NETCore.App', version '6.0.14' (x64)
  .NET location: C:\Program Files\dotnet\

  The following frameworks were found:
    7.0.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

  Learn about framework resolution:
  https://aka.ms/dotnet/app-launch-failed

  To install missing framework, download:
  https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.14&arch=x64&rid=win10-x64

It then reports this error after installing the requested framework.
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Using launch settings from 'C:\Users\boonek\git\fhir-server\src\Microsoft.Health.Fhir.R4.Web\Properties\launchSettings.json' [Profile 'Default']...
You must install or update .NET to run this application.

App: C:\Users\boonek\git\fhir-server\src\Microsoft.Health.Fhir.R4.Web\bin\Debug\net6.0\Microsoft.Health.Fhir.R4.Web.dll
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '6.0.19' (x64)
.NET location: C:\Program Files\dotnet\

The following frameworks were found:
  7.0.8 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.19&arch=x64&rid=win10-x64
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[22576] Microsoft.Health.Fhir.R4.Web.dll' has exited with code -2147450730 (0x80008096).

Finally, after installing both, it seems to be functioning properly.

AB#105117

**Comment by keithboone** [comment]
Also note: Azure Storage Emulator was apparently replaced by Azurite.

**Comment by EXPEkesheth** [comment]
@keithboone - Documentation https://github.com/microsoft/fhir-server/wiki/Build-and-debug-locally  is updated to list needed .NET versions. Closing the issue and please feel free to reach out for any additional questions.
