### ISSUE TITLE
Support batch

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#341]
**User story**
As a user, I want to POST a bundle with batch mode so that I can process multiple requests at once.

http://hl7.org/fhir/STU3/http.html#transaction

**Acceptance criteria**
1. When I POST a bundle, then each entry within the bundle is processed.

**Comment by brianpos** [comment]
Would be great to be able to ask for sets of queries as in this example
```
{
  "resourceType" : "Bundle",
  "id" : "PrePopQuery",
  "type" : "batch",
  "entry" : [
    {
      "fullUrl" : "urn:uuid:88f151c0-a954-468a-88bd-5ae15c08e059",
      "request" : {
        "method" : "GET",
        "url" : "RelatedPerson?patient=1&active=true"
      }
    }
  ]
}
```

**Comment by hansenms** [comment]
We are working on it. If you follow the PRs, you will start to see this going in.

**Comment by umberto-cappellini** [comment]
Not sure 100% if related to this request... Is there a way at the moment to POST multiple resources at one in a Bundle ? Like a Patient and a related Encounter. Thanks

**Comment by hansenms** [comment]
As mentioned above. We are working on it. In general the FHIR spec describes how to do that with batch or transaction bundles. We are in the process on implementing both.

**Comment by gravityh1** [comment]
Any update on the progress of handling Bundle types "transaction" and "batch"?  
My recent test on an open source subscription instance this week shows a bundle is accepted using the "Transaction" type but the embedded resources are not loaded.  I queried for individual resourceTypes embedded in the Bundle and they were not found.  This was a version 4 FHIR instance.  Thanks

**Comment by hansenms** [comment]
Transactions and batch are both supported on the SQL based version of the OSS server. The Cosmos DB backed version of OSS supports batch only. Same goes for the managed service.

Are you posting the transaction bundle to the root `/` or to the `/Bundle` endpoint. For the individual entries to be processed, the bundle has to be POST'ed to the  root `/`.

**Comment by gravityh1** [comment]
I was posting to this URL: https://PatsFhirEngine.azurehealthcareapis.com/Bundle

So you are saying I should post to this https://PatsFhirEngine.azurehealthcareapis.com/  
if so I will give it a try...

**Comment by hansenms** [comment]
Yes, that is per the spec:

https://www.hl7.org/fhir/http.html#transaction

**Comment by gravityh1** [comment]
Michael, just letting you know we figured it out and we were able to successfully load a simple bundle on a new Open Source Server we built last night and this morning.  Now to build a more complex version that meets the Di Vinci Project spec using MessageHeader along with other resourceTypes..  THANK YOU for your support...

**Comment by IoTFier** [comment]
Hi @jackliums, @brendankowitz  and Azure FHIR Server team,

Any new update on this request ?

I am running a  OSS Azure FHIR Server locally backed by Sql sever 2019. I would like to upload a population created using Synthea in my local FHIR Server endpoint using FHIR Batch / Transaction.
Is there a sample that you can point me that I can follow in uploading my data ?

What impact on the FHIR database should I keep in mind when I update the github FHIR Server repo, rebuild and restart my server? - especially when schema were to change?

Thank you.

**Comment by brendankowitz** [comment]
Both Batch and Transaction are now supported with the SQL persistence provider.
The Cosmos backend supports Batch, check [supported features](https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir-features-supported) for the latest.

When upgrading, and if a schema upgrade is required, we have a [Schema Migration Guide](https://github.com/microsoft/fhir-server/blob/master/docs/SchemaMigrationGuide.md) as a starting point.

**Comment by IoTFier** [comment]
Hello @brendankowitz , is there a sample that you can point me that I can follow in uploading data in the local OSS FHIR server instance ?

**Comment by brendankowitz** [comment]
Read through #1027 first, the [FhirLoader](https://github.com/hansenms/FhirLoader) tool might be what you're after

**Comment by IoTFier** [comment]
> Read through #1027 first, the [FhirLoader](https://github.com/hansenms/FhirLoader) tool might be what you're after

Thank you @brendankowitz
