### ISSUE TITLE
Support _outputFormat query parameter in $export operation

### ISSUE THREAD

**Issue by jackliums** [Microsoft/fhir-server#343]
**User story**

As a customer, I want to be able to specify `_outputFormat` query parameter when calling $export operation so that I can specify the output format.

**Acceptance criteria**

1. Verify if `_outputFormat` parameter is not specified, then `application/fhir+ndjson` is used.
2. Verify if `_outputFormat` parameter is specified, then value is one of the following: `application/fhir+ndjson`, `application/ndjson`, or `ndjson`.
3. Verify if `_outputFormat` parameter is specified with a non-supported value, then 415 Unsupported Media Type is returned.

**Comment by namadabu** [comment]
Moved tracking of user story level items to Azure DevOps.
