### ISSUE TITLE
Support _type query parameter in $export operation

### ISSUE THREAD

**Issue by jackliums** [Microsoft/fhir-server#345]
**User story**

As a customer, I want to be able to specify `_type` query parameter when calling $export operation so that I I can limit the type of resources being returned

**Acceptance criteria**

1. Verify if `_type` parameter is specified, then only resources matching the specified type are included.
2. Verify if multiple types delimited by command is specified by `_type` parameter, then only resources matching any of the specified types are included.
3. Verify if `_type` parameter is not specified, then all resources types are returned.

**Comment by namadabu** [comment]
Moved tracking of user story level items to Azure DevOps.
