### ISSUE TITLE
Audit event logging

### ISSUE THREAD

**Issue by reubenelder** [microsoft/fhir-server#3473]
Hi,

We have an OSS setup in Azure which points to Application Insights for logging.  At the moment audit logs are coming through as expected as trace events however there are a lot of other trace events that we do not want to see (such as Smart Data Action is present etc.).  I've tried a few configuration changes around the logging but haven't successfully been able to remove them the non-audit trace events.  Is it possible to only log the audit events and remove the other trace information?  Note - we deploy to azure app services linux which doesn't like the '.' in LoggingLevel__Microsoft.Health.

Thanks for the help,
Reuben

**Comment by reubenelder** [comment]
Hi @EXPEkesheth any suggestions for this - it would be great to only log relevant information, i.e. the audit events.  thanks

**Comment by EXPEkesheth** [comment]
@reubenelder - Microsoft fhir server emit traces from various parts of code that include audit logs and other informational logs. We suggest you use the query to filter out just the audit event traces, such as (for example)
traces| where message has 'EventType: AuditEvent'

**Comment by EXPEkesheth** [comment]
@reubenelder - Question is answered and hence closing the issue. Please open another issue for any additional questions. Thanks !
