### ISSUE TITLE
ReIndexing Operation on Production is safe or not

### ISSUE THREAD

**Issue by Sameer2810** [microsoft/fhir-server#3517]
**Question**

I want to perform reindex operation on Fhir. 

**Description**
 I just wanted to know whether it is safe operation or not, like do we need to take database backup before applying reindexing operation
on Fhir or anything else specific do wee need to do to perform this operation 
I have gone through below link ae well
https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/how-to-run-a-reindex
 But I just wanted to know whether it is safe to perform reindex operation on production environment or do we need to take some steps before performing reidexing

**Comment by EXPEkesheth** [comment]
@Sameer2810  - This is a safe operation and the reindex operation will scan resources for any values that were not yet indexed.  It will not alter any resources. Reindex operation will enable search parameters for searching.

**Comment by EXPEkesheth** [comment]
@Sameer2810 We have no specific guidance to take data base backup prior to reindexing.

**Comment by EXPEkesheth** [comment]
@Sameer2810 - Closing this issue as we have answered, We would like to get your input on the FHIR service usage poll : https://github.com/microsoft/fhir-server/discussions/3504, please provide input.
