### ISSUE TITLE
What are different type of sorting supported in microsoft-fhir server 

### ISSUE THREAD

**Issue by Sameer2810** [microsoft/fhir-server#3537]
**Question**

What are different type of sorting supported in microsoft-fhir server 

**Description**
We want to sort by patient name but it gives result as not supported. Can you give me link as what are different types sorting supported

**Comment by Sameer2810** [comment]
Hi @brendankowitz,

If we combining 2 resources like ImagingStudy and Patient then sorting on patient name not working

![image](https://github.com/microsoft/fhir-server/assets/38692494/5184d9ed-22ce-4471-9607-47bab8a90e0c)

**Comment by EXPEkesheth** [comment]
@Sameer2810 - Are you running above query on Azure API for FHIR ?

**Comment by Sameer2810** [comment]
@EXPEkesheth - No I amusing Microsoft fhir server version 2.2.0

**Comment by EXPEkesheth** [comment]
@Sameer2810 - What is the persistence layer used for Microsoft fhir server version 2.2.0?

**Comment by EXPEkesheth** [comment]
No response and, hence closing the issue. Please reopen for any additional question on the same topic.

**Comment by Sameer2810** [comment]
@EXPEkesheth  Using CosmosDb for persistence layer

**Comment by brendankowitz** [comment]
Hi @Sameer2810, there isn't currently support for sorting via a chained parameter, it must be a search parameter that is indexed on the primary resource type

**Comment by Sameer2810** [comment]
Hi @brendankowitz, if I want to apply sort on chained resource then is there any alternate way we can apply sorting

**Comment by EXPEkesheth** [comment]
@Sameer2810 - Unfortunately there is no alternate way today. One suggestion you could try is to look for Patient resources with references to ImagingStudy resources (basically flip the query).

**Comment by Sameer2810** [comment]
@EXPEkesheth - There is reference in ImagingStudy for Patient but in Patient there is no reference for ImagingStudy so how can we flip the query or you are saying something different
