### ISSUE TITLE
Error Message when deploying from Portal

### ISSUE THREAD

**Issue by ashley-kainos** [microsoft/fhir-server#3562]
**Describe the bug**
when deploying from teh deploy to Azure portal version the app service fails with teh error 
Cannot find ServerFarm with name appfhiriaasneu. Click here for details

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
1. follow steps to deploy from portal
2. 
3. 

**Expected behavior**
expect delpoyment to be successful

**Actual behavior**
Deployment fails to deploy app service
<img width="772" alt="fhir server portal error" src="https://github.com/microsoft/fhir-server/assets/109275604/9dc16e83-0a03-4977-9682-21a9f6cb9a4f">

**Comment by EXPEkesheth** [comment]
@ashley-kainos - Can you please provide details on deployment script used?

**Comment by EXPEkesheth** [comment]
Closing this issue, with no response
