### ISSUE TITLE
Question on making FHIR server HA

### ISSUE THREAD

**Issue by ashley-kainos** [microsoft/fhir-server#3563]
**Question**

we have a scenario to make this service highly available across regions, and can't find any documentation to support how to do this. Is this possible in teh 1st instance and if so can you give some guidance as to how to achieve this please? 

* Is your question answered in our documentation? - https://docs.microsoft.com/azure/healthcare-apis/

* Our team also monitors the FHIR Community chat @ http://chat.fhir.org

**Description**
If you cannot find the answer at one of the sites above, please provide a detailed description of your question.

**Comment by EXPEkesheth** [comment]
@ashley-kainos - For managed service, we offer high availability, please refer to [Azure documentation]( https://learn.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/disaster-recovery)

For more information on how Cosmos does HA , you can refer to Azure documentation : [High availability in Azure Cosmos DB | Microsoft Learn](https://learn.microsoft.com/en-us/azure/cosmos-db/high-availability)
