### ISSUE TITLE
PUT search parameter results in "invalid" 400 error

### ISSUE THREAD

**Issue by dfjones1981** [microsoft/fhir-server#3595]
**Describe the bug**
When attempting to change the value of a SearchParameter via a PUT request we receive a 400 error
Snippet of response here, with personal data replaced:
"issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "A search parameter with the same code value 'yourid' already exists for base type 'base-type-here'.",
            "location": [
                "Code // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"
            ],
            "expression": [
                "Code"
            ]
        }
    ]

This behaviour worked correctly a few weeks ago when it was last attempted. We're using the Azure Health Data FHIR Service.

**FHIR Version?**
R4

**Data provider?**
SQL Server

**To Reproduce**
1. Save a new Search Parameter with a known id via a POST request
2. Update the Search Parameter via a PUT request, using the same id in the url and body
3. Inspect the response back as a 400

**Expected behavior**
200 response and the Search Parameter updated

**Actual behavior**
400 response and the Search Parameter not updated

**Comment by abiisnn** [comment]
Would you mind adding the body of your request?

Thanks!

**Comment by dfjones1981** [comment]
{
    "resourceType" : "SearchParameter",
    "id" : "all-text",
    "url" : "https://xyz.com/fhir/SearchParameter/AllText",
    "name" : "all-text",
    "status" : "active",
    "date" : "2023-09-26",
    "publisher" : "xyz",
    "contact" : [
      {
        "name" : "xyz"
      }
    ],
    "description" : "Compound text search",
    "code" : "all-text",
    "base" : [
      "HealthcareService"
    ],
    "type" : "string",
    "expression": "category.coding.display | name | comment"
  }

**Comment by dfjones1981** [comment]
Worth noting that this is happening for all our Search Parameters, not just this one. And last week the same PUT requests were working with no errors

**Comment by abiisnn** [comment]
What Field are you trying to update in that example? and could you share what's the original search parameter?

**Comment by abiisnn** [comment]
Hi @dfjones1981,
1. Can you re-try? we had some issues with PUT some weeks ago, but we have already fixed it and if you pull the last version of the FHIR server, it should be fine now.
2. If you have a Provisioned FHIR service in the azure portal, you can provide us the FHIR service URL and we could look at what's happening, also, it would be best if you open a support ticket.

**Comment by EXPEkesheth** [comment]
@dfjones1981 - If no further comments, the issue will be closed in a week

**Comment by EXPEkesheth** [comment]
Closing the issue per above comment
