### ISSUE TITLE
What are different type of sorting supported in microsoft-fhir server #3537

### ISSUE THREAD

**Issue by Sameer2810** [microsoft/fhir-server#3597]
@EXPEkesheth  Using CosmosDb for persistence layer

_Originally posted by @Sameer2810 in https://github.com/microsoft/fhir-server/issues/3537#issuecomment-1816338425_

**Comment by EXPEkesheth** [comment]
@Sameer2810 - is there a specific question, we can help you with?

**Comment by EXPEkesheth** [comment]
Closing as no comment
