### ISSUE TITLE
How to enable SMART on FHIR locally?

### ISSUE THREAD

**Issue by Skopfy** [microsoft/fhir-server#3620]
**Question**

Hey!
I want to enable Smart On FHIR on the FHIR server. I had a look at the samples specified under https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/smart-on-fhir
but they seem to be only for deployment in the cloud. Anyhow, I want to deploy Smart locally like the FHIR server and not in the cloud.
The "SMART on FHIR Proxy " apparently is legacy (= deprecated?), so I guess its not recommended to use in the long run?
How do I achieve that? 

Thanks,
Skopfy

**Comment by EXPEkesheth** [comment]
SMART on FHIR proxy will be deprecated soon and yes we advise against relying on it long run. 
Can you please elaborate on?
1. SMART scenario 
2. Details on your integration with the SMART samples/ workflow
Thanks !

**Comment by Skopfy** [comment]
Thanks EXPEkesheth for your answer :)

1. Scenario:
Id say its quite basic. I have a platform, consisting of a mobile App for Patients & a web platform for practitioners (monitoring etc.). Both need access to the FHIR db. Earlier, credentials were saved in a db. Now, I want to leverage access to an authentication server and thought of implementing SMART. 
Am i right that this is Standalone Launch?
2. I did not test the samples yet, as I see they are only for cloud usage? I would like to test it, but as I understand with the used services immediately some costs would apply. As I am a student, this is not feasible (yet^^).

**Comment by feordin** [comment]
When running the FHIR server hosted yourself, you can use authentication settings to point to an identity provider, or you can use the built-in in-memory identity provider.  The samples that you have seen are, as you saw, designed to enable our managed service, with Microsoft Entra ID as the identity provider to be compatible with SMART.

Which authentication server were you thinking of using?  Does the authentication server support SMART?

**Comment by EXPEkesheth** [comment]
No further comments and hence issue is closed.
