### ISSUE TITLE
Authentication Issue: Unable to Fetch FHIR Resources After Deploying DICOM Cast and Syncing Metadata into FHIR Server for Azure

### ISSUE THREAD

**Issue by NancyOsalaniya** [microsoft/fhir-server#3637]
I've deployed [DICOM Cast](https://github.com/microsoft/dicom-server/blob/main/docs/quickstarts/deploy-dicom-cast.md#deploy-via-azure-with-oss) successfully. And I have performed all the steps of [Sync Medical Imaging Server for DICOM metadata into FHIR Server for Azure](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/sync-dicom-metadata-to-fhir.md). 

I am unable to fetch FHIR resources when I setup [authentication](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/sync-dicom-metadata-to-fhir.md#set-the-authentication-for-your-fhir--dicom-app-services) in the FHIR service.
![image](https://github.com/microsoft/dicom-server/assets/69629001/e25017a6-34dc-41b5-af5f-c4fd95ef1db3)

As you can see in the below diagram, If I skipped step no 3 then I'm able to fetch FHIR resources.
![DICOMCastDiagram](https://github.com/microsoft/dicom-server/assets/69629001/8fb74311-f5bf-469b-868b-a32b18e5f5bb)

I cannot fetch FHIR resources when I set up [authentication](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/sync-dicom-metadata-to-fhir.md#set-the-authentication-for-your-fhir--dicom-app-services) in the FHIR service. It is working fine when I skip that step. Do you have any ideas on why I'm unable to get FHIR resources?

**Comment by brendankowitz** [comment]
> I cannot fetch FHIR resources when I set up [authentication](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/sync-dicom-metadata-to-fhir.md#set-the-authentication-for-your-fhir--dicom-app-services) in the FHIR service. It is working fine when I skip that step. Do you have any ideas on why I'm unable to get FHIR resources? 

@NancyOsalaniya sorry can you explain this a little more?
Azure Health Data Services: FHIR uses Azure RBAC and always has authentication enabled. If you're setting up an application to access FHIR against the managed service were the correct roles also assigned? https://learn.microsoft.com/en-us/azure/healthcare-apis/authentication-authorization#application-roles

**Comment by NancyOsalaniya** [comment]
Hi @brendankowitz , sorry for the delay in the reply. 
Yes, the roles have been assigned properly as mentioned in the document. 
But I was asking is that, whenever I set up this [Authentication](https://github.com/microsoft/fhir-server/issues/3637) step in the FHIR Service at that time I'm not able to get FHIR resources. But if I skip this step, then it is working. But I think that this is step is mandatory one. In that case, could you please look into the matter why I'm not able to fetch FHIR resources while I configure this [Authentication](https://github.com/microsoft/dicom-server/blob/main/docs/how-to-guides/sync-dicom-metadata-to-fhir.md#set-the-authentication-for-your-fhir--dicom-app-services) step?

**Comment by EXPEkesheth** [comment]
@NancyOsalaniya - From the work flow it seems you are updating the FHIR service audience URL with client App ID URL. Approach you can try - instead of updating the FHIR service audience URL, register a client application and provide it access to FHIR service. Let us know if this approach resolves the issue for you.

**Comment by EXPEkesheth** [comment]
@NancyOsalaniya - Issue will be closed in a week, incase of no further updates.

**Comment by EXPEkesheth** [comment]
Closing the issue with above comment
