### ISSUE TITLE
Use the :identifier modifier for searching in subject fields

### ISSUE THREAD

**Issue by aematteo** [microsoft/fhir-server#3640]
**User story**
As a FHIR server consumer, I would to search for resources by subject field using the identifier modifier instead of the literal reference.
For example /Procedure?subject:identifier=system|value

**Comment by mikaelweave** [comment]
Hi @aematteo,

I don't think we support this currently as written above. The example above is searching without chaining. You can achieve this today with the search below which is the same search but with chaining.

`/Procedure?subject:Patient.identifier=system|value`

**Comment by EXPEkesheth** [comment]
@aematteo do you have any further questions? If no response, this thread will be closed in a week.
