### ISSUE TITLE
How to ingest data in Azure API for FHIR from SQL Server.

### ISSUE THREAD

**Issue by Kedar782** [microsoft/fhir-server#3645]
I want to ingest data from Sql Server into the Azure API for FHIR.
I don't have any idea about this. I will really appreciate your help on this. Is there any project online that I can use to ingest the data from the SQL server into Azure API for FHIR.

I will really appreciate your help on this.

**Comment by brendankowitz** [comment]
Hi @Kedar782, are you referring to a legacy/existing SQL database? Are you looking to migrate data and move to FHIR or setup a sync? Additionally, Health Data Services: FHIR has a Bulk import feature which would be a consideration.

**Comment by EXPEkesheth** [comment]
@Kedar782 - do you have any further questions? If no response, this issue will be closed in a week.
