### ISSUE TITLE
Support _destinationType and _destinationConnectionSettings in $export operation

### ISSUE THREAD

**Issue by jackliums** [Microsoft/fhir-server#365]
**User story**

As a user, I want to be able to specify the destination location so that the bulk export can directly write the output to.

**Acceptance criteria**
1. Verify `400 Bad Request` is returned if `_destinationType` query parameter is not specified or if specified and the value is not `AzureBlockBlob`.
1. Verify `400 Bad Request` is returned if `_destinationConnectionSettings` query parameter is not specified, or if specified and the value is not valid connection settings for the `AzureBlockBlob`.
1. Verify there is an abstraction layer `ISecretStore` and an implementation for `Azure KeyVault` that can be used to store and retrieve secrets.
1. Verify $export operation will store the `_destinationType` and `_destinationConnectionSettings` in the secret store and save the secret name in the job record.
1. Verify `500 Internal Server Error` is returned if saving the secret to the secret store fails.

**Comment by namadabu** [comment]
Moved tracking of user story level items to Azure DevOps.
