### ISSUE TITLE
Export resources into the appropriate file

### ISSUE THREAD

**Issue by jackliums** [Microsoft/fhir-server#366]
**User story**

As a user, I want to be able to export all resources to the appropriate destination file. There should be one file per resource type.

This user story:

- does not include the ability to resume export in the case of failure. If the job fails, it simply restarts from the beginning.
- does not include the ability to split the file. There will be one file per resource type.
- should include the implementation to retry the transient errors (e.g., network error). 
- should fail the job if it encounters error that's not retriable (e.g., unauthorized error).

**Acceptance criteria**

1. Verify one file is created for each resource type and all of the resources belonging to that resource type is exported to that file.
1. Verify the exported result is correct.
1. Verify the job retries up to X number of times in the case of transient error. 
1. Verify the job is marked as failure if it encounters a non-retriable error or if it fails even after retries in the previous step.
1. Verify job record is marked as completed if it succeeds
1. Verify job record is marked as failed if it fails.

**Comment by namadabu** [comment]
Moved tracking of user story level items to Azure DevOps.
