### ISSUE TITLE
Azure Health Data Services Fhir Service Questionnaire fhir resource not validation properly and returning non-informative response

### ISSUE THREAD

**Issue by iofh** [microsoft/fhir-server#3664]
Im not sure if this is the correct place to raise this issue. I am having issue with Azure Health Data Services's fhir service on STU3 version where sending a POST Questionnaire request results in a non-informative response.

sending a post request to https://*******.fhir.azurehealthcareapis.com/Questionnaire with the following json 
```
{
    "resourceType": "Questionnaire",
    "id": "123",
    "title": "Test",
    "status": "active",
    "useContext": [
        {
            "code": {
                "code": "L1",
                "display": "this is the element causing the issue"
            }
        }
    ]
}
```

returns
```
{
    "resourceType": "OperationOutcome",
    "id": "09f075cbe8277369597ae3b07casdfas",
    "meta": {
        "lastUpdated": "2024-01-11T02:49:13.2509628+00:00"
    },
    "issue": [
        {
            "severity": "error",
            "code": "unknown",
            "diagnostics": ""
        }
    ]
}
```

The issue is with the `useContext.code.display`. Without the display, the POST request execute fine. But with the display, the POST request fails.

Request below POST fine.
```
{
    "resourceType": "Questionnaire",
    "id": "123",
    "title": "Test",
    "status": "active",
    "useContext": [
        {
            "code": {
                "code": "L1"
            }
        }
    ]
}
```

i've tried different fhir resource that uses useContext and all were fine with having `useContext.code.display`. It's only the fhir Questionnaire having the issue

**FHIR Version**
Stu3

**Comment by EXPEkesheth** [comment]
Thanks for reporting the issue ! Have created bug [#114322](https://microsofthealth.visualstudio.com/Health/_workitems/edit/114322) to investigate. 
@iofh - Are you using FHIR service in OSS/ Azure Health Data Services managed service? If latter, you can create issue using support request

**Comment by iofh** [comment]
Im using the Azure Health Data Services managed service. THank you, will raise a support request with azure

**Comment by EXPEkesheth** [comment]
@iofh - thankyou ! We will close this ticket and look forward to support ticket on managed service.
