### ISSUE TITLE
Multiple App Service Instances

### ISSUE THREAD

**Issue by reubenelder** [microsoft/fhir-server#3843]
Hi,

Currently we host the OSS version of the FHIR server in an Azure App Service (we are hoping to move to the managed service pending a couple of features being available).  

For availability reasons Azure recommends using multiple instances in Azure App Services.  I've always assumed that this wouldn't be a problem but I wanted to double check that there is no reason the OSS version cannot run multiple instance count pointing to the same FHIR SQL database.

Thanks for your help,
Reuben

**Comment by EXPEkesheth** [comment]
@reubenelder there is nothing blocking you from running multiple instance count. Some caveats to note are the cached durations mapped with custom search and validate operation.  

On the side note, you mentioned about waiting on couple of features with managed service. Can you please share those?

**Comment by reubenelder** [comment]
thanks for the quick response.  What exactly do you mean about the "cached durations mapped with custom search"?

re: switching to managed service - I was referring to this issue:
https://github.com/microsoft/fhir-server/issues/3776

More specifically the need for us to be able to run this behind AFD and have the appropriate urls returned in the FHIR bundles (i.e. the url of the AFD instance not the FHIR service url).
Ideally we could also adjust the bundle count to 2000.

**Comment by feordin** [comment]
"cached durations for custom search parameters" refers to the fact that when you submit a new custom search parameter to the service, it will take time to propagate the change to all instances of your FHIR service.

**Comment by reubenelder** [comment]
cool - thanks for the explanation

**Comment by EXPEkesheth** [comment]
@reubenelder closing the issue as it is answered.
