### ISSUE TITLE
Centralize the OpenIdConfiguration related logic

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#385]
**Describe the bug**
There are multiple places where Open ID configuration is fetched (AadSmartOnFhirProxyController, 
CapabilityStatementExtensions). We should move them to a centralized location and initialize it at proper place (e.g., not inside constructor).

**Comment by EXPEkesheth** [comment]
No enhancements will be made to SMART on FHIR proxy and hence closing
