### ISSUE TITLE
How can a Practitioners get Patient data

### ISSUE THREAD

**Issue by phxtho** [microsoft/fhir-server#3853]
**Question**

We're using Azure Healthcare Services FHIR service (SQL Server backed I believe) with AAD B2C as our Identity provider, our users will be practitioners who will need to access patient data and by the look of [this test](https://github.com/microsoft/fhir-server/blob/5a98e34186cf9ef1f698c6edee1da59c60bad28a/test/Microsoft.Health.Fhir.Shared.Tests.Integration/Features/Smart/SmartSearchTests.cs#L493) this should be possible.

Is it possible for Practitioners who are not the patients `generalPractitioner` to query the patient data. i.e Practitioners in a CareTeam

**Comment by EXPEkesheth** [comment]
@phxtho - are you looking to use SMART on FHIR feature capability with this workflow? Reference page : [SMART on FHIR](https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/smart-on-fhir)

**Comment by EXPEkesheth** [comment]
@phxtho no response in a week, this issue will be marked as closed.

**Comment by EXPEkesheth** [comment]
Closing the issue
