### ISSUE TITLE
Search might return empty result with CT even though there might be data available

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#388]
**Describe the bug**

We had a report that a query similar to /Patient?identifier=11111111-1111-1111-1111-111111111111 was returning empty result even though the data exists in the database. Investigating further, the search was returning empty result with next link and if the next link is followed a few times, eventually the data shows up.

This is due to the fact that Cosmos DB executes queries partition by partition when EnableCrossPartitionQuery = true. When there are large enough data that spans multiple partitions, the query might not find matching data in the first partition it queries, and so it returns empty result back with continuation token.

This is not an idea behavior.

**To Reproduce**
1. Creates large enough data so that there are multiple partitions in Cosmos DB.
2. Search with a query that targets a specific record (not by id) such that the data cannot be found within the first partition.

**Expected behavior**

If the data exists, the search should do best effort and search until it finds one.

**Actual behavior**

Empty result is returned with a continuation token.

**Comment by CaitlinV39** [comment]
This is a by-product of using Cosmos. Given our focus on SQL we will close for now.
