### ISSUE TITLE
Which Issue is resolved in which release ?

### ISSUE THREAD

**Issue by LKShankarKarthik** [microsoft/fhir-server#3880]
We are using "Microsoft FHIR Server(OSS)" and hosting it on our Server. We would like to know, how to identify the bugs/issues are resolved (fixed) in which release? So we can upgrade to the required release?

**Comment by mikaelweave** [comment]
Hi @LKShankarKarthik, I would recommend checking the [releases page](https://github.com/microsoft/fhir-server/releases) in this repository. This will tell you which features/bug fixes are included in each release. 

Will this work for you?

**Comment by LKShankarKarthik** [comment]
Hi Mikael

Thanks. We are in a version which older than 18 Months now. So going through every release is challenging. If we know the BUG ID (like #3880), is it possible to know in which release that was resolved?

**Comment by EXPEkesheth** [comment]
@LKShankarKarthik - You can identify by doing a page search with pull request id.  Other than that, there is no direct way to link between bug id and release number.

**Comment by LKShankarKarthik** [comment]
@EXPEkesheth - Thanks. Im trying to navigate using the Issue ID. For eg: when I checked the Issue(Bug) #3755, its in closed state but there is NO pull request associated it.

![image](https://github.com/microsoft/fhir-server/assets/36524787/af46923c-4ef8-4b27-aecb-7dd0cfa4653b)

**Comment by EXPEkesheth** [comment]
Closing as the question is answered
