### ISSUE TITLE
gives error in publish for project.assets.json file

### ISSUE THREAD

**Issue by shahedaAnsari** [microsoft/fhir-server#4003]
**Question**

build the project in x64 platform and also run the command dotnet restore command
the project.assets.json file is created in obj folder but when we try to publish it checks the path obj/publish/win-64 for project.assets.json file
I applied lots of combination to fix this issue but still failed

can you please provide any solution for this

**Comment by EXPEkesheth** [comment]
@shahedaAnsari - Have you tried publishing artefacts with build configuration :any CPU ?

**Comment by shahedaAnsari** [comment]
I tried using any CPU also still same issue

**Comment by EXPEkesheth** [comment]
@shahedaAnsari - can you please share error details on the issue you are facing? Team members working on this project are not facing the issue and hence not able to repro on our end.

**Comment by shahedaAnsari** [comment]
![image](https://github.com/user-attachments/assets/ea2f1d68-4963-484d-a0db-e45b9a1b2f82)

while publishing the projects is expecting the project.assets.json file at "obj/publish/win-x64/project.assets.json" file but this file is generated at "obj/project.assets.json"

I tried in both any cpu and x64 still same issue

**Comment by EXPEkesheth** [comment]
@shahedaAnsari this seems to be your environment specific. Are you able to build and run local debug? You can refer further to this [link](https://github.com/microsoft/fhir-server/wiki/Build-and-debug-locally) for further assistance.

**Comment by shahedaAnsari** [comment]
@EXPEkesheth  I am able to build and run locally but when I published that time it is giving error

**Comment by EXPEkesheth** [comment]
@shahedaAnsari - we publish our build artifacts , please refer to the [yml](https://github.com/microsoft/fhir-server/blob/main/build/jobs/package-web.yml) as an example.

**Comment by EXPEkesheth** [comment]
@shahedaAnsari - with no response the issue will be closed in a week

**Comment by shahedaAnsari** [comment]
currently we are not using CI / CD. Not have much knowledge regarding yml

**Comment by EXPEkesheth** [comment]
@shahedaAnsari - This seems to be associated with your specific environment. We apologize but we wont be able to help further.
