### ISSUE TITLE
Requests to /AadSmartOnFhirProxy with invalid params return 500

### ISSUE THREAD

**Issue by cunninghamjc** [microsoft/fhir-server#406]
**Describe the bug**
Calling the SMART on FHIR proxy's APIs with invalid params returns 500.

**To Reproduce**
1. GET /AadSmartOnFhirProxy/authorize (no query params)
1. GET /AadSmartOnFhirProxy/callback/baddata

**Expected behavior**
400 with an operation outcome explaining the problem.

**Actual behavior**
500 with the following response:
```
{
  "resourceType": "OperationOutcome",
  "id": "38b57afda0e1c445808614327dcbcab6",
  "issue": [
    {
      "severity": "error",
      "code": "exception",
      "diagnostics": "There was an error processing your request."
    }
  ]
}
```

**Comment by brandonpollett** [comment]
@feordin - Can this be closed since #428 was merged?
