### ISSUE TITLE
SmartProxy E2E test is failing

### ISSUE THREAD

**Issue by namadabu** [Microsoft/fhir-server#409]
**Describe the bug**
The SmartProxy E2E test is failing with the following error:
Microsoft.Health.Fhir.Tests.E2E.SmartProxy.SmartProxyTests.GivenPatientIdAndSmartAppUrl_WhenLaunchingApp_LaunchSequenceAndSignIn [FAIL]
Failed  Microsoft.Health.Fhir.Tests.E2E.SmartProxy.SmartProxyTests.GivenPatientIdAndSmartAppUrl_WhenLaunchingApp_LaunchSequenceAndSignIn
Error Message:
OpenQA.Selenium.WebDriverException : unknown error: Element <input type="submit" id="idSIButton9" class="btn btn-block btn-primary" data-bind="

**To Reproduce**
1. Just running the test against a test environment is enough to trigger the failure.

**Expected behavior**
Test should pass

**Actual behavior**
Test fails

**Comment by hansenms** [comment]
@namadabu is this a persistent error or does it repeating fix it. Some of these selenium tests are a bit problematic.

**Comment by namadabu** [comment]
This test started failing recently and in a consistent manner. We (Raja and @brandonpollett) figured out that we were moving through the buttons/actions too quickly. PR out to fix it - https://github.com/Microsoft/fhir-server/pull/410
