### ISSUE TITLE
PartialDateTime should not allow Hour and Minute without Seconds

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#411]
**Describe the bug**

According to the spec (http://hl7.org/fhir/STU3/datatypes.html#datetime):

> A date, date-time or partial date (e.g. just year or year + month) as used in human communication. If hours and minutes are specified, a time zone SHALL be populated. Seconds must be provided due to schema type constraints but may be zero-filled and may be ignored. Dates SHALL be valid dates. The time "24:00" is not allowed.

Current implementation allows hour and minute without seconds so that should be changed.

**Comment by johnstairs** [comment]
@LTA-Thinking this part of the spec does not seem to be enforced:
> If hours and minutes are specified, a time zone SHALL be populated

**Comment by LTA-Thinking** [comment]
Strange. We seem to have code to handle that senario: https://github.com/microsoft/fhir-server/blob/13a410bea18435288e7725b5be8fd324c0dac310/src/Microsoft.Health.Fhir.Core/Models/PartialDateTime.cs#L110. I'll look into it.

**Comment by rotodd** [comment]
As discussed with @jackliums, the current implementation where seconds are populated if hours and minutes are specified is fine.

The [spec](http://hl7.org/fhir/search.html#date) does not indicate that seconds need to be provided by the user when specifying a `DateTime` search parameter.
