### ISSUE TITLE
[((@@VIRAL~VIDEO@@)) Original James Charles Leaked VIDEO Reddit Twitter

### ISSUE THREAD

**Issue by gh-cobaia** [microsoft/fhir-server#4256]
[((@@TERABOX~VIDEO@@)) Original James Charles Leaked VIDEO Reddit Twitter

🟢➤➤➤🌐CLICK HERE TO WATCH LEAKED VIDEO ONLINE

[🔴➤►👉👉CLICK HERE DOWNLOAD FULL VIDEO HD

In the aftermath of the horrific rape and murder of a junior doctor at RG Kar Medical College and Hospital in Kolkata, a video has surfaced on social media claiming to show her final moments. This video has caused widespread outrage and confusion. However, it has been confirmed upon investigation that the video is unrelated to the tragic incident.

Social Media Posts:
A viral short video clip purports to show the last moments of the doctor who was raped and murdered in Kolkata. The video claims to depict tragic scenes of the doctor recording herself shortly before her death.

Facebook

The story gained traction on social media, and the sensational nature of the video further fueled the claim, which quickly spread across platforms like Facebook and YouTube.

The video was viral on TikTok also.

Fact-Check :
Recently, a video has gone viral on social media, claiming to show the final moments of the late Dr. Moumita Debnath, a doctor who was allegedly raped and murdered. This video has stirred significant emotions and concerns, prompting many to question its authenticity.

Source of the Video:
We searched for some of the first occurrences of the video and noticed they had been shared at least since August 15th, as seen here. While some initial videos were removed now, these posts claimed that the clip was an instance of the late Dr Moumita recording her last moments and sending them to her mother. However, we didn’t notice any report from international media of such a video being sent to Moumita’s mother.

While several users also highlighted the unrelated viral video making rounds, we couldn’t identify the source of the video; it appears to be a scene from a staged scene, not a recording by the victim. Also, upon close inspection, it appears that the face of the victim in this tragic incident, the late Dr Moumita Debnath, does not match that of the girl seen in the viral video either.

While the video appears to recreate the pain Dr Moumita endured during her last moments, its visual and thematic content matches scenes from a fictional production that has been taken out of context to mislead the public.

WHEN
August 21, 2024 at 6:00pm - 9pm

**Comment by isratjerinruba2** [comment]
https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

https://skylivetvgo.com/viral/?jaes

**Comment by viralvid** [comment]
<h3><a href="//black-adam-watch-online.blogspot.com/">WATCH HERE Full ➣➣ Sona Dey Viral Video MMS </a></h3>

<h3><a href="//black-adam-watch-online.blogspot.com/">Download NOW Full ➣➣Sona Dey Viral Video MMS  </a></h3>

<a href='//black-adam-watch-online.blogspot.com/' title='PLAY NOW'><img src='https://github.com/thecwtv/-Watch-VIRAL-Video-Sona-Dey-Viral-Video-MMS-On-Twitter-and-TikTok/blob/main/player.jpg?raw=true' /></a>




.
...
.
.<h3><a href="//black-adam-watch-online.blogspot.com/">WATCH HERE Full ➣➣ Sona Dey Viral Video MMS </a></h3>

<h3><a href="//black-adam-watch-online.blogspot.com/">Download NOW Full ➣➣Sona Dey Viral Video MMS  </a></h3>

<a href='//black-adam-watch-online.blogspot.com/' title='PLAY NOW'><img src='https://github.com/thecwtv/-Watch-VIRAL-Video-Sona-Dey-Viral-Video-MMS-On-Twitter-and-TikTok/blob/main/player.jpg?raw=true' /></a>




.
...
.
.<h3><a href="//black-adam-watch-online.blogspot.com/">WATCH HERE Full ➣➣ Sona Dey Viral Video MMS </a></h3>

<h3><a href="//black-adam-watch-online.blogspot.com/">Download NOW Full ➣➣Sona Dey Viral Video MMS  </a></h3>

<a href='//black-adam-watch-online.blogspot.com/' title='PLAY NOW'><img src='https://github.com/thecwtv/-Watch-VIRAL-Video-Sona-Dey-Viral-Video-MMS-On-Twitter-and-TikTok/blob/main/player.jpg?raw=true' /></a>




.
...
.
.<h3><a href="//black-adam-watch-online.blogspot.com/">WATCH HERE Full ➣➣ Sona Dey Viral Video MMS </a></h3>

<h3><a href="//black-adam-watch-online.blogspot.com/">Download NOW Full ➣➣Sona Dey Viral Video MMS  </a></h3>

<a href='//black-adam-watch-online.blogspot.com/' title='PLAY NOW'><img src='https://github.com/thecwtv/-Watch-VIRAL-Video-Sona-Dey-Viral-Video-MMS-On-Twitter-and-TikTok/blob/main/player.jpg?raw=true' /></a>




.
...
.
.<h3><a href="//black-adam-watch-online.blogspot.com/">WATCH HERE Full ➣➣ Sona Dey Viral Video MMS </a></h3>

<h3><a href="//black-adam-watch-online.blogspot.com/">Download NOW Full ➣➣Sona Dey Viral Video MMS  </a></h3>

<a href='//black-adam-watch-online.blogspot.com/' title='PLAY NOW'><img src='https://github.com/thecwtv/-Watch-VIRAL-Video-Sona-Dey-Viral-Video-MMS-On-Twitter-and-TikTok/blob/main/player.jpg?raw=true' /></a>




.
...
.
.<h3><a href="//black-adam-watch-online.blogspot.com/">WATCH HERE Full ➣➣ Sona Dey Viral Video MMS </a></h3>

<h3><a href="//black-adam-watch-online.blogspot.com/">Download NOW Full ➣➣Sona Dey Viral Video MMS  </a></h3>

<a href='//black-adam-watch-online.blogspot.com/' title='PLAY NOW'><img src='https://github.com/thecwtv/-Watch-VIRAL-Video-Sona-Dey-Viral-Video-MMS-On-Twitter-and-TikTok/blob/main/player.jpg?raw=true' /></a>




.
...
.
.<h3><a href="//black-adam-watch-online.blogspot.com/">WATCH HERE Full ➣➣ Sona Dey Viral Video MMS </a></h3>

<h3><a href="//black-adam-watch-online.blogspot.com/">Download NOW Full ➣➣Sona Dey Viral Video MMS  </a></h3>

<a href='//black-adam-watch-online.blogspot.com/' title='PLAY NOW'><img src='https://github.com/thecwtv/-Watch-VIRAL-Video-Sona-Dey-Viral-Video-MMS-On-Twitter-and-TikTok/blob/main/player.jpg?raw=true' /></a>




.
...
.
.<h3><a href="//black-adam-watch-online.blogspot.com/">WATCH HERE Full ➣➣ Sona Dey Viral Video MMS </a></h3>

<h3><a href="//black-adam-watch-online.blogspot.com/">Download NOW Full ➣➣Sona Dey Viral Video MMS  </a></h3>

<a href='//black-adam-watch-online.blogspot.com/' title='PLAY NOW'><img src='https://github.com/thecwtv/-Watch-VIRAL-Video-Sona-Dey-Viral-Video-MMS-On-Twitter-and-TikTok/blob/main/player.jpg?raw=true' /></a>




.
...
.
.ss

**Comment by kkpbalikpapan** [comment]
🔴 ➤► LINK DOWNLOAD ✅👉 **[Yandex Semua Film](https://github.com/sephianiarxi/-Download-Yandex-Semua-Film-Video-Bokeh-HD-Jepang-Tanpa-VPN-/)**

🔴 ➤► LINK DOWNLOAD ✅👉 **[Yandex Semua Film](https://github.com/sephianiarxi/LINK-DOWNLOAD-Yandex-Semua-Film-Video-Bokeh-HD-Jepang-Tanpa-VPN/)**

🔴 ➤► LINK DOWNLOAD ✅👉 **[Yandex Semua Film](https://github.com/sephianiarxi/-WATCH-Yandex-Semua-Film.-Video-Bokeh-HD-Jepang-Tanpa-VPN-Gratis-/)**

🔴 ➤► LINK DOWNLOAD ✅👉 **[Yandex Semua Film](https://github.com/sephianiarxi/-LINK-DOWNLOAD-Yandex-Semua-Film-Viral-Terbaru-2024-Bebas-Gak-Perlu-VPN)**

🔴 ➤► LINK DOWNLOAD ✅👉 **[Yandex Semua Film](https://github.com/sephianiarxi/Yandex-Semua-Film-Video-Negara-Indonesia-Terbaru-2024/)**

🔴 ➤► LINK DOWNLOAD ✅👉 **[Yandex Semua Film](https://github.com/sephianiarxi/Download-Yandex-Browser-Jepang-2024-Streaming-Tanpa-Iklan-di-Semua-Perangkat/)**

🔴 ➤► LINK DOWNLOAD ✅👉 **[Yandex Semua Film](https://github.com/sephianiarxi/-LINK-DOWNLOAD-NONTON-Semua-Film-dan-Video-Bokeh-Viral-Japan-di-Yandex-Semua-Jepang-Yandex-Com/)**

🔴 ➤► LINK DOWNLOAD ✅👉 **[Yandex Semua Film](https://github.com/sephianiarxi/Yandex-Semua-Film-Video-Bokeh-HD-Jepang-Tanpa-VPN/)**
