### ISSUE TITLE
Continuation tokens exceed max URL length for App Service

### ISSUE THREAD

**Issue by hansenms** [microsoft/fhir-server#442]
**Describe the bug**
The `CosmosDb:ContinuationTokenSizeLimitInKb` setting is default set to `2`. The resulting continuation tokens can exceed the max URL length for App Service.

**To Reproduce**
1. Deploy OSS server with App Service
2. Load several thousand patients. 
3. Attempt to follow next link.

**Expected behavior**
The continuation token should not exceed max URL length in App Service. We should default to `CosmosDb:ContinuationTokenSizeLimitInKb = 1` when deploying in App Service.  

**Actual behavior**
URLs are too long and we get resource not found.

**Comment by brandonpollett** [comment]
@hansenms - Can this be closed?
