### ISSUE TITLE
AAD SMART on FHIR proxy error messages return internal variable names

### ISSUE THREAD

**Issue by brandonpollett** [microsoft/fhir-server#445]
**Describe the bug**
In the AAD smart on FHIR proxy, when you don't pass in a parameter/form value, the 400 response includes the internal variable name instead of the parameter/form name. This occurs for a number of variables within the methods on the controller. 

**To Reproduce**
1. Issue POST to //fhirserver/AadSmartOnFhirProxy/token

**Expected behavior**
The server responds that a parameter is missing with the name of the parameter. In this case `grant_type`

**Actual behavior**
The server responds that a parameter is missing with the name `grantType` which is the internal variable name. 

AB#101210

**Comment by CaitlinV39** [comment]
@brandonpollett is this still an issue?

**Comment by netinorthwell** [comment]
I just had this happen to me as well when trying to launch the SmartLauncher
![image](https://user-images.githubusercontent.com/64535712/93632263-0c5f6380-f9bb-11ea-97c5-83ab23b3cd68.png)

**Comment by EXPEkesheth** [comment]
Closing as stale issue. There is enhanced capability available for integrating with SMART on FHIR IG https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/smart-on-fhir. Let us know if you have further questions
