### ISSUE TITLE
Profile Extensions Not Being Validated

### ISSUE THREAD

**Issue by edwinnswift** [microsoft/fhir-server#4695]
I have a profile on Practitioner that includes extension definitions as follows

![Image](https://github.com/user-attachments/assets/3ea2e266-f0e3-4f26-8450-9a434f2e29fb)

The profile structure definition has been uploaded to the server, as well as each extension structure definition. I also have a slice on identifier as illustrated above. If I try to create the Practitioner resource without the required identifier I get the expected operation outcome. However, if I make one of the extensions mandatory, I do not get the same result. Furthermore, if I attempt to create the extension with a type other than what is defined (e.g. valueString vs valueReference) I do not receive a negative outcome.

Clearly the profile is defined correctly since the identifier is being validated. Am I missing something with the extensions?

**Comment by EXPEkesheth** [comment]
@edwinnswift, could you please provide steps to reproduce the issue? We would also like to understand how you are using the $validate operation. For more information on the validation operation, please see the [documentation link](https://learn.microsoft.com/en-us/azure/healthcare-apis/fhir/validation-against-profiles).

**Comment by EXPEkesheth** [comment]
Closing issue as it is working as expected
