### ISSUE TITLE
Add a compartment index for self if resource type and compartment type match

### ISSUE THREAD

**Issue by garamamo** [microsoft/fhir-server#486]
CompartmentIndexer should add an index for self in case the resource type matches the compartment type.

For example queries such as below should return self.
/Patient/1/Patient should also return patient with id 1.
/Encounter/99/Encounter should also return encounter with id 99
and so on.

Necessary code changes in CompartmentIndexer.cs.
Extract method in CompartmentIndexer should take the entire resource or additionally the resource id.
If the resource type and compartment type match (e.g. Patient, Device, Practitioner, RelatedPerson, Encounter), add an additional resource id of the id from the resource to the resourceIds hashset.

**Comment by CaitlinV39** [comment]
Reviewed and closing as won't fix
