### ISSUE TITLE
Removed the destination info from the request URI.

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#503]
**Describe the bug**
We store the complete requestUri when saving the ExportJobRecord in the data store. This uri will contain destination connection information in the query parameters. We need to remove this information before storing the requestUri.

**To Reproduce**
1. Create a new export job with _destinationType and _destinationConnectionSettings.

**Expected behavior**
The request URI stored in the datastore should not contain the secret.

**Actual behavior**
The request URI stored in the data store contains the secret.

**Comment by brandonpollett** [comment]
@jackliums can this be closed?
