### ISSUE TITLE
Multiple composite search doesn't always work

### ISSUE THREAD

**Issue by brandonpollett** [microsoft/fhir-server#523]
**Describe the bug**
When doing a composite search with multiple values specified and separated by a `,`, you can get unexpected results depending on the data.

**To Reproduce**
Given at least two `DocumentReference` documents, on with each of the following two sections, execute a search like `relationship=DocumentReference/example-appends,DocumentReference/example-replaces$replaces` or `relationship=DocumentReference/example-appends$appends,DocumentReference/example-replaces$replaces`

```json
"relatesTo": [
    {
      "code": "appends",
      "target": {
        "reference": "DocumentReference/example-appends"
      }
    }
  ],
```

```json
"relatesTo": [
    {
      "code": "transforms",
      "target": { "reference": "DocumentReference/example-transforms" }
    },
    {
      "code": "replaces",
      "target": { "reference": "DocumentReference/example-replaces" }
    }
  ],
```

**Expected behavior**
The expected behavior would be that you would get both resources back.

**Actual behavior**
You actually only receive the document containing the example-replaces back or the server throws an exception.

**Comment by jackliums** [comment]
In `SearchParameterExpressionParser.Parse1 method, when the value is composite search parameter, it doesn't split the supplied value by OR separator so the search value `DocumentReference/example-appends,DocumentReference/example-replaces$replaces` gets split into `relationship=DocumentReference/example-appends,DocumentReference/example-replaces` and `replaces`, which is incorrect. We need to follow the same pattern for non-composite search value, which is to parse the OR separater first, then process each part.

**Comment by johnstairs** [comment]
@brandonpollett, I don't think 

```
relationship=DocumentReference/example-appends,DocumentReference/example-replaces$replaces
``` 
is valid.  On the other hand, 
```
relationship=DocumentReference/example-appends$appends,DocumentReference/example-replaces$replaces
````

is valid because both options that are ORed together specify the all composite components.

The spec just says:
>This sequence is a single value and itself can be composed into a set of values, so that, for example, multiple matching characteristic-value parameters can be specified as `GET [base]/Group?characteristic-value=gender$mixed,owner$Eve`

**Comment by brandonpollett** [comment]
@johnstairs Makes sense.

**Comment by CaitlinV39** [comment]
closing as duplicate
