### ISSUE TITLE
Resolve() in search parameters results in an exception

### ISSUE THREAD

**Issue by brandonpollett** [microsoft/fhir-server#534]
**Describe the bug**
When resolve() is used in a search parameter, the indexing code throws an exception.

**To Reproduce**
Update search parameters to use resolve()
`Observation.subject.where(resolve() is Patient)`

**Expected behavior**
observation has a "Patient" search parameter indexed with the reference type and value of the reference.

**Actual behavior**
An exception is thrown internally and the value is not indexed. You can stop the exception by adding `FhirPathCompiler.DefaultSymbolTable.AddFhirExtensions();` in the startup, but the indexing still doesn't occur.

**Temporary workaround**
A temporary workaround is to use the previous search-parameter definition that doesn't include resolve.

**Comment by brendankowitz** [comment]
This was implemented in #904
