### ISSUE TITLE
Validation messages are missing details

### ISSUE THREAD

**Issue by johnstairs** [microsoft/fhir-server#536]
**Describe the bug**
The server provides insufficient information when rejecting a POST because of validation errors

**To Reproduce**
```
curl -X POST \
  https://localhost:44348/DiagnosticReport \
  -H 'Accept: */*' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Host: localhost:44348' \
  -H 'User-Agent: PostmanRuntime/7.13.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 39' \
  -d '{
	"resourceType": "DiagnosticReport"
}'
```
**Expected behavior**
Information about which elements are missing

**Actual behavior**
``` json
{
    "resourceType": "OperationOutcome",
    "id": "bd982592-509b-42c2-be8f-90fc304869bb",
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "Element with min. cardinality 1 cannot be null"
        },
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "Element with min. cardinality 1 cannot be null"
        }
    ]
}
```

**Comment by johnstairs** [comment]
cc @brendankowitz

**Comment by ElYusubov** [comment]
I am seeing same generic error on FHIR API as well.
@johnstairs & @brendankowitz is there an ETA when error details will be added?

![image](https://user-images.githubusercontent.com/29330538/64457694-4f58dc80-d0c1-11e9-98f2-5eeffb6feccd.png)

**Comment by brendankowitz** [comment]
I'm pretty sure the information is there, it's just not being passed through correctly. I'll look at getting this scheduled.
