### ISSUE TITLE
Support multi tenanted use case

### ISSUE THREAD

**Issue by nzandy** [microsoft/fhir-server#545]
**User story**
As a provider of clinical data to multiple consumers I want a way to restrict what resources consumers have access to so that consumers can only access data that belongs to them.

**Acceptance criteria**
1. Have a standard way for an API consumer to be associated with specific resources that are retuned by the API.
2. The proposed solution does not involve rolling out a seperate server for each consumer group.

Questions:
1) Has anyone currently implemented this logic on top of microsoft/fhir-server?
2) Is there a suggested workflow for implementing this?
3) If not, is this feature on the roadmap?

**Comment by hansenms** [comment]
Could you clarify what you mean by "consumer". If by consumer you mean "Patient", then we do index the Patient compartment, so for instance:

```
GET //server/Patient/1234/*
```

Gives you all the resources for patient `1234`

**Comment by nzandy** [comment]
An example would be if we provide a SaaS solution to multiple clinical providers, each that has their own groups of patients, appointments etc. For each clinical provider we would only want them to be able to access data that is relevant (owned?) by them.

For your above example, patient `1234` may belong to ClinicalProviderId = 1. Therefore that `GET //server/Patient/1234/*` should only work for that specific ClinicalProviderId, and not for anyone else.

**Comment by hansenms** [comment]
Sure, how would you express that data boundary in FHIR?

If you really want to segment the data between providers and you don't have a way to express it in terms of compartments or some other FHIR based rule, they should probably have separate FHIR servers. 

There are probably some things you could do like use API management in front of the FHIR server to append metadata tags to resources added from specific providers and then append all searches with that metadata predicate. 

Again, the more solid solution is separate databases.

**Comment by CaitlinV39** [comment]
@nzandy I'm going to close this issue based on Michael's response but if you have additional questions or information please let us know. Thanks!
