### ISSUE TITLE
Running locally instructions

### ISSUE THREAD

**Issue by courtenayparserr** [microsoft/fhir-server#556]
Curious if there are any instructions for running locally from VS? Particularly with SQL first?

Launching the smartlauncher we get this:

![image](https://user-images.githubusercontent.com/24819057/60247879-da209c80-9904-11e9-90a9-dc567c9b5c84.png)

**Comment by ElYusubov** [comment]
@courtenayparserr did you get response on how to run it locally?

**Comment by courtenayparserr** [comment]
@ElYusubov its a bit of a process but eventually got there. I didn't use the smart launcher. I just ran the API itself project itself (Microsoft.Health.Fhir.R4.Web). I found it didnt support what we needed so we went with another open-source FHIR server

**Comment by ElYusubov** [comment]
@courtenayparserr - quick question.
Do you see identidtyserver error when running Microsoft.Health.Fhir.R4.Web with Cosmos? (details of error are posted here [https://github.com/microsoft/fhir-server/issues/595](https://github.com/microsoft/fhir-server/issues/595) )

Or did you run it with local SQL instance connection?
