### ISSUE TITLE
Mapping Practitioners and AAD accounts for RBAC

### ISSUE THREAD

**Issue by jahead** [microsoft/fhir-server#560]
**User story**
Hey guys, love your work.
I'm aware of the current plans to improve the Authorization story in the service with more a powerful RBAC story. 
However, our current user story is using this API service in Azure to do a triage decision aid tool that maps to directly to the FHIR API, for a clinical trial. What we would like to have is The Clinicians logging in using their @nswhealth.gov.au logins using federated access (this is solved), but these logins are mapped to their respective practitioner objects. We then would also like to use PractitionerRole objects to control access to patients and organization objects.

We don't mind doing some leg work here, obviously, it would be much better if we could leverage the PaaS solution, but I get that solution will have to wait for future releases. 
We are looking for direction on how we could modify the solution to change Authorization policies, and add query filters to enforce this authorization 

**Acceptance criteria**
1. AAD 1:1 with Practitioner
    * we would prefer that the practitioner is provisioned on the DDT Tool first. As Health Orgs don't like to sync up.
2. Filter query results Based on this relationship. 
    * Resource -> organization -> PractitionerRole -> Practitioner
       * All resources that we are looking to use can be tied to a practitioner or organization in some way. 
3. restrict resource action based on PractitionerRole.  Clinician | Researcher | Admin

`3` is not so much of an importance for the initial trial, but will become more of an issue as the trial sites grow. 

I saw someone saying that we could leverage a management API to trivial filter query results, by appending filters as a proxy. But we still need to map the PractitionerId with the ADD.

**Comment by hansenms** [comment]
We are very much interested in these scenarios. I think this one might require getting on a call to sort out some of the details. Can you email me `mihansen` AT `microsoft.com` we will try to find some time. Please add as much detail as possible in your email.

We will keep this issues open to track RBAC scenatios.

**Comment by jahead** [comment]
Done, and done. Yea, the call should hopefully be a short one, the RBAC solution we hope to be simple.

**Comment by CaitlinV39** [comment]
We have recently released RBAC in the Azure API for FHIR and will continue to make updates there. For now, closing this as won't fix in the open source FHIR Server.
