### ISSUE TITLE
Self-link is incorrect when paging

### ISSUE THREAD

**Issue by hansenms** [microsoft/fhir-server#561]
**Describe the bug**
If you follow the `next` link on a search, the `self` link on page 2 and beyond will point to the original search, i.e. the first page. 

**To Reproduce**
1. Perform a search the returns many results.
2. Follow the `next` link
3. Follow the `self` link on page 2, it will take you back to start

**Expected behavior**
`self` link should point to the page itself, not to the first page. 

**Actual behavior**
`self` link always points to first page.

**Comment by feordin** [comment]
Verified as fixed
