### ISSUE TITLE
Supports for Lists endpoint?

### ISSUE THREAD

**Issue by courtenayparserr** [microsoft/fhir-server#571]
**User story**
As a Client, I want to support the Lists endpoint so that I can process a number of transactions.

https://www.hl7.org/fhir/list.html

**Acceptance criteria**

**Comment by hansenms** [comment]
`List` is supported. Can you clarify.

**Comment by courtenayparserr** [comment]
Apologies.

We have a need to create a list (how does one create one through the API?) which maintains a list of Patients whose details have otherwise recently changed (keeps two disparate systems syncing). We are aware this isnt perfect for now but its our MVP.

Is that possible?

**Comment by hansenms** [comment]
The purpose of `List` is to create a point in time collection of resources and you would create it with:

```
POST /List
```

With the actual list. The `List` resource does not imply a query or collection that is dynamically updated when things change. 

What you are talking about could be a `Subscription` where changes to a certain search trigger some hook. That spec is currently in some flux and we don't support it. 

A simpler version may be just using the `_history` query as a change feed.

Either way, I don't think `List` is what you are looking for unless you are reading something different into the spec?

**Comment by courtenayparserr** [comment]
No that's all good.

We are looking to keep two fhir servers in sync which actually brought up another issue in Id's relating to this issue here: https://github.com/microsoft/fhir-server/issues/236

Our source FHIR server provides Id's, but the CREATE request on our OSS MS Server doesn't respect those if passed in as spoken about here: https://www.hl7.org/fhir/http.html#upsert

If we try the PUT request, that doesnt work either, however it does say its supported here: https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir-features-supported#rest-api

**Comment by hansenms** [comment]
Please clarify. 

`PUT` is supported. Specifically if you do say:

```
PUT //fhirserver/Patient/1234
```

with a payload of:

```json
{
    "resourceType": "Patient",
    "id": "1234",
     //...
}
```

Patient `1234` will get replaced (creating a new version) with the new Patient payload. If you have an example of this not working, please submit it here and we will investigate.

**Comment by hansenms** [comment]
@courtenayparserr wanted to follow up here Can you confirm that `PUT` is working for you or do you still have issues.

**Comment by brendankowitz** [comment]
Given the name of the original issue, I'm tracking support for _list here: https://github.com/microsoft/fhir-server/issues/1071
