### ISSUE TITLE
Capability statement summary does not include SMART on FHIR security auth extensions

### ISSUE THREAD

**Issue by namalu** [microsoft/fhir-server#572]
**Describe the bug**
Making a GET request for the CapabilityStatement resource and including _summary=true, results in the omission of SMART on FHIR security extensions used for authentication.

**To Reproduce**
1. Enable the SMART on FHIR Proxy on the server
2. Request the CapabilityStatment summary (e.g. https://FHIR_SERVER/metadata?_summary=true) 

**Expected behavior**
The CapabilityStatment resource should be returned with the SMART on FHIR security extensions.

**Actual behavior**
The CapabilityStatment resource does not include the SMART on FHIR security extensions.

**Comment by hansenms** [comment]
Given that the SMART on FHIR security extensions are extensions, I am not sure they should be returned:

https://www.hl7.org/fhir/search.html#summary

Looking at the StructureDefinition for `CapabilityStatement`:

```json
{
      "id" : "CapabilityStatement.rest.security.extension",
      "path" : "CapabilityStatement.rest.security.extension",
      "short" : "Additional content defined by implementations",
      "definition" : "May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.",
      "comment" : "There can be no stigma associated with the use of extensions by any application, project, or standard - regardless of the institution or jurisdiction that uses or defines the extensions.  The use of extensions is what allows the FHIR specification to retain a core level of simplicity for everyone.",
      "alias" : ["extensions",
      "user content"],
      "min" : 0,
      "max" : "*",
      "base" : {
        "path" : "Element.extension",
        "min" : 0,
        "max" : "*"
      },
      "type" : [{
        "code" : "Extension"
      }],
      "isModifier" : false,
      "isSummary" : false,
      "mapping" : [{
        "identity" : "rim",
        "map" : "n/a"
      }]
    }
```

It explicitly sets `isSummary` to `false`. According to the spec it says about the `_summary=true` result: **This subset SHOULD consist solely of all supported elements that are marked as "summary" in the base definition of the resource(s)**.

So I understand why getting this is helpful, but I am not sure it should be returned. 

@jmandel, do you have some insights?

**Comment by CaitlinV39** [comment]
@namalu are you okay for me to close this issue or is there additional discussion you'd like to have on it?
