### ISSUE TITLE
SqlMetadataUtilities crashes in EU regional cultures 

### ISSUE THREAD

**Issue by devcs21** [microsoft/fhir-server#577]
**Describe the bug**
EU uses comma (",") as number decimal separator
USA uses dot "."
so
this code crashes (format exception) when one tries to run ms fhir server in EU-environment

private static decimal GetMinOrMaxSqlDecimalValueForColumn(SqlMetaData columnMetadata, bool min)
        {
            EnsureArg.IsNotNull(columnMetadata, nameof(columnMetadata));
            EnsureArg.Is((int)SqlDbType.Decimal, (int)columnMetadata.SqlDbType, nameof(columnMetadata));

            **var val = decimal.Parse($"{new string('9', columnMetadata.Precision - columnMetadata.Scale)}.{new string('9', columnMetadata.Scale)}");**
            return min ? -val : val;
        }
**To Reproduce**
1.  windows based systems: go to Settings->Time & Language->Region
2. Set any EU-based regional format 
3. Try to run ms fhir server in SQL Server mode
4. Format exception in \src\Microsoft.Health.Fhir.SqlServer\Features\Schema\Model\SqlMetadataUtilities.cs

**Expected behavior**
Correctly define number separator based on current culture

**Actual behavior**
Format Exception while trying to parse

proposal: our current workaround for this issue is:

 var separator = Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator;

  var val = decimal.Parse($"{new string('9', columnMetadata.Precision - columnMetadata.Scale)}**{separator}**{new string('9', columnMetadata.Scale)}");

**Comment by CaitlinV39** [comment]
AB#76057

**Comment by CaitlinV39** [comment]
@devcs21 this has been resolved. Let us know if you have any other issues!
