### ISSUE TITLE
lost Sorting data while parsing incoming search parameters

### ISSUE THREAD

**Issue by devcs21** [microsoft/fhir-server#578]
**Describe the bug**
if one sends sorting parameters to fhir server it  lost them in SearchOptionsFactory so it's impossible to sort

**To Reproduce**
1. open Visual Studio, go to SearchOptionsFactory->Create method
2. Set a breakpoint on " return searchOptions;" 
3. using postman/fiddler/(or custom FHIR client of your choice) send a request with "sort" parameter in URL  something like that https://localhost:44348/CommunicationRequest?_sort=-occurrence&occurrence=lt2019-07-12 
4. once reached breakpoint go to "watch" window:
searchParams variable **contains** sorting parameter (searchParams.Sort property  contains correct sorting data) but searchOptions does **not**

**Expected behavior**
Add sorting parameter data to returning searchOptions

**Actual behavior**
sorting parameters are not processed in any way

possible fix (our current workaround):
1. modify Microsoft.Health.Fhir.Core.Features.Search.SearchOptions by adding new property:
public IEnumerable<Tuple<string, string>> Sort { get;  set; }

2. modify Microsoft.Health.Fhir.Core.Features.Search.SearchOptionsFactory by adding this code **before** "return searchOptions;" statement :
             if (null != searchParams.Sort && 0 < searchParams.Sort.Count)
            {
                searchOptions.Sort = searchParams.Sort.Select(sorting => Tuple.Create(sorting.Item1, 
                                                                               sorting.Item2.ToString()));
            }

            return searchOptions;

**Comment by jackliums** [comment]
We haven't implemented the sorting yet and that's why it's not being handled currently. But we could expose it in the SearchOptions at least so if someone needs to use it, it won't be lost.

**Comment by devcs21** [comment]
@jackliums it would be great!
