### ISSUE TITLE
Deployment from Master deploys STU3

### ISSUE THREAD

**Issue by mmacagno** [microsoft/fhir-server#582]
After deploying from master through the documented template:

```bash
az group deployment create -g $(groupName) --template-uri https://raw.githubusercontent.com/Microsoft/fhir-server/master/samples/templates/default-azuredeploy.json --parameters serviceName=$(serviceName) securityAuthenticationAuthority=${authenticationAuthority} securityAuthenticationAudience=${authenticationAudience}
```
The application configuration seems to indicate that the project is using Stu3 instead of R4.

![image](https://user-images.githubusercontent.com/2315384/61254866-0d439800-a71b-11e9-96af-fb8af2d09da4.png)

Is that accurate? I believe it should be src/Microsoft.Health.Fhir.R4.Web/Microsoft.Health.Fhir.R4.Web.csproj.

**Comment by hansenms** [comment]
You will get R4 if you add a `fhirVersion` parameter: `fhirVersion=R4`. The default is STU3.

**Comment by mmacagno** [comment]
thanks! closing
