### ISSUE TITLE
Remove the Base64 format check

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#591]
We changed the logic to base64 encoding the continuation token to avoid some encoding issues. To maintain backwards compatibility, we added the logic to check and see if the incoming token is base 64 encoded or not and processes it differently. We should remove this logic after a few releases.

**Comment by LTA-Thinking** [comment]
Additional context: Added the encoding in PR #584, the check is in SearchOptionsFactory.cs

**Comment by CaitlinV39** [comment]
@LTA-Thinking is this still an issue?

**Comment by LTA-Thinking** [comment]
Yes, we never came back to this. [This](https://github.com/microsoft/fhir-server/blob/5a74aa2746811e2ab53402b7d38f54f31483f158/src/Microsoft.Health.Fhir.Shared.Core/Features/Search/SearchOptionsFactory.cs#L84) section needs to be edited so that we only support base 64 encoded continuation tokens.

**Comment by CaitlinV39** [comment]
AB#76206

**Comment by LTA-Thinking** [comment]
In order to prevent possible interruptions in export jobs running during a system upgrade a temporary fix had to be added to #1278 so that it checks for base64 encoded CTs. This should be removed soon.

**Comment by CaitlinV39** [comment]
@LTA-Thinking Is this one okay to close?
