### ISSUE TITLE
Exported resources doesn't have proper meta property.

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#593]
**Describe the bug**
Using the bulk export to exported resources to a blob storage. Looking at the result, the resource is there but the Meta property is missing.

**To Reproduce**
1. Queue an export job.

**Expected behavior**
The exported resources should have Meta property with LastUpdated timestamp and VersionId.

**Actual behavior**
The Meta property is missing.

**Comment by brendankowitz** [comment]
Does it make sense to set those Meta properties on the way in now? Seems like it would simplify a few things (though existing data will need to be considered)

**Comment by jackliums** [comment]
@brendankowitz I think we should set the Meta properties on the way in so that we don't have this special business logic around how to retrieve the resource and end up with bug like this one. That's more work though so for now I will simply fix the issue and file a separate user story to track the refactoring work.
