### ISSUE TITLE
Running FHIR Server locally

### ISSUE THREAD

**Issue by ElYusubov** [microsoft/fhir-server#595]
**Error in start-up**
Can not run fhir server locally with VS2017.
I got master branch , restored nuget packages, set Microsoft.Health.Fhir.R4.Web as start-up project. Pressed F5 - server not starting.

**Setup and local development instructions?**
Is there an official development  environment set-up documentation/tutorial for "FHIR-Server"?
The WIKI does not have instructions on "how to set FHIR server locally and run it on your PC".

**To Reproduce**
1. Get master repo
2. Restore nuget packages
3. Set Microsoft.Health.Fhir.R4.Web as start-up project
4. Press F5

**Expected behavior**
I would expect server start-up, so i can get metadata, like : {fhir-base-url}/metadata

**Actual behavior**
Getting IdentifyServer error:

![image](https://user-images.githubusercontent.com/29330538/62020088-7e5d6380-b18f-11e9-87d1-5face559fea6.png)

IdentityServer4.Startup:Information: Starting IdentityServer4 version 2.4.0.0
IdentityServer4.Startup:Information: You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
IdentityServer4.Startup:Information: Using the default authentication scheme Bearer for IdentityServer
IdentityServer4.Startup:Error: Authentication scheme Bearer is configured for IdentityServer, but it is not a scheme that supports signin (like cookies). Either configure the default authentication scheme with cookies or set the CookieAuthenticationScheme on the IdentityServerOptions.
IdentityServer4.Startup:Debug: Using Bearer as default ASP.NET Core scheme for authentication

**Comment by ElYusubov** [comment]
Is there any instruction how to run Microsoft.Health.Fhir.R4.Web - without error?
Hope, there is a step-by-step document that works for everyone.

**Comment by brendankowitz** [comment]
We have some internal notes which I'll share now. Let's validate (or improve them) and I'll add them to the documentation.
Although we've tried to keep dependencies to a minimum, you will need the Cosmos DB emulator and/or SQL Server (depending on the datalayer you've chosen)

* Open Microsoft.Health.Fhir.sln, set Microsoft.Health.Fhir.Web as StartUp Project, and press F5
* This will launch a web browser with the server address as: https://localhost:44348/
* If you get a timeout error with respect to initializing the DocumentClient (which is used to talk to the Cosmos DB instance) make sure **Cosmos Db emulator** is running and you are able to access it normally. If it still does not work, create an actual Cosmos Db instance on Azure and update the Host and Key properties in appsettings.json file
* If the root web page ("/") shows a HTTP 401 error, that is expected. As long as you are able to hit the metadata endpoint (https://localhost:44348/metadata) it means that the server is running.

We have documentation hosted on the docs site (look for OSS FHIR Server):
* https://docs.microsoft.com/en-us/azure/healthcare-apis/
* And some technical documentation / design documents in the repo here: https://github.com/microsoft/fhir-server/tree/master/docs

**Comment by ElYusubov** [comment]
Thanks @brendankowitz for those notes.
I will verify and share my findings here for the community.

**Comment by ElYusubov** [comment]
Thanks @brendankowitz for list of instructions.
I am using Cosmos DB (with Cosmos selection in VS) emulator to run the Microsoft.Health.Fhir.R4.Web with F5.

However, i am still getting error in "default authentication scheme Bearer for IdentityServer
IdentityServer4.Startup:Error: Authentication scheme Bearer is configured for IdentityServer, but it is not a scheme that supports signin (like cookies). Either configure the default authentication scheme with cookies or set the CookieAuthenticationScheme on the IdentityServerOptions.

**Is there instructions how to setup IdentitiyServer so bearer authentication succeeds?**

**Complete list of logs where Bearer token authentication fails with IdentitiyServer is listed below:**

`Microsoft.Health.CosmosDb.Features.Storage.CosmosDbDistributedLock:Information: Lock UpgradeLock:2 released
Microsoft.Health.Fhir.CosmosDb.Features.Storage.FhirDocumentClientInitializer:Information: Cosmos DB Database health and collections successfully initialized
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.6\System.Threading.Tasks.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Route matched with {action = "Search", controller = "Fhir"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Search() on controller Microsoft.Health.Fhir.Api.Controllers.FhirController (Microsoft.Health.Fhir.R4.Api).
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization failed.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult:Information: Executing ChallengeResult with authentication schemes ().
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler:Information: AuthenticationScheme: Bearer was challenged.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action Microsoft.Health.Fhir.Api.Controllers.FhirController.Search (Microsoft.Health.Fhir.R4.Api) in 67.1521ms
Microsoft.Health.Fhir.Api.Features.Audit.IAuditLogger:Information: ActionType: Executed
EventType: AuditEvent
Audience: fhir-api
Authority: https://localhost:44348
ResourceType: (null)
RequestUri: https://localhost:44348/
Action: search-system
StatusCode: Unauthorized
CorrelationId: f7e02aba-3c95-40eb-983d-16e11b8f5333
Claims: 
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\2.2.6\Microsoft.AspNetCore.WebUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 4472.4875ms 401 
Failed to load resource: the server responded with a status of 401 (Unauthorized) [https://localhost:44348/]
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET https://localhost:44348/  
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Route matched with {action = "Search", controller = "Fhir"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Search() on controller Microsoft.Health.Fhir.Api.Controllers.FhirController (Microsoft.Health.Fhir.R4.Api).
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization failed.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult:Information: Executing ChallengeResult with authentication schemes ().
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler:Information: AuthenticationScheme: Bearer was challenged.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action Microsoft.Health.Fhir.Api.Controllers.FhirController.Search (Microsoft.Health.Fhir.R4.Api) in 23.3967ms
Microsoft.Health.Fhir.Api.Features.Audit.IAuditLogger:Information: ActionType: Executed
EventType: AuditEvent
Audience: fhir-api
Authority: https://localhost:44348
ResourceType: (null)
RequestUri: https://localhost:44348/
Action: search-system
StatusCode: Unauthorized
CorrelationId: 2bf9faf6-e4d2-43ee-a894-794933dc51c2
Claims: 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 46.1651ms 401 
Failed to load resource: the server responded with a status of 401 (Unauthorized) [https://localhost:44348/]`

**Comment by ElYusubov** [comment]
What is the right place for the authentication settings described below in the doc?
[https://github.com/microsoft/fhir-server/blob/master/docs/Authentication.md](https://github.com/microsoft/fhir-server/blob/master/docs/Authentication.md)

**Comment by brendankowitz** [comment]
If you're just debugging, then using the IdentityServer is easy enough, the details in the above doc work fine for me in postman:

![image](https://user-images.githubusercontent.com/197221/62074527-db8cff80-b1f7-11e9-9cb5-5e287cbf294a.png)

If you are not using AAD, you can configure the "EnableAadSmartOnFhirProxy" to false in `appsettings.json`. This will ensure the `/connect/token` endpoint appears in the /metadata document.

**Comment by ElYusubov** [comment]
@brendankowitz - i am getting **401 response** when [https://localhost:44348/](https://localhost:44348/) is loading. This is the issue that i am trying to overcome.

**Which configuration file & where is expected to have below configuration?**
`
"FhirServer" : {
    "Security": {
        "Enabled":  true,
        "Authentication": {
            "Audience": "fhir-api",
            "Authority": "https://localhost:44348"
        }
    }
}
`

**Could you point which configuration settings i should check/verify?**

**Comment by brendankowitz** [comment]
@ElYusubov this is expected. Unless you've passed in a bearer token, https://localhost:44348/  will return a 401, as noted in the instructions above.
The only unauthenticated endpoint is https://localhost:44348/metadata.

The screenshot I posted earlier was demonstrating how to get a token.

**Comment by ElYusubov** [comment]
@brendankowitz thanks for looking into it!
Indeed, i am getting metadata response when request sent from browser.
However, i am getting nothing back when same request posted with "Postman".

Do you have any glues to **why server does not respond** to Postman?

![image](https://user-images.githubusercontent.com/29330538/62130824-d4bdc580-b2a7-11e9-83a6-a39bb6788420.png)

**Comment by ElYusubov** [comment]
Here is the another post for token where  "EnableAadSmartOnFhirProxy" is set to false on app settings.
For some reason, postman is not able to invoke https://localhost:44348/

![image](https://user-images.githubusercontent.com/29330538/62131111-83fa9c80-b2a8-11e9-87ff-efd39fa5d1ce.png)

**Comment by hansenms** [comment]
@ElYusubov, if you are not getting any response from the server, it looks like it is not running. Are you able to get the `https://localhost:44348/metadata` endpoint from Postman. If not, that is the first thing we need to get to the bottom off. If you try to hit the metadata endpoint, is the service responding at all?

**Comment by ElYusubov** [comment]
@hansenms issue was in latest Postman version configuration update.
Have to switch off SSL certificate verification to make it work:
![image](https://user-images.githubusercontent.com/29330538/62151603-aef7e700-b2ce-11e9-91b4-c15d4d15419c.png)

**Comment by hansenms** [comment]
You can also accept the dotnet development certificate. Glad you got it working.

**Comment by muruganrk** [comment]
How to update patient data with localhost "https://localhost:44348/" endpoint? 

share me update patient endpoint and request JSON or postman collection.
