### ISSUE TITLE
Health check should use DocumentClient in the same way as the FHIR service

### ISSUE THREAD

**Issue by cunninghamjc** [microsoft/fhir-server#600]
**Describe the bug**
Health check uses a DocumentClient differently than the rest of the FHIR service, so if there is a bug that affects the service's ability to connect to Cosmos DB, we might not catch it via health check.

**To Reproduce**
1. Undo PR 559
2. Repro the issue that 559 fixed.
3. GET health/check

**Expected behavior**
health/check should fail in the same way as other requests against the FHIR service.

**Actual behavior**
health/check succeeds.

**Comment by brendankowitz** [comment]
Some changes for this also here #562

**Comment by CaitlinV39** [comment]
AB#76157
