### ISSUE TITLE
Create a new resource with given ID

### ISSUE THREAD

**Issue by mmacagno** [microsoft/fhir-server#614]
Is it possible to force the id of a resource to a specific guid?

Since multiple resources can be linked together via reference pointers, in case of migration, maintenance where bunch of records needs to be migrated, it would be good to have a way to preserve the original GUID for the resources.

**Comment by hansenms** [comment]
Just do a PUT to a specific resource id, e.g.:

```
PUT /Patient/1234
```

with a payload of:

```json
{
   "resourceType": "Patient",
   "id": "1234",

    // Other stuff
}
```

**Comment by hansenms** [comment]
https://www.hl7.org/fhir/http.html#upsert

**Comment by mmacagno** [comment]
Brilliant! Thanks
