### ISSUE TITLE
Requesting token from AadSmartOnFhirProxy fails fo the token "scope" is null

### ISSUE THREAD

**Issue by namalu** [microsoft/fhir-server#615]
**Describe the bug**
When making a request to /AadSmartOnFhirProxy/token the request will fail with an OperationOutcome resource if the token provided by AAD has no "scope"

**To Reproduce**
1. Register a public client application with no scopes 
2. Attempt to retrieve a token

It appears that on line 392 of the AadSmartOnFhirProxyController, it is assumed that the "scope" provided by AAD can never be null:

  // Replace fully qualifies scopes with short scopes and replace $
            string[] scopes = tokenResponse["scope"].ToString().Split(' ');

**Expected behavior**
The AadSmartOnFhirProxy should complete successfully with the token provided by AAD.

**Actual behavior**
The request fails with an OperationOutcome resource:

"diagnostics": "Value supplied for the \"Content-Type\" header is not supported"

**Comment by hansenms** [comment]
@namalu ?

**Comment by namalu** [comment]
@hansenms - Yes

**Comment by hansenms** [comment]
OK, There was no info in the bug initially. Thanks for this. We will add it to the list. You should be able to work around this for now, right?

**Comment by namalu** [comment]
Yes there is a simple workaround. I can also submit a fix for this later today for your consideration.

**Comment by CaitlinV39** [comment]
@namalu - did you submit a fix for this?

**Comment by namalu** [comment]
It looks like @hansenms fixed this issue #704.
