### ISSUE TITLE
Checks on resource references on POST/PUT

### ISSUE THREAD

**Issue by ElYusubov** [microsoft/fhir-server#640]
FHIR Server does not check resource references in posted/updated fhir resource.

1. Sent Post request to FHIR R4 endpoint: POST  {base_url}/ExplanationOfBenefit
2. Body of resource
 `{
        "resourceType": "ExplanationOfBenefit",
        "identifier": [
          {
            "system": "https://bluebutton.cms.gov/resources/variables/pde_id",
            "value": "2220815701"
          },
          {
            "system": "http://bluebutton.cms.hhs.gov/identifier#claimGroup",
            "value": "3359444166"
          },
          {
            "system": "CCW.RX_SRVC_RFRNC_NUM",
            "value": "63931043057"
          }
        ],
        "status": "active",
        "type": {
          "coding": [
            {
              "system": "https://bluebutton.cms.gov/developer/docs/reference/some-thing",
              "code": "PDE"
            },
            {
              "system": "http://hl7.org/fhir/ex-claimtype",
              "code": "PHARMACY"
            }
          ]
        },
        "use": "claim",
        "patient": {
          "reference": "Patient/20140000000277"
        },
        "created": "2014-08-16",
        "facility": {
          "extension": [
            {
              "url": "https://bluebutton.cms.gov/resources/variables/phrmcy_srvc_type_cd",
              "valueCoding": {
                "system": "https://bluebutton.cms.gov/resources/variables/phrmcy_srvc_type_cd",
                "code": "04",
                "display": "Institutional pharmacy"
              }
            }
          ],
          "identifier": {
            "system": "http://hl7.org/fhir/sid/us-npi",
            "value": "999999999999999"
          }
        },
        "disposition": "Debit accepted",
        "supportingInfo": [
          {
            "sequence": 1,
            "category": {
              "coding": [
                {
                  "system": "https://bluebutton.cms.gov/resources/variables/daw_prod_slctn_cd",
                  "code": "0",
                  "display": "No Product Selection Indicated (may also have missing values)"
                }
              ]
            }
          },
          {
            "sequence": 2,
            "category": {
              "coding": [
                {
                  "system": "https://bluebutton.cms.gov/resources/variables/dspnsng_stus_cd",
                  "code": "P",
                  "display": "Partial fill"
                }
              ]
            }
          },
          {
            "sequence": 3,
            "category": {
              "coding": [
                {
                  "system": "https://bluebutton.cms.gov/resources/variables/drug_cvrg_stus_cd",
                  "code": "C",
                  "display": "Covered"
                }
              ]
            }
          },
          {
            "sequence": 4,
            "category": {
              "coding": [
                {
                  "system": "https://bluebutton.cms.gov/resources/variables/rx_orgn_cd",
                  "code": "4",
                  "display": "Facsimile"
                }
              ]
            }
          },
          {
            "sequence": 5,
            "category": {
              "coding": [
                {
                  "system": "https://bluebutton.cms.gov/resources/variables/brnd_gnrc_cd",
                  "code": "G",
                  "display": "Generic Null/missing"
                }
              ]
            }
          },
          {
            "sequence": 6,
            "category": {
              "coding": [
                {
                  "system": "https://bluebutton.cms.gov/resources/variables/phrmcy_srvc_type_cd",
                  "code": "04",
                  "display": "Institutional pharmacy"
                }
              ]
            }
          },
          {
            "sequence": 7,
            "category": {
              "coding": [
                {
                  "system": "https://bluebutton.cms.gov/resources/variables/ptnt_rsdnc_cd",
                  "code": "01",
                  "display": "Home"
                }
              ]
            }
          },
          {
            "sequence": 8,
            "category": {
              "coding": [
                {
                  "system": "https://bluebutton.cms.gov/resources/variables/submsn_clr_cd",
                  "code": "08",
                  "display": "Process compound for approved ingredients"
                }
              ]
            }
          }
        ],
        "careTeam": [
          {
            "sequence": 2,
            "provider": {
              "identifier": {
                "system": "http://hl7.org/fhir/sid/us-npi",
                "value": "999999999999999"
              }
            },
            "role": {
              "coding": [
                {
                  "system": "http://hl7.org/fhir/claimcareteamrole",
                  "code": "primary"
                }
              ]
            }
          }
        ],
        "insurance": {
          "coverage": {
            "extension": [
              {
                "url": "https://bluebutton.cms.gov/resources/variables/plan_cntrct_rec_id",
                "valueIdentifier": {
                  "system": "https://bluebutton.cms.gov/resources/variables/plan_cntrct_rec_id",
                  "value": "99999"
                }
              },
              {
                "url": "https://bluebutton.cms.gov/resources/variables/plan_pbp_rec_num",
                "valueIdentifier": {
                  "system": "https://bluebutton.cms.gov/resources/variables/plan_pbp_rec_num",
                  "value": "999"
                }
              }
            ],
            "reference": "Coverage/part-d-20140000000277"
          }
        },
        "insurer": { "reference": "Organization/3" },
        "provider": { "reference": "Practitioner/1" },
        "outcome": "complete",
        "item": [
          {
            "sequence": 1,
            "careTeamSequence": [
              2
            ],
            "productOrService": {
              "coding": [
                {
                  "system": "https://www.accessdata.fda.gov/scripts/cder/ndc",
                  "code": "62037083110"
                }
              ]
            },
            "servicedDate": "2016-10-01",
            "quantity": {
              "extension": [
                {
                  "url": "https://bluebutton.cms.gov/resources/variables/fill_num",
                  "valueQuantity": {
                    "value": 1
                  }
                },
                {
                  "url": "https://bluebutton.cms.gov/resources/variables/days_suply_num",
                  "valueQuantity": {
                    "value": 90
                  }
                }
              ],
              "value": 90.000
            },
            "adjudication": [
              {
                "category": {
                  "coding": [
                    {
                      "system": "CMS Adjudications",
                      "code": "Part D Covered"
                    }
                  ]
                },
                "amount": {
                  "value": 0.00,
                 "currency": "USD"
                }
              },
              {
                "category": {
                  "coding": [
                    {
                      "system": "CMS Adjudications",
                      "code": "Gross Drug Cost Below Out-of-Pocket Threshold (GDCB)"
                    }
                  ]
                },
                "amount": {
                  "value": 40.00,
                  "currency": "USD"
                }
              },
              {
                "category": {
                  "coding": [
                    {
                      "system": "CMS Adjudications",
                      "code": "Gross Drug Cost Above Out-of-Pocket Threshold (GDCA)"
                    }
                  ]
                },
                "amount": {
                  "value": 0.00,
                  "currency": "USD"
                }
              },
              {
                "category": {
                  "coding": [
                    {
                      "system": "CMS Adjudications",
                      "code": "Patient Pay Amount"
                    }
                  ]
                },
                "amount": {
                  "value": 0.00,
                  "currency": "USD"
                }
              },
              {
                "category": {
                  "coding": [
                    {
                      "system": "CMS Adjudications",
                      "code": "Other True Out-of-Pocket (TrOOP) Amount"
                    }
                  ]
                },
                "amount": {
                  "value": 0.00,
                  "currency": "USD"
                }
              },
              {
                "category": {
                  "coding": [
                    {
                      "system": "CMS Adjudications",
                      "code": "Part D Low Income Subsidy (LICS) Amount"
                    }
                  ]
                },
                "amount": {
                  "value": 0.00,
                  "currency": "USD"
                }
              },
              {
                "category": {
                  "coding": [
                    {
                      "system": "CMS Adjudications",
                      "code": "Reduction in patient liability due to payments by other payers (PLRO) Amount"
                    }
                  ]
                },
                "amount": {
                  "value": 0.00,
                  "currency": "USD"
                }
              },
              {
                "category": {
                  "coding": [
                    {
                      "system": "CMS Adjudications",
                      "code": "Total Prescription Cost"
                    }
                  ]
                },
                "amount": {
                  "value": 40.00,
                 "currency": "USD"
                }
              },
              {
                "category": {
                  "coding": [
                    {
                      "system": "CMS Adjudications",
                      "code": "Medicare Coverage Gap Discount Amount"
                    }
                  ]
                },
                "amount": {
                  "value": 0.00,
                 "currency": "USD"
                }
              }
            ]
          }
        ]
}`

3. The reference resource Patient/20140000000277 is not created

**Expected behavior**
Should be getting OperationOutcome resource with Status 400
Like the following:
`{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Resource Patient/20140000000277 not found, specified in path: ExplanationOfBenefit.patient</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Resource Patient/20140000000277 not found, specified in path: ExplanationOfBenefit.patient"
    }
  ]
}`

**Actual behavior**
Error is ignored &  a Status 201 is returned with new resource

**Comment by jackliums** [comment]
We currently don't enforce reference integrity. This is something on our roadmap.

**Comment by CaitlinV39** [comment]
@ElYusubov right now we don't have this prioritized in the roadmap and so are going to close as won't fix.
