### ISSUE TITLE
Cannot open all projects in Visual Studio 2019

### ISSUE THREAD

**Issue by alexsab1** [microsoft/fhir-server#653]
**Describe the bug**

Hi, I have cloned the project and tried to open solution in Visual Studio 2019. Many projects are failing to open

![image](https://user-images.githubusercontent.com/9371364/64982850-c1c97980-d884-11e9-934c-b789202a95ce.png)

I ran dotnet --info

![image](https://user-images.githubusercontent.com/9371364/64982879-d0b02c00-d884-11e9-9382-61fe53ff3451.png)

Visual Studio info

![image](https://user-images.githubusercontent.com/9371364/64982951-02c18e00-d885-11e9-80e4-5a0ec7d6215d.png)

**To Reproduce**

See above

**Expected behavior**

Open and build in Visual Studio 2019

**Actual behavior**

Cannot open many projects in Visual Studio 2019

**Comment by hansenms** [comment]
Try to install the .NET SDK version in the `global.json` file:

https://github.com/microsoft/fhir-server/blob/master/global.json

**Comment by alexsab1** [comment]
Success! The issue was solved after installing SDK version 2.2.107.
