### ISSUE TITLE
Validation messages need reformatting

### ISSUE THREAD

**Issue by rotodd** [microsoft/fhir-server#660]
**Describe the bug**

The FHIR paths (locations) of the validation messages for the attribute and id validators are not properly formatted.

**To Reproduce**

1. Using Postman, create a PUT request `https://localhost:44348/Observation/f002!`
2. Set the request body to [this](https://www.hl7.org/fhir/observation-example-f001-glucose.json.html)
3. In the request body, remove the line `"status": "final",` and update the id to `f002!`

**Expected behavior**

- For id validation, the location should specify the resource type (e.g. "Observation" opposed to "Resource")
- For attribute validation, the FHIR path should be lowercase and set to the name of the attribute (e.g. "Observation.status" opposed to "Observation.StatusElement")

**Actual behavior**

![validation_messages_with_location](https://user-images.githubusercontent.com/54082711/65347337-a36cc200-db93-11e9-8299-81473a0f2fc7.png)

**Comment by brandonpollett** [comment]
@rbans96 This may be related to your open PR #781.

**Comment by Ivanidzo4ka** [comment]
@rotodd  @CaitlinV39  I've tried to reproduce this bug, and it seems to me to be fixed. Can we close this issue?

**Comment by CaitlinV39** [comment]
@rotodd - Do you think we can close this?

**Comment by CaitlinV39** [comment]
AB#70337
