### ISSUE TITLE
Deployment template fails in Azure Gov with App Insights

### ISSUE THREAD

**Issue by hansenms** [microsoft/fhir-server#662]
**Describe the bug**
Deployment template is failing in Azure Gov unless the App Insights resource is deleted. Problem reported is that the region for App Insights is invalid for Gov since it is now available. 

**To Reproduce**
1. Deploy the default template in Gov

**Expected behavior**
Correct regions for App Insights should be selected for Azure Gov

**Actual behavior**
Wrong region is selected. App Insights fails to deploy.

**Comment by CaitlinV39** [comment]
Fixed
