### ISSUE TITLE
de-identify sensitive data

### ISSUE THREAD

**Issue by jues** [microsoft/fhir-server#666]
De-identification is the process of removing identifying information from data. De-identification has multiple uses cases: for example, you might want to de-identify data before analyzing or sharing it.

reference:
https://cloud.google.com/healthcare/docs/how-tos/fhir-deidentify

**Comment by hansenms** [comment]
We understand that there is a need for de-identification and we are exploring this. We will keep this issue here to track it.

**Comment by CaitlinV39** [comment]
@jues we released the FHIR tools for anonymization in March of this year which gives tools to do safe harbor de-identification. You can find this project here: https://github.com/microsoft/FHIR-Tools-for-Anonymization

@ranvijaykumar FYI
