### ISSUE TITLE
DOS on bad continuation tokens

### ISSUE THREAD

**Issue by mmacagno** [microsoft/fhir-server#674]
**Describe the bug**
Providing altered continuation tokens on a query (adding a few digits) will cause a Denial Of Service on the FHIR instance.

**To Reproduce**
1. Produce a FHIR query that returns a next element with continuation token, for example:

https://{{fhir_uri}}/Observation?date=2019-09-20

2. Use the next URL and verify you get additional records
3. add a few random digits at the end, for example:

https://{{fhir_uri}}/Observation?date=2019-09-20&ct=eyJ0b2tlbiI6IitSSUQ6MzRKOEFQeEJHcUpsQmdBQUFBQUFBQT09I1JUOjEjVFJDOjEwI0lTVjoyI0lFTzo2NTUzNiIsInJhbmdlIjp7Im1pbiI6IiIsIm1heCI6IkZGIn19**1122**

**Expected behavior**
A 400 error for bad continuation token

**Actual behavior**
The server will timeout and restart 
From Postman: 
error 502 >> The specified CGI application encountered an error and the server terminated the process.

I can repro consistently.

**Comment by CaitlinV39** [comment]
@CaitlinV39 create an investigation story

**Comment by CaitlinV39** [comment]
AB#76150

**Comment by CaitlinV39** [comment]
@johnstairs can we close?
