### ISSUE TITLE
Update Roadmap.md

### ISSUE THREAD

**Issue by cristianrablau** [microsoft/fhir-server#695]
Hi guys,

Could you please update the [Roadmap](https://github.com/microsoft/fhir-server/blob/master/docs/Roadmap.md)? Almost an year has passed since the last update. Some links are broken and maybe some items are already completed. 

For the next year I suggest a table at the end of the file where we can see the status of each feature.

I think the entire community is eager to see the progress 😄

**Comment by hansenms** [comment]
I am actually thinking we should remove that page altogether. It doesn't make a whole lot of sense right now since it is not being maintained. The current open issues and the commit history should really be a better more dynamic way to maintain this.

**Comment by hansenms** [comment]
We have removed the Roadmap page, since it was not being maintained. I suspect you have preferred it be updated, but we keep a list of to do items in the form of issues and we keep track of what is completed. This Roadmap page was a bit of double accounting.

**Comment by cristianrablau** [comment]
@hansenms I'm ok with it. Just make sure you keep [Azure FHIR Supported Features](https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir-features-supported) up to date. Keep up the good work 👍

**Comment by SychevIgor** [comment]
@hansenms it will be great to publish a new roadmap in 2020. all about healthcare is hot this year. 
We would like (will) to use this implementation, but without roadmap we can invest our time in some feature that is under development.

**Comment by CaitlinV39** [comment]
@SychevIgor right now we don't have plans to update this roadmap but if there are specific features or questions you can open an issue and we can track there. We update our roadmap and prioritization based on feedback were hearing from customers and partners so try to be flexible and agile in where we take our development based on where we are getting feedback.

**Comment by uxbridgeroad** [comment]
@CaitlinV39  thanks for the feedback on this. We working on a major project underpinned by MS FHIR Sever and it is very important for us to be able to plan our own releases based on timelines from the fhir-server team.
If a 'roadmap' s not available, would it be possible to link to an updated features table for Cosmos & SQL?

The linked  [https://docs.microsoft.com/en-us/azure/healthcare-apis/fhir-features-supported](url) seems be be out of date.

We are particularly interested in the  completeness of support  (and known issues) for chaining, reverse chaining, _includes & _revinclude in Cosmos & SQL. For example, the fhir-features-supported page shows _has as not implemented in SQL DB but my own testing shoes this as being available, although it is not full clear what are the gaps.

**Comment by SychevIgor** [comment]
We did perf comparison of CosmosDB vs SQL DB. Will share our approach and results here.

**Comment by kiprian2007** [comment]
Our team did performance comparison for FHIR Server between CosmosDB and SQL Server. We have some realistic data taken from official FHIR portal, for example real-world patient data (https://www.hl7.org/fhir/patient-example-f001-pieter.json.html)
We have configured both servers with the following:

**SQL Server characteristics**
Location: East US
DTU Quota: 20 DTU
Pricing tier: Standard S1

**Cosmos DB characteristics**
Location: East US
Throughput: 400 RU/s
Capacity mode: Provisioned throughput

**Approach 1**: Using BenchmarkDotNet Library (https://github.com/dotnet/BenchmarkDotNet). Sending all the requests sequentially and measuring the average processing time.

**Results:**

Database | Min | Max | Median

**Create 10 Patients (50 iterations)**
Cosmos DB | 0.8749 s | 1.512 s | 1.177 s
SQL Server | 1.1856 s | 1.342s | 1.211 s
**Create 50 Patients with 50 iterations**
Cosmos DB | 0.8700 s | 1.192 s | 1.170 s
SQL Server | 0.8826 s | 1.243 s | 1.178 s
**Create 100 Patients with 100 iterations**
Cosmos DB | 0.8707 s | 1.337 s | 1.197 s
SQL Server | 0.8808 s | 1.376 s | 1.229 s
**Create 300 Patients sequentially**
Cosmos DB | 0.8651 s | 1.227 s | 1.164 s
SQL Server | 1.4553 s | 2.539 s | 2.009 s
**Read 10 Patients (50 iterations)**
Cosmos DB | 1.156 s | 1.486 s | 1.413 s
SQL Server | 1.152 s | 1.516 s | 1.437 s
**Read 50 Patients (10 iterations)**
Cosmos DB | 2.226 s | 2.226 s | 2.226 s
SQL Server | 1.805 s | 1.805 s | 1.805 s
**Read 3200 resource records**
Cosmos DB | 76.43 s | 76.43 s | 76.43 s
SQL Server | 140.40 s | 140.40 s | 140.40 s

**Approach 2:** Using custom made benchmarking tool that will use a FHIR Client class to operate with FHIR Server. Sending all the requests simultaneously to see how it’s performing under heavy workload.

**Results:**
Create 10 new Patients
![image](https://user-images.githubusercontent.com/20209044/93382879-7c5ed400-f86b-11ea-9243-729f771052f9.png)
Create 50 new Patients
![image](https://user-images.githubusercontent.com/20209044/93382896-8385e200-f86b-11ea-85f7-951b88342b85.png)
Create 100 new Patients
![image](https://user-images.githubusercontent.com/20209044/93382916-88e32c80-f86b-11ea-9c17-e6db6f16cb5c.png)

**Comment by johnstairs** [comment]
@kiprian2007, this is great, thanks for sharing. Over the coming months, we will be investing in improving performance of the SQL stack, with some optimizations also benefiting Cosmos DB.
Some questions on the tests you performed:
- What is "Read 3200 resource records" scenario doing? Are you doing a search over the entire system? How does it contrast with the "Read 50 Patients (10 iterations)" scenario?
- What are the x and y axes in approach 2?

**Comment by CaitlinV39** [comment]
I am going to close this issue. Right now the best place to see our supported features are https://docs.microsoft.com/azure/healthcare-apis/fhir-features-supported. We don't have a roadmap slide, but do use the issues here to track what we are currently working on with milestones assigned. I'm always happy to connect on specific features or track specific features in their own issues.
