### ISSUE TITLE
Documentation on SMART authorization for FHIR

### ISSUE THREAD

**Issue by shiva-annadi** [microsoft/fhir-server#700]
**User story**
As a FHIR server Dev and Ops team, I want to authenticate  the server with Crucible. Does Microsoft FHIR server support this feature?

The guild i am following is available in https://github.com/fhir-crucible/crucible. 

**Acceptance criteria**
1. The server to be tested must declare their compliance with the SMART authorization specification by including security and extension elements in the conformance.. This is detailed in the  Conformance section of https://github.com/fhir-crucible/crucible. How do i achieve it on Azure. Please guide?

**Comment by hansenms** [comment]
https://docs.microsoft.com/en-us/azure/healthcare-apis/use-smart-on-fhir-proxy

**Comment by shiva-annadi** [comment]
Thanks @hansenms for the quick response. Will check and get back on that.
