### ISSUE TITLE
How to enable SMART on FHIR AAD in Azure FHIR SERVER?

### ISSUE THREAD

**Issue by vishnu-anil** [microsoft/fhir-server#707]
**User story**
Trying to add the below code as per https://github.com/fhir-crucible/crucible to test FHIR server in Azure with crusible. Could see that FHIR server web app configuration do have the below configuration option: FhirServer:Security:EnableAadSmartOnFhirProxy

Need to add 

`{
"resourceType": "Conformance",
"rest": [{
  "security": {
    "service": [
      {
        "coding": [
          {
            "system": "http://hl7.org/fhir/restful-security-service",
            "code": "SMART-on-FHIR"
          }
        ],
        "text": "OAuth2 using SMART-on-FHIR profile (see http://docs.smarthealthit.org)"
      }
    ],
    "extension": [{
      "url": "http://fhir-registry.smarthealthit.org/StructureDefinition/oauth-uris",
      "extension": [{
        "url": "token",
        "valueUri": "https://my-server.org/token"
      },{
        "url": "authorize",
        "valueUri": "https://my-server.org/authorize"
      }]
    }],`

Is it possible? Tried adding in AAD App registration Manifest but looks like its not supported as i gets below error? 

Failed to update https://xxxxxxxxxxxxxxxxxxxxxxx application. Error detail: A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value

**Acceptance criteria**
Able to have SMART on Azure FHIR server

**Comment by hansenms** [comment]
If you enable `FhirServer:Security:EnableAadSmartOnFhirProxy` (set it to `true`) and you Azure AD configured and you have `FhirServer:Security:Enable` set to `true`, those fields in the conformance statement will automatically be populated and set to point to the SMART on FHIR proxy on the service.

**Comment by CaitlinV39** [comment]
@vishnu-anil I'm going to close this per Michael's comment above but if you have additional questions please let us know. We have some additional details on Smart of FHIR here: https://docs.microsoft.com/en-us/azure/healthcare-apis/use-smart-on-fhir-proxy
