### ISSUE TITLE
Deployment docs omit details on how to login to correct tenant

### ISSUE THREAD

**Issue by stevehaigh** [microsoft/fhir-server#708]
**Describe the bug**
The DefaultDeployment.md doc describes how to create an application registration in ADD, but does not state that you need to be logged in to the correct tenant.

**To Reproduce**
Follow the DefaultDeployment.md doc

**Expected behavior**
Docs should prompt you to log in to the correct tenant using `Connect-AzureAD -TenantId <xxxxxx>`

**Actual behavior**
Application might not be registered correctly with the right AAD tenant.

**Comment by hansenms** [comment]
Not really sure this is a bug? Would you not log into the "right" tenant before you start creating app registrations?

**Comment by stevehaigh** [comment]
Yeah, agree it is not a bug as such but seems to be something worth clarifying in the docs perhaps? As there is a chance the user may be using the ‘FHIR app tenant’ when they really need to be using the ‘AAD tenant’, if you see what I mean?

Perhaps this doesn’t affect people outside MSFT so much as they can grant API permissions in their own tenant, so it might actually make things less clear, but getting AAD right seems to be something that trips people up, so anything to make it super clear is useful.

Thanks,
Steve

**Comment by hansenms** [comment]
I think it is a fairly MSFT specific thing. If there is something you would like added to the docs, we can take a PR, but for now, I am closing this.
