### ISSUE TITLE
Support :not modifier for token search parameter

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#709]
**User story**
As a user, I want to be able to use :not modifier on token search parameter so that filter out resource easily..

http://hl7.org/fhir/search.html#token
> Reverse the code matching described in the paragraph above: return all resources that do not have a matching item. Note that this includes resources that have no value for the parameter - e.g. ?gender:not=male includes all patients that do not have gender = male, including patients that do not have a gender at all

**Acceptance criteria**
1. When I search `/Observation?category:not=vital-signs`, then any Observation with condition `observation.Category == null || !(observation.Category.Any(category => category.Coding.Any(coding => coding.Code == "vital-signs")))` should be returned.
1. When I search `/Observation?category:not=http://terminology.hl7.org/CodeSystem/observation-category|vital-signs`, then any Observation with condition `observation.Category == null || !(observation.Category.Any(category => category.Coding.Any(coding => coding.System == "http://terminology.hl7.org/CodeSystem/observation-category" && coding.Code == "vital-signs")))` should be returned.
1. When I search `/Observation?category:not=|vital-signs`, then any Observation with condition `observation.Category == null || !(observation.Category.Any(category => category.Coding.Any(coding => coding.System == null && coding.Code == "vital-signs")))` should be returned.
1. When I search `/Observation?category:not=http://terminology.hl7.org/CodeSystem/observation-category|`, then any Observation with condition `observation.Category == null || !(observation.Category.Any(category => category.Coding.Any(coding => coding.System == "http://terminology.hl7.org/CodeSystem/observation-category")))` should be returned.

**Comment by CaitlinV39** [comment]
AB#77478

**Comment by CaitlinV39** [comment]
@Ivanidzo4ka @johnstairs Is this issue closed?

**Comment by Ivanidzo4ka** [comment]
I believe it is.
