### ISSUE TITLE
Show profile for resources in the metadata

### ISSUE THREAD

**Issue by brandonpollett** [microsoft/fhir-server#724]
**User story**
With the recent changes in the conformance generation, the `profile` property is no longer showing up for individual resources. This should be updated to show the profile.

```json
"resource" : [{
      "type" : "Account",
      "profile" : "http://hl7.org/fhir/StructureDefinition/Account",
```

**Acceptance criteria**
1. Profile is shown for individual resource types in the capability statement.

**Comment by brendankowitz** [comment]
Looks good, closing this out
