### ISSUE TITLE
Smart for fhir Azure server authentication error

### ISSUE THREAD

**Issue by bobosette** [microsoft/fhir-server#727]
Hi everybody. I'm trying to setup an Azure Fhir Server with Smart authentication. I have 2 issues:

1 I'm getting the access token with Postman:

grant_type : authorization_code
callback_url : https://www.getpostman.com/oauth2/callback
auth_url : https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/authorize
access_token_url : https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/token
client_id : my app client id
client_secret : my app client secret
scope : https://{MYFHIRSERVICE}.azurewebsites.net/user_impersonation

Of course i registered my app on azure active directory following the guides. But when i try to do a rest call (for example POST https://{MYFHIRSERVICE}.azurewebsites.net/Patient) this is the response body:

{
    "resourceType": "OperationOutcome",
    "id": "1d206436-dc23-4c5c-951d-d3144dba994d",
    "issue": [
        {
            "severity": "error",
            "code": "forbidden",
            "diagnostics": "Authorization failed."
        }
    ]
}

i tried everything, but response is always the same. 
Someone can help me? Where am i making a mistake?

2 Another problem is the R4 Fhir version. Here we have the 4.0.0, but i need the 4.0.1. Will an update come?

Thank u

**Comment by hansenms** [comment]
When you get a 401 (which I assume you are getting) you should get some response headers indicating what is wrong with your token (possibly the audience?). I would take the token, paste it into https://jwt.ms and see what claims you have in the token and make sure that you have the right authority, audience configured on the FHIR service.

On version 4.0.1, it has been out for just a week, so we will get to it. You can, since you are running OSS, update the definitions yourself and recompile, but we don't have instructions for it.

**Comment by bobosette** [comment]
i don't get a 401, i get a 403 forbidden, but in the response headers i have no error description:

Transfer-Encoding: "chunked"
Content-Type: "application/fhir+json; charset=utf-8"
Server: "Kestrel"
Request-Context: "appId=cid-v1:d758c693-f7ab-407d-87bd-8126dfeec5c9"
X-Request-Id: "28b82158-fb6d-490c-9971-62757cbffa44"
X-Content-Type-Options: "nosniff"
X-Powered-By: "ASP.NET"
Date: "Thu, 07 Nov 2019 20:01:23 GMT"

I got on jwt.ms, and i have the right stuff. so it should work!!! Damn

On version 4.0.1 thank u

**Comment by hansenms** [comment]
403 mean that your identity (user) doesn't have access to the FHIR server. So in the case of OSS, you don't have the right app role.

**Comment by bobosette** [comment]
And how can i configure the role? In the app manifest right?

**Comment by hansenms** [comment]
You specify the roles in the app manifest for the resource application (not the client) and then you have to give your user that app role.

**Comment by bobosette** [comment]
ok. so when i specify the roles in the resource app manifest how can i give the app role? in the manifest of the client app?

**Comment by bobosette** [comment]
Did it!!! Finally! I found this guide for the role: https://docs.microsoft.com/it-it/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps

Thank u for your answer, cause in the other guides there isn't that advice (adding roles and how to)!!!!!
Thank u again

**Comment by hansenms** [comment]
Sure thing. #please-close
