### ISSUE TITLE
Support FHIR 4.0.1

### ISSUE THREAD

**Issue by hansenms** [microsoft/fhir-server#728]
**User story**
As a user I want my R4 FHIR API to conform to the 4.0.1 specification.

http://www.hl7.org/fhir/directory.html

**Acceptance criteria**
1. When I provision a FHIR API, then the CapabilityStatement should say FHIR version `4.0.1`.

**Comment by brendankowitz** [comment]
Likely the following should be updated: 
* https://github.com/microsoft/fhir-server/tree/master/src/Microsoft.Health.Fhir.R4.Core/Features/Definition
* Hl7.Fhir.R4 nuget packages

**Comment by brendankowitz** [comment]
@hansenms this should reach Azure API for FHIR. w/o 23rd March
