### ISSUE TITLE
Refactor _total parameter implementation so that SearchOptions is returned to its original state

### ISSUE THREAD

**Issue by rotodd** [microsoft/fhir-server#729]
**User story**

We are mutating SearchOptions in both the SQL and Cosmos search service classes. Return it to its original state in a try-finally block. This will allow the properties of the SearchOptions to remain in the state set by user input.

**Acceptance criteria**

The SearchOptions object is not modified after it is used in the search service classes.

**Comment by CaitlinV39** [comment]
@rotodd Does this item have additional work pending?

**Comment by rotodd** [comment]
> @rotodd Does this item have additional work pending?

@CaitlinV39 nope, closing it now. Thanks 😊
