### ISSUE TITLE
Typo in LogSqlComand method signature

### ISSUE THREAD

**Issue by jjcollinge** [microsoft/fhir-server#737]
LogSqlComand method has a typo in its method signature.
LogSqlComand --> LogSqlCommand 

https://github.com/microsoft/fhir-server/blob/139428be0e460cc358a3428a3a325ee548bf9998/src/Microsoft.Health.Fhir.SqlServer/Features/Search/SqlServerSearchService.cs#L276

**Comment by salmanmkc** [comment]
hopefully this fixes it, thanks
