### ISSUE TITLE
ResourceType is null in emitted metrics

### ISSUE THREAD

**Issue by YazanMSFT** [microsoft/fhir-server#745]
**Describe the bug**
When ApiResponseNotification or CosmosStorageRequestMetricsNotifications are sent, the ResourceType parameter is always null.

**To Reproduce**
1. Add metrics middleware to startup
2. Make a request for observations

**Expected behavior**
ResourceType in emitted notification is set

**Actual behavior**
ResourceType is null.

**Comment by brendankowitz** [comment]
@YazanMSFT can this be closed?

**Comment by YazanMSFT** [comment]
@brendankowitz I don't think anyone did acceptance for this.

**Comment by brendankowitz** [comment]
Got it, thanks
