### ISSUE TITLE
Patient Search with Multiple Given Names return zero results.

### ISSUE THREAD

**Issue by granadacoder** [microsoft/fhir-server#760]
**Describe the bug**

When searching for a Patient using multiple given names, (more than 1), the results come back empty on legitimate inputs.

**To Reproduce**
1.  Use Sql Server (not CosmoDB)
2. Add some Patient(s) Resources to the database.  With Multiple Given Names.

One like this:

```
                "name": [
                    {
                        "family": "Smith",
                        "given": [
                            "John",
                            "Apple",
                            "Jingerheimer"
                        ]
                    }
                ]
```
second one like this:

```
                "name": [
                    {
                        "family": "Smith",
                        "given": [
                            "John",
                            "Banana",
                            "Jingerheimer"
                        ]
                    }
                ]

```
Same two patients seen below with more json.

```

{
    "resourceType": "Bundle",
    "id": "269caf66-0ccc-43e7-b9a5-f16f84db0149",
    "meta": {
        "lastUpdated": "2019-11-20T19:30:26.858917+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://localhost:44348/Patient?given=Jingerheimer"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://localhost:44348/Patient/504f6bd3-e9b4-4846-8948-97bf09c70722",
            "resource": {
                "resourceType": "Patient",
                "id": "504f6bd3-e9b4-4846-8948-97bf09c70722",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2019-11-20T19:26:11.005+00:00"
                },
                "identifier": [
                    {
                        "system": "ssn",
                        "value": "111-11-1111"
                    },
                    {
                        "system": "uuid",
                        "value": "da55d068e0784b359fa97498a11543c5"
                    }
                ],
                "name": [
                    {
                        "family": "Smith",
                        "given": [
                            "John",
                            "Apple",
                            "Jingerheimer"
                        ]
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://localhost:44348/Patient/10054ce9-6141-4eca-bc5b-0978f8c8afcb",
            "resource": {
                "resourceType": "Patient",
                "id": "10054ce9-6141-4eca-bc5b-0978f8c8afcb",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2019-11-20T19:26:48.962+00:00"
                },
                "identifier": [
                    {
                        "system": "ssn",
                        "value": "222-22-2222"
                    },
                    {
                        "system": "uuid",
                        "value": "52d09f9436d44591816fd229dd139523"
                    }
                ],
                "name": [
                    {
                        "family": "Smith",
                        "given": [
                            "John",
                            "Banana",
                            "Jingerheimer"
                        ]
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}

```

Perform a search with mutiple given names

`https://localhost:44348/Patient/?given=Jingerheimer&given=Apple

`

3. 

**Expected behavior**

Return 

[](
{
    "resourceType": "Bundle",
    "id": "269caf66-0ccc-43e7-b9a5-f16f84db0149",
    "meta": {
        "lastUpdated": "2019-11-20T19:30:26.858917+00:00"
    },
    "type": "searchset",
    "link": [{
            "relation": "self",
            "url": "https://localhost:44348/Patient?given=Jingerheimer&given=Apple"
        }
    ],
    "entry": [{
            "fullUrl": "https://localhost:44348/Patient/504f6bd3-e9b4-4846-8948-97bf09c70722",
            "resource": {
                "resourceType": "Patient",
                "id": "504f6bd3-e9b4-4846-8948-97bf09c70722",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2019-11-20T19:26:11.005+00:00"
                },
                "identifier": [{
                        "system": "ssn",
                        "value": "111-11-1111"
                    }, {
                        "system": "uuid",
                        "value": "da55d068e0784b359fa97498a11543c5"
                    }
                ],
                "name": [{
                        "family": "Smith",
                        "given": [
                            "John",
                            "Apple",
                            "Jingerheimer"
                        ]
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}

)

**Actual behavior**

Return zero results.

========================

Issue:

The generated SQL looks like this:

```

exec sp_executesql N'SET STATISTICS IO ON;
SET STATISTICS TIME ON;

WITH cte0 AS
(
    SELECT ResourceSurrogateId AS Sid1
    FROM dbo.StringSearchParam
    WHERE IsHistory = 0
        AND ResourceTypeId = @p0
        AND SearchParamId = @p1
        AND TextOverflow IS NULL AND Text LIKE @p2
        AND TextOverflow IS NULL AND Text LIKE @p3
    
),
cte1 AS
(
    SELECT * FROM cte0
    UNION ALL
    SELECT ResourceSurrogateId AS Sid1
    FROM dbo.StringSearchParam
    WHERE IsHistory = 0
        AND ResourceTypeId = @p0
        AND SearchParamId = @p1
        AND TextOverflow IS NOT NULL AND Text LIKE @p2
        AND TextOverflow IS NOT NULL AND Text LIKE @p3
    
),
cte2 AS
(
    SELECT DISTINCT TOP (@p4) Sid1, 1 AS IsMatch 
    FROM cte1
    ORDER BY Sid1 ASC
)
SELECT r.ResourceTypeId, r.ResourceId, r.Version, r.IsDeleted, r.ResourceSurrogateId, r.RequestMethod, CAST(IsMatch AS bit) AS IsMatch, r.RawResource
FROM dbo.Resource r
INNER JOIN cte2
ON r.ResourceSurrogateId = cte2.Sid1
ORDER BY r.ResourceSurrogateId ASC
OPTION(RECOMPILE)',N'@p0 smallint,@p1 smallint,@p2 nvarchar(256),@p3 nvarchar(256),@p4 int',@p0=103,@p1=694,@p2=N'Jingerheimer%',@p3=N'Apple%',@p4=11

```

The area of concern is this:

```
    SELECT ResourceSurrogateId AS Sid1
	--		SELECT *
    FROM dbo.StringSearchParam
    WHERE IsHistory = 0
        AND ResourceTypeId = 103
        AND SearchParamId = 694
        AND TextOverflow IS NULL AND Text LIKE 'Jingerheimer%'
        AND TextOverflow IS NULL AND Text LIKE 'Apple%'
```

The last two ANDs exclude each other.

If the generated SQL were the below: (note the INTERSECT)

```
    SELECT ResourceSurrogateId AS Sid1
	--		SELECT *
    FROM dbo.StringSearchParam
    WHERE IsHistory = 0
        AND ResourceTypeId = 103
        AND SearchParamId = 694
        AND TextOverflow IS NULL AND Text LIKE 'Jingerheimer%'
	INTERSECT
    SELECT ResourceSurrogateId AS Sid1
	--		SELECT *
    FROM dbo.StringSearchParam
    WHERE IsHistory = 0
        AND ResourceTypeId = 103
        AND SearchParamId = 694
        AND TextOverflow IS NULL AND Text LIKE 'Apple%'
```

It would find the correct rows.

But it looks like some decent refactoring of the below class and method.

```
namespace Microsoft.Health.Fhir.Core.Features.Search
{
    public class SearchOptionsFactory
public SearchOptions Create(string compartmentType, string compartmentId, string resourceType, IReadOnlyList<Tuple<string, string>> queryParameters)
```

**Comment by hansenms** [comment]
I have confirmed this bug. Adding the patient from our docs:

```
{
    "resourceType": "Patient",
    "active": true,
    "name": [
        {
            "use": "official",
            "family": "Kirk",
            "given": [
                "James",
                "Tiberious"
            ]
        },
        {
            "use": "usual",
            "given": [
                "Jim"
            ]
        }
    ],
    "gender": "male",
    "birthDate": "1960-12-25"
}
```

And searching for `/Patient?name=James&name=Tiberious` return no results.

**Comment by johnstairs** [comment]
Thanks @granadacoder for the excellent bug report.

Looks like TableExpressionCombiner is at fault here.

**Comment by hansenms** [comment]
@granadacoder, there should be a fix in for this now. Could you give it a go?

**Comment by granadacoder** [comment]
Sorry for the late response. I wasn't getting email alerts for some reason.

So the new pull is working correctly.

I will point out that in the generated sql, that cte0 and cte1 look somewhat redundant (see below).  But I may under appreciate how the sql-generation is.

But I am getting expected results.  Thanks.  #metYouAtJuneDevDays

(Both referring to @p2)

Query:

https://localhost:44348/Patient/?given=Jingerheimer&given=Apple

(from Profiler)


exec sp_executesql N'SET STATISTICS IO ON;
SET STATISTICS TIME ON;

WITH cte0 AS
(
    SELECT ResourceSurrogateId AS Sid1
    FROM dbo.StringSearchParam
    WHERE IsHistory = 0
        AND ResourceTypeId = @p0
        AND SearchParamId = @p1
        AND TextOverflow IS NULL AND Text LIKE @p2
),
cte1 AS
(
    SELECT * FROM cte0
    UNION ALL
    SELECT ResourceSurrogateId AS Sid1
    FROM dbo.StringSearchParam
    WHERE IsHistory = 0
        AND ResourceTypeId = @p0
        AND SearchParamId = @p1
        AND TextOverflow IS NOT NULL AND Text LIKE @p2
),
cte2 AS
(
    SELECT ResourceSurrogateId AS Sid1
    FROM dbo.StringSearchParam
    WHERE IsHistory = 0
        AND ResourceSurrogateId IN (SELECT Sid1 FROM cte1)
        AND ResourceTypeId = @p0
        AND SearchParamId = @p1
        AND TextOverflow IS NULL AND Text LIKE @p3
),
cte3 AS
(
    SELECT * FROM cte2
    UNION ALL
    SELECT ResourceSurrogateId AS Sid1
    FROM dbo.StringSearchParam
    WHERE IsHistory = 0
        AND ResourceSurrogateId IN (SELECT Sid1 FROM cte1)
        AND ResourceTypeId = @p0
        AND SearchParamId = @p1
        AND TextOverflow IS NOT NULL AND Text LIKE @p3
),
cte4 AS
(
    SELECT DISTINCT TOP (@p4) Sid1, 1 AS IsMatch 
    FROM cte3
    ORDER BY Sid1 ASC
)
SELECT r.ResourceTypeId, r.ResourceId, r.Version, r.IsDeleted, r.ResourceSurrogateId, r.RequestMethod, CAST(IsMatch AS bit) AS IsMatch, r.RawResource
FROM dbo.Resource r
INNER JOIN cte4
ON r.ResourceSurrogateId = cte4.Sid1
ORDER BY r.ResourceSurrogateId ASC
OPTION(RECOMPILE)',N'@p0 smallint,@p1 smallint,@p2 nvarchar(256),@p3 nvarchar(256),@p4 int',@p0=103,@p1=694,@p2=N'Jingerheimer%',@p3=N'Apple%',@p4=11

**Comment by johnstairs** [comment]
@granadacoder, thanks for validating. The similar CTEs above are expected. cte2 unions cte1, but the difference between the two is that first one only considers entries where the TextOverflow column in not null and the second where it is null. There are filtered nonclustered indexes on these two criteria (among others) and concatenating these two is more efficient than performing a single query with an OR.

**Comment by granadacoder** [comment]
Ok, thanks for the cte1 and cte2 explanation. I 'see' it now!
