### ISSUE TITLE
Server not responding to simple GET/POST on Patient

### ISSUE THREAD

**Issue by singhmanjeet1982** [microsoft/fhir-server#766]
**Describe the bug**
Installed FHIR server on our azure subscription with backend as SQL server. 
Run some GET/POST command and it worked.
Started Running regression test cases and it ran succesfully initially but started getting failed later on
Now simple GET/POST on patient is also not running. Giving 500 and 503 for GET and POST respectively
Only GET on metadata is working. so seems like server is up

**To Reproduce**
Steps to reproduce are given above

**Expected behavior**
Test cases should pass.

**Actual behavior**
All test cases failed after initial test. Now server is not responding to any GET/POST request

**Comment by hansenms** [comment]
@singhmanjeet1982, thanks for the bug report. Would it be possible to get a bit more specific on the steps to reproduce:

1. When you say you ran "some GET/POST", what exactly did you run?
2. Which regression test cases?

In other words, if you could provide the actual steps you did, it would help. 

Also, are you getting 500 or 503? And are there any logs on the web app?

**Comment by singhmanjeet1982** [comment]
Hi,
I Posted patient and get the patient. It worked fine.
Then I ran crucible tool for regression testing to see the conformance of my FHIR server. Test were passing initially then start failing.

There are no logs on the webapp. Using app insight on azure.

Thanks

**Comment by hansenms** [comment]
I would like to reproduce this, but I need a bit more specific information:

1. Exactly what patient did you POST? Please provide the payload.
2. Exactly which test did you run?

**Comment by singhmanjeet1982** [comment]
Say, GET is not working. No Payload, I just run it on postman
"https://<<Servername>>/Patient"
It should return me all the patients.

https://<<servername>>/metadata is working fine.

About regression testing. I ran crucible tool(projectcrucible.org/) on my azure FHIR server. It failed

**Comment by hansenms** [comment]
I cannot reproduce the problem from the steps you have provided. Please provide:

1. The data you loaded into the server.
2. The exact test that made it fail. 

We load data and run crucible tests with every build and have not observed the problem you are describing, so it is not easy to debug without the steps that creates it. I understand that it can sometimes be hard to trace the steps and figure out exactly when it happened, but it is even harder for us without access to your specific set-up. 

Can I ask that you:

1. Spin up a new server. 
2. Repeat the POSTs that you did. 
3. Run the crucible tests until you find the one that made it fail. 
4. Attach the steps to this bug report.

Also you say that you have app insights hooked up. Do you see any errors there. Any stacktrace?

**Comment by singhmanjeet1982** [comment]
ok. Let me spin up another server and try it again. I will let you know the results. Thanks

**Comment by singhmanjeet1982test** [comment]
I resolved the error by adding connectionstring to the FHIR server. It was deleted somehow by redeploying it. Thanks for your time.

**Comment by singhmanjeet1982** [comment]
I resolved the error by adding connectionstring to the FHIR server. It was deleted somehow when redeploying it. Thanks for your time.
