### ISSUE TITLE
Search using custom search parameters

### ISSUE THREAD

**Issue by ellgre** [microsoft/fhir-server#768]
**User story**
As an end user I want to be able to filter Practitioners based on qualification.code so that I can look at a specific group of Practitioners.

**Acceptance criteria**
1. When I use the FHIR search criteria for code, only Practitioners with the given qualification.code are returned. 

Search criteria for code as explained in FHIR (https://www.hl7.org/fhir/search.html):
_GET [base]/Condition?code=http://acme.org/conditions/codes\|ha125_ | Search for any condition with a code "ha125" in the code system "http://acme.org/conditions/codes"
-- | --
_GET [base]/Condition?code=ha125_ | Search for any condition with a code "ha125". Note that there is not often any useful overlap in literal symbols between code systems, so the previous example is generally preferred.

We need the same for type.code for healthcareService and maybe also other resources.

**Comment by hansenms** [comment]
Searching for CodeableConcepts as you describe is supported in general and it works for Condition as you described. However, qualification is not a standard search parameter per the FHIR spec. If you want to add it yourself you can add it to `search-parameters.json` (e.g. https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.R4.Core/Features/Definition/search-parameters.json) and the server will index it.

Adding @brendankowitz to see if anything needs to be done to add it to the capability statement after the refactor of that code.

We are planning some easier ways to do this in our managed service as well, but for now it is only possible in the OSS version.

**Comment by hansenms** [comment]
Renaming this to reflect the actual request.

**Comment by brendankowitz** [comment]
Should be fine, currently, all search parameters defined in this file should be reflected in the capability statement.

**Comment by CaitlinV39** [comment]
This is now available. You can find all the documentation here:

1. https://docs.microsoft.com/azure/healthcare-apis/fhir/how-to-do-custom-search
2. https://docs.microsoft.com/azure/healthcare-apis/fhir/how-to-run-a-reindex

**Comment by neenujoy** [comment]
> Searching for CodeableConcepts as you describe is supported in general and it works for Condition as you described. However, qualification is not a standard search parameter per the FHIR spec. If you want to add it yourself you can add it to `search-parameters.json` (e.g. https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.R4.Core/Features/Definition/search-parameters.json) and the server will index it.
> 
> Adding @brendankowitz to see if anything needs to be done to add it to the capability statement after the refactor of that code.
> 
> We are planning some easier ways to do this in our managed service as well, but for now it is only possible in the OSS version.

Can you specify custom search parameter for immunization/recorded

> Searching for CodeableConcepts as you describe is supported in general and it works for Condition as you described. However, qualification is not a standard search parameter per the FHIR spec. If you want to add it yourself you can add it to `search-parameters.json` (e.g. https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.R4.Core/Features/Definition/search-parameters.json) and the server will index it.
> 
> Adding @brendankowitz to see if anything needs to be done to add it to the capability statement after the refactor of that code.
> 
> We are planning some easier ways to do this in our managed service as well, but for now it is only possible in the OSS version.

Can you give custom search parameter for "immunization/recorded" to be included in search-parameters.json

**Comment by CaitlinV39** [comment]
@neenujoy - Now we would recommend that you could create a custom search parameter as defined in the documents above and reindex your database. If you have additional questions, please feel free to open a new issue so we can track.
