### ISSUE TITLE
Invalid `Patient.birthDate` formats not rejected

### ISSUE THREAD

**Issue by hansenms** [microsoft/fhir-server#775]
**Describe the bug**
The FHIR spec defines `Patient.birthDate` as a `date` type and clearly says about this type that "There SHALL be no time zone". It defines a date with the regex `([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1]))?)?`. 

The FHIR server accepts `Patient.birthDate` with the form: `2019-11-04T23:00:00.000Z`. 

**To Reproduce**
1. POST /Patient with payload:

```
{
    "resourceType": "Patient",
    "active": true,
    "name": [
        {
            "use": "official",
            "family": "Kirk",
            "given": [
                "James",
                "Tiberious"
            ]
        },
        {
            "use": "usual",
            "given": [
                "Jim"
            ]
        }
    ],
    "gender": "male",
    "birthDate": "2019-11-04T23:00:00.000Z"
}
```

**Expected behavior**
The FHIR server should reject the resource since it fails validation. 

**Actual behavior**
Patient resources with malformed `birthDate` fields are accepted.

**Comment by brendankowitz** [comment]
This regex is already defined in Hl7.Fhir.Model.Date which is used on the Patient model (Hl7.Fhir.Model.Patient.BirthDateElement). Possibly its not rejected because we're using PermissiveParsing (Microsoft.Health.Fhir.Core.Features.DefaultParserSettings).
Perhaps the question is should we expose an option to set stricter validation?

**Comment by hansenms** [comment]
I think it should default to strict.

**Comment by brendankowitz** [comment]
I'll make a task for exposing this setting, there will be a fair bit of fall-out with strict on; I think there are Crucible tests that fail, potentially E2E (which we can/should fix). Then it would be ok for new instances, but existing instances would want this to remain off.

**Comment by CaitlinV39** [comment]
Closing this as we will look to address in profile and validation work. Have this documented as a scenario
