### ISSUE TITLE
Setup docker container build

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#779]
**User story**
As a developer, I want to build a docker container during CI/PRs so that it remains deployable and valid

**Acceptance criteria**
1. Build step for docker container
1. CI Build pushes to dockerhub or ACR
1. Tagging a release can tag the docker image

**Comment by egbertn** [comment]
I found out that
docker_global.json should be:
 {
  "sdk": {
    "version": "2.2.207"
  }
}
and global.json should have
{
  "sdk": {
    "version": "2.2.105"
  }
}

but then later during building the release build the nuget packages use obsolete versions.

  Restore completed in 3.38 sec for /build/src/Microsoft.Health.Fhir.R4.Core/Microsoft.Health.Fhir.R4.Core.csproj.
  Restore completed in 10.77 sec for /build/src/Microsoft.Health.Fhir.SqlServer.Api/Microsoft.Health.Fhir.SqlServer.Api.csproj.
  Restore completed in 130.23 ms for /build/src/Microsoft.Health.Fhir.SqlServer/Microsoft.Health.Fhir.SqlServer.csproj.
  Restore completed in 12.14 sec for /build/src/Microsoft.Health.Fhir.R4.Web/Microsoft.Health.Fhir.R4.Web.csproj.
  Restore completed in 100.04 ms for /build/src/Microsoft.Health.Fhir.ValueSets/Microsoft.Health.Fhir.ValueSets.csproj.
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Repository has no remote. [/build/src/Microsoft.Health.Extensions.DependencyInjection/Microsoft.Health.Extensions.DependencyInjection.csproj]
/root/.nuget/packages/microsoft.sourcelink.github/1.0.0-beta2-19270-01/build/Microsoft.SourceLink.GitHub.targets(36,5): warning : Unable to determine repository url, the source code won't be available via source link. [/build/src/Microsoft.Health.Extensions.DependencyInjection/Microsoft.Health.Extensions.DependencyInjection.csproj]
/root/.nuget/packages/microsoft.sourcelink.common/1.0.0-beta2-19270-01/build/Microsoft.SourceLink.Common.targets(50,5): warning : Source control information is not available - the generated source link is empty. [/build/src/Microsoft.Health.Extensions.DependencyInjection/Microsoft.Health.Extensions.DependencyInjection.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-19270-01/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Repository has no remote. [/build/src/Microsoft.Health.Fhir.ValueSets/Microsoft.Health.Fhir.ValueSets.csproj]
/root/.nuget/packages/microsoft.sourcelink.github/1.0.0-beta2-19270-01/build/Microsoft.SourceLink.GitHub.targets(36,5): warning : Unable to determine repository url, the source code won't be available via source link. [/build/src/Microsoft.Health.Fhir.ValueSets/Microsoft.Health.Fhir.ValueSets.csproj]
/root/.nuget/packages/microsoft.sourcelink.common/1.0.0-beta2-19270-01/build/Microsoft.SourceLink.Common.targets(50,5): warning : Source control information is not available - the generated source link is empty. [/build/src/Microsoft.Health.Fhir.ValueSets/Microsoft.Health.Fhir.ValueSets.csproj]
  Microsoft.Health.Fhir.ValueSets -> /build/src/Microsoft.Health.Fhir.ValueSets/bin/Release/netcoreapp2.2/Microsoft.Health.Fhir.ValueSets.dll
  Microsoft.Health.Extensions.DependencyInjection -> /build/src/Microsoft.Health.Extensions.DependencyInjection/bin/Release/netstandard2.0/Microsoft.Health.Extensions.DependencyInjection.dll

**Comment by hansenms** [comment]
@egbertn, I think #803 addresses this.

**Comment by egbertn** [comment]
" Repository has no remote. "
"Unable to determine repository url, the source code won't be available via source link. "

Still not solved.

**Comment by egbertn** [comment]
The problem is, the docker build fails because the csproj files contain references to beta nuget packages which are not available. Maybe it can be solved if no beta's are used and merged with master? Thanks!

**Comment by hansenms** [comment]
@brendankowitz what is the story with that sourcelink stuff?

**Comment by brendankowitz** [comment]
From what I've seen today, it'd make things easier if the docker build respected the Directory.build.props file.

For now, I'd propose something like this (I was testing this as part of upgrading to 3.1, seemed to build fine for me):
https://github.com/microsoft/fhir-server/blob/8992089313014f380b59215ff5cf2c1d82275bf1/samples/docker/Dockerfile#L10-L11

We are only using public nuget feeds in this repository they should all exist. Sourcelink allows us to generate pdb files that link back to the sourcecode here on github.

**Comment by brendankowitz** [comment]
Closing this as we now are using docker images in our builds and prs
