### ISSUE TITLE
Can't deploy ARM template on existing linux app service plan

### ISSUE THREAD

**Issue by jahead** [microsoft/fhir-server#783]
Hey guys, 

I'm seeing an issue when I deploy the default arm template when trying to deploy to an existing plan. 
` Microsoft.Web/sites/config `
```
 Status Message
{
  "Code": "BadRequest",
  "Message": "AppSetting with name 'KeyVault:Endpoint' is not allowed.",
  "Target": null,
  "Details": [
    {
      "Message": "AppSetting with name 'KeyVault:Endpoint' is not allowed."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "04072",
        "MessageTemplate": "AppSetting with name '{0}' is not allowed.",
        "Parameters": [
          "KeyVault:Endpoint"
        ],
        "Code": "BadRequest",
        "Message": "AppSetting with name 'KeyVault:Endpoint' is not allowed."
      }
    }
  ],
  "Innererror": null
}
```

**Comment by hansenms** [comment]
Could you provide the steps to reproduce the error?

**Comment by jahead** [comment]
1. Have an existing blessed Linux app service plan (S1)
2. Deploy the standard default cosmosDB Arm template
* Default settings
* Fhir proxy disabled
* Stu3
* I was deploying on Australia east.
* set App service plan resource group to where the app service plan lives
* Set app service plan name to the correct plan name

Hit purchase

Should crash quickly on the key vault app settings

When I looked into this a while back.
I believe it's due to the string structure. The azure blessed Linux images are docker based and I think it's because it's setting an app setting string that the Linux app service doesn't like. But it has been a while since I had a serious look into it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hansenms** [comment]
We don't really test with that configuration. We cannot generally support arbitrary custom images. I would recommend that you roll your own deployment for this. Do a separate build of the FHIR server (on your own device) or make a docker container (We have a Dockerfile in the repo) and deploy yourself. Without specific steps (that would include your custom image, etc.), there is no way for us to dig in and debug this.

**Comment by jahead** [comment]
It's not a custom image.

It's the default linux image that ships with Azure app service.

**Comment by hansenms** [comment]
It’s not really a scenario we test with the arm template. The template is an example of how one could provision the service but not tested with every permutation of app service configuration. So to be specific Linux app service is not a tester scenario at the moment. We do build the code and run unit tests on Linux but we don’t deploy on Linux app service.

**Comment by jahead** [comment]
Um, okay. Maybe we could document that in the DefaultDeployment.md?
"ARM doesn't support existing Linux app service plans?"
As I wasted a bit of time thinking it was something I was doing wrong. 

I'd fix this for you; if you want, but I'm not really an arm expert.

If you're looking for more information about this. Read on, otherwise thank you for your help :) 

I believe the issue is that you are trying to set an invalid environment variable for Linux. 
For reference

```
Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names.
```
Which is probably why the Linux app service plan blocks such assignments.

The offending assignment is ``` KeyVault:Endpoint``` as an environment variable.

**Comment by hansenms** [comment]
I understand that it is frustrating to waste time on something that doesn't work the way you expect, it is just not a scenario that we have tested. So my apologies for that, I am not sure we can really practically enumerate all the things we don't test. 

You may be on to the explanation with the stuff you posted, but it would take some more digging in to determine if that is really the case.  If you want to commit a fix for it, we would be very grateful. We test the standard deployment as part of our PR build process, so we would notice if it broke the standard deployment. 

Again, if you want to deploy it on Linux, I suggest taking the Dockerfile and deploying it as a container. You may find that to be a smoother ride.
