### ISSUE TITLE
FHIR Everything

### ISSUE THREAD

**Issue by ecaras** [microsoft/fhir-server#784]
As a user, I want to get a resource and all it's related sub-resource. Example a Patient and all of it's related Encounters,Practitioners and so on $everything.

**Comment by hansenms** [comment]
You could just do a search for 

`/Patient/1234/*`

And you will get all the resources in that patients compartment. the `$everything`  is not super well defined in the spec, so it is not clear we would have a better implementation than just everything in the compartment.

**Comment by ecaras** [comment]
Great! thanks Michael..

**Comment by rameshkr1994** [comment]
> 
> 
> As a user, I want to get a resource and all it's related sub-resource. Example a Patient and all of it's related Encounters,Practitioners and so on $everything.



Hi @ecaras  and @hansenms 

i wanted to same query that fetch all matched data from all resources based on identifier or gender or any other fields ?


could you please help me out .

below is the more details about my issue...
[https://github.com/microsoft/fhir-server/issues/837](url)




Thanks
HadoopHelp

**Comment by rameshkr1994** [comment]
> 
> 
> You could just do a search for
> 
> `/Patient/1234/*`
> 
> And you will get all the resources in that patients compartment. the `$everything` is not super well defined in the spec, so it is not clear we would have a better implementation than just everything in the compartment.

Dear  @hansenms .

as per your given query: -

>>/Patient/1234/*

here  "1234" is id for Patient resource ?that id will match with all related sub resources(id:-1234) ?

but in my case all ID is different to each other but identifier value is same for all resources ?how can we search in this case?



Thanks
HadoopHelp

**Comment by rameshkr1994** [comment]
Hi @ecaras  and @hansenms .

i tried the same but not working please help :-  
with my query 👎 
https://opensrce.azurewebsites.net/?Patient/549/*&_format=application/json //here added ?
below is the screen error:-  
![image](https://user-images.githubusercontent.com/51785654/72627216-1afc0380-3972-11ea-80f8-8a9ae129ca40.png)

with your query not getting data?
![image](https://user-images.githubusercontent.com/51785654/72627308-3f57e000-3972-11ea-95c9-78ed5c11f733.png)



i written query as same  you discussed  but i am fail in my case.

in my case ,id value is same for each resources but getting all records(matched and  non matched ) from fhir server but we are looking for only matched id value like id:549 ?


is there any concept of linking the resource with each other please help me ?



Thanks
HadoopHelp




in above error Link is showing zero

**Comment by hansenms** [comment]
Both of those URLs are incorrect, in the first case, with the `?` added before Patient, you are referring to a non-existing resource type. In the latter case, you have the `&` without other search parameters.

The correct URL (which I have checked) would be:

https://opensrce.azurewebsites.net/Patient/549/*?_format=application/json

> Please direct all general FHIR questions to https://chat.fhir.org or https://stackoverflow.com/questions/tagged/hl7-fhir. The issues here should really focus on bugs and features directly related to the Microsoft FHIR server for Azure.

**Comment by rameshkr1994** [comment]
Hi @ecaras  and @hansenms 

i tried with same but no result is fetching .

Address :-
![image](https://user-images.githubusercontent.com/51785654/72706573-5f5eed80-3b84-11ea-9aeb-6244c25ea808.png)
below the query/URL response : -

![image](https://user-images.githubusercontent.com/51785654/72707354-37708980-3b86-11ea-800b-ae7a268ffa4e.png)


i don,t know why ?i think is there any concept for linking all resources ?


below is my sample data for Patient and Practitioner  with FHIR SERVER:-
Patient;-
`{
    "id": "549",
    "isSystem": false,
    "searchIndices": [
        {
            "p": "_id",
            "c": "549"
        },
        {
            "p": "_lastUpdated",
            "st": "2020-01-17T14:31:33.0060000+00:00",
            "et": "2020-01-17T14:31:33.0060000+00:00"
        },
        {
            "p": "active",
            "s": "http://hl7.org/fhir/special-values",
            "c": "true"
        },
        {
            "p": "address",
            "s": "PleasantVille",
            "n_s": "PLEASANTVILLE"
        },
        {
            "p": "address",
            "s": "Rainbow",
            "n_s": "RAINBOW"
        },
        {
            "p": "address",
            "s": "534 Erewhon St",
            "n_s": "534 EREWHON ST"
        },
        {
            "p": "address",
            "s": "3999",
            "n_s": "3999"
        },
        {
            "p": "address",
            "s": "Vic",
            "n_s": "VIC"
        },
        {
            "p": "address",
            "s": "534 Erewhon St PeasantVille, Rainbow, Vic  3999",
            "n_s": "534 EREWHON ST PEASANTVILLE, RAINBOW, VIC  3999"
        },
        {
            "p": "address-city",
            "s": "PleasantVille",
            "n_s": "PLEASANTVILLE"
        },
        {
            "p": "address-postalcode",
            "s": "3999",
            "n_s": "3999"
        },
        {
            "p": "address-state",
            "s": "Vic",
            "n_s": "VIC"
        },
        {
            "p": "address-use",
            "s": "http://hl7.org/fhir/address-use",
            "c": "home"
        },
        {
            "p": "birthdate",
            "st": "1974-12-25T00:00:00.0000000+00:00",
            "et": "1974-12-25T23:59:59.9999999+00:00"
        },
        {
            "p": "deceased",
            "s": "http://hl7.org/fhir/special-values",
            "c": "false"
        },
        {
            "p": "family",
            "s": "Chalmers",
            "n_s": "CHALMERS"
        },
        {
            "p": "family",
            "s": "Windsor",
            "n_s": "WINDSOR"
        },
        {
            "p": "gender",
            "s": "http://hl7.org/fhir/administrative-gender",
            "c": "male"
        },
        {
            "p": "given",
            "s": "bhau",
            "n_s": "BHAU"
        },
        {
            "p": "given",
            "s": "James",
            "n_s": "JAMES"
        },
        {
            "p": "given",
            "s": "Jim",
            "n_s": "JIM"
        },
        {
            "p": "given",
            "s": "Peter",
            "n_s": "PETER"
        },
        {
            "p": "identifier",
            "s": "urn:oid:1.2.36.146.595.217.0.1",
            "c": "549"
        },
        {
            "p": "name",
            "s": "bhau",
            "n_s": "BHAU"
        },
        {
            "p": "name",
            "s": "James",
            "n_s": "JAMES"
        },
        {
            "p": "name",
            "s": "Chalmers",
            "n_s": "CHALMERS"
        },
        {
            "p": "name",
            "s": "Jim",
            "n_s": "JIM"
        },
        {
            "p": "name",
            "s": "Peter",
            "n_s": "PETER"
        },
        {
            "p": "name",
            "s": "James",
            "n_s": "JAMES"
        },
        {
            "p": "name",
            "s": "Windsor",
            "n_s": "WINDSOR"
        },
        {
            "p": "organization",
            "rt": "Organization",
            "ri": "1"
        },
        {
            "p": "phone",
            "s": "work",
            "c": "(03) 5555 6473"
        },
        {
            "p": "phone",
            "s": "mobile",
            "c": "(03) 3410 5613"
        },
        {
            "p": "phone",
            "s": "old",
            "c": "(03) 5555 8834"
        },
        {
            "p": "phonetic",
            "s": "bhau",
            "n_s": "BHAU"
        },
        {
            "p": "phonetic",
            "s": "James",
            "n_s": "JAMES"
        },
        {
            "p": "phonetic",
            "s": "Chalmers",
            "n_s": "CHALMERS"
        },
        {
            "p": "phonetic",
            "s": "Jim",
            "n_s": "JIM"
        },
        {
            "p": "phonetic",
            "s": "Peter",
            "n_s": "PETER"
        },
        {
            "p": "phonetic",
            "s": "James",
            "n_s": "JAMES"
        },
        {
            "p": "phonetic",
            "s": "Windsor",
            "n_s": "WINDSOR"
        },
        {
            "p": "telecom",
            "s": "work",
            "c": "(03) 5555 6473"
        },
        {
            "p": "telecom",
            "s": "mobile",
            "c": "(03) 3410 5613"
        },
        {
            "p": "telecom",
            "s": "old",
            "c": "(03) 5555 8834"
        }
    ],
    "partitionKey": "Patient_549",
    "lastModified": "2020-01-17T14:31:33.0060000+00:00",
    "rawResource": {
        "data": "{\"resourceType\":\"Patient\",\"id\":\"549\",\"text\":{\"status\":\"generated\",\"div\":\"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">\\n\\t\\t\\t<table>\\n\\t\\t\\t\\t<tbody>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Name</td>\\n\\t\\t\\t\\t\\t\\t<td>Peter James \\n              <b>Chalmers</b> (&quot;Jim&quot;)\\n            </td>\\n\\t\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Address</td>\\n\\t\\t\\t\\t\\t\\t<td>534 Erewhon, Pleasantville, Vic, 3999</td>\\n\\t\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Contacts</td>\\n\\t\\t\\t\\t\\t\\t<td>Home: unknown. Work: (03) 5555 6473</td>\\n\\t\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t\\t<td>Id</td>\\n\\t\\t\\t\\t\\t\\t<td>MRN: 12345 (Acme Healthcare)</td>\\n\\t\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\t</tbody>\\n\\t\\t\\t</table>\\n\\t\\t</div>\"},\"identifier\":[{\"use\":\"usual\",\"type\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0203\",\"code\":\"MR\"}]},\"system\":\"urn:oid:1.2.36.146.595.217.0.1\",\"value\":\"549\",\"period\":{\"start\":\"2001-05-06\"},\"assigner\":{\"display\":\"Acme Healthcare\"}}],\"active\":true,\"name\":[{\"use\":\"official\",\"family\":\"Chalmers\",\"given\":[\"bhau\",\"James\"]},{\"use\":\"usual\",\"given\":[\"Jim\"]},{\"use\":\"maiden\",\"family\":\"Windsor\",\"given\":[\"Peter\",\"James\"],\"period\":{\"end\":\"2002\"}}],\"telecom\":[{\"use\":\"home\"},{\"system\":\"phone\",\"value\":\"(03) 5555 6473\",\"use\":\"work\",\"rank\":1},{\"system\":\"phone\",\"value\":\"(03) 3410 5613\",\"use\":\"mobile\",\"rank\":2},{\"system\":\"phone\",\"value\":\"(03) 5555 8834\",\"use\":\"old\",\"period\":{\"end\":\"2014\"}}],\"gender\":\"male\",\"birthDate\":\"1974-12-25\",\"deceasedBoolean\":false,\"address\":[{\"use\":\"home\",\"type\":\"both\",\"text\":\"534 Erewhon St PeasantVille, Rainbow, Vic  3999\",\"line\":[\"534 Erewhon St\"],\"city\":\"PleasantVille\",\"district\":\"Rainbow\",\"state\":\"Vic\",\"postalCode\":\"3999\",\"period\":{\"start\":\"1974-12-25\"}}],\"contact\":[{\"relationship\":[{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0131\",\"code\":\"N\"}]}],\"name\":{\"family\":\"du MarchÃ©\",\"given\":[\"BÃ©nÃ©dicte\"]},\"telecom\":[{\"system\":\"phone\",\"value\":\"+33 (237) 998327\"}],\"address\":{\"use\":\"home\",\"type\":\"both\",\"line\":[\"534 Erewhon St\"],\"city\":\"PleasantVille\",\"district\":\"Rainbow\",\"state\":\"Vic\",\"postalCode\":\"3999\",\"period\":{\"start\":\"1974-12-25\"}},\"gender\":\"female\",\"period\":{\"start\":\"2012\"}}],\"managingOrganization\":{\"reference\":\"Organization/1\"}}",
        "format": "Json"
    },
    "request": {
        "url": "https://opensrcfhirservice.azurewebsites.net/Patient/549",
        "method": "PUT"
    },
    "isDeleted": false,
    "resourceId": "549",
    "resourceTypeName": "Patient",
    "isHistory": false,
    "lastModifiedClaims": [],
    "compartmentIndices": {},
    "version": "2",
    "_rid": "SDIsAOrCbqeHAAAAAAAAAA==",
    "_self": "dbs/SDIsAA==/colls/SDIsAOrCbqc=/docs/SDIsAOrCbqeHAAAAAAAAAA==/",
    "_etag": "\"0000ef03-0000-0c00-0000-5e21c5450000\"",
    "_attachments": "attachments/",
    "_ts": 1579271493
}`

Practitioner sample data:-
--------------------------------------------------------------------------------------------------------
`{
    "id": "549",
    "isSystem": false,
    "searchIndices": [
        {
            "p": "_id",
            "c": "549"
        },
        {
            "p": "_lastUpdated",
            "st": "2020-01-17T14:52:36.5620000+00:00",
            "et": "2020-01-17T14:52:36.5620000+00:00"
        },
        {
            "p": "address",
            "s": "PleasantVille",
            "n_s": "PLEASANTVILLE"
        },
        {
            "p": "address",
            "s": "534 br St",
            "n_s": "534 BR ST"
        },
        {
            "p": "address",
            "s": "3999",
            "n_s": "3999"
        },
        {
            "p": "address",
            "s": "Vic",
            "n_s": "VIC"
        },
        {
            "p": "address-city",
            "s": "PleasantVille",
            "n_s": "PLEASANTVILLE"
        },
        {
            "p": "address-postalcode",
            "s": "3999",
            "n_s": "3999"
        },
        {
            "p": "address-state",
            "s": "Vic",
            "n_s": "VIC"
        },
        {
            "p": "address-use",
            "s": "http://hl7.org/fhir/address-use",
            "c": "home"
        },
        {
            "p": "family",
            "s": "Careful",
            "n_s": "CAREFUL"
        },
        {
            "p": "given",
            "s": "bhau",
            "n_s": "BHAU"
        },
        {
            "p": "phonetic",
            "s": "bhau",
            "n_s": "BHAU"
        },
        {
            "p": "phonetic",
            "s": "Careful",
            "n_s": "CAREFUL"
        },
        {
            "p": "phonetic",
            "s": "Dr",
            "n_s": "DR"
        },
        {
            "p": "active",
            "s": "http://hl7.org/fhir/special-values",
            "c": "true"
        },
        {
            "p": "identifier",
            "s": "http://www.acme.org/practitioners",
            "c": "111"
        },
        {
            "p": "name",
            "s": "bhau",
            "n_s": "BHAU"
        },
        {
            "p": "name",
            "s": "Careful",
            "n_s": "CAREFUL"
        },
        {
            "p": "name",
            "s": "Dr",
            "n_s": "DR"
        }
    ],
    "partitionKey": "Practitioner_549",
    "lastModified": "2020-01-17T14:52:36.5620000+00:00",
    "rawResource": {
        "data": "{\"resourceType\":\"Practitioner\",\"id\":\"549\",\"text\":{\"status\":\"generated\",\"div\":\"<div xmlns=\\\"http://www.w3.org/1999/xhtml\\\">\\n      <p>Dr Adam Careful is a Referring Practitioner for Acme Hospital from 1-Jan 2012 to 31-Mar\\n        2012</p>\\n    </div>\"},\"identifier\":[{\"system\":\"http://www.acme.org/practitioners\",\"value\":\"111\"}],\"active\":true,\"name\":[{\"family\":\"Careful\",\"given\":[\"bhau\"],\"prefix\":[\"Dr\"]}],\"address\":[{\"use\":\"home\",\"line\":[\"534 br St\"],\"city\":\"PleasantVille\",\"state\":\"Vic\",\"postalCode\":\"3999\"}],\"qualification\":[{\"identifier\":[{\"system\":\"http://example.org/UniversityIdentifier\",\"value\":\"12345\"}],\"code\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0360/2.7\",\"code\":\"BS\",\"display\":\"Bachelor of Science\"}],\"text\":\"Bachelor of Science\"},\"period\":{\"start\":\"1995\"},\"issuer\":{\"display\":\"Example University\"}}]}",
        "format": "Json"
    },
    "request": {
        "url": "https://opensrcfhirservice.azurewebsites.net/Practitioner/549",
        "method": "PUT"
    },
    "isDeleted": false,
    "resourceId": "549",
    "resourceTypeName": "Practitioner",
    "isHistory": false,
    "lastModifiedClaims": [],
    "compartmentIndices": {},
    "version": "2",
    "_rid": "SDIsAOrCbqeJAAAAAAAAAA==",
    "_self": "dbs/SDIsAA==/colls/SDIsAOrCbqc=/docs/SDIsAOrCbqeJAAAAAAAAAA==/",
    "_etag": "\"0000f303-0000-0c00-0000-5e21ca340000\"",
    "_attachments": "attachments/",
    "_ts": 1579272756
}`

We can check above sample Practitioner  and Patient data have same ID value :-  549

Now we want to get both records by using above query/URL?

Note:- The main agenda here is , i want all resources data that contains ID=549.



Thanks
HadoopHelp






below is my search code :-
that is not fetching any data;-
https://opensice.azurewebsites.net/Patient/549/*?_format=application/json

I want to fetch all data that contains ID=549?




Thanks
HadoopHelp

**Comment by hansenms** [comment]
When you do a search for:

```
GET https://fhirserver/Patient/549/*
```

You should get all resources in patient 549's compartment. So all the resources linked to that patient: https://www.hl7.org/fhir/compartmentdefinition-patient.html. That is assuming that you have made sure that resource links (e.g. `Observation.subject.reference`, etc.) are set correctly to point to that patient. 

If you would like all resources that have `id` 549, then you would do something like:

```
GET https://fhirserver/?_id=549
```

It is, however, not best practice to use the same ids (even across resources). It is possible, but probably not the best id.

> It would be best if we could put general FHIR questions on Stackoverflow (https://stackoverflow.com/tags/hl7-fhir) or https://chat.fhir.org.
