### ISSUE TITLE
FHIR Resource ID striped by API

### ISSUE THREAD

**Issue by ecaras** [microsoft/fhir-server#786]
FHIR API striped the resource ID when posting/uploading resource. Hence the reference for each resource is lost. For example an encounter resource lost the reference to patient resource because the patient id is striped and replaced when uploaded though FHIR api. Is there a setting or a way we can stop this feature by the api? If there's no way, is there a way where we can upload resource and still retain the reference to each resources.

Steps to replicate:
1. Post a patient resource using postman.
2. Check the patient resource and inspect the ID, notice that it has been replaced.

**Comment by hansenms** [comment]
This is correct behavior. When you `POST` a resource, the server should create a new `id`. If you would like to preserve the `id`, use `PUT`, e.g.:

```
PUT //Patient/1234
```

with a payload:

```
{
  "resourceType": "Patient",
  "id": "1234",

   // ... more stuff
}
```

If Patient `1234` already exists, it will be updated, if not it will be created (with that id). 

This is all according to spec.
