### ISSUE TITLE
crucible Conformance - 85%

### ISSUE THREAD

**Issue by singhmanjeet1982test** [microsoft/fhir-server#791]
Hi
I ran the crucible on my server and the conformance score come out to be 85%
https://projectcrucible.org/servers/5ddb184604ebd0407b00001c

Is there any way we can increase it to 90% +

Thanks for your time.

Manjeet

**Comment by hansenms** [comment]
What specific functionality are you looking for? 90% is pretty arbitrary and it really all depends on what you are trying to support.

**Comment by hansenms** [comment]
We are not planning on targeting a specific percentage on this.
