### ISSUE TITLE
Upgrade to .Net Core 3

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#797]
It seems .NET Core 2.2 has reached end of support as of Dec 23. We should look into upgrading to .NET Core 3.

https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by chgl** [comment]
There is already some work being done here: https://github.com/microsoft/fhir-server/pull/685.

**Comment by hansenms** [comment]
Thanks @chgl, that PR is auto-generated, but there is a bit of work here, so this issue is mean to track that.
