### ISSUE TITLE
Docker for development doesn't work

### ISSUE THREAD

**Issue by dixpac** [microsoft/fhir-server#802]
I'm trying to setup development following docker instructions here https://github.com/microsoft/fhir-server/blob/master/samples/docker/README.md

`env SAPASSWORD='mypass' docker-compose -f samples/docker/docker-compose.yaml up -d`

But it doesn't work I get this error (tried on OSX mojave and Ubuntu 18.94)
<img width="1280" alt="Screenshot 2020-01-02 at 12 54 37" src="https://user-images.githubusercontent.com/7427365/71666000-54702480-2d5f-11ea-87ba-9ede338187e6.png">

Help would be much appreciated :) ?

**Comment by dixpac** [comment]
I'm .net beginner. It seems that docker image `mcr.microsoft.com/dotnet/core/sdk:2.2-bionic`
doesn't have a SKD with version `2.2.408` but `2.2.207`. When I change to `2.2.207` here [here](https://github.com/microsoft/fhir-server/blob/master/samples/docker/docker_global.json#L3)
Then this step executes successfully but I got error on publish [here](https://github.com/microsoft/fhir-server/blob/master/samples/docker/Dockerfile#L14)

**Comment by hansenms** [comment]
@marrobi

**Comment by marrobi** [comment]
@dixpac odd. Just pulled from master and ran the compose command and the images built ok.

We are doing something slightly odd to override the default SDK version, this line: https://github.com/microsoft/fhir-server/blob/e2a8a845563770f812badfc693fccc6317d82fed/samples/docker/Dockerfile#L8 to set it to `2.2.408` as thats waht was in the image `2.2-bionic` image

Hmm, just re pulled the `2.2-bionic` image and seems the tag is associated with a new image. I can reproduce the error. Leave it with me while I figure out how the image versions work..

**Comment by marrobi** [comment]
@dixpac weird that the SDK version has gone from `2.2.408` to `2.2.207` in a newer image. I'll update the `global.json` and the image tag to `2.2.207-bionic`

I made the change exactly as you have above and the build succeeded. Could you post the error you got on publish?

@hansenms do you know we can ensure we always use the SDK version available in the image? Otherwise each time it is changed on Docker hub the build will break. Will try to find out.

**Comment by hansenms** [comment]
Well, I think what we ultimately need to do is to have the Docker build done as part of our PR build process, so we know it is working. We should then publish the images so that we at least know where to find a working version. We have a work item for this #779.

**Comment by hansenms** [comment]
@dixpac, can you have a look at this branch (#803)  and see if that solves your problem. We are running tests, etc. and will merge upon confirmation that it addresses your issue.

**Comment by dixpac** [comment]
@marrobi @hansenms https://github.com/microsoft/fhir-server/pull/803
