### ISSUE TITLE
Can we provide own sql server licence

### ISSUE THREAD

**Issue by Lovkeshgoyal** [microsoft/fhir-server#808]
Hi,

I am going to deploy this fhir server to Azure. I would like to use SQL Db to enable the transaction bundle as It is not enabled in cosmos DB.
But I do have my SQL server DB license already so I would like to reuse it to save my cost.
I am not sure whether we can use my license or not If we can use it then what I need to do for this?
and Is there any possibility if I can use any other opensource database like MySql, PostgreSQL etc.?

**Comment by hansenms** [comment]
When you provision your SQL server, you can (at least for the vCores model) select bring your own license:

![image](https://user-images.githubusercontent.com/1149740/72083806-423e3b00-32b7-11ea-83b9-b18b02f2fd0b.png)

You can also run the SQL server in a VM or in a Docker container, e.g. if you want to run the development version. 

If this is for cheap development version, I think you will find that the lower tier Azure SQL would be cheaper either way.

We don't have templates that deploy the FHIR server with those options, but it should be trivial to modify the template (https://github.com/microsoft/fhir-server/blob/master/samples/templates/default-azuredeploy-sql.json) we have to use whatever SQL server you have deployed.

In terms of using another database, this was raised in #800,  we are currently planning support for other databases solely to reduce the license cost of running the server. If there is additional functionality it would unlock, we can consider it. 

For now I am closing this issue. It is a database licensing thing and not something we can tackle as part of this project.
