### ISSUE TITLE
OR conditions for composite search fails

### ISSUE THREAD

**Issue by hansenms** [microsoft/fhir-server#814]
**Describe the bug**
When searching using an OR condition on composite search parameters, server fails with 403 forbidden, "The number of composite components specified for search parameter 'component-code-value-quantity' exceeded the number of components defined."

**To Reproduce**
1. Spin up an Azure FHIR server 
2. Search for:
    ```
    GET https://myfhirserver/Observation?component-code-value-quantity=http://loinc.org|8462-4$gt70,http://loinc.org|8462-6$gt150
    ```
    i.e., diastolic blood pressure greater than 70 OR systolic blood pressure greater than 150
3.  Return:

    ```
    {
    "resourceType": "OperationOutcome",
    "id": "873868e8-8d15-46d3-a989-bb6281beb56f",
    "issue": [
        {
            "severity": "error",
            "code": "forbidden",
            "diagnostics": "The number of composite components specified for search parameter 'component-code-value-quantity' exceeded the number of components defined."
        }
    ]
    }
    ```

**Expected behavior**
Should return a search result bundle

The following searches work on public servers:

`http://hapi.fhir.org/baseR4/Observation?component-code-value-quantity=http://loinc.org|8462-4$gt70,http://loinc.org|8462-6$gt150`

Vonk also ignores:

`https://vonk.fire.ly/Observation?component-code-value-quantity=http://loinc.org|8462-4$gt70,http://loinc.org|8462-6$gt150`

(search parameters excluded in self link)

**Actual behavior**
Returns `403`

**Comment by brandonpollett** [comment]
Is this the same issue as https://github.com/microsoft/fhir-server/issues/523?

**Comment by hansenms** [comment]
@brandonpollett , yeah, I think two different symptoms of the same issue that we are not processing the ORs correctly for composites. We can close one or keep them both open since they sort of lay out the test cases that would need to go in.
