### ISSUE TITLE
fhir-azure-server deployment is not adding ADF AND BLOB (fhirimport and fhirexport)

### ISSUE THREAD

**Issue by rameshkr1994** [microsoft/fhir-server#816]
Dear @hansenms   and @vinayakasy99

I want to deployed fhir-server from this given github template but this template is not adding ADF and azure blob container (fhirimport tools) .
below template :  
![image](https://user-images.githubusercontent.com/51785654/72323641-35628280-36cf-11ea-95be-69fdd7c7b22a.png)

i followed this step for multiple time but i am only getting below server with separate Resource group .
Below is image:  -
![image](https://user-images.githubusercontent.com/51785654/72323234-347d2100-36ce-11ea-966c-892954c338c0.png)

**Acceptance criteria**
i seen @hansenms  event DevDays 2018 Amsterdam there cleared spoken  that ADF and blob container(fhirimport and export tools)will be added when we deployed this fhir-server.
but in  my case why i am not getting this services.

Note - i am able to add fhir server with below components but i want to import data using fhirimport/export and ADF.(need)

![image](https://user-images.githubusercontent.com/51785654/72323493-e288cb00-36ce-11ea-9791-1a25b1ac84fe.png)

Thanks
HadoopHelp

**Comment by hansenms** [comment]
That is a different github repo: https://github.com/Microsoft/fhir-server-samples, which (I hope) I references in my presentation at DevDays.

**Comment by rameshkr1994** [comment]
great thanks @hansenms you for your quick reply !

so we need to pass that repo in below template ?

can we complete this process by replacing this below repo with this :- [https://github.com/hansenms/fhir-server-samples](url)

![image](https://user-images.githubusercontent.com/51785654/72324695-84a9b280-36d1-11ea-94ed-4616d0c70ef3.png)

case 01:- if add this repo with this tempate it will work?

case 02:- we need to do it manual as given?

case 02:- i want automate through given template ? is it possible?





Thanks
HadoopHelp

**Comment by hansenms** [comment]
No, that repo has specific scripts that you need to run to deploy all the components as I covered in the presentation. You need to follow the instructions here: https://github.com/microsoft/fhir-server-samples/blob/master/README.md

That will deploy the FHIR server **and** the other stuff you are looking for. The FHIR serve is just one of the components of the other scenario. If you have questions about deploying the samples scenario you can add issues to the other repo, but please follow the instructions over there. You have to use the provided scripts to set up identity configurations, etc.

**Comment by rameshkr1994** [comment]
Hi @hansenms 

i followed this step multiple times but i having some issue... could you please suggest me where we are doing mistake ?

because error show cleared way object ID not found for user.

what is here Environment Name?is this value is predefined or we can pass any name for that.
---------------------i given fhirserver01 in my use case.------------------------

![image](https://user-images.githubusercontent.com/51785654/72326156-a48ea580-36d4-11ea-9f43-2b045d0e10c1.png)


![image](https://user-images.githubusercontent.com/51785654/72325691-ac9a1580-36d3-11ea-86a5-2d4261958e60.png)


Please correct me!


Thanks
HadoopHelp

**Comment by hansenms** [comment]
I think this error may be caused by some glitch that I have seen in the `Az` powershell module where the context user is actually not your username@organization but instead your email address. I have seen it before and will try to repro and get a fix for it. In the meantime, after you see that error, just do `Login-AzAccount` again and try to run the command again.

The `EnvironmentName` is the name of the environment you are creating. It is something you decide and it should be unique. Choosing something like `fhirserver01` is probably a bad idea since it would probably be taken and you will get an error.

Please take comments/questions on the `fhir-server-samples` repo over to that repo.

**Comment by rameshkr1994** [comment]
Of-course @hansenms 

Thanks







HadoopHelp
