### ISSUE TITLE
storing all resouces data into single collection with cosmosdb

### ISSUE THREAD

**Issue by rameshkr1994** [microsoft/fhir-server#831]
Dear @hansenms 

i am posting the data to FHIR SEVRER through python client-py and this data is going to store into cosmosdb(health) internally but this data is storing into defaults collection/container fhirR4 only for all Resources?

is this good way for storing huge data with this structure or any other way to create separate collection/container within same cosmosdb data bases(health) and store the data for separate resources -

this is the storage structure here :  -
![image](https://user-images.githubusercontent.com/51785654/72525088-5e2e7780-3889-11ea-9ad5-68893022d3a7.png)

what is maximum capacity to hold the data with single container in fhir server?

>defaults mentioned 10GB in single container as per MS-Cosmos db docs.

>if we store all resources into single container, is reduce the performance  or not?

Note:-
which is the good way to acceding or search the data for query purpose ,either persistence level(cosmosdb) query or directly through FHIR SERVER?

Thanks
HadoopHelp

**Comment by hansenms** [comment]
There is no 10GB limit on a container. There is a 10GB limit on a partition. We spread the resources into many partitions (they have a partition key). There is no loss of efficiency from storing everything in a single container and there is no practical limit to how big a container can be. Under the hood it is partitioned out. 

You should **not** search the data directly in the Cosmos DB. Use the FHIR API. There is no contract on the schema in the database, so any application that takes a dependency on how exactly the data are stored is likely to break during future updates. Use the FHIR API, that is the contract.

There is no issue on the server here, so I will close this.

**Comment by swapnilbjadhav** [comment]
@rameshkr1994 @hansenms how have you created the persistence layer of Azure CosmosDB, as i am referring the template provided in this link https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FMicrosoft%2Ffhir-server%2Fmaster%2Fsamples%2Ftemplates%2Fdefault-azuredeploy-sql.json. It creates SQL Server as a persistence layer. And i want it to be Azure CosmosDB. Is there any setting in the template parameters or what changes i need to do in the template?. I am actually looking for a ARM template based solution
