### ISSUE TITLE
Templates is not working for FHIR-SERVER-FOR-SQL

### ISSUE THREAD

**Issue by rameshkr1994** [microsoft/fhir-server#836]
Dear @brendankowitz  and @hansenms 

Below templates is not going forward to add fhir-server with SQL .

Template Link:-

[https://azure.microsoft.com/en-in/blog/microsoft-fhir-server-for-azure-extends-to-sql/](url)

https://azure.microsoft.com/en-in/blog/microsoft-fhir-server-for-azure-extends-to-sql/

Only adding apps inside services with above template ?

![image](https://user-images.githubusercontent.com/51785654/72596479-16175f80-3932-11ea-9b8e-b11f5d008943.png)

Please help me.

Thanks
HadoopHelp

**Comment by hansenms** [comment]
We deploy these templates as part of our integration tests, so we have some confidence that they actually deploy the server. We need some more information to help with the problem. It just says 2 failed, but what was the error message?

**Comment by hansenms** [comment]
@rameshkr1994 can you provide the actual error messages and a way to reproduce this issue?

**Comment by rameshkr1994** [comment]
Hi @hansenms .

Its working now... some issue was coming from my side only.




Thanks
HadoopHelp
