### ISSUE TITLE
R4 should support scientific notation in decimal

### ISSUE THREAD

**Issue by brandonpollett** [microsoft/fhir-server#838]
**Describe the bug**
Per the [R4 Spec](https://www.hl7.org/fhir/datatypes.html#decimal), the decimal has a regex that allows scientific notation `-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?`. Additionally, some [search examples](https://www.hl7.org/fhir/search.html#quantity) make use of this functionality. When you send a search such as `GET [base]/Observation?value-quantity=5.40e-3|http://unitsofmeasure.org|g` the server responds with an operation outcome with the message `"Malformed search value '5.40e-3'."`

**To Reproduce**
1. Send search for `Observation?value-quantity=5.40e-3|http://unitsofmeasure.org|g`

**Expected behavior**
Search completes and the self link includes the search parameters

**Actual behavior**
Operation outcome is returned with the message `"Malformed search value '5.40e-3'."`

**Comment by albamati** [comment]
I think this issue can be closed now

**Comment by CaitlinV39** [comment]
Thank you so much @albamati for picking this one up!
