### ISSUE TITLE
what is  patients compartment for all resources in FHIR Server Data

### ISSUE THREAD

**Issue by rameshkr1994** [microsoft/fhir-server#845]
Hi @hansenms  and @brendankowitz 
i have linked two resources Patient and Organization.

and we want to search Patient resources based on ID:-(here id=f001)

Search query :-  
https://opensrxxxxxxrvice.azurewebsites.net/Patient/f001/?_format=application/json

and i am getting responses data as below :- 

`{"resourceType":"Patient","id":"f001","meta":{"versionId":"1","lastUpdated":"2020-01-20T09:32:14.776+00:00"},"text":{"status":"generated","div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative with Details</b></p><p><b>id</b>: f001</p><p><b>identifier</b>: 738472983 (USUAL), ?? (USUAL)</p><p><b>active</b>: true</p><p><b>name</b>: Pieter van de Heuvel </p><p><b>telecom</b>: ph: 0648352638(MOBILE), p.heuvel@gmail.com(HOME)</p><p><b>gender</b>: male</p><p><b>birthDate</b>: 17/11/1944</p><p><b>deceased</b>: false</p><p><b>address</b>: Van Egmondkade 23 Amsterdam 1024 RJ NLD (HOME)</p><p><b>maritalStatus</b>: Getrouwd <span>(Details : {http://terminology.hl7.org/CodeSystem/v3-MaritalStatus code 'M' = 'Married', given as 'Married'})</span></p><p><b>multipleBirth</b>: true</p><h3>Contacts</h3><table><tr><td>-</td><td><b>Relationship</b></td><td><b>Name</b></td><td><b>Telecom</b></td></tr><tr><td>*</td><td>Emergency Contact <span>(Details : {http://terminology.hl7.org/CodeSystem/v2-0131 code 'C' = 'Emergency Contact)</span></td><td>Sarah Abels </td><td>ph: 0690383372(MOBILE)</td></tr></table><h3>Communications</h3><table><tr><td>-</td><td><b>Language</b></td><td><b>Preferred</b></td></tr><tr><td>*</td><td>Nederlands <span>(Details : {urn:ietf:bcp:47 code 'nl' = 'Dutch', given as 'Dutch'})</span></td><td>true</td></tr></table><p><b>managingOrganization</b>: <a>Burgers University Medical Centre</a></p></div>"},"identifier":[{"use":"usual","system":"urn:oid:2.16.840.1.113883.2.4.6.3","value":"738472983"},{"use":"usual","system":"urn:oid:2.16.840.1.113883.2.4.6.3"}],"active":true,"name":[{"use":"usual","family":"van de Heuvel","given":["Pieter"],"suffix":["MSc"]}],"telecom":[{"system":"phone","value":"0648352638","use":"mobile"},{"system":"email","value":"p.heuvel@gmail.com","use":"home"}],"gender":"male","birthDate":"1944-11-17","deceasedBoolean":false,"address":[{"use":"home","line":["Van Egmondkade 23"],"city":"Amsterdam","postalCode":"1024 RJ","country":"NLD"}],"maritalStatus":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/v3-MaritalStatus","code":"M","display":"Married"}],"text":"Getrouwd"},"multipleBirthBoolean":true,"contact":[{"relationship":[{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/v2-0131","code":"C"}]}],"name":{"use":"usual","family":"Abels","given":["Sarah"]},"telecom":[{"system":"phone","value":"0690383372","use":"mobile"}]}],"communication":[{"language":{"coding":[{"system":"urn:ietf:bcp:47","code":"nl","display":"Dutch"}],"text":"Nederlands"},"preferred":true}],"****_managingOrganization":{"reference":"Organization/f001","display":"Burgers University Medical Centre**_**"}}`

in above responces we can see :-  
`managingOrganization":{"reference":"Organization/f001","display":"Burgers University Medical Centre**_**"`

but here showing the references as Organization/f001
image 01:-  

![image](https://user-images.githubusercontent.com/51785654/72721919-1ff3c980-3ba3-11ea-89fc-df50fcad0690.png)

that is fine but how can we get all data related with Patient/f001 in single page?

we want to display all data from Organization/f001 and Patient/f001 in single page-

and what is patients compartment in below comment i received ?
image 02:-

![image](https://user-images.githubusercontent.com/51785654/72721737-c1c6e680-3ba2-11ea-89ed-c26665471a06.png)

**Acceptance criteria**
is my image 01 reference is  patients compartment for Organization/f001

if "yes " then how can we get all data in single page URL by using Patient ID.

Thanks
HadoopHelp

**Comment by hansenms** [comment]
I think I have just answered this one in a previous thread. Compartments are part of the FHIR spec:

https://www.hl7.org/fhir/compartmentdefinition.html

> Please refrain from cross posting on multiple issues and it would be great if we could put general FHIR questions on Stackoverflow (https://stackoverflow.com/tags/hl7-fhir) or https://chat.fhir.org
