### ISSUE TITLE
FHIR Server deployment from ARM template fails

### ISSUE THREAD

**Issue by arieschwartzman** [microsoft/fhir-server#856]
Running this command on the master branch of the repo:

```
New-AzResourceGroupDeployment -TemplateUri https://raw.githubusercontent.com/Microsoft/fhir-server/master/samples/templates/default-azuredeploy.json -ResourceGroupName $rg.ResourceGroupName -serviceName $fhirServiceName
```
Gives this error when deploying on the AppService on West US 2 region:

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling ASP.NET Core Web Application deployment.
A compatible installed .NET Core SDK for global.json version [3.1.100] from [D:\home\site\repository\global.json] was not found
Install the [3.1.100] .NET Core SDK or update [D:\home\site\repository\global.json] with an installed .NET Core SDK:
  1.1.14 [D:\Program Files (x86)\dotnet\sdk]
  2.1.509 [D:\Program Files (x86)\dotnet\sdk]
  2.2.109 [D:\Program Files (x86)\dotnet\sdk]
Failed exitCode=-2147450735, command=dotnet restore "D:\home\site\repository\Microsoft.Health.Fhir.sln"
An error has occurred during web site deployment.
A compatible installed .NET Core SDK for global.json version [3.1.100] from [D:\home\site\repository\global.json] was not found\r\nInstall the [3.1.100] .NET Core SDK or update [D:\home\site\repository\global.json] with an installed .NET Core SDK:\r\nD:\Program Files (x86)\SiteExtensions\Kudu\85.11214.4277\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

It worked fine just last week

**Comment by hansenms** [comment]
This is acknowledged. It appears that App Service does not have support for .NET Core 3.1 for Kudu builds. The SDK is not installed. We have to come up with a mitigation strategy and will also investigate when it might be available. 

As a workaround, you can still build locally and deploy the build to app service (which is what our CI/CD does) You just cannot build in the app service. If you set the `repositoryUrl` template parameter to `""` (blank string), the code will not be deployed, but all the database, app service, etc. will bet set up. You can then deploy your build to the app service and you should be good to go.

**Comment by brandonpollett** [comment]
Here's some discussion around 3.1 in App Service - https://github.com/Azure/app-service-announcements-discussions/issues/129

**Comment by brendankowitz** [comment]
For now, try specifying this branch from the last .net 2.2 release:
```
-repositoryBranch releases/20200117-4
```

**Comment by brendankowitz** [comment]
@arieschwartzman the template has been updated in master, you should be able to rerun the original command. Let me know if this unblocks deployment

**Comment by brendankowitz** [comment]
Closing out this issue. We can reopen if further issues occur

**Comment by vishnu-anil** [comment]
Please reoped this as i am getting the below error when performing External git deployment.

`Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling ASP.NET Core Web Application deployment.
A compatible installed .NET Core SDK for global.json version [3.1.100] from [D:\home\site\repository\global.json] was not found
  1.1.14 [D:\Program Files (x86)\dotnet\sdk]
  2.1.509 [D:\Program Files (x86)\dotnet\sdk]
  2.2.109 [D:\Program Files (x86)\dotnet\sdk]
Failed exitCode=-2147450735, command=dotnet restore "D:\home\site\repository\Microsoft.Health.Fhir.sln"
An error has occurred during web site deployment.
Install the [3.1.100] .NET Core SDK or update [D:\home\site\repository\global.json] with an installed .NET Core SDK:
A compatible installed .NET Core SDK for global.json version [3.1.100] from [D:\home\site\repository\global.json] was not found\r\nInstall the [3.1.100] .NET Core SDK or update [D:\home\site\repository\global.json] with an installed .NET Core SDK:\r\nD:\Program Files (x86)\SiteExtensions\Kudu\85.11214.4277\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"`

**Comment by hansenms** [comment]
I have answered on your other issue. We will not be enabling Kudu builds in the default template. When .NET Core 3.1 becomes available, you can, of course, switch back if you want.

This issue was fixed in:

https://github.com/microsoft/fhir-server/pull/858

**Comment by hansenms** [comment]
Or as stated, you can switch to the previous (.NET Core 2.2) release until .NET Core 3.1 is available.

**Comment by brendankowitz** [comment]
Yes, so right now there are two options, use the branch parameter as mentioned above (https://github.com/microsoft/fhir-server/issues/856#issuecomment-578878649) to continue to use .net 2.2. Or grab the updated deployment templates (https://github.com/microsoft/fhir-server/tree/master/samples/templates)

**Comment by uxbridgeroad** [comment]
I have tried the updated template but it fails with the exception below:-

az group deployment create -g <resource_group> --template-uri https://raw.githubusercontent.com/Microsoft/fhir-server/master/samples/templates/default-azuredeploy.json --parameters serviceName=<name> fhirVersion=R4 applicationInsightsLocation=westeurope

Azure Error: InvalidTemplateDeployment
Message: The template deployment 'default-azuredeploy' is not valid according to the validation procedure. The tracking id is 'fc319f96-e4cb-45e2-92c6-24112d2b9476'. See inner errors for details.
Exception Details:
	Error Code: ValidationForResourceFailed
	Message: Validation failed for a resource. Check 'Error.Details[0]' for more information.

**Comment by hansenms** [comment]
This has been reported and we will post a workaround:

https://github.com/microsoft/fhir-server/issues/877

We recommend not commenting on closed issues. We might not see it.
