### ISSUE TITLE
Next Link incorrect when searching Encounters with search parameters

### ISSUE THREAD

**Issue by modusandrew** [microsoft/fhir-server#860]
**Describe the bug**
Issue occurs in Azure FHIR API STU 3.  Next Link not returning expected response for Encounters.

**To Reproduce**
1. Search against a collection of Encounters greater of 18 using the following search parameters: status, identifier and _count (using 15).
For example: https://yourname-azurehealthcareapis.com/Encounter?status=in-progress&identifier=123&_count=15
2. Note 15 encounters are returned as expected.
3. Perform a second search using the next link returned from the response.

**Expected behavior**
The last 3 encounters should be returned since there are 18 encounters total in the collection.

**Actual behavior**
10 encounters are being returned and some of them don't even belong to the original search parameters.

**Comment by hansenms** [comment]
Can you please POST exact output of the next link and what you are doing when you search. There is not enough here to repro. I would like to see the self-link, the next-link, and the exact search you perform in 3.

**Comment by CaitlinV39** [comment]
@modusandrew I am going to close this issue for now but if you have additional details on your output and your search we are happy to help you resolve the issue.
