### ISSUE TITLE
facing issue while ETL from sql server data to FHIR Server Format(json)

### ISSUE THREAD

**Issue by rameshkr1994** [microsoft/fhir-server#869]
**User story**
Dear all.
i have huge data within on-premise sql server and want to perform ETL for FHIR server format.

currently i am extracting data from sql and storing into a json file .and then putting that json file data to fhir serever  using python api one by one.

but difficulty here is  while extracting the file in FHIR -JSON format.

because the structure of FHIR JSON is something complex for me.

**below is my dummy sql query that i am trying to do:-**
`select resourceType,identifier as id,case Active 
		  WHEN'A'
          THEN'true'
          WHEN'N'
          THEN'false'
          ELSE'UNKNOWN'
		  end as 'active'

,'[{"use":"official","family":"family","given":["'+fname+','+lname+']},
{"use":"usual","given":['+fname+' '+lname+']}]' AS name,CASE gender
          WHEN 'M'
          THEN 'male'
          WHEN 'F'
          THEN 'female'
          ELSE 'UNKNOWN'
       END as gender,birthDate into 
MigrationAzfhir02 from MigrationAzure1`

while running the select statement for above table ("MigrationAzfhir02 ")
`select * from MigrationAzfhir02 `
getting output data format as below (schema is not coming bcz i copied from sql terminal):--
`Patient	1000	true	[{"use":"official","family":"family","given":["FIRSTNAME1000,LASTNAME1000]},  {"use":"usual","given":[FIRSTNAME1000 LASTNAME1000]}]	male	1924-11-20 00:00:00.000
Patient	10049	true	[{"use":"official","family":"family","given":["FIRSTNAME10049,LASTNAME10049]},  {"use":"usual","given":[FIRSTNAME10049 LASTNAME10049]}]	male	1950-03-25 00:00:00.000
Patient	10049	true	[{"use":"official","family":"family","given":["FIRSTNAME10049,LASTNAME10049]},  {"use":"usual","given":[FIRSTNAME10049 LASTNAME10049]}]	male	1950-03-25 00:00:00.000`
**Acceptance criteria**
**when i storing above output with json file getting some extra fields("\","rb") as below:-**

` {
        "resourceType": "Patient",
        "id": 1000,
        "active": "true",
        "**name": "[{\"use\":\"official\",\"family\":\"family\",\"given\":[\**"FIRSTNAME1000,LASTNAME1000]},\r\n{\"use\":\"usual\",\"given\":[FIRSTNAME1000 LASTNAME1000]}]",
        "gender": "male",
        "birthDate": "1924-11-20T00:00:00"
    },
    {
        "resourceType": "Patient",
        "id": 10049,
        "active": "true",
        "**name": "[{\"use\":\"official\",\"family\":\"family\",\"given\":[\"FIRSTNAME10049,LASTNAME10049]},\r\n{\"use\":\"usual\",\"given\":[FIRSTNAME10049 LASTNAME10049]}]",**
        "gender": "male",
        "birthDate": "1950-03-25T00:00:00"
    },`

**Note : -we want the solution for above issue or if anyone has implemented the same use case please help?**

Thanks
HadoopHelp

**Comment by brendankowitz** [comment]
You could use something like the FHIR Validator (https://wiki.hl7.org/Using_the_FHIR_Validator) to do offline validation that the resources are structurally correct. 
I think you have 2 factors here to verify before sending it to the server
1. Is it valid JSON
1. Is it a valid FHIR object

For an example I'm aware of OMOP-on-FHIR that serves FHIR data from the OMOP SQL schema.

**Comment by rameshkr1994** [comment]
Hi @brendankowitz .

validation is not an issue for me here .

here facing issue while ETL from sql server to FHIR JSON format.

**is there any use can that is taking On-Premise sql server data into FHIR SERVER Object format then putting into FHIR SERVER.**

I am trying the same way to implement but issue is coming like we are not able reference different resources .

>if try to transform the data from On-Premise sql server to FHIR OBJECT format that time data format is adding some extra fields as above mentioned .

"\r\n{\"use\":\"usual\",\"given\":[FIRSTNAME10049" added auto extra value \r\n...tec


Thanks
HadoopHelp

**Comment by hansenms** [comment]
@rameshkr1994 we will need you to add some more details to the question and rephrase. It is not possible to decipher you issue or question from the question above. 

In this and other issues you have sort of asked different versions of "how do I ingest my SQL server into FHIR"? We cannot answer that question in general and this is not the right forum for it. It will depend on the schema of your existing SQL server, the tooling you are using, etc. etc. 

We would like to keep the issues here focused on the FHIR server. I would propose taking the more generic "transform to FHIR" questions to either stackoverflow (https://stackoverflow.com/questions/tagged/hl7-fhir) or the Zulip chat (https://chat.fhir.org).

**Comment by rameshkr1994** [comment]
Thanks

@brendankowitz  and @hansenms
