### ISSUE TITLE
$validate doesn't fully honor feature flag

### ISSUE THREAD

**Issue by LTA-Thinking** [microsoft/fhir-server#870]
**Describe the bug**
When the validate feature flag is turned off the endpoint will still return validation results for invalid resources.

**To Reproduce**
1. Turn off the validate feature flag
2. Send an invalid resource to a validate endpoint

**Expected behavior**
An operation outcome of unsupported is returned

**Actual behavior**
An operation outcome with validation errors is returned

**Comment by CaitlinV39** [comment]
@CaitlinV39 create bug in VSTS

**Comment by CaitlinV39** [comment]
AB#76148

**Comment by CaitlinV39** [comment]
Closing this issue because it will be covered as part of the further development for profile & validation.
