### ISSUE TITLE
Search for `_profile` fails on R4

### ISSUE THREAD

**Issue by hansenms** [microsoft/fhir-server#880]
**Describe the bug**
Search for resources using the `_profile` parameter come up empty on R4.

**To Reproduce**
1. Spin up an R4 instance of the service.  
2. POST a resource like:
    ```json
    {
      "resourceType": "Device",
      "meta": {
  	    "profile": [
  		    "http://foo.com/bar"
  	    ]
      },
      "identifier": [
       {
          "system": "http://goodcare.org/devices/id",
          "value": "345675"
        }
      ]
     }
    ```
3.  Search for:
    ```http
    https://fhirserver/Device?_profile=http://foo.com/bar
    ```

**Expected behavior**
Should return the resource with profile

**Actual behavior**
Returns no results.

**Comment by hansenms** [comment]
There is a docs issue that should be kept up-to-date as this is mitigated: https://github.com/MicrosoftDocs/azure-docs/issues/47937

**Comment by hansenms** [comment]
This is likely related to profile changing from url to canonical in R4.

**Comment by brandonpollett** [comment]
We receive the following error when parsing `Microsoft.Health.Fhir.Core.Features.Search.SearchIndexer: Warning: The FHIR element 'canonical' is not supported.` from line 222 in `SearchIndexer.cs`

**Comment by brandonpollett** [comment]
Additionally, there appears to be four added primitive types in R4 - http://services.w3.org/htmldiff?doc1=http%3A%2F%2Fhl7.org%2Ffhir%2FSTU3%2Fdatatypes.html&doc2=http%3A%2F%2Fbuild.fhir.org%2Fdatatypes.html

**Comment by brandonpollett** [comment]
There are additional search semantics also defined for canonical - https://www.hl7.org/fhir/search.html#versions

**Comment by brendankowitz** [comment]
We will address re-enabling this functionality in #882
