### ISSUE TITLE
Add support for R4 type Canonical => URI searches

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#882]
**User story**
Add support for the R4 primitive type [Canonical](https://www.hl7.org/fhir/datatypes.html).

**Acceptance criteria**
1. Support is visible at the /metadata endpoint
1. Canonical urls are indexed correctly
1. Verify resources can be searched by _profile, including _profile=http://url|version
1. Verify resources can be searched by Uri, e.g. ConceptMap.source(uri)

**Comment by CaitlinV39** [comment]
AB#69418

**Comment by CaitlinV39** [comment]
AB#76717

**Comment by CaitlinV39** [comment]
AB#76852

**Comment by CaitlinV39** [comment]
AB#76852

**Comment by brendankowitz** [comment]
Spec issue that may affect this in future: https://jira.hl7.org/browse/FHIR-30514
