### ISSUE TITLE
Most efficient way of DataStore refresh

### ISSUE THREAD

**Issue by GlenQu** [microsoft/fhir-server#888]
Hi,

Currently running the PaaS version of the Azure API for FHIR.  I am currently looking at the most optimal way of refreshing the data store or bringing the service back to a default state with no data.

A few options I have been looking at:
1. Create a script which stores all the id's then created individual delete requests to the server.
2. Conditional deletes (not-supported)?
3. Destroy and recreate the PaaS service (Would have to go through all apps and reassign permissions)

The only feasible option seems to be number 1 so far unless there is another method I have not uncovered.

Thanks for your help!

Kind Regards,

Glen

**Comment by hansenms** [comment]
I use this little tool I made:

https://github.com/hansenms/ClearFhirService

I am not sure you need to first store all the ids. You can just do a search for `/*`, it will return all resources then run through and delete. add the `?hardDelete=true` query parameter to get rid of all revision history.

**Comment by GlenQu** [comment]
Thanks Michael, that is really handy.

Kind Regards,

Glen
