### ISSUE TITLE
When I create a Specimen with a Request, I should find the Specimen in the ProcedureRequest

### ISSUE THREAD

**Issue by christopheblin** [microsoft/fhir-server#889]
**User story**
When I create a Specimen with a Request, I should find the Specimen in the ProcedureRequest

Note: in v4, this is ServiceRequest

**Acceptance criteria**
Using the library Firely and FluentAssertions

```
var fhirClient = new FhirClient("http://localhost:8080");

var p = new ProcedureRequest() { ... }
p = fhirClient.Create(p);

var s = new Hl7.Fhir.Model.Specimen() { 
   ..., 
   Request = new List<ResourceReference> { new ResourceReference($"ProcedureRequest/{p.Id}") } 
};
s = fhirClient.Create(s);


fhirClient.Read<ProcedureRequest>($"ProcedureRequest/{p.Id}").Specimen.Should().NotBeEmpty();
```

**Comment by hansenms** [comment]
Interesting, so your expectation would be that when you add the specimen we go back and update the request (automatically)?

We don't even enforce referential integrity at the moment, so this would be a step well beyond where we are, but I am also not sure that it would be correct behavior. Convenient in some use cases, absolutely, but there could be some unintended consequences. 

I checked a few other servers and couldn't find one that does it, so I am not sure it would be the expected behavior, but I would love to hear comments from others on this. My intuition is that we should not do this. But I am prepared to be convinced otherwise.

**Comment by christopheblin** [comment]
I agree that referential integrity is a required first step before this story.

But, this is also what would break this kind of circular reference.

Ex: you would now not be able to delete the procedure because the specimen references it AND you cannot delete the specimen because the procedure references it...)

However, I disagree when you say that this "parentship" should not be done.

The "problem" is that this kind of "circular reference" is well avoided in other scenarios.

For ex, the ProcedureRequest has no reference to the DiagnosticReport but DiagnoticReport.BasedOn does know the procedure

Another ex, a Task.Input knows its resources but absolutely no resource has a reference to a Task

Final ex, a Patient does not reference directly any other resource (but nearly all resources reference a patient)

I am not an expert of all the possibilities, I am just saying that I think that Specimen <-> ProcedureRequest is a very special case.

Anyway, I know that you can solve the problem by profiling the ProcedureRequest to forbid specimen (and use only the specimen as a resource).

That way, you are pretty much safer I think but this is a normative problem (not an implementation problem) and also a problem for contexts where the specimen has no standalone existence (note that I am not aware of such context personnally)

**Comment by hansenms** [comment]
To me this just sounds like something that should be done in a transaction bundle?

**Comment by CaitlinV39** [comment]
@christopheblin I wanted to check if Michael's suggestion around a transaction bundle resolved your issue or if you had additional questions? Thanks!

**Comment by christopheblin** [comment]
@CaitlinV39 In the end, we decided to forbid the use of the property Specimen.Request (to keep spirit of FHIR top-down like in Tasks and DiagnosticReport) and we use a transaction bundle when we add a specimen to the request.

**Comment by CaitlinV39** [comment]
Sounds great. Thanks so much @christopheblin
