### ISSUE TITLE
NullReferenceException is thrown if EntryComponent url is null

### ISSUE THREAD

**Issue by jackliums** [microsoft/fhir-server#890]
**Describe the bug**
When making a batch/transaction call, if the EntryComponent.Requset.Url is not specified, then the server throws NullReferenceException.

In the code below, it's not checking to make sure requestUrl is not null.
```
if ((requestMethod == HTTPVerb.POST && requestUrl.Contains("_search", StringComparison.OrdinalIgnoreCase))
                || (requestMethod == HTTPVerb.DELETE && requestUrl.Contains("?", StringComparison.Ordinal)))
```

**To Reproduce**
1. Create a bundle with EntryComponent without specifying the request url.

**Expected behavior**
400 Bad Request should be thrown (or something equivalent).

**Actual behavior**
500 Internal Server Error is thrown.

**Comment by CaitlinV39** [comment]
@brendankowitz to investigate

**Comment by CaitlinV39** [comment]
@CaitlinV39 link this in VSTS

**Comment by CaitlinV39** [comment]
This may be related to AB#78977

**Comment by CaitlinV39** [comment]
AB#84441

**Comment by CaitlinV39** [comment]
Not going to prioritize for now
