### ISSUE TITLE
Add support for FHIR searches of types Money => Quantity

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#891]
**User story**
Add support for the R4 primitive type [Money](https://www.hl7.org/fhir/datatypes.html).

**Acceptance criteria**
1. Support is visible at the /metadata endpoint
1. Canonical urls are indexed correctly
1. Search mapped from Money=>Quantity. e.g. Account.Balance

**Comment by CaitlinV39** [comment]
AB#72427
