### ISSUE TITLE
Add support for FHIR searches of types String=>Token

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#892]
**User story**
Add support for the R4 [primitive types](https://www.hl7.org/fhir/datatypes.html).

**Acceptance criteria**
1. Support is visible at the /metadata endpoint
1. Datatype is indexed correctly
1. Verify resources can be searched by version. e.g. ActivityDefinition.version with version=abc123

**Comment by CaitlinV39** [comment]
AB#72424
