### ISSUE TITLE
Azure API for FHIR offline

### ISSUE THREAD

**Issue by dikokob** [microsoft/fhir-server#920]
We currently have an EHR system running on top of the Azure API for FHIR. One of the doctors needing to use the system have problems with their internet. We are exploring how we can cache the data locally and update when a string internet connection is available.

If anyone has experience for the use case please let me know.

**Comment by chgl** [comment]
These links could be helpful:

* https://fhircast.org/
* http://www.healthintersections.com.au/?p=2950

Maybe also ask in the FHIR Chat (https://chat.fhir.org/).

**Comment by CaitlinV39** [comment]
@dikokob we don't have any plans to provide an offline cache right now. For now I'm going to close as won't fix.
