### ISSUE TITLE
Microsoft.AspNetCore.WebUtilities should not be referenced by core projects

### ISSUE THREAD

**Issue by YazanMSFT** [microsoft/fhir-server#926]
Microsoft.AspNetCore.WebUtilities is being referenced by core projects (Stu3.Core, R4.Core, and the upcoming R5.Core). We should look into removing this reference.

_Originally posted by @brendankowitz in https://github.com/microsoft/fhir-server/pull/921_

**Comment by brendankowitz** [comment]
Thanks @YazanMSFT I was looking into this Friday (#923)
