### ISSUE TITLE
authenticating-using-built-in-identityserver has (stale) error in documentation

### ISSUE THREAD

**Issue by granadacoder** [microsoft/fhir-server#942]
Please update the documentation.

https://github.com/microsoft/fhir-server/blob/master/docs/Authentication.md#authenticating-using-built-in-identityserver

Currently it says:

**POST /connect/token HTTP/1.1
Host: https://localhost:44348
Content-Type: application/x-www-form-urlencoded

_client_id=serviceclient&client_secret=serviceclient&grant_type=client_credentials&scope=fhir-api_**

(stale) issue:

"serviceclient" is no longer in testauthenvironment.json

See

https://github.com/microsoft/fhir-server/blob/master/testauthenvironment.json

Looks like "serviceclient" has been changed to "globalAdminServicePrincipal" ??

I think the documentation should be changed to:

client_id=globalAdminServicePrincipal&client_secret=globalAdminServicePrincipal&grant_type=client_credentials&scope=fhir-api

**Comment by hansenms** [comment]
Yes, we should correct that. Also do feel free to put up a PR with these types of changes.

**Comment by hansenms** [comment]
Fixed.

**Comment by granadacoder** [comment]
Thanks 
(and "feel free to create PR" duly noted)
