### ISSUE TITLE
Linux App Service Plan  deployment

### ISSUE THREAD

**Issue by kavithakrishnasamy** [microsoft/fhir-server#948]
Hi,

By default if we deploy open source fhir server using ARM template means it will use Windows app service plan. But in our case we need to use Linux app service plan which is already created.

any idea how to deploy it?

*Note: Cosmos DB, Key Vault, App service and  Linux App plan service already created. we just need to re use it.

Thanks in advance

**Comment by hansenms** [comment]
You could use the Docker container. 

https://github.com/microsoft/fhir-server/tree/master/samples/docker

We will be expanding on that concept and add that to our templates in the near term.

You could also just build the code on Linux and deploy to a Linux web app.

**Comment by kavithakrishnasamy** [comment]
Thanks for you reply..  from that url we came to know how to deploy the code to Linux app plan..
but how to deploy the FHIR from source code from local system. which project we need to use for deploy app service ?

**Comment by brendankowitz** [comment]
For a custom build, given that its a fairly standard ASP.NET Web app, you should be able to utilize the tutorials from the ASP.NET docs, i.e. https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-custom-docker-image. The links @hansenms posted list out the parameters you'd need to set in specifically for our app (such as SqlServer__ConnectionString)

**Comment by kavithakrishnasamy** [comment]
> You could use the Docker container.
> 
> https://github.com/microsoft/fhir-server/tree/master/samples/docker
> 
> We will be expanding on that concept and add that to our templates in the near term.
> 
> You could also just build the code on Linux and deploy to a Linux web app.

**Comment by hansenms** [comment]
Check out the docker templates in here:

https://github.com/microsoft/fhir-server/tree/master/samples/templates

They reference pre-built Docker images and shows how to deploy them.
