### ISSUE TITLE
Clean up Config locations

### ISSUE THREAD

**Issue by brendankowitz** [microsoft/fhir-server#951]
**User story**
Evaluate if some config items in 
https://github.com/microsoft/fhir-server/blob/master/src/Microsoft.Health.Fhir.Api/Configs/ can be moved into https://github.com/microsoft/fhir-server/tree/master/src/Microsoft.Health.Fhir.Core/Configs.

Examples:
Cors configuration might make sense to stay in API
Feature configuration (Conditional) might make sense to move to Core

**Comment by CaitlinV39** [comment]
AB#76159

**Comment by EXPEkesheth** [comment]
Closing as we do not plan to address the issue. Let us know if you have any questions/comments.
