### ISSUE TITLE
Privacy and encrypted data storage

### ISSUE THREAD

**Issue by fungiboletus** [microsoft/fhir-server#963]
**User story**

As a software developer, I need to store FHIR data in a private and encrypted storage. I seek good security and privacy by design.

Does microsoft/fhir-server supports encryption of FHIR documents before storage ? I quikly browsed the code and searched for encryption and found nothing.

I know that [CosmosDB do data encryption at rest](https://docs.microsoft.com/en-us/azure/cosmos-db/database-encryption-at-rest), but it doesn't count since the keys are managed and hosted by Microsoft (remember the famous USA PATRIOT Act and similar stuff). Some alternative FHIR databases do encryption before storage, and expose a set of fields for indexing, sometimes hashed with salt and pepper.

Is a set of features related to encryption and privacy planned for microsoft/fhir-server ?

Thank you very much.

**Comment by johnstairs** [comment]
Hi, both Cosmos DB and SQL support customer-managed keys aka BYOK (https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-cmk and https://docs.microsoft.com/en-us/azure/sql-database/transparent-data-encryption-byok-azure-sql).

Please evaluate if this meets your needs. Encrypting the data such that the database cannot decrypt it makes some searches impossible. [Secure enclaves](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-enclaves?view=sql-server-ver15) would be a solution to this, but we do not currently have plans to support it in the near future.

**Comment by fungiboletus** [comment]
Thanks for your answer.

I understand that you can bring your own RSA keys with Cosmos DB and Microsoft SQL Server, however :
> You must store customer-managed keys in Azure Key Vault.

For sure the key is stored in a fancy HSM and this kind of setup checks the "encryption" box for many companies, but from a user point of view I store the data at Microsoft and I give the keys to Microsoft.

Secure enclaves do sound like a good solution for my needs. I'm sure I will hear more about your project if you decide to support such a solution in the future.
