### ISSUE TITLE
Support for Custom identity provider like Auth0

### ISSUE THREAD

**Issue by Sacratees** [microsoft/fhir-server#969]
We are using Auth0 as service provider for managing authentication / authorization for our application. Right now i could see only AAD for fhir server. 

How do I integrate Auth0 for access token validation? Is there any plan to support different identity provider from out of the box?

**Comment by hansenms** [comment]
It should be a fairly light task to use another OAuth2 provider. You can see some other issues where people are looking at B2C: https://github.com/microsoft/fhir-server/issues/774. At the moment we only test with AAD, but we should not be restricted to AAD.

**Comment by tragdorvigani1** [comment]
@Sacratees - FWIW, it wasn't very difficult to get FS working with AD B2C. @hansenms 's recommendations plus a little research was enough. You may have the same limitations with Auth0 I have, around claims and RBAC.

**Comment by CaitlinV39** [comment]
@Sacratees I wanted to follow up to see if you had additional questions on this or if you are okay to close. Thanks!
