### ISSUE TITLE
Support installation via Helm Chart

### ISSUE THREAD

**Issue by chgl** [microsoft/fhir-server#994]
**User story**
As a Developer/Operator, I want the FHIR server to be available as a Helm Chart so that I can easily deploy it to Kubernetes.

**Acceptance criteria**
1. When I do `helm install my-fhir-server <chart-repo>/fhir-server`, then the FHIR server gets installed on Kubernetes using a MSSQL Server as the default data store.

I would like to work on this. Should I just create a `chart` folder in this repo or is there a dedicated one for MS charts (I found [this one](https://github.com/microsoft/charts) but it seems to only host the build *.tar.gz)?

There are also some helpful linting/chart testing tools which could be integrated in the CI (https://github.com/helm/chart-testing, https://github.com/instrumenta/kubeval, https://github.com/swade1987/deprek8ion, and https://github.com/norwoodj/helm-docs). Unfortunately I am not very familiar with Azure DevOps.

**Comment by hansenms** [comment]
@chgl, thanks for the suggestion. We actually already have some work going on this and we will be adding a helm chart to the repo in the not so distant future. For that help chart we are taking a dependency on some tooling for deploying Azure services that we depend on (database, etc.). They still need a bit of work but it is coming together. I don't have an exact timeline on this, but we are aiming to get it out as soon as we can.

**Comment by chgl** [comment]
@hansenms great to hear! I saw some mentions of kubernetes and helm in other issues so I was suspecting that it's at least on your agenda. Looking forward to trying it out.

**Comment by hansenms** [comment]
@chgl, just merged the helm chart.
